import { writeLocaleFile, allKeys } from './build-all-locales.js';
import { TranslationSchema } from '../src/locales/types.js';

// ============================================================================
// 1. BENGALI (বাংলা - bn)
// ============================================================================
export function generateBengali() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: "সহায় (SAHAAY)",
    emblemLetter: "স",
    tagline: "আপনার জমি। আপনার মামলা। আপনার অধিকার।",
    heroSub: "ভূমি অধিগ্রহণ এবং সংবিধিবদ্ধ ক্ষতিপূরণের জন্য নাগরিক তথ্য পোর্টাল",
    portalSubtitle: "জমি • ক্ষতিপূরণ • পুনর্বাসন (R&R) • অভিযোগ • মামলা ট্র্যাকিং",
    citizenPortal: "নাগরিক পোর্টাল",
    officerPortal: "ভূমি অধিগ্রহণ আধিকারিক পোর্টাল",
    demoMode: "ডেমো মোড সক্রিয়",
    signIn: "লগইন করুন",
    signOut: "লগ আউট",
    landowner: "জমির মালিক",
    landOfficer: "ভূমি অধিগ্রহণ আধিকারিক (LAO)",
    switchRole: "ভূমিকা পরিবর্তন",
    switchCitizen: "নাগরিক (রাজেশ শর্মা)",
    switchOfficer: "আধিকারিক (বিক্রম চৌহান)",
    welcomeBack: "স্বাগতম",
    navHome: "হোম",
    navFindLand: "আমার জমি খুঁজুন",
    navGisMap: "GIS জমির মানচিত্র",
    navDocIntel: "নথি বিশ্লেষণ (AI)",
    navCompensation: "ক্ষতিপূরণ ও পুনর্বাসন",
    navDocuments: "নথিপত্র ভল্ট",
    navActionCenter: "কার্যক্রম কেন্দ্র",
    navGrievances: "অভিযোগ ও নিষ্পত্তি",
    navNotices: "বিজ্ঞপ্তি ও সতর্কতা",
    navOfficerDashboard: "আধিকারিক ড্যাশবোর্ড",
    navCasesRegistry: "মামলা রেজিস্ট্রি",
    navGrievancesQueue: "অভিযোগের সারি",
    citizenServices: "নাগরিক সেবা",
    quickActions: "দ্রুত পদক্ষেপ",
    submit: "জমা দিন",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    edit: "সম্পাদনা",
    delete: "মুছুন",
    search: "অনুসন্ধান করুন",
    filter: "ফিল্টার",
    back: "ফিরে যান",
    next: "পরবর্তী",
    close: "বন্ধ করুন",
    view: "দেখুন",
    download: "ডাউনলোড",
    upload: "আপলোড করুন",
    export: "রপ্তানি",
    refresh: "রিফ্রেশ",
    print: "প্রিন্ট করুন",
    loading: "লোড হচ্ছে...",
    actions: "পদক্ষেপ",
    details: "বিবরণ",
    status: "অবস্থা",
    viewDetails: "বিবরণ দেখুন",
    viewOnMap: "মানচিত্রে দেখুন",
    viewCase: "সম্পূর্ণ মামলা দেখুন",
    trackProgress: "অগ্রগতি ট্র্যাক করুন",
    proceed: "এগিয়ে যান",
    confirm: "নিশ্চিত করুন",
    retry: "পুনরায় চেষ্টা করুন",
    clearAll: "সব মুছে ফেলুন",
    applyFilter: "ফিল্টার প্রয়োগ করুন",
    active: "সক্রিয়",
    pending: "বিচারাধীন",
    completed: "সম্পন্ন",
    resolved: "নিষ্পত্তিকৃত",
    inProgress: "চলমান",
    actionRequired: "পদক্ষেপ প্রয়োজনীয়",
    verified: "যাচাইকৃত",
    all: "সকল",
    noData: "তথ্য উপলব্ধ নেই",
    noResults: "কোনো ফলাফল পাওয়া যায়নি",
    loadingData: "তথ্য লোড হচ্ছে...",
    somethingWentWrong: "কিছু ভুল হয়েছে",
    tryAgain: "দয়া করে পুনরায় চেষ্টা করুন",
    errorOccurred: "একটি ত্রুটি ঘটেছে",
    help: "সাহায্য ও প্রশ্নাবলী",
    helpdesk: "সহায়তা কেন্দ্র",
    helpline: "1800-180-LAND",
    tollFree: "টোল ফ্রি জাতীয় হেল্পলাইন",
    rightsReserved: "সর্বস্বত্ব সংরক্ষিত",
    status_ACTIVE: "সক্রিয়",
    status_COMPLETED: "সম্পন্ন",
    status_VERIFIED: "যাচাইকৃত",
    status_PAID: "প্রদত্ত (DBT)",
    status_SANCTIONED: "অনুমোদিত",
    status_RESOLVED: "নিষ্পত্তিকৃত",
    status_ELIGIBLE: "যোগ্য",
    status_VERIFICATION: "যাচাইকরণ পর্যায়",
    status_IN_PROGRESS: "চলমান",
    status_UNDER_REVIEW: "পর্যালোচনাধীন",
    status_CURRENT: "বর্তমান অবস্থা",
    status_PROCESSING: "প্রক্রিয়াধীন",
    status_ACTION_REQUIRED: "পদক্ষেপ প্রয়োজনীয়",
    status_UPCOMING: "আসন্ন",
    status_PENDING: "বিচারাধীন",
    status_REJECTED: "প্রত্যাখ্যাত",
    status_FAILED: "ব্যর্থ",
    status_DEPOSITED_PFMS: "PFMS জমা হয়েছে",
    status_CLAIM_SUBMITTED: "দাবি দাখিলকৃত",
    status_DISCREPANCY_FLAGGED: "অসঙ্গতি চিহ্নিত",
    status_RESPONSE_ADDED: "উত্তর যুক্ত হয়েছে",
    status_AWAITING_HEARING: "শুনানির অপেক্ষায়",
    status_CLOSED: "নিষ্পন্ন",
    status_ASSESSED: "মূল্যায়িত",
    status_APPROVED: "অনুমোদিত",
    status_DISCREPANCY_FOUND: "অসঙ্গতি প্রাপ্ত",
    status_DISPUTED: "বিরোধপূর্ণ",
    status_HIGH: "উচ্চ অগ্রাধিকার",
    status_SUBMITTED: "দাখিলকৃত",
    status_UNPAID: "অপরিশোধিত",
    status_PROPOSAL: "প্রস্তাব পর্যায়",
    status_NOTIFICATION: "বিজ্ঞপ্তি পর্যায়",
    welcomeTitle: "সহায় (SAHAAY) পোর্টালে স্বাগতম",
    welcomeSub: "আপনার জমি অধিগ্রহণ ও ক্ষতিপূরণ ট্র্যাক করতে লগইন করুন।",
    demoAccountsTitle: "ডেমো অ্যাকাউন্ট নির্বাচন করুন",
    demoBadge: "ডেমো মোড",
    demoCitizenTitle: "🌾 নাগরিক / জমির মালিক",
    demoCitizenSub: "রাজেশ শর্মা (দাগ #১০৪২)",
    demoOfficerTitle: "🏛️ ভূমি অধিগ্রহণ আধিকারিক (LAO)",
    demoOfficerSub: "বিক্রম চৌহান (ভোপাল সার্কেল)",
    tabSignIn: "লগইন করুন",
    tabRegister: "নাগরিক নিবন্ধন",
    fullNameLabel: "পূর্ণ নাম (রেকর্ড অনুযায়ী)",
    fullNamePlaceholder: "উদাঃ রাজেশ শর্মা",
    villageLabel: "গ্রাম / মৌজা",
    districtLabel: "জেলা",
    emailLabel: "ইমেল / মোবাইল নম্বর",
    emailPlaceholder: "name@sahaay.demo",
    passwordLabel: "পাসওয়ার্ড",
    passwordPlaceholder: "••••••••",
    verifyingBtn: "যাচাই করা হচ্ছে...",
    createAccountBtn: "অ্যাকাউন্ট তৈরি করুন",
    signInBtn: "নিরাপদে লগইন করুন",
    demoFillBtn: "ডেমো তথ্য পূরণ করুন",
    loginErrorDefault: "লগইন ব্যর্থ হয়েছে। তথ্য যাচাই করুন।",
    registerSuccessToast: "অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে! লগইন করুন।",
    quickAccessSection: "দ্রুত নাগরিক সেবা",
    findLandCardTitle: "আমার জমি খুঁজুন",
    findLandCardDesc: "দাগ নম্বর ও মৌজা দিয়ে অধিগ্রহণের স্থিতি জানুন।",
    docIntelCardTitle: "AI নথি বিশ্লেষণ",
    docIntelCardDesc: "অধিগ্রহণ নোটিশ আপলোড করে সহজ ব্যাখ্যা পান।",
    gisMapCardTitle: "GIS প্রকল্পের মানচিত্র",
    gisMapCardDesc: "মহাসড়ক প্রান্তরেখা ও জমির সীমানা স্যাটেলাইটে দেখুন।",
    compensationCardTitle: "ক্ষতিপূরণ মূল্যায়ন",
    compensationCardDesc: "RFCTLARR আইনের ১০০% তোষণ ও DBT স্থিতি দেখুন।",
    actionCenterCardTitle: "কার্যক্রম কেন্দ্র",
    actionCenterCardDesc: "আইনি সময়সীমা ও করণীয় কাজ পরিচালনা করুন।",
    grievancesCardTitle: "অভিযোগ ও আপত্তি",
    grievancesCardDesc: "ধারা ১৫ আপত্তি ও ক্ষতিপূরণ বিরোধ দাখিল করুন।",
    summaryParcelsCount: "সংযুক্ত জমির দাগ",
    summaryActiveAcquisitions: "সক্রিয় অধিগ্রহণ প্রক্রিয়া",
    summaryTotalAssessedComp: "মোট নির্ধারিত ক্ষতিপূরণ",
    summaryPendingActions: "জরুরি করণীয় কাজ",
    timelineTitle: "আইনসম্মত অধিগ্রহণ অগ্রগতি",
    timelineSub: "RFCTLARR আইন ২০১৩ অনুযায়ী মামলার পর্যায়সমূহ",
    stepSec11: "ধারা ১১(১) প্রাথমিক বিজ্ঞপ্তি",
    stepSec15: "ধারা ১৫ শুনানি ও আপত্তি",
    stepSec19: "ধারা ১৯ চূড়ান্ত ঘোষণা",
    stepSec23: "ধারা ২৩ ক্ষতিপূরণ অ্যাওয়ার্ড",
    stepPayment: "PFMS ক্ষতিপূরণ বিতরণ",
    stepPossession: "দখল গ্রহণ ও পুনর্বাসন",
    discrepancyBannerTitle: "সতর্কতা: দাগ #১০৪২ এর ক্ষেত্রফলে অসঙ্গতি ধরা পড়েছে",
    discrepancyBannerDesc: "বিজ্ঞপ্তির ক্ষেত্রফল (১.১০ হেক্টর) রাজস্ব রেকর্ডের চেয়ে কম। ধারা ১৫(১) অনুযায়ী ৬০ দিনের মধ্যে আপত্তি জানান।",
    reviewDiscrepancyBtn: "অসঙ্গতি পর্যালোচনা",
    fileObjectionBtn: "আপত্তি দাখিল করুন",
    findLandTitle: "দাগ নম্বর দিয়ে জমি অনুসন্ধান",
    findLandSubtitle: "মহাসড়ক বা রেল প্রকল্পের আওতাধীন জমি অবিলম্বে খুঁজুন।",
    surveyInputLabel: "দাগ নম্বর / খতিয়ান",
    surveyInputPlaceholder: "উদাঃ ১০৪২ বা ৪৫/ক",
    villageSelectLabel: "মৌজা / গ্রাম",
    allVillagesOption: "সকল মৌজা",
    districtSelectLabel: "জেলা",
    allDistrictsOption: "সকল জেলা",
    searchLandSubmitBtn: "জমি অনুসন্ধান করুন",
    searchResultsHeading: "অনুসন্ধানের ফলাফল",
    parcelCardSurveyLabel: "দাগ নম্বর:",
    parcelCardVillageLabel: "মৌজা ও জেলা:",
    parcelCardAreaLabel: "বিজ্ঞাপিত আয়তন:",
    parcelCardOwnerLabel: "মালিকের নাম:",
    parcelCardProjectLabel: "প্রকল্প:",
    parcelCardStageLabel: "বর্তমান পর্যায়:",
    parcelCardCompLabel: "নির্ধারিত ক্ষতিপূরণ:",
    viewGisMapBtn: "GIS মানচিত্রে দেখুন",
    viewCompDetailsBtn: "ক্ষতিপূরণের বিবরণ",
    noSearchResultsTitle: "কোনো জমির রেকর্ড পাওয়া যায়নি",
    noSearchResultsDesc: "সঠিক দাগ নম্বর ও গ্রাম যাচাই করে পুনরায় চেষ্টা করুন।",
    gisTitle: "ইন্টারেক্টিভ GIS প্রকল্প সীমানা মানচিত্র",
    gisSubtitle: "অধিগ্রহণ প্রান্তরেখা, বাফার জোন ও পার্শ্ববর্তী দাগসমূহ দেখুন।",
    legendTitle: "মানচিত্র নির্দেশিকা",
    legendAcquired: "বিজ্ঞাপিত অধিগ্রহণ এলাকা",
    legendBuffer: "প্রকল্পের বাফার জোন (৫০ মিটার)",
    legendYourLand: "আপনার জমির দাগ (#১০৪২)",
    legendAdjacent: "পার্শ্ববর্তী দাগসমূহ",
    mapLayerControl: "মানচিত্র স্তর",
    layerSatellite: "স্যাটেলাইট দৃশ্য",
    layerCadastral: "মৌজা নকশা (Cadastral)",
    layerProjectAlign: "প্রকল্প প্রান্তরেখা",
    parcelInfoPanelTitle: "নির্বাচিত দাগের তথ্য",
    infoSurveyNo: "দাগ নম্বর",
    infoVillage: "মৌজা ও ব্লক",
    infoTotalArea: "মোট জমির ক্ষেত্রফল",
    infoAcquiredArea: "অধিগ্রহণকৃত ক্ষেত্রফল",
    infoOwner: "মালিকের নাম",
    infoStatus: "অধিগ্রহণ স্থিতি",
    infoEstimatedVal: "নির্ধারিত ক্ষতিপূরণ",
    measureDistanceBtn: "দূরত্ব পরিমাপ",
    measureAreaBtn: "ক্ষেত্রফল পরিমাপ",
    clearMeasureBtn: "পরিমাপ মুছুন",
    docIntelTitleFull: "AI সরকারি নথি বিশ্লেষণ ইঞ্জিন",
    docIntelSubtitle: "জমি অধিগ্রহণ গেজেট নোটিশ সহজ ভাষায় বুঝুন।",
    uploadZoneTitle: "নোটিশ বা অ্যাওয়ার্ড নথি আপলোড করুন",
    uploadZoneSubtitle: "PDF, JPG বা PNG ফাইল নির্বাচন করুন (সর্বোচ্চ ২৫MB)",
    sampleNoticesTitle: "বা ডেমো নোটিশ পরীক্ষা করুন:",
    sampleSec11Btn: "📄 ধারা ১১(১) নোটিশ (দাগ #১০৪২)",
    sampleAwardBtn: "📄 ধারা ২৩ অ্যাওয়ার্ড নির্দেশনামা",
    sampleSec19Btn: "📄 ধারা ১৯(১) ঘোষণা নোটিশ",
    analysisResultsTitle: "AI নথি বিশ্লেষণ সারাংশ",
    docTypeDetected: "নথির ধরন",
    gazetteRefNo: "গেজেট রেফারেন্স নম্বর",
    issuingAuthority: "প্রদানকারী কর্তৃপক্ষ",
    issueDate: "প্রকাশের তারিখ",
    affectedVillage: "প্রভাবিত মৌজা ও জেলা",
    statutorySection: "প্রযোজ্য আইনি ধারা",
    keyFindingsHeading: "মূল তথ্য (সহজ ভাষায়):",
    detectedDiscrepanciesTitle: "⚠️ চিহ্নিত অসঙ্গতি ও আপত্তি:",
    actionableStepsHeading: "আপনার করণীয় পদক্ষেপ:",
    confidenceScoreLabel: "AI নির্ভুলতার হার:",
    downloadAnalysisReportBtn: "সম্পূর্ণ AI রিপোর্ট ডাউনলোড",
    fileObjectionFromDocBtn: "এই নোটিশে আপত্তি দাখিল করুন",
    compPageTitle: "আইনসম্মত ক্ষতিপূরণ ও পুনর্বাসন (R&R) সুবিধাসমূহ",
    compPageSubtitle: "RFCTLARR আইন ২০১৩ অনুযায়ী পূর্ণ ক্ষতিপূরণ, তোষণ ও DBT বিতরণ।",
    assessedLandValueCard: "মূল জমির মূল্যায়ন",
    solatium100Card: "১০০% তোষণ অনুদান (সোলেটিয়াম)",
    statutoryInterestCard: "১২% অতিরিক্ত বার্ষিক সুদ",
    totalCompensationCard: "মোট ক্ষতিপূরণ অ্যাওয়ার্ড",
    compBreakdownTitle: "ক্ষতিপূরণ গণনার পূর্ণ বিবরণ (RFCTLARR তফশিল ১)",
    colComponent: "উপাদান",
    colStatutoryBasis: "আইনি ভিত্তি",
    colCalculation: "গণনার পদ্ধতি",
    colAmount: "পরিমাণ (₹)",
    rowBaseLandVal: "মূল বাজার দর",
    rowBaseLandValDesc: "বিগত ৩ বছরের গড় নিবন্ধিত মূল্যের ভিত্তিতে",
    rowMultiFactor: "গ্রামীণ গুণক ফ্যাক্টর (১.৫x)",
    rowMultiFactorDesc: "RFCTLARR আইনের ধারা ২৬(২) গ্রামীণ নিয়ম",
    rowSolatium: "১০০% বাধ্যতামূলক তোষণ",
    rowSolatiumDesc: "ধারা ৩০(১) অনুযায়ী সমপরিমাণ তোষণ অনুদান",
    rowInterest: "১২% অতিরিক্ত বার্ষিক সুদ",
    rowInterestDesc: "ধারা ৩০(৩) অনুযায়ী বিজ্ঞপ্তি থেকে অ্যাওয়ার্ড পর্যন্ত",
    rowStructures: "কাঠামো ও ভবনের ক্ষতিপূরণ",
    rowStructuresDesc: "পূর্ত বিভাগের প্রকৌশল মূল্যায়ন",
    rowTrees: "গাছপালা ও ফসলের ক্ষতিপূরণ",
    rowTreesDesc: "বন ও উদ্যানপালন বিভাগের মূল্যায়ন",
    rowTotalNet: "মোট নিট ক্ষতিপূরণ অ্যাওয়ার্ড",
    paymentDistributionTitle: "PFMS সরাসরি সুবিধা হস্তান্তর (DBT) বিতরণ",
    linkedBankCard: "সংযুক্ত আধার ব্যাংক অ্যাকাউন্ট:",
    ifscCard: "IFSC কোড:",
    pfmsTxnCard: "PFMS লেনদেন ID:",
    disbursedDateCard: "জমা হওয়ার তারিখ:",
    paymentProgressLabel: "বিতরণ অগ্রগতি:",
    rrEntitlementsTitle: "পুনর্বাসন ও পুনর্সংস্থাপন (R&R) সুবিধাসমূহ (তফশিল ২)",
    rrResettlementHouse: "বিকল্প বাসস্থান / প্লট বরাদ্দ",
    rrResettlementHouseDesc: "প্রধানমন্ত্রী আবাস যোজনা অনুযায়ী পাকা বাড়ি বা সমপরিমাণ অর্থ।",
    rrSubsistence: "জীবনধারণ অনুদান (মাসিক ভাতা)",
    rrSubsistenceDesc: "প্রভাবিত পরিবারকে মাসে ₹৩,০০০ করে ১২ মাস প্রদান।",
    rrTransport: "স্থানান্তর ও পরিবহন ভাতা",
    rrTransportDesc: "আসবাবপত্র পরিবহনের জন্য এককালীন ₹৫০,০০০ টাকা।",
    rrSkill: "দক্ষতা উন্নয়ন ও কর্মসংস্থান",
    rrSkillDesc: "পরিবারের একজন সদস্যকে দক্ষতা প্রশিক্ষণ ও কর্মসংস্থান সহায়তা।",
    disputeNoticeText: "স্মরণ রাখবেন: গণনায় আপত্তি থাকলে অ্যাওয়ার্ড জারির ৬০ দিনের মধ্যে ল্যান্ড অথরিটিতে (LARRA) আপিল করা যাবে।",
    fileCompGrievanceBtn: "ক্ষতিপূরণে আপত্তি / আপিল দাখিল",
    documentsPageTitle: "ডিজিটাল নথি ভল্ট",
    documentsPageSubtitle: "জমি অধিগ্রহণ সংক্রান্ত সকল যাচাইকৃত সরকারি নথিপত্র।",
    uploadDocBtn: "নতুন নথি আপলোড করুন",
    allDocTypesFilter: "সকল নথির ধরন",
    docTitleLandRecords: "জমির স্বত্বাধিকার রেকর্ড (খতিয়ান / পরচা)",
    docTitleGovNotices: "সরকারি গেজেট বিজ্ঞপ্তি",
    docTitleIdentityProof: "পরিচয় ও ঠিকানার প্রমাণপত্র",
    docTitleBankPassbook: "ব্যাংক পাসবই ও অ্যাকাউন্ট বিবরণ",
    docTitleClaimReceipts: "দাবি রসিদ ও অ্যাওয়ার্ড আদেশ",
    docTableColName: "নথির নাম",
    docTableColType: "বিভাগ",
    docTableColDate: "আপলোডের তারিখ",
    docTableColStatus: "যাচাই স্থিতি",
    docTableColActions: "পদক্ষেপ",
    viewDocumentAction: "দেখুন",
    downloadDocumentAction: "ডাউনলোড",
    explainWithAiAction: "AI দিয়ে বুঝুন",
    deleteDocumentAction: "মুছুন",
    docStatusVerified: "যাচাইকৃত",
    docStatusPending: "যাচাই প্রক্রিয়াধীন",
    actionCenterPageTitle: "নাগরিক কার্যক্রম কেন্দ্র ও সময়সীমা",
    actionCenterPageSubtitle: "আপনার করণীয় কাজ, সরকারি নোটিশ ও আইনি সময়সীমা পরিচালনা।",
    urgentActionsTitle: "জরুরি আইনি কার্যক্রম",
    upcomingDeadlinesTitle: "আসন্ন সময়সীমা ও শুনানি",
    completedHistoryTitle: "সম্পন্ন কার্যক্রম",
    actionDueLabel: "শেষ তারিখ:",
    daysLeftLabel: "দিন বাকি",
    actionCompletedBadge: "সম্পন্ন",
    actionPendingBadge: "পদক্ষেপ প্রয়োজনীয়",
    btnCompleteAction: "কার্যক্রম সম্পন্ন করুন",
    btnViewNoticeDetails: "নোটিশের বিবরণ",
    grievancesPageTitle: "নাগরিক অভিযোগ ও ধারা ১৫ আপত্তি",
    grievancesPageSubtitle: "জমি অধিগ্রহণ প্রক্রিয়া, ক্ষেত্রফল বা ক্ষতিপূরণে আপত্তি দাখিল।",
    submitNewGrievanceBtn: "নতুন আপত্তি / অভিযোগ দাখিল",
    trackGrievancesHeading: "দাখিলকৃত আপত্তির বর্তমান স্থিতি",
    grievanceModalTitle: "নতুন আপত্তি দাখিল করুন",
    grievanceTypeLabel: "আপত্তির শ্রেণিবিভাগ",
    selectGrievanceTypePlaceholder: "শ্রেণি নির্বাচন করুন",
    optCompensationDispute: "ক্ষতিপূরণ গণনায় অসন্তোষ",
    optAreaDiscrepancy: "ক্ষেত্রফল পরিমাপে অমিল (ধারা ১৫)",
    optOwnershipDispute: "মালিকানা বিরোধ বা নাম সংশোধন",
    optPaymentDelay: "ক্ষতিপূরণ প্রাপ্তিতে বিলম্ব (DBT/PFMS)",
    optRRDispute: "পুনর্বাসন সুবিধা (R&R) না পাওয়া",
    optOther: "অন্যান্য প্রশাসনিক সমস্যা",
    grievanceDescLabel: "আপত্তির পূর্ণ বিবরণ",
    grievanceDescPlaceholder: "আপনার সমস্যা বিস্তারিত লিখুন...",
    supportingDocsLabel: "প্রমাণ নথি সংযুক্ত করুন (PDF, JPG - সর্বোচ্চ ১০MB)",
    submitGrievanceConfirmBtn: "দাখিল করুন",
    grievanceTicketLabel: "টোকেন নম্বর:",
    assignedOfficerLabel: "নিষ্পত্তি আধিকারিক:",
    expectedResolutionLabel: "সম্ভাব্য নিষ্পত্তির তারিখ:",
    hearingScheduleLabel: "শুনানির তারিখ:",
    officerRemarksLabel: "আধিকারিকের মন্তব্য:",
    noticesPageTitle: "বিজ্ঞপ্তি ও সরকারি গেজেট ঘোষণা",
    noticesPageSubtitle: "জমি অধিগ্রহণ সংক্রান্ত সর্বশেষ সরকারি বিজ্ঞপ্তি।",
    filterUnreadOnly: "না পড়া বিজ্ঞপ্তি",
    btnMarkAllAsRead: "সব পড়া হয়েছে চিহ্নিত করুন",
    noticeCardDateLabel: "তারিখ:",
    noticeCardSectionLabel: "আইনি ধারা:",
    noticeCardDownloadGazetteBtn: "গেজেট ডাউনলোড করুন",
    noticeCardExplainAiBtn: "AI দিয়ে বুঝুন",
    officerDashboardTitle: "ভূমি অধিগ্রহণ আধিকারিক (LAO) প্রশাসনিক কেন্দ্র",
    officerDashboardSubtitle: "প্রকল্পের দাগ, ধারা ১৫ আপত্তি ও ক্ষতিপূরণ বিতরণ পরিচালনা।",
    metricTotalAcquisitions: "মোট অধিগ্রহণ প্রকল্প",
    metricTotalParcels: "বিজ্ঞাপিত জমির দাগ",
    metricDisbursedBudget: "বিতরণকৃত ক্ষতিপূরণ বাজেট",
    metricPendingReviews: "পর্যালোচনার অপেক্ষায় ফাইল",
    officerSectionCases: "প্রকল্প মামলার রেজিস্ট্রি",
    officerSectionGrievances: "নাগরিক আপত্তি ও শুনানির সারি",
    tableColCaseId: "মামলা ID",
    tableColProject: "প্রকল্পের নাম",
    tableColVillage: "মৌজা",
    tableColLandowner: "মালিক",
    tableColSurvey: "দাগ নং",
    tableColArea: "ক্ষেত্রফল (হেক্টর)",
    tableColStage: "আইনি পর্যায়",
    tableColCompStatus: "ক্ষতিপূরণ স্থিতি",
    tableColAction: "পদক্ষেপ",
    btnReviewCase: "মামলা পর্যালোচনা",
    btnUpdateStatus: "স্থিতি পরিবর্তন",
    btnScheduleHearing: "শুনানির তারিখ নির্ধারণ",
    btnDisbursePayment: "DBT অর্থ বরাদ্দ",
    resolveGrievanceBtn: "নিষ্পত্তি আদেশ জারি",
    officerCasesTitle: "প্রকল্প মামলার মাস্টার রেজিস্ট্রি",
    officerCasesSub: "গেজেট নোটিশ, জরিপ ও ক্ষতিপূরণ অ্যাওয়ার্ড নিয়ন্ত্রণ ব্যবস্থা।",
    searchCasePlaceholder: "মামলা ID, দাগ নম্বর বা মালিকের নাম দিয়ে খুঁজুন...",
    filterAllStages: "সকল আইনি পর্যায়",
    stageVerification: "যাচাইকরণ পর্যায়",
    stageHearing: "ধারা ১৫ শুনানি",
    stageAward: "ধারা ২৩ অ্যাওয়ার্ড আদেশ",
    stagePayment: "DBT অর্থ স্থানান্তর",
    stagePossession: "দখল গ্রহণ",
    caseOfficerNotesLabel: "আধিকারিকের পর্যবেক্ষণ ও আদেশের বিবরণ",
    saveStatusUpdateBtn: "সংরক্ষণ করুন",
    noticeLabel: "জরুরি নোটিশ:",
    tickerAdvisory: "নাগরিক বার্তা: জমি অধিগ্রহণ স্থিতি ও ক্ষতিপূরণ অনলাইনে যাচাই করুন।",
    tickerDocIntel: "নতুন সুবিধা: গেজেট নোটিশ আপলোড করে AI দ্বারা সহজ ব্যাখ্যা পান।",
    tickerObjections: "সতর্কতা: ধারা ১১(১) প্রকাশের ৬০ দিনের মধ্যে ধারা ১৫ আপত্তি দাখিল করুন।",
    tickerDbt: "PFMS DBT: ক্ষতিপূরণ সরাসরি আধার সংযুক্ত ব্যাংক অ্যাকাউন্টে জমা হবে।",
    footerTagline: "ভূমি অধিগ্রহণ, ক্ষতিপূরণ ও পুনর্বাসনের স্বচ্ছ জাতীয় নাগরিক পোর্টাল",
    footerDescription: "RFCTLARR আইন ২০১৩ অনুযায়ী পরিচালিত স্বচ্ছ নাগরিক তথ্য ব্যবস্থা।",
    footerHelplineLabel: "জাতীয় ভূমি অধিকার হেল্পলাইন:",
    footerServicesTitle: "নাগরিক সেবা",
    footerServiceFindLand: "জমি সন্ধান",
    footerServiceDocIntel: "AI নথি বিশ্লেষণ",
    footerServiceGis: "GIS মানচিত্র",
    footerServiceComp: "ক্ষতিপূরণ মূল্যায়ন",
    footerServiceActions: "কার্যক্রম কেন্দ্র",
    footerServiceGrievances: "ধারা ১৫ আপত্তি",
    footerStatutoryTitle: "আইনি বিধিমালিকা",
    footerStatutoryAct: "RFCTLARR আইন, ২০১৩",
    footerStatutorySec11: "ধারা ১১(১) প্রাথমিক বিজ্ঞপ্তি",
    footerStatutorySec15: "ধারা ১৫ আপত্তির অধিকার",
    footerStatutorySec19: "ধারা ১৯ চূড়ান্ত ঘোষণা",
    footerStatutorySec23: "ধারা ২৩ ক্ষতিপূরণ অ্যাওয়ার্ড",
    footerStatutoryPfms: "PFMS সরাসরি অর্থ স্থানান্তর",
    footerAssistanceTitle: "সাহায্য ও যোগাযোগ",
    footerAddress: "কেন্দ্রীয় ভূমি রাজস্ব ও জাতীয় মহাসড়ক কর্তৃপক্ষ, নতুন দিল্লি",
    footerTollFree: "টোল ফ্রি হেল্পলাইন: 1800-180-LAND (5263)",
    footerEmail: "ইমেল: support@sahaay.gov.in",
    footerCopyright: "© 2026 সহায় (SAHAAY) • ভারত সরকার। সর্বস্বত্ব সংরক্ষিত।",
    footerDemoDisclaimer: "এই পোর্টালটি ডেমো তথ্যাবলি সংবলিত প্রাতিষ্ঠানিক নাগরিক সেবা প্ল্যাটফর্ম।"
  };

  writeLocaleFile('bn', 'Bengali (বাংলা)', t);
}

// ============================================================================
// 2. MARATHI (मराठी - mr)
// ============================================================================
export function generateMarathi() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: "सहाय (SAHAAY)",
    emblemLetter: "स",
    tagline: "तुमची जमीन. तुमचे प्रकरण. तुमचा हक्क.",
    heroSub: "जमीन संपादन, भरपाई आणि पुनर्वसन नागरिक साहाय्यता पोर्टल",
    portalSubtitle: "जमीन • भरपाई • पुनर्वसन (R&R) • तक्रारी • प्रकरण ट्रॅकिंग",
    citizenPortal: "नागरिक पोर्टल",
    officerPortal: "जमीन संपादन अधिकारी पोर्टल",
    demoMode: "डेमो मोड सक्रिय",
    signIn: "लॉग इन करा",
    signOut: "लॉग आउट",
    landowner: "जमीन मालक",
    landOfficer: "जमीन संपादन अधिकारी (LAO)",
    switchRole: "भूमिका बदला",
    switchCitizen: "नागरिक (राजेश शर्मा)",
    switchOfficer: "अधिकारी (विक्रम चौहान)",
    welcomeBack: "पुन्हा स्वागत आहे",
    navHome: "मुख्यपृष्ठ",
    navFindLand: "माझी जमीन शोधा",
    navGisMap: "GIS जमीन नकाशा",
    navDocIntel: "दस्तऐवज विश्लेषण (AI)",
    navCompensation: "भरपाई आणि पुनर्वसन",
    navDocuments: "दस्तऐवज लॉकर",
    navActionCenter: "कृती केंद्र",
    navGrievances: "तक्रार व निवारण",
    navNotices: "सूचना व इशारे",
    navOfficerDashboard: "अधिकारी डॅशबोर्ड",
    navCasesRegistry: "प्रकरण नोंदवही",
    navGrievancesQueue: "तक्रार रांग",
    citizenServices: "नागरिक सेवा",
    quickActions: "जलद कृती",
    submit: "सादर करा",
    save: "जतन करा",
    cancel: "रद्द करा",
    edit: "संपादित करा",
    delete: "हटवा",
    search: "शोधा",
    filter: "फिल्टर",
    back: "मागे",
    next: "पुढे",
    close: "बंद करा",
    view: "पहा",
    download: "डाउनलोड",
    upload: "अपलोड करा",
    export: "निर्यात",
    refresh: "ताजे करा",
    print: "मुद्रित करा",
    loading: "लोड होत आहे...",
    actions: "कृती",
    details: "तपशील",
    status: "स्थिती",
    viewDetails: "तपशील पहा",
    viewOnMap: "नकाशावर पहा",
    viewCase: "पूर्ण प्रकरण पहा",
    trackProgress: "प्रगती ट्रॅक करा",
    proceed: "पुढे चला",
    confirm: "पुष्टी करा",
    retry: "पुन्हा प्रयत्न करा",
    clearAll: "सर्व साफ करा",
    applyFilter: "फिल्टर लागू करा",
    active: "सक्रिय",
    pending: "प्रलंबित",
    completed: "पूर्ण झाले",
    resolved: "निकाली काढले",
    inProgress: "प्रगतीपथावर",
    actionRequired: "कृती आवश्यक",
    verified: "सत्यापित",
    all: "सर्व",
    noData: "माहिती उपलब्ध नाही",
    noResults: "कोणतेही निकाल आढळले नाहीत",
    loadingData: "माहिती लोड होत आहे...",
    somethingWentWrong: "काहीतरी चूक झाली",
    tryAgain: "कृपया पुन्हा प्रयत्न करा",
    errorOccurred: "त्रुटी आली",
    help: "मदत व वारंवार विचारले जाणारे प्रश्न",
    helpdesk: "मदत केंद्र",
    helpline: "1800-180-LAND",
    tollFree: "टोल फ्री राष्ट्रीय हेल्पलाइन",
    rightsReserved: "सर्व हक्क राखीव",
    status_ACTIVE: "सक्रिय",
    status_COMPLETED: "पूर्ण झाले",
    status_VERIFIED: "सत्यापित",
    status_PAID: "वितरित (DBT)",
    status_SANCTIONED: "मंजूर",
    status_RESOLVED: "निकाली काढले",
    status_ELIGIBLE: "पात्र",
    status_VERIFICATION: "पडताळणी टप्पा",
    status_IN_PROGRESS: "प्रगतीपथावर",
    status_UNDER_REVIEW: "पुनरावलोकनाखाली",
    status_CURRENT: "सध्याची स्थिती",
    status_PROCESSING: "प्रक्रिया सुरू",
    status_ACTION_REQUIRED: "कृती आवश्यक",
    status_UPCOMING: "आगामी",
    status_PENDING: "प्रलंबित",
    status_REJECTED: "नाकारले",
    status_FAILED: "अयशस्वी",
    status_DEPOSITED_PFMS: "PFMS जमा झाले",
    status_CLAIM_SUBMITTED: "दावा सादर केला",
    status_DISCREPANCY_FLAGGED: "तफावत आढळली",
    status_RESPONSE_ADDED: "उत्तर जोडले",
    status_AWAITING_HEARING: "सुनावणीच्या प्रतीक्षेत",
    status_CLOSED: "प्रकरण बंद",
    status_ASSESSED: "मूल्यांकन केले",
    status_APPROVED: "मंजूर केले",
    status_DISCREPANCY_FOUND: "तफावत सापडली",
    status_DISPUTED: "विवादित",
    status_HIGH: "उच्च प्राधान्य",
    status_SUBMITTED: "सादर केले",
    status_UNPAID: "अदत्त",
    status_PROPOSAL: "प्रस्ताव टप्पा",
    status_NOTIFICATION: "अधिसूचना टप्पा",
    welcomeTitle: "सहाय (SAHAAY) पोर्टलवर स्वागत आहे",
    welcomeSub: "जमीन संपादन आणि भरपाई ट्रॅक करण्यासाठी लॉग इन करा.",
    demoAccountsTitle: "डेमो खाते निवडा",
    demoBadge: "डेमो मोड",
    demoCitizenTitle: "🌾 नागरिक / जमीन मालक",
    demoCitizenSub: "राजेश शर्मा (गट #१०४२)",
    demoOfficerTitle: "🏛️ जमीन संपादन अधिकारी (LAO)",
    demoOfficerSub: "विक्रम चौहान (भोपाळ मंडळ)",
    tabSignIn: "लॉग इन करा",
    tabRegister: "नागरिक नोंदणी",
    fullNameLabel: "पूर्ण नाव (नोंदणीनुसार)",
    fullNamePlaceholder: "उदा. राजेश शर्मा",
    villageLabel: "गाव",
    districtLabel: "जिल्हा",
    emailLabel: "ईमेल / मोबाईल नंबर",
    emailPlaceholder: "name@sahaay.demo",
    passwordLabel: "पासवर्ड",
    passwordPlaceholder: "••••••••",
    verifyingBtn: "पडताळणी होत आहे...",
    createAccountBtn: "खाते तयार करा",
    signInBtn: "सुरक्षित लॉग इन करा",
    demoFillBtn: "डेमो माहिती भरा",
    loginErrorDefault: "लॉग इन अयशस्वी. कृपया माहिती तपासा.",
    registerSuccessToast: "खाते यशस्वीरित्या तयार झाले! लॉग इन करा.",
    quickAccessSection: "जलद नागरिक सेवा",
    findLandCardTitle: "माझी जमीन शोधा",
    findLandCardDesc: "गट क्रमांक व गावावरून संपादन स्थिती तपासा.",
    docIntelCardTitle: "AI दस्तऐवज विश्लेषण",
    docIntelCardDesc: "संपादन नोटीस अपलोड करून सोपे स्पष्टीकरण मिळवा.",
    gisMapCardTitle: "GIS प्रकल्प नकाशा",
    gisMapCardDesc: "महामार्ग संरेखन व जमिनीच्या सीमा सॅटेलाइटवर पहा.",
    compensationCardTitle: "भरपाई मूल्यांकन",
    compensationCardDesc: "RFCTLARR कायद्यानुसार १००% सोलेशियम व DBT स्थिती पहा.",
    actionCenterCardTitle: "कृती केंद्र",
    actionCenterCardDesc: "वैधानिक मुदती व प्रलंबित कामे व्यवस्थापित करा.",
    grievancesCardTitle: "तक्रारी व हरकती",
    grievancesCardDesc: "कलम १५ हरकती व भरपाई विवाद दाखल करा.",
    summaryParcelsCount: "जोडलेले गट क्रमांक",
    summaryActiveAcquisitions: "सक्रिय संपादन प्रक्रिया",
    summaryTotalAssessedComp: "एकूण निर्धारित भरपाई",
    summaryPendingActions: "तातडीची प्रलंबित कामे",
    timelineTitle: "वैधानिक संपादन प्रगती",
    timelineSub: "RFCTLARR कायदा २०१३ नुसार प्रकरणाचे टप्पे",
    stepSec11: "कलम ११(१) प्राथमिक अधिसूचना",
    stepSec15: "कलम १५ सुनावणी व हरकती",
    stepSec19: "कलम १९ अंतिम घोषणा",
    stepSec23: "कलम २३ भरपाई निवाडा",
    stepPayment: "PFMS भरपाई वितरण",
    stepPossession: "ताबा व पुनर्वसन",
    discrepancyBannerTitle: "सूचना: गट #१०४२ च्या क्षेत्रफळात तफावत आढळली आहे",
    discrepancyBannerDesc: "नोटीसमधील क्षेत्रफळ (१.१० हेक्टर) महसूल नोंदीपेक्षा कमी आहे. कलम १५(१) अंतर्गत ६० दिवसांत हरकत नोंदवा.",
    reviewDiscrepancyBtn: "तफावत पुनरावलोकन",
    fileObjectionBtn: "हरकत नोंदवा",
    findLandTitle: "गट क्रमांकाद्वारे जमीन शोध",
    findLandSubtitle: "महामार्ग किंवा रेल्वे प्रकल्पांतर्गत बाधित जमीन त्वरित शोधा.",
    surveyInputLabel: "गट क्रमांक / सर्व्हे नंबर",
    surveyInputPlaceholder: "उदा. १०४२ किंवा ४५/अ",
    villageSelectLabel: "गाव",
    allVillagesOption: "सर्व गावे",
    districtSelectLabel: "जिल्हा",
    allDistrictsOption: "सर्व जिल्हे",
    searchLandSubmitBtn: "जमीन शोधा",
    searchResultsHeading: "शोधाचे निकाल",
    parcelCardSurveyLabel: "गट क्रमांक:",
    parcelCardVillageLabel: "गाव व जिल्हा:",
    parcelCardAreaLabel: "अधिसूचित क्षेत्रफळ:",
    parcelCardOwnerLabel: "मालकाचे नाव:",
    parcelCardProjectLabel: "प्रकल्प:",
    parcelCardStageLabel: "सध्याचा टप्पा:",
    parcelCardCompLabel: "निर्धारित भरपाई:",
    viewGisMapBtn: "GIS नकाशावर पहा",
    viewCompDetailsBtn: "भरपाई तपशील",
    noSearchResultsTitle: "कोणतीही जमीन नोंद आढळली नाही",
    noSearchResultsDesc: "योग्य गट क्रमांक व गाव तपासून पुन्हा प्रयत्न करा.",
    gisTitle: "परस्परसंवादी GIS प्रकल्प सीमा नकाशा",
    gisSubtitle: "संपादन संरेखन, बफर झोन व शेजारील गट क्रमांक पहा.",
    legendTitle: "नकाशा सूची",
    legendAcquired: "अधिसूचित संपादन क्षेत्र",
    legendBuffer: "प्रकल्प बफर क्षेत्र (५० मीटर)",
    legendYourLand: "तुमचा गट क्रमांक (#१०४२)",
    legendAdjacent: "शेजारील गट क्रमांक",
    mapLayerControl: "नकाशा स्तर",
    layerSatellite: "सॅटेलाइट दृश्य",
    layerCadastral: "महसूल नकाशा (Cadastral)",
    layerProjectAlign: "प्रकल्प संरेखन रेषा",
    parcelInfoPanelTitle: "निवडलेल्या गटाची माहिती",
    infoSurveyNo: "गट क्रमांक",
    infoVillage: "गाव व तालुका",
    infoTotalArea: "एकूण क्षेत्रफळ",
    infoAcquiredArea: "संपादित क्षेत्रफळ",
    infoOwner: "मालकाचे नाव",
    infoStatus: "संपादन स्थिती",
    infoEstimatedVal: "निर्धारित भरपाई",
    measureDistanceBtn: "अंतर मोजा",
    measureAreaBtn: "क्षेत्रफळ मोजा",
    clearMeasureBtn: "मापे पुसा",
    docIntelTitleFull: "AI सरकारी दस्तऐवज विश्लेषण इंजिन",
    docIntelSubtitle: "जमीन संपादन गॅझेट नोटिसांचे सोप्या भाषेत स्पष्टीकरण मिळवा.",
    uploadZoneTitle: "नोटीस किंवा निवाडा दस्तऐवज अपलोड करा",
    uploadZoneSubtitle: "PDF, JPG किंवा PNG फाईल निवडा (कमाल २५MB)",
    sampleNoticesTitle: "किंवा नमुना नोटिसा तपासा:",
    sampleSec11Btn: "📄 कलम ११(१) नोटीस (गट #१०४२)",
    sampleAwardBtn: "📄 कलम २३ निवाडा आदेश",
    sampleSec19Btn: "📄 कलम १९(१) घोषणा नोटीस",
    analysisResultsTitle: "AI दस्तऐवज विश्लेषण सारांश",
    docTypeDetected: "दस्तऐवजाचा प्रकार",
    gazetteRefNo: "गॅझेट संदर्भ क्रमांक",
    issuingAuthority: "जारी करणारे प्राधिकरण",
    issueDate: "प्रसिद्धी तारीख",
    affectedVillage: "बाधित गाव व जिल्हा",
    statutorySection: "लागू कायदेशीर कलम",
    keyFindingsHeading: "मुख्य मुद्दे (सोप्या भाषेत):",
    detectedDiscrepanciesTitle: "⚠️ आढळलेल्या तफावती व हरकती:",
    actionableStepsHeading: "तुमच्यासाठी पुढील पावले:",
    confidenceScoreLabel: "AI अचूकता प्रमाण:",
    downloadAnalysisReportBtn: "पूर्ण AI अहवाल डाउनलोड करा",
    fileObjectionFromDocBtn: "या नोटिसीवर हरकत नोंदवा",
    compPageTitle: "वैधानिक भरपाई आणि पुनर्वसन (R&R) फायदे",
    compPageSubtitle: "RFCTLARR कायदा २०१३ नुसार पूर्ण भरपाई, सोलेशियम व DBT वितरण.",
    assessedLandValueCard: "मूळ जमीन मूल्यांकन",
    solatium100Card: "१००% सोलेशियम (दिलासा रक्कम)",
    statutoryInterestCard: "१२% अतिरिक्त वार्षिक व्याज",
    totalCompensationCard: "एकूण निवाडा भरपाई",
    compBreakdownTitle: "भरपाई गणनेचे सविस्तर विवरण (RFCTLARR अनुसूची १)",
    colComponent: "घटक",
    colStatutoryBasis: "कायदेशीर आधार",
    colCalculation: "गणना पद्धत",
    colAmount: "रक्कम (₹)",
    rowBaseLandVal: "मूळ बाजारभाव मूल्य",
    rowBaseLandValDesc: "मागील ३ वर्षांच्या सरासरी नोंदणी मूल्यावर आधारित",
    rowMultiFactor: "ग्रामीण गुणांक घटक (१.५x)",
    rowMultiFactorDesc: "RFCTLARR कायद्याचे कलम २६(२) ग्रामीण नियम",
    rowSolatium: "१००% अनिवार्य सोलेशियम",
    rowSolatiumDesc: "कलम ३०(१) नुसार सममूल्य सोलेशियम रक्कम",
    rowInterest: "१२% अतिरिक्त वार्षिक व्याज",
    rowInterestDesc: "कलम ३०(३) नुसार अधिसूचनेपासून निवाड्यापर्यंत",
    rowStructures: "इमारती व बांधकामांची भरपाई",
    rowStructuresDesc: "सार्वजनिक बांधकाम विभागाचे मूल्यांकन",
    rowTrees: "झाडे व पिकांची भरपाई",
    rowTreesDesc: "वन व कृषी विभागाचे मूल्यांकन",
    rowTotalNet: "एकूण निವ್ವळ निवाडा भरपाई",
    paymentDistributionTitle: "PFMS थेट लाभ हस्तांतरण (DBT) वितरण",
    linkedBankCard: "जोडलेले आधार बँक खाते:",
    ifscCard: "IFSC कोड:",
    pfmsTxnCard: "PFMS व्यवहार ID:",
    disbursedDateCard: "जमा झाल्याची तारीख:",
    paymentProgressLabel: "वितरण प्रगती:",
    rrEntitlementsTitle: "पुनर्वसन आणि पुनर्स्थापना (R&R) फायदे (अनुसूची २)",
    rrResettlementHouse: "पर्यायी घर / भूखंड वाटप",
    rrResettlementHouseDesc: "प्रधानमंत्री आवास योजनेनुसार पक्के घर किंवा सममूल्य भरपाई रक्कम.",
    rrSubsistence: "निर्वाह अनुदान (मासिक भत्ता)",
    rrSubsistenceDesc: "बाधित कुटुंबास दरमहा ₹३,००० प्रमाणे १२ महिन्यांसाठी भत्ता.",
    rrTransport: "स्थलांतर व वाहतूक भत्ता",
    rrTransportDesc: "घरगुती साहित्याच्या वाहतुकीसाठी एकरकमी ₹५०,०००.",
    rrSkill: "कौशल्य प्रशिक्षण व रोजगार",
    rrSkillDesc: "कुटुंबातील एका सदस्यास कौशल्य विकास प्रशिक्षण व रोजगार साहाय्य.",
    disputeNoticeText: "लक्षात ठेवा: गणनेवर आक्षेप असल्यास निवाडा जारी झाल्यापासून ६० दिवसांत लँड अथॉरिटी (LARRA) कडे अपील करता येते.",
    fileCompGrievanceBtn: "भरपाईवर हरकत / अपील दाखल करा",
    documentsPageTitle: "डिजिटल दस्तऐवज लॉकर",
    documentsPageSubtitle: "जमीन संपादनाशी संबंधित सर्व सत्यापित सरकारी दस्तऐवज.",
    uploadDocBtn: "नवीन दस्तऐवज अपलोड करा",
    allDocTypesFilter: "सर्व दस्तऐवज प्रकार",
    docTitleLandRecords: "जमीन मालकी हक्क (७/१२ / फेरफार)",
    docTitleGovNotices: "सरकारी गॅझेट अधिसूचना",
    docIdentityProof: "ओळख व पत्त्याचा पुरावा",
    docTitleBankPassbook: "बँक खाते तपशील",
    docTitleClaimReceipts: "दावा पावत्या व निवाडा आदेश",
    docTableColName: "दस्तऐवजाचे नाव",
    docTableColType: "प्रवर्ग",
    docTableColDate: "अपलोड तारीख",
    docTableColStatus: "पडताळणी स्थिती",
    docTableColActions: "कृती",
    viewDocumentAction: "पहा",
    downloadDocumentAction: "डाउनलोड",
    explainWithAiAction: "AI ने समजून घ्या",
    deleteDocumentAction: "हटवा",
    docStatusVerified: "सत्यापित",
    docStatusPending: "पडताळणी प्रलंबित",
    actionCenterPageTitle: "नागरिक कृती केंद्र आणि मुदती",
    actionCenterPageSubtitle: "तुमच्याकडील प्रलंबित कामे, सरकारी नोटिसा व कायदेशीर मुदतीचे व्यवस्थापन.",
    urgentActionsTitle: "तातडीच्या कायदेशीर कृती",
    upcomingDeadlinesTitle: "आगामी मुदती व सुनावणी",
    completedHistoryTitle: "पूर्ण केलेल्या कृती",
    actionDueLabel: "अंतिम मुदत:",
    daysLeftLabel: "दिवस शिल्लक",
    actionCompletedBadge: "पूर्ण",
    actionPendingBadge: "कृती आवश्यक",
    btnCompleteAction: "कृती पूर्ण करा",
    btnViewNoticeDetails: "नोटीस तपशील",
    grievancesPageTitle: "नागरिक तक्रारी व कलम १५ हरकती",
    grievancesPageSubtitle: "संपादन प्रक्रिया, क्षेत्रफळ किंवा भरपाईवर हरकती दाखल करा.",
    submitNewGrievanceBtn: "नवीन हरकत / तक्रार दाखल करा",
    trackGrievancesHeading: "दाखल केलेल्या हरकतींची सद्यस्थिती",
    grievanceModalTitle: "नवीन हरकत दाखल करा",
    grievanceTypeLabel: "हरकतीचा प्रवर्ग",
    selectGrievanceTypePlaceholder: "प्रवर्ग निवडा",
    optCompensationDispute: "भरपाई रकमेबाबत आक्षेप",
    optAreaDiscrepancy: "क्षेत्रफळ मोजणीत तफावत (कलम १५)",
    optOwnershipDispute: "मालकी हक्क किंवा नाव दुरुस्ती",
    optPaymentDelay: "भरपाई मिळण्यात विलंब (DBT/PFMS)",
    optRRDispute: "पुनर्वसन फायदे (R&R) न मिळणे",
    optOther: "इतर प्रशासकीय अडचणी",
    grievanceDescLabel: "हरकतीचे सविस्तर वर्णन",
    grievanceDescPlaceholder: "तुमची समस्या सविस्तर लिहा...",
    supportingDocsLabel: "पुरावा दस्तऐवज जोडा (PDF, JPG - कमाल १०MB)",
    submitGrievanceConfirmBtn: "दाखल करा",
    grievanceTicketLabel: "टोकन क्रमांक:",
    assignedOfficerLabel: "निवारण अधिकारी:",
    expectedResolutionLabel: "अपेक्षित निकाल तारीख:",
    hearingScheduleLabel: "सुनावणी तारीख:",
    officerRemarksLabel: "अधिकाऱ्याची टिप्पणी:",
    noticesPageTitle: "सूचना व सरकारी गॅझेट घोषणा",
    noticesPageSubtitle: "जमीन संपादनासंबंधी अद्ययावत सरकारी सूचना.",
    filterUnreadOnly: "न वाचलेल्या सूचना",
    btnMarkAllAsRead: "सर्व वाचले म्हणून चिन्हांकित करा",
    noticeCardDateLabel: "तारीख:",
    noticeCardSectionLabel: "कायदेशीर कलम:",
    noticeCardDownloadGazetteBtn: "गॅझेट डाउनलोड करा",
    noticeCardExplainAiBtn: "AI ने समजून घ्या",
    officerDashboardTitle: "जमीन संपादन अधिकारी (LAO) नियंत्रण केंद्र",
    officerDashboardSubtitle: "प्रकल्पातील गट, कलम १५ हरकती व भरपाई वाटप व्यवस्थापन.",
    metricTotalAcquisitions: "एकूण संपादन प्रकल्प",
    metricTotalParcels: "अधिसूचित गट क्रमांक",
    metricDisbursedBudget: "वितरित भरपाई बजेट",
    metricPendingReviews: "पुनरावलोकनासाठी फायली",
    officerSectionCases: "प्रकल्प प्रकरण नोंदवही",
    officerSectionGrievances: "नागरिक हरकती व सुनावणी रांग",
    tableColCaseId: "प्रकरण ID",
    tableColProject: "प्रकल्पाचे नाव",
    tableColVillage: "गाव",
    tableColLandowner: "मालक",
    tableColSurvey: "गट क्र.",
    tableColArea: "क्षेत्रफळ (हेक्टर)",
    tableColStage: "कायदेशीर टप्पा",
    tableColCompStatus: "भरपाई स्थिती",
    tableColAction: "कृती",
    btnReviewCase: "प्रकरण तपासा",
    btnUpdateStatus: "स्थिती बदला",
    btnScheduleHearing: "सुनावणी तारीख ठरवा",
    btnDisbursePayment: "DBT निधी मंजूर करा",
    resolveGrievanceBtn: "निवारण आदेश जारी करा",
    officerCasesTitle: "प्रकल्प प्रकरणांची मास्टर नोंदवही",
    officerCasesSub: "गॅझेट नोटिसा, मोजणी व भरपाई निवाडे व्यवस्थापन प्रणाली.",
    searchCasePlaceholder: "प्रकरण ID, गट क्रमांक किंवा मालकाच्या नावाने शोधा...",
    filterAllStages: "सर्व कायदेशीर टप्पे",
    stageVerification: "पडताळणी टप्पा",
    stageHearing: "कलम १५ सुनावणी",
    stageAward: "कलम २३ निवाडा आदेश",
    stagePayment: "DBT निधी हस्तांतरण",
    stagePossession: "ताबा घेणे",
    caseOfficerNotesLabel: "अधिकाऱ्याची टिप्पणी व आदेश तपशील",
    saveStatusUpdateBtn: "जतन करा",
    noticeLabel: "महत्त्वाची सूचना:",
    tickerAdvisory: "नागरिक संदेश: जमीन संपादन स्थिती व भरपाई ऑनलाइन तपासा.",
    tickerDocIntel: "नवीन सुविधा: गॅझेट नोटीस अपलोड करा व AI सोपे स्पष्टीकरण मिळवा.",
    tickerObjections: "वैधानिक इशारा: कलम ११(१) प्रसिद्धीनंतर ६० दिवसांत कलम १५ हरकती नोंदवा.",
    tickerDbt: "PFMS DBT: भरपाई रक्कम थेट आधार लिंक बँक खात्यात जमा केली जाते.",
    footerTagline: "जमीन संपादन, भरपाई व पुनर्वसनाचे पारदर्शक राष्ट्रीय नागरिक पोर्टल",
    footerDescription: "RFCTLARR कायदा २०१३ अंतर्गत चालवली जाणारी पारदर्शक नागरिक माहिती प्रणाली.",
    footerHelplineLabel: "राष्ट्रीय जमीन हक्क हेल्पलाइन:",
    footerServicesTitle: "नागरिक सेवा",
    footerServiceFindLand: "जमीन शोधा",
    footerServiceDocIntel: "AI दस्तऐवज विश्लेषण",
    footerServiceGis: "GIS नकाशा",
    footerServiceComp: "भरपाई मूल्यांकन",
    footerServiceActions: "कृती केंद्र",
    footerServiceGrievances: "कलम १५ हरकती",
    footerStatutoryTitle: "वैधानिक तरतुदी",
    footerStatutoryAct: "RFCTLARR कायदा, २०१३",
    footerStatutorySec11: "कलम ११(१) प्राथमिक अधिसूचना",
    footerStatutorySec15: "कलम १५ हरकतींचा हक्क",
    footerStatutorySec19: "कलम १९ अंतिम घोषणा",
    footerStatutorySec23: "कलम २३ भरपाई निवाडा",
    footerStatutoryPfms: "PFMS थेट लाभ हस्तांतरण",
    footerAssistanceTitle: "मदत व संपर्क",
    footerAddress: "केंद्रीय भू-महसूल व राष्ट्रीय महामार्ग प्राधिकरण, नवी दिल्ली",
    footerTollFree: "टोल फ्री हेल्पलाइन: 1800-180-LAND (5263)",
    footerEmail: "ईमेल: support@sahaay.gov.in",
    footerCopyright: "© 2026 सहाय (SAHAAY) • भारत सरकार. सर्व हक्क राखीव.",
    footerDemoDisclaimer: "हे पोर्टल नमुना माहितीसह उपलब्ध अधिकृत नागरिक सेवा व्यासपीठ आहे."
  };

  writeLocaleFile('mr', 'Marathi (मराठी)', t);
}

// ============================================================================
// 3. GUJARATI (ગુજરાતી - gu)
// ============================================================================
export function generateGujarati() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: "સહાય (SAHAAY)",
    emblemLetter: "સ",
    tagline: "તમારી જમીન. તમારો કેસ. તમારો અધિકાર.",
    heroSub: "જમીન સંપાદન, વળતર અને પુનર્વસન નાગરિક સહાયતા પોર્ટલ",
    portalSubtitle: "જમીન • વળતર • પુનર્વસન (R&R) • ફરિયાદો • કેસ ટ્રેકિંગ",
    citizenPortal: "નાગરિક પોર્ટલ",
    officerPortal: "જમીન સંપાદન અધિકારી પોર્ટલ",
    demoMode: "ડેમો મોડ સક્રિય",
    signIn: "લૉગ ઇન કરો",
    signOut: "લૉગ આઉટ",
    landowner: "જમીન માલિક",
    landOfficer: "જમીન સંપાદન અધિકારી (LAO)",
    switchRole: "રોલ બદલો",
    switchCitizen: "નાગરિક (રાજેશ શર્મા)",
    switchOfficer: "અધિકારી (વિક્રમ ચૌહાણ)",
    welcomeBack: "ફરી સ્વાગત છે",
    navHome: "મુખ્ય પૃષ્ઠ",
    navFindLand: "મારી જમીન શોધો",
    navGisMap: "GIS જમીન નકશો",
    navDocIntel: "દસ્તાવેજ વિશ્લેષણ (AI)",
    navCompensation: "વળતર અને પુનર્વસન",
    navDocuments: "દસ્તાવેજ લોકર",
    navActionCenter: "કાર્ય કેન્દ્ર",
    navGrievances: "ફરિયાદ નિવારણ",
    navNotices: "સૂચનાઓ અને ચેતવણીઓ",
    navOfficerDashboard: "અધિકારી ડેશબોર્ડ",
    navCasesRegistry: "કેસ રજિસ્ટ્રી",
    navGrievancesQueue: "ફરિયાદ કતાર",
    citizenServices: "નાગરિક સેવાઓ",
    quickActions: "ઝડપી ક્રિયાઓ",
    submit: "સબમિટ કરો",
    save: "સાચવો",
    cancel: "રદ કરો",
    edit: "સુધારો",
    delete: "કાઢી નાખો",
    search: "શોધો",
    filter: "ફિલ્ટર",
    back: "પાછા જાઓ",
    next: "આગળ",
    close: "બંધ કરો",
    view: "જુઓ",
    download: "ડાઉનલોડ",
    upload: "અપલોડ કરો",
    export: "નિકાસ",
    refresh: "રિફ્રેશ",
    print: "પ્રિન્ટ કરો",
    loading: "લોડ થઈ રહ્યું છે...",
    actions: "પગલાં",
    details: "વિગતો",
    status: "સ્થિતિ",
    viewDetails: "વિગતો જુઓ",
    viewOnMap: "નકશા પર જુઓ",
    viewCase: "સંપૂર્ણ કેસ જુઓ",
    trackProgress: "પ્રગતિ ટ્રેક કરો",
    proceed: "આગળ વધો",
    confirm: "પુષ્ટિ કરો",
    retry: "ફરી પ્રયાસ કરો",
    clearAll: "બધું સાફ કરો",
    applyFilter: "ફિલ્ટર લાગુ કરો",
    active: "સક્રિય",
    pending: "બાકી",
    completed: "પૂર્ણ થયેલ",
    resolved: "ઉકેલાયેલ",
    inProgress: "ચાલુ છે",
    actionRequired: "પગલાં જરૂરી",
    verified: "ચકાસાયેલ",
    all: "બધું",
    noData: "માહિતી ઉપલબ્ધ નથી",
    noResults: "કોઈ પરિણામ મળ્યું નથી",
    loadingData: "માહિતી લોડ થઈ રહી છે...",
    somethingWentWrong: "કંઈક ખોટું થયું",
    tryAgain: "કૃપા કરીને ફરી પ્રયાસ કરો",
    errorOccurred: "ભૂલ આવી",
    help: "મદદ અને પ્રશ્નોત્તરી",
    helpdesk: "મદદ કેન્દ્ર",
    helpline: "1800-180-LAND",
    tollFree: "ટોલ ફ્રી રાષ્ટ્રીય હેલ્પલાઇન",
    rightsReserved: "સર્વાધિકાર સુરક્ષિત",
    status_ACTIVE: "સક્રિય",
    status_COMPLETED: "પૂર્ણ થયેલ",
    status_VERIFIED: "ચકાસાયેલ",
    status_PAID: "ચૂકવેલ (DBT)",
    status_SANCTIONED: "મંજૂર",
    status_RESOLVED: "ઉકેલાયેલ",
    status_ELIGIBLE: "પાત્ર",
    status_VERIFICATION: "ચકાસણી તબક્કો",
    status_IN_PROGRESS: "ચાલુ છે",
    status_UNDER_REVIEW: "સમીક્ષા હેઠળ",
    status_CURRENT: "હાલની સ્થિતિ",
    status_PROCESSING: "પ્રક્રિયા ચાલુ",
    status_ACTION_REQUIRED: "પગલાં જરૂરી",
    status_UPCOMING: "આગામી",
    status_PENDING: "બાકી",
    status_REJECTED: "અસ્વીકાર થયેલ",
    status_FAILED: "નિષ્ફળ",
    status_DEPOSITED_PFMS: "PFMS જમા થયેલ",
    status_CLAIM_SUBMITTED: "દાવા અરજી સબમિટ",
    status_DISCREPANCY_FLAGGED: "વિસંગતતા મળી",
    status_RESPONSE_ADDED: "જવાબ ઉમેરાયો",
    status_AWAITING_HEARING: "સુનાવણીની રાહમાં",
    status_CLOSED: "કેસ પૂર્ણ",
    status_ASSESSED: "મૂલ્યાંકન થયેલ",
    status_APPROVED: "મંજૂર થયેલ",
    status_DISCREPANCY_FOUND: "વિસંગતતા પ્રાપ્ત",
    status_DISPUTED: "વિવાદિત",
    status_HIGH: "ઉચ્ચ પ્રાથમિકતા",
    status_SUBMITTED: "સબમિટ થયેલ",
    status_UNPAID: "ચૂકવણી બાકી",
    status_PROPOSAL: "દરખાસ્ત તબક્કો",
    status_NOTIFICATION: "જાહેરનામા તબક્કો",
    welcomeTitle: "સહાય (SAHAAY) પોર્ટલ પર સ્વાગત છે",
    welcomeSub: "જમીન સંપાદન અને વળતર ટ્રેક કરવા લૉગ ઇન કરો.",
    demoAccountsTitle: "ડેમો એકાઉન્ટ પસંદ કરો",
    demoBadge: "ડેમો મોડ",
    demoCitizenTitle: "🌾 નાગરિક / જમીન માલિક",
    demoCitizenSub: "રાજેશ શર્મા (સર્વે #૧૦૪૨)",
    demoOfficerTitle: "🏛️ જમીન સંપાદન અધિકારી (LAO)",
    demoOfficerSub: "વિક્રમ ચૌહાણ (ભોપાલ સર્કલ)",
    tabSignIn: "લૉગ ઇન કરો",
    tabRegister: "નાગરિક નોંધણી",
    fullNameLabel: "પૂરું નામ (રેકોર્ડ મુજબ)",
    fullNamePlaceholder: "દા.ત. રાજેશ શર્મા",
    villageLabel: "ગામ",
    districtLabel: "જિલ્લો",
    emailLabel: "ઇમેઇલ / મોબાઇલ નંબર",
    emailPlaceholder: "name@sahaay.demo",
    passwordLabel: "પાસવર્ડ",
    passwordPlaceholder: "••••••••",
    verifyingBtn: "ચકાસણી થઈ રહી છે...",
    createAccountBtn: "એકાઉન્ટ બનાવો",
    signInBtn: "સુરક્ષિત લૉગ ઇન કરો",
    demoFillBtn: "ડેમો વિગતો ભરો",
    loginErrorDefault: "લૉગ ઇન નિષ્ફળ. વિગતો તપાસો.",
    registerSuccessToast: "એકાઉન્ટ સફળતાપૂર્વક બન્યું! લૉગ ઇન કરો.",
    quickAccessSection: "ઝડપી નાગરિક સેવાઓ",
    findLandCardTitle: "મારી જમીન શોધો",
    findLandCardDesc: "સર્વે નંબર અને ગામ દ્વારા સંપાદન સ્થિતિ તપાસો.",
    docIntelCardTitle: "AI દસ્તાવેજ વિશ્લેષણ",
    docIntelCardDesc: "સંપાદન નોટિસ અપલોડ કરી સરળ સમજૂતી મેળવો.",
    gisMapCardTitle: "GIS પ્રોજેક્ટ નકશો",
    gisMapCardDesc: "હાઇવે એલાઇનમેન્ટ અને જમીનની સીમાઓ સેટેલાઇટ પર જુઓ.",
    compensationCardTitle: "વળતર મૂલ્યાંકન",
    compensationCardDesc: "RFCTLARR કાયદા મુજબ ૧૦૦% સોલેશિયમ અને DBT સ્થિતિ જુઓ.",
    actionCenterCardTitle: "કાર્ય કેન્દ્ર",
    actionCenterCardDesc: "કાનૂની મુદત અને બાકી કાર્યોનું સંચાલન કરો.",
    grievancesCardTitle: "ફરિયાદો અને વાંધા",
    grievancesCardDesc: "કલમ ૧૫ વાંધા અને વળતર વિવાદો નોંધાવો.",
    summaryParcelsCount: "જોડાયેલા સર્વે નંબરો",
    summaryActiveAcquisitions: "સક્રિય સંપાદન પ્રક્રિયા",
    summaryTotalAssessedComp: "કુલ નિર્ધારિત વળતર",
    summaryPendingActions: "તાત્કાલિક બાકી પગલાં",
    timelineTitle: "કાનૂની સંપાદન પ્રગતિ",
    timelineSub: "RFCTLARR કાયદા ૨૦૧૩ મુજબ કેસના તબક્કા",
    stepSec11: "કલમ ૧૧(૧) પ્રારંભિક જાહેરનામું",
    stepSec15: "કલમ ૧૫ સુનાવણી અને વાંધા",
    stepSec19: "કલમ ૧૯ અંતિમ જાહેરાત",
    stepSec23: "કલમ ૨૩ વળતર એવોર્ડ",
    stepPayment: "PFMS વળતર વિતરણ",
    stepPossession: "કબજો અને પુનર્વસન",
    discrepancyBannerTitle: "ચેતવણી: સર્વે #૧૦૪૨ ના ક્ષેત્રફળમાં વિસંગતતા મળી છે",
    discrepancyBannerDesc: "નોટિસનું ક્ષેત્રફળ (૧.૧૦ હેક્ટર) મહેસૂલી રેકોર્ડ કરતાં ઓછું છે. કલમ ૧૫(૧) હેઠળ ૬૦ દિવસમાં વાંધો નોંધાવો.",
    reviewDiscrepancyBtn: "વિસંગતતા સમીક્ષા",
    fileObjectionBtn: "વાંધો નોંધાવો",
    findLandTitle: "સર્વે નંબર દ્વારા જમીન શોધ",
    findLandSubtitle: "હાઇવે અથવા રેલવે પ્રોજેક્ટ હેઠળ આવતી જમીન તુરંત શોધો.",
    surveyInputLabel: "સર્વે નંબર / બ્લોક નંબર",
    surveyInputPlaceholder: "દા.ત. ૧૦૪૨ અથવા ૪૫/અ",
    villageSelectLabel: "ગામ",
    allVillagesOption: "બધા ગામો",
    districtSelectLabel: "જિલ્લો",
    allDistrictsOption: "બધા જિલ્લાઓ",
    searchLandSubmitBtn: "જમીન શોધો",
    searchResultsHeading: "શોધ પરિણામો",
    parcelCardSurveyLabel: "સર્વે નંબર:",
    parcelCardVillageLabel: "ગામ અને જિલ્લો:",
    parcelCardAreaLabel: "સૂચિત ક્ષેત્રફળ:",
    parcelCardOwnerLabel: "માલિકનું નામ:",
    parcelCardProjectLabel: "પ્રોજેક્ટ:",
    parcelCardStageLabel: "હાલનો તબક્કો:",
    parcelCardCompLabel: "નિર્ધારિત વળતર:",
    viewGisMapBtn: "GIS નકશા પર જુઓ",
    viewCompDetailsBtn: "વળતર વિગતો",
    noSearchResultsTitle: "કોઈ જમીન રેકોર્ડ મળ્યો નથી",
    noSearchResultsDesc: "યોગ્ય સર્વે નંબર અને ગામ ચકાસી ફરી પ્રયાસ કરો.",
    gisTitle: "ઇન્ટરેક્ટિવ GIS પ્રોજેક્ટ સીમા નકશો",
    gisSubtitle: "સંપાદન એલાઇનમેન્ટ, બફર ઝોન અને આસપાસના સર્વે નંબરો જુઓ.",
    legendTitle: "નકશા સંકેતો",
    legendAcquired: "સૂચિત સંપાદન ક્ષેત્ર",
    legendBuffer: "પ્રોજેક્ટ બફર ઝોન (૫૦ મીટર)",
    legendYourLand: "તમારો સર્વે નંબર (#૧૦૪૨)",
    legendAdjacent: "આસપાસના સર્વે નંબરો",
    mapLayerControl: "નકશા સ્તરો",
    layerSatellite: "સેટેલાઇટ દૃશ્ય",
    layerCadastral: "મહેસૂલી નકશો (Cadastral)",
    layerProjectAlign: "પ્રોજેક્ટ એલાઇનમેન્ટ રેખા",
    parcelInfoPanelTitle: "પસંદ કરેલા સર્વેની વિગતો",
    infoSurveyNo: "સર્વે નંબર",
    infoVillage: "ગામ અને તાલુકો",
    infoTotalArea: "કુલ ક્ષેત્રફળ",
    infoAcquiredArea: "સંપાદિત ક્ષેત્રફળ",
    infoOwner: "માલિકનું નામ",
    infoStatus: "સંપાદન સ્થિતિ",
    infoEstimatedVal: "નિર્ધારિત વળતર",
    measureDistanceBtn: "અંતર માપો",
    measureAreaBtn: "ક્ષેત્રફળ માપો",
    clearMeasureBtn: "માપ સાફ કરો",
    docIntelTitleFull: "AI સરકારી દસ્તાવેજ વિશ્લેષણ એન્જિન",
    docIntelSubtitle: "જમીન સંપાદન ગેઝેટ નોટિસોની સરળ ભાષામાં સમજૂતી મેળવો.",
    uploadZoneTitle: "નોટિસ અથવા એવોર્ડ દસ્તાવેજ અપલોડ કરો",
    uploadZoneSubtitle: "PDF, JPG અથવા PNG ફાઇલ પસંદ કરો (મહત્તમ ૨૫MB)",
    sampleNoticesTitle: "અથવા નમૂના નોટિસો તપાસો:",
    sampleSec11Btn: "📄 કલમ ૧૧(૧) નોટિસ (સર્વે #૧૦૪૨)",
    sampleAwardBtn: "📄 કલમ ૨૩ એવોર્ડ હુકમ",
    sampleSec19Btn: "📄 કલમ ૧૯(૧) જાહેરાત નોટિસ",
    analysisResultsTitle: "AI દસ્તાવેજ વિશ્લેષણ સારાંશ",
    docTypeDetected: "દસ્તાવેજનો પ્રકાર",
    gazetteRefNo: "ગેઝેટ સંદર્ભ નંબર",
    issuingAuthority: "જારી કરનાર સત્તામંડળ",
    issueDate: "પ્રસિદ્ધિ તારીખ",
    affectedVillage: "અસરગ્રસ્ત ગામ અને જિલ્લો",
    statutorySection: "લાગુ કાયદાકીય કલમ",
    keyFindingsHeading: "મુખ્ય મુદ્દા (સરળ ભાષામાં):",
    detectedDiscrepanciesTitle: "⚠️ જણાયેલ વિસંગતતાઓ અને વાંધા:",
    actionableStepsHeading: "તમારા માટે જરૂરી પગલાં:",
    confidenceScoreLabel: "AI ચોકસાઈ દર:",
    downloadAnalysisReportBtn: "સંપૂર્ણ AI રિપોર્ટ ડાઉનલોડ",
    fileObjectionFromDocBtn: "આ નોટિસ સામે વાંધો નોંધાવો",
    compPageTitle: "કાનૂની વળતર અને પુનર્વસન (R&R) લાભો",
    compPageSubtitle: "RFCTLARR કાયદા ૨૦૧૩ મુજબ સંપૂર્ણ વળતર, સોલેશિયમ અને DBT ચૂકવણી.",
    assessedLandValueCard: "મૂળ જમીન મૂલ્યાંકન",
    solatium100Card: "૧૦૦% સોલેશિયમ (આશ્વાસન રકમ)",
    statutoryInterestCard: "૧૨% વધારાનું વાર્ષિક વ્યાજ",
    totalCompensationCard: "કુલ એવોર્ડ વળતર",
    compBreakdownTitle: "વળતર ગણતરીની વિગતવાર માહિતી (RFCTLARR અનુસૂચિ ૧)",
    colComponent: "ઘટક",
    colStatutoryBasis: "કાનૂની આધાર",
    colCalculation: "ગણતરી પદ્ધતિ",
    colAmount: "રકમ (₹)",
    rowBaseLandVal: "મૂળ બજારભાવ મૂલ્ય",
    rowBaseLandValDesc: "છેલ્લા ૩ વર્ષના સરેરાશ નોંધણી મૂલ્યના આધારે",
    rowMultiFactor: "ગ્રામીણ ગુણક પરિબળ (૧.૫x)",
    rowMultiFactorDesc: "RFCTLARR કાયદાની કલમ ૨૬(૨) ગ્રામીણ નિયમ",
    rowSolatium: "૧૦૦% ફરજિયાત સોલેશિયમ",
    rowSolatiumDesc: "કલમ ૩૦(૧) મુજબ સમકક્ષ સોલેશિયમ રકમ",
    rowInterest: "૧૨% વધારાનું વાર્ષિક વ્યાજ",
    rowInterestDesc: "કલમ ૩૦(૩) મુજબ જાહેરનામાથી એવોર્ડ સુધી",
    rowStructures: "મકાન અને બાંધકામનું વળતર",
    rowStructuresDesc: "માર્ગ અને મકાન વિભાગનું મૂલ્યાંકન",
    rowTrees: "વૃક્ષો અને પાકનું વળતર",
    rowTreesDesc: "વન અને બાગાયત વિભાગનું મૂલ્યાંકન",
    rowTotalNet: "કુલ ચોખ્ખું એવોર્ડ વળતર",
    paymentDistributionTitle: "PFMS ડાયરેક્ટ બેનિફિટ ટ્રાન્સફર (DBT) વિતરણ",
    linkedBankCard: "જોડાયેલ આધાર બેંક ખાતું:",
    ifscCard: "IFSC કોડ:",
    pfmsTxnCard: "PFMS ટ્રાન્ઝેક્શન ID:",
    disbursedDateCard: "જમા થયાની તારીખ:",
    paymentProgressLabel: "વિતરણ પ્રગતિ:",
    rrEntitlementsTitle: "પુનર્વસન અને પુનઃસ્થાપન (R&R) લાભો (અનુસૂચિ ૨)",
    rrResettlementHouse: "વૈકલ્પિક મકાન / પ્લોટ ફાળવણી",
    rrResettlementHouseDesc: "પ્રધાનમંત્રી આવાસ યોજના મુજબ પાકું મકાન અથવા સમકક્ષ વળતર રકમ.",
    rrSubsistence: "નિર્વાહ અનુદાન (માસિક ભથ્થું)",
    rrSubsistenceDesc: "અસરગ્રસ્ત કુટુંબને માસિક ₹૩,૦૦૦ લેખે ૧૨ મહિના માટે ભથ્થું.",
    rrTransport: "સ્થળાંતર અને પરિવહન ભથ્થું",
    rrTransportDesc: "ઘરવખરી સામાનની હેરફેર માટે એકસાથે ₹૫૦,૦૦૦.",
    rrSkill: "કૌશલ્ય તાલીમ અને રોજગાર",
    rrSkillDesc: "કુટુંબના એક સભ્યને કૌશલ્ય વિકાસ તાલીમ અને રોજગાર સહાય.",
    disputeNoticeText: "ધ્યાન રાખો: ગણતરી સામે વાંધો હોય તો એવોર્ડ જારી થયાના ૬૦ દિવસમાં લેન્ડ ઓથોરિટી (LARRA) સમક્ષ અપીલ કરી શકાય છે.",
    fileCompGrievanceBtn: "વળતર સામે વાંધો / અપીલ દાખલ કરો",
    documentsPageTitle: "ડિજિટલ દસ્તાવેજ લોકર",
    documentsPageSubtitle: "જમીન સંપાદન સંબંધિત તમામ ચકાસાયેલ સરકારી દસ્તાવેજો.",
    uploadDocBtn: "નવો દસ્તાવેજ અપલોડ કરો",
    allDocTypesFilter: "બધા દસ્તાવેજ પ્રકારો",
    docTitleLandRecords: "જમીન માલિકી હક (૭/૧૨, ૮-અ, હકપત્રક)",
    docTitleGovNotices: "સરકારી ગેઝેટ જાહેરનામા",
    docTitleIdentityProof: "ઓળખ અને સરનામાના પુરાવા",
    docTitleBankPassbook: "બેંક ખાતાની વિગતો",
    docTitleClaimReceipts: "દાવા પહોંચ અને એવોર્ડ હુકમ",
    docTableColName: "દસ્તાવેજનું નામ",
    docTableColType: "શ્રેણી",
    docTableColDate: "અપલોડ તારીખ",
    docTableColStatus: "ચકાસણી સ્થિતિ",
    docTableColActions: "પગલાં",
    viewDocumentAction: "જુઓ",
    downloadDocumentAction: "ડાઉનલોડ",
    explainWithAiAction: "AI થી સમજો",
    deleteDocumentAction: "કાઢી નાખો",
    docStatusVerified: "ચકાસાયેલ",
    docStatusPending: "ચકાસણી બાકી",
    actionCenterPageTitle: "નાગરિક કાર્ય કેન્દ્ર અને મુદતો",
    actionCenterPageSubtitle: "તમારા તરફથી બાકી કાર્યો, સરકારી નોટિસો અને કાનૂની મુદતનું સંચાલન.",
    urgentActionsTitle: "તાત્કાલિક કાનૂની કાર્યો",
    upcomingDeadlinesTitle: "આગામી મુદતો અને સુનાવણી",
    completedHistoryTitle: "પૂર્ણ થયેલ કાર્યો",
    actionDueLabel: "અંતિમ મુદત:",
    daysLeftLabel: "દિવસો બાકી",
    actionCompletedBadge: "પૂર્ણ",
    actionPendingBadge: "પગલાં જરૂરી",
    btnCompleteAction: "કાર્ય પૂર્ણ કરો",
    btnViewNoticeDetails: "નોટિસ વિગતો",
    grievancesPageTitle: "નાગરિક ફરિયાદો અને કલમ ૧૫ વાંધા",
    grievancesPageSubtitle: "સંપાદન પ્રક્રિયા, ક્ષેત્રફળ અથવા વળતર સામે વાંધા નોંધાવો.",
    submitNewGrievanceBtn: "નવો વાંધો / ફરિયાદ દાખલ કરો",
    trackGrievancesHeading: "દાખલ કરેલા વાંધાઓની સદ્યસ્થિતિ",
    grievanceModalTitle: "નવો વાંધો દાખલ કરો",
    grievanceTypeLabel: "વાંધાનો પ્રકાર",
    selectGrievanceTypePlaceholder: "પ્રકાર પસંદ કરો",
    optCompensationDispute: "વળતર રકમની ગણતરી સામે વાંધો",
    optAreaDiscrepancy: "ક્ષેત્રફળ માપણીમાં વિસંગતતા (કલમ ૧૫)",
    optOwnershipDispute: "માલિકી હક અથવા નામ સુધારો",
    optPaymentDelay: "વળતર મળવામાં વિલંબ (DBT/PFMS)",
    optRRDispute: "પુનર્વસન લાભો (R&R) ન મળવા",
    optOther: "અન્ય વહીવટી પ્રશ્નો",
    grievanceDescLabel: "વાંધાનું સવિસ્તાર વર્ણન",
    grievanceDescPlaceholder: "તમારી સમસ્યા વિગતવાર લખો...",
    supportingDocsLabel: "પુરાવા દસ્તાવેજો જોડો (PDF, JPG - મહત્તમ ૧૦MB)",
    submitGrievanceConfirmBtn: "દાખલ કરો",
    grievanceTicketLabel: "ટોકન નંબર:",
    assignedOfficerLabel: "નિવારણ અધિકારી:",
    expectedResolutionLabel: "અપેક્ષિત નિકાલ તારીખ:",
    hearingScheduleLabel: "સુનાવણી તારીખ:",
    officerRemarksLabel: "અધિકારીની નોંધ:",
    noticesPageTitle: "સૂચનાઓ અને સરકારી ગેઝેટ જાહેરાતો",
    noticesPageSubtitle: "જમીન સંપાદન સંબંધિત અદ્યતન સરકારી માહિતી.",
    filterUnreadOnly: "ન વંચાયેલ સૂચનાઓ",
    btnMarkAllAsRead: "બધું વંચાયેલ તરીકે ચિહ્નિત કરો",
    noticeCardDateLabel: "તારીખ:",
    noticeCardSectionLabel: "કાનૂની કલમ:",
    noticeCardDownloadGazetteBtn: "ગેઝેટ ડાઉનલોડ કરો",
    noticeCardExplainAiBtn: "AI થી સમજો",
    officerDashboardTitle: "જમીન સંપાદન અધિકારી (LAO) નિયંત્રણ કેન્દ્ર",
    officerDashboardSubtitle: "પ્રોજેક્ટના સર્વે નંબરો, કલમ ૧૫ વાંધા અને વળતર વિતરણ સંચાલન.",
    metricTotalAcquisitions: "કુલ સંપાદન પ્રોજેક્ટ્સ",
    metricTotalParcels: "સૂચિત સર્વે નંબરો",
    metricDisbursedBudget: "વિતરિત વળતર બજેટ",
    metricPendingReviews: "સમીક્ષા માટે બાકી ફાઇલો",
    officerSectionCases: "પ્રોજેક્ટ કેસ રજિસ્ટ્રી",
    officerSectionGrievances: "નાગરિક વાંધા અને સુનાવણી કતાર",
    tableColCaseId: "કેસ ID",
    tableColProject: "પ્રોજેક્ટનું નામ",
    tableColVillage: "ગામ",
    tableColLandowner: "માલિક",
    tableColSurvey: "સર્વે નં.",
    tableColArea: "ક્ષેત્રફળ (હેક્ટર)",
    tableColStage: "કાનૂની તબક્કો",
    tableColCompStatus: "વળતર સ્થિતિ",
    tableColAction: "પગલાં",
    btnReviewCase: "કેસ તપાસો",
    btnUpdateStatus: "સ્થિતિ બદલો",
    btnScheduleHearing: "સુનાવણી તારીખ નક્કી કરો",
    btnDisbursePayment: "DBT ભંડોળ મંજૂર કરો",
    resolveGrievanceBtn: "નિકાલ હુકમ જારી કરો",
    officerCasesTitle: "પ્રોજેક્ટ કેસોની માસ્ટર રજિસ્ટ્રી",
    officerCasesSub: "ગેઝેટ નોટિસો, માપણી અને વળતર એવોર્ડ સંચાલન વ્યવસ્થા.",
    searchCasePlaceholder: "કેસ ID, સર્વે નંબર અથવા માલિકના નામથી શોધો...",
    filterAllStages: "બધા કાનૂની તબક્કા",
    stageVerification: "ચકાસણી તબક્કો",
    stageHearing: "કલમ ૧૫ સુનાવણી",
    stageAward: "કલમ ૨૩ એવોર્ડ હુકમ",
    stagePayment: "DBT ભંડોળ ટ્રાન્સફર",
    stagePossession: "કબજો મેળવવો",
    caseOfficerNotesLabel: "અધિકારીની નોંધ અને હુકમ વિગતો",
    saveStatusUpdateBtn: "સાચવો",
    noticeLabel: "મહત્વપૂર્ણ નોટિસ:",
    tickerAdvisory: "નાગરિક સંદેશ: જમીન સંપાદન સ્થિતિ અને વળતર ઓનલાઇન તપાસો.",
    tickerDocIntel: "નવી સુવિધા: ગેઝેટ નોટિસ અપલોડ કરો અને AI સરળ સમજૂતી મેળવો.",
    tickerObjections: "કાનૂની ચેતવણી: કલમ ૧૧(૧) પ્રસિદ્ધિ પછી ૬૦ દિવસમાં કલમ ૧૫ વાંધા નોંધાવો.",
    tickerDbt: "PFMS DBT: વળતર રકમ સીધી આધાર લિંક બેંક ખાતામાં જમા થાય છે.",
    footerTagline: "જમીન સંપાદન, વળતર અને પુનર્વસનનું પારદર્શક રાષ્ટ્રીય નાગરિક પોર્ટલ",
    footerDescription: "RFCTLARR કાયદા ૨૦૧૩ હેઠળ કાર્યરત પારદર્શક નાગરિક માહિતી પ્રણાલી.",
    footerHelplineLabel: "રાષ્ટ્રીય જમીન અધિકાર હેલ્પલાઇન:",
    footerServicesTitle: "નાગરિક સેવાઓ",
    footerServiceFindLand: "જમીન શોધો",
    footerServiceDocIntel: "AI દસ્તાવેજ વિશ્લેષણ",
    footerServiceGis: "GIS નકશો",
    footerServiceComp: "વળતર મૂલ્યાંકન",
    footerServiceActions: "કાર્ય કેન્દ્ર",
    footerServiceGrievances: "કલમ ૧૫ વાંધા",
    footerStatutoryTitle: "કાનૂની જોગવાઈઓ",
    footerStatutoryAct: "RFCTLARR કાયદો, ૨૦૧૩",
    footerStatutorySec11: "કલમ ૧૧(૧) પ્રારંભિક જાહેરનામું",
    footerStatutorySec15: "કલમ ૧૫ વાંધાનો અધિકાર",
    footerStatutorySec19: "કલમ ૧૯ અંતિમ જાહેરાત",
    footerStatutorySec23: "કલમ ૨૩ વળતર એવોર્ડ",
    footerStatutoryPfms: "PFMS ડાયરેક્ટ બેનિફિટ ટ્રાન્સફર",
    footerAssistanceTitle: "મદદ અને સંપર્ક",
    footerAddress: "કેન્દ્રીય ભૂ-મહેસૂલ અને રાષ્ટ્રીય ધોરીમાર્ગ સત્તામંડળ, નવી દિલ્હી",
    footerTollFree: "ટોલ ફ્રી હેલ્પલાઇન: 1800-180-LAND (5263)",
    footerEmail: "ઇમેઇલ: support@sahaay.gov.in",
    footerCopyright: "© 2026 સહાય (SAHAAY) • ભારત સરકાર. સર્વાધિકાર સુરક્ષિત.",
    footerDemoDisclaimer: "આ પોર્ટલ નમૂના માહિતી સાથે ઉપલબ્ધ અધિકૃત નાગરિક સેવા પ્લેટફોર્મ છે."
  };

  writeLocaleFile('gu', 'Gujarati (ગુજરાતી)', t);
}

// ============================================================================
// 4. PUNJABI (ਪੰਜਾਬੀ - pa)
// ============================================================================
export function generatePunjabi() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: "ਸਹਾਏ (SAHAAY)",
    emblemLetter: "ਸ",
    tagline: "ਤੁਹਾਡੀ ਜ਼ਮੀਨ। ਤੁਹਾਡਾ ਕੇਸ। ਤੁਹਾਡਾ ਹੱਕ।",
    heroSub: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ, ਮੁਆਵਜ਼ਾ ਅਤੇ ਮੁੜ ਵਸੇਬਾ ਨਾਗਰਿਕ ਸਹਾਇਤਾ ਪੋਰਟਲ",
    portalSubtitle: "ਜ਼ਮੀਨ • ਮੁਆਵਜ਼ਾ • ਮੁੜ ਵਸੇਬਾ (R&R) • ਸ਼ਿਕਾਇਤਾਂ • ਕੇਸ ਟਰੈਕਿੰਗ",
    citizenPortal: "ਨਾਗਰਿਕ ਪੋਰਟਲ",
    officerPortal: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਅਧਿਕਾਰੀ ਪੋਰਟਲ",
    demoMode: "ਡੈਮੋ ਮੋਡ ਸਰਗਰਮ",
    signIn: "ਲੌਗ ਇਨ ਕਰੋ",
    signOut: "ਲੌਗ ਆਉਟ",
    landowner: "ਜ਼ਮੀਨ ਮਾਲਕ",
    landOfficer: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਅਧਿਕਾਰੀ (LAO)",
    switchRole: "ਭੂਮਿਕਾ ਬਦਲੋ",
    switchCitizen: "ਨਾਗਰਿਕ (ਰਾਜੇਸ਼ ਸ਼ਰਮਾ)",
    switchOfficer: "ਅਧਿਕਾਰੀ (ਵਿਕਰਮ ਚੌਹਾਨ)",
    welcomeBack: "ਜੀ ਆਇਆਂ ਨੂੰ",
    navHome: "ਮੁੱਖ ਪੰਨਾ",
    navFindLand: "ਮੇਰੀ ਜ਼ਮੀਨ ਲੱਭੋ",
    navGisMap: "GIS ਜ਼ਮੀਨ ਨਕਸ਼ਾ",
    navDocIntel: "ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ (AI)",
    navCompensation: "ਮੁਆਵਜ਼ਾ ਅਤੇ ਮੁੜ ਵਸੇਬਾ",
    navDocuments: "ਦਸਤਾਵੇਜ਼ ਲਾਕਰ",
    navActionCenter: "ਕਾਰਵਾਈ ਕੇਂਦਰ",
    navGrievances: "ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਨ",
    navNotices: "ਨੋਟਿਸ ਅਤੇ ਚੇਤਾਵਨੀਆਂ",
    navOfficerDashboard: "ਅਧਿਕਾਰੀ ਡੈਸ਼ਬੋਰਡ",
    navCasesRegistry: "ਕੇਸ ਰਜਿਸਟਰੀ",
    navGrievancesQueue: "ਸ਼ਿਕਾਇਤ ਕਤਾਰ",
    citizenServices: "ਨਾਗਰਿਕ ਸੇਵਾਵਾਂ",
    quickActions: "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    save: "ਸੰਭਾਲੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    edit: "ਸੋਧੋ",
    delete: "ਮਿਟਾਓ",
    search: "ਖੋਜ ਕਰੋ",
    filter: "ਫਿਲਟਰ",
    back: "ਪਿੱਛੇ",
    next: "ਅੱਗੇ",
    close: "ਬੰਦ ਕਰੋ",
    view: "ਵੇਖੋ",
    download: "ਡਾਊਨਲੋਡ",
    upload: "ਅੱਪਲੋਡ ਕਰੋ",
    export: "ਨਿਰਯਾਤ",
    refresh: "ਤਾਜ਼ਾ ਕਰੋ",
    print: "ਪ੍ਰਿੰਟ ਕਰੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    actions: "ਕਾਰਵਾਈਆਂ",
    details: "ਵੇਰਵੇ",
    status: "ਸਥਿਤੀ",
    viewDetails: "ਵੇਰਵੇ ਵੇਖੋ",
    viewOnMap: "ਨਕਸ਼ੇ ਤੇ ਵੇਖੋ",
    viewCase: "ਪੂਰਾ ਕੇਸ ਵੇਖੋ",
    trackProgress: "ਤਰੱਕੀ ਟਰੈਕ ਕਰੋ",
    proceed: "ਅੱਗੇ ਵਧੋ",
    confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
    retry: "ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    clearAll: "ਸਭ ਸਾਫ਼ ਕਰੋ",
    applyFilter: "ਫਿਲਟਰ ਲਾਗੂ ਕਰੋ",
    active: "ਸਰਗਰਮ",
    pending: "ਬਕਾਇਆ",
    completed: "ਮੁਕੰਮਲ ਹੋਇਆ",
    resolved: "ਹੱਲ ਹੋਇਆ",
    inProgress: "ਜਾਰੀ ਹੈ",
    actionRequired: "ਕਾਰਵਾਈ ਲੋੜੀਂਦੀ",
    verified: "ਪੜਤਾਲਿਆ ਗਿਆ",
    all: "ਸਭ",
    noData: "ਜਾਣਕਾਰੀ ਉਪਲਬਧ ਨਹੀਂ",
    noResults: "ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ",
    loadingData: "ਜਾਣਕਾਰੀ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...",
    somethingWentWrong: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
    tryAgain: "ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    errorOccurred: "ਗਲਤੀ ਹੋਈ",
    help: "ਮਦਦ ਅਤੇ ਸਵਾਲ-ਜਵਾਬ",
    helpdesk: "ਮਦਦ ਕੇਂਦਰ",
    helpline: "1800-180-LAND",
    tollFree: "ਟੋਲ ਫ੍ਰੀ ਰਾਸ਼ਟਰੀ ਹੈਲਪਲਾਈਨ",
    rightsReserved: "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ",
    status_ACTIVE: "ਸਰਗਰਮ",
    status_COMPLETED: "ਮੁਕੰਮਲ",
    status_VERIFIED: "ਪੜਤਾਲਿਆ",
    status_PAID: "ਅਦਾਇਗੀ ਹੋਈ (DBT)",
    status_SANCTIONED: "ਮਨਜ਼ੂਰ",
    status_RESOLVED: "ਹੱਲ ਹੋਇਆ",
    status_ELIGIBLE: "ਯੋਗ",
    status_VERIFICATION: "ਪੜਤਾਲ ਪੜਾਅ",
    status_IN_PROGRESS: "ਜਾਰੀ ਹੈ",
    status_UNDER_REVIEW: "ਸਮੀਖਿਆ ਅਧੀਨ",
    status_CURRENT: "ਮੌਜੂਦਾ ਸਥਿਤੀ",
    status_PROCESSING: "ਪ੍ਰਕਿਰਿਆ ਅਧੀਨ",
    status_ACTION_REQUIRED: "ਕਾਰਵਾਈ ਲੋੜੀਂਦੀ",
    status_UPCOMING: "ਆਉਣ ਵਾਲਾ",
    status_PENDING: "ਬਕਾਇਆ",
    status_REJECTED: "ਰੱਦ ਕੀਤਾ",
    status_FAILED: "ਅਸਫਲ",
    status_DEPOSITED_PFMS: "PFMS ਜਮ੍ਹਾਂ ਹੋਇਆ",
    status_CLAIM_SUBMITTED: "ਦਾਅਵਾ ਜਮ੍ਹਾਂ ਹੋਇਆ",
    status_DISCREPANCY_FLAGGED: "ਅੰਤਰ ਮਿਲਿਆ",
    status_RESPONSE_ADDED: "ਜਵਾਬ ਸ਼ਾਮਲ",
    status_AWAITING_HEARING: "ਸੁਣਵਾਈ ਦੀ ਉਡੀਕ",
    status_CLOSED: "ਕੇਸ ਸਮਾਪਤ",
    status_ASSESSED: "ਮੁਲਾਂਕਣ ਹੋਇਆ",
    status_APPROVED: "ਪ੍ਰਵਾਨਿਤ",
    status_DISCREPANCY_FOUND: "ਅੰਤਰ ਪਾਇਆ ਗਿਆ",
    status_DISPUTED: "ਵਿਵਾਦਿਤ",
    status_HIGH: "ਉੱਚ ਤਰਜੀਹ",
    status_SUBMITTED: "ਜਮ੍ਹਾਂ ਕੀਤਾ",
    status_UNPAID: "ਅਣ-ਅਦਾਇਗੀ",
    status_PROPOSAL: "ਤਜਵੀਜ਼ ਪੜਾਅ",
    status_NOTIFICATION: "ਨੋਟੀਫਿਕੇਸ਼ਨ ਪੜਾਅ",
    welcomeTitle: "ਸਹਾਏ (SAHAAY) ਪੋਰਟਲ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ",
    welcomeSub: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਅਤੇ ਮੁਆਵਜ਼ਾ ਟਰੈਕ ਕਰਨ ਲਈ ਲੌਗ ਇਨ ਕਰੋ।",
    demoAccountsTitle: "ਡੈਮੋ ਖਾਤਾ ਚੁਣੋ",
    demoBadge: "ਡੈਮੋ ਮੋਡ",
    demoCitizenTitle: "🌾 ਨਾਗਰਿਕ / ਜ਼ਮੀਨ ਮਾਲਕ",
    demoCitizenSub: "ਰਾਜੇਸ਼ ਸ਼ਰਮਾ (ਖਸਰਾ #1042)",
    demoOfficerTitle: "🏛️ ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਅਧਿਕਾਰੀ (LAO)",
    demoOfficerSub: "ਵਿਕਰਮ ਚੌਹਾਨ (ਭੋਪਾਲ ਸਰਕਲ)",
    tabSignIn: "ਲੌਗ ਇਨ ਕਰੋ",
    tabRegister: "ਨਾਗਰਿਕ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    fullNameLabel: "ਪੂਰਾ ਨਾਮ (ਮਾਲ ਰਿਕਾਰਡ ਅਨੁਸਾਰ)",
    fullNamePlaceholder: "ਉਦਾ. ਰਾਜੇਸ਼ ਸ਼ਰਮਾ",
    villageLabel: "ਪਿੰਡ",
    districtLabel: "ਜ਼ਿਲ੍ਹਾ",
    emailLabel: "ਈਮੇਲ / ਮੋਬਾਈਲ ਨੰਬਰ",
    emailPlaceholder: "name@sahaay.demo",
    passwordLabel: "ਪਾਸਵਰਡ",
    passwordPlaceholder: "••••••••",
    verifyingBtn: "ਪੜਤਾਲ ਹੋ ਰਹੀ ਹੈ...",
    createAccountBtn: "ਖਾਤਾ ਬਣਾਓ",
    signInBtn: "ਸੁਰੱਖਿਅਤ ਲੌਗ ਇਨ ਕਰੋ",
    demoFillBtn: "ਡੈਮੋ ਵੇਰਵੇ ਭਰੋ",
    loginErrorDefault: "ਲੌਗ ਇਨ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਵੇਰਵੇ ਜਾਂਚੋ।",
    registerSuccessToast: "ਖਾਤਾ ਸਫਲਤਾਪੂਰਵਕ ਬਣ ਗਿਆ! ਲੌਗ ਇਨ ਕਰੋ।",
    quickAccessSection: "ਤੁਰੰਤ ਨਾਗਰਿਕ ਸੇਵਾਵਾਂ",
    findLandCardTitle: "ਮੇਰੀ ਜ਼ਮੀਨ ਲੱਭੋ",
    findLandCardDesc: "ਖਸਰਾ ਨੰਬਰ ਅਤੇ ਪਿੰਡ ਰਾਹੀਂ ਪ੍ਰਾਪਤੀ ਸਥਿਤੀ ਜਾਂਚੋ।",
    docIntelCardTitle: "AI ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ",
    docIntelCardDesc: "ਨੋਟਿਸ ਅੱਪਲੋਡ ਕਰਕੇ ਸਰਲ ਵਿਆਖਿਆ ਪ੍ਰਾਪਤ ਕਰੋ।",
    gisMapCardTitle: "GIS ਪ੍ਰੋਜੈਕਟ ਨਕਸ਼ਾ",
    gisMapCardDesc: "ਹਾਈਵੇ ਅਲਾਈਨਮੈਂਟ ਅਤੇ ਹੱਦਾਂ ਸੈਟੇਲਾਈਟ ਤੇ ਵੇਖੋ।",
    compensationCardTitle: "ਮੁਆਵਜ਼ਾ ਮੁਲਾਂਕਣ",
    compensationCardDesc: "RFCTLARR ਕਾਨੂੰਨ ਮੁਤਾਬਕ 100% ਸੋਲੇਸ਼ੀਅਮ ਅਤੇ DBT ਸਥਿਤੀ ਵੇਖੋ।",
    actionCenterCardTitle: "ਕਾਰਵਾਈ ਕੇਂਦਰ",
    actionCenterCardDesc: "ਕਾਨੂੰਨੀ ਸਮਾਂ-ਸੀਮਾ ਅਤੇ ਬਕਾਇਆ ਕੰਮ ਪ੍ਰਬੰਧਿਤ ਕਰੋ।",
    grievancesCardTitle: "ਸ਼ਿਕਾਇਤਾਂ ਅਤੇ ਇਤਰਾਜ਼",
    grievancesCardDesc: "ਧਾਰਾ 15 ਇਤਰਾਜ਼ ਅਤੇ ਮੁਆਵਜ਼ਾ ਵਿਵਾਦ ਦਰਜ ਕਰੋ।",
    summaryParcelsCount: "ਜੁੜੇ ਹੋਏ ਖਸਰਾ ਨੰਬਰ",
    summaryActiveAcquisitions: "ਸਰਗਰਮ ਪ੍ਰਾਪਤੀ ਪ੍ਰਕਿਰਿਆ",
    summaryTotalAssessedComp: "ਕੁੱਲ ਨਿਰਧਾਰਤ ਮੁਆਵਜ਼ਾ",
    summaryPendingActions: "ਜ਼ਰੂਰੀ ਬਕਾਇਆ ਕਾਰਵਾਈਆਂ",
    timelineTitle: "ਕਾਨੂੰਨੀ ਪ੍ਰਾਪਤੀ ਤਰੱਕੀ",
    timelineSub: "RFCTLARR ਐਕਟ 2013 ਅਨੁਸਾਰ ਕੇਸ ਦੇ ਪੜਾਅ",
    stepSec11: "ਧਾਰਾ 11(1) ਮੁੱਢਲੀ ਨੋਟੀਫਿਕੇਸ਼ਨ",
    stepSec15: "ਧਾਰਾ 15 ਸੁਣਵਾਈ ਅਤੇ ਇਤਰਾਜ਼",
    stepSec19: "ਧਾਰਾ 19 ਅੰਤਿਮ ਘੋਸ਼ਣਾ",
    stepSec23: "ਧਾਰਾ 23 ਮੁਆਵਜ਼ਾ ਅਵਾਰਡ",
    stepPayment: "PFMS ਮੁਆਵਜ਼ਾ ਵੰਡ",
    stepPossession: "ਕਬਜ਼ਾ ਅਤੇ ਮੁੜ ਵਸੇਬਾ",
    discrepancyBannerTitle: "ਚੇਤਾਵਨੀ: ਖਸਰਾ #1042 ਦੇ ਰਕਬੇ ਵਿੱਚ ਅੰਤਰ ਪਾਇਆ ਗਿਆ ਹੈ",
    discrepancyBannerDesc: "ਨੋਟਿਸ ਵਿਚਲਾ ਰਕਬਾ (1.10 ਹੈਕਟੇਅਰ) ਮਾਲ ਰਿਕਾਰਡ ਨਾਲੋਂ ਘੱਟ ਹੈ। ਧਾਰਾ 15(1) ਅਧੀਨ 60 ਦਿਨਾਂ ਵਿੱਚ ਇਤਰਾਜ਼ ਦਰਜ ਕਰੋ।",
    reviewDiscrepancyBtn: "ਅੰਤਰ ਸਮੀਖਿਆ",
    fileObjectionBtn: "ਇਤਰਾਜ਼ ਦਰਜ ਕਰੋ",
    findLandTitle: "ਖਸਰਾ ਨੰਬਰ ਰਾਹੀਂ ਜ਼ਮੀਨ ਖੋਜ",
    findLandSubtitle: "ਹਾਈਵੇ ਜਾਂ ਰੇਲਵੇ ਪ੍ਰੋਜੈਕਟ ਅਧੀਨ ਜ਼ਮੀਨ ਤੁਰੰਤ ਲੱਭੋ।",
    surveyInputLabel: "ਖਸਰਾ ਨੰਬਰ / ਮੁਰੱਬਾ",
    surveyInputPlaceholder: "ਉਦਾ. 1042 ਜਾਂ 45/A",
    villageSelectLabel: "ਪਿੰਡ",
    allVillagesOption: "ਸਾਰੇ ਪਿੰਡ",
    districtSelectLabel: "ਜ਼ਿਲ੍ਹਾ",
    allDistrictsOption: "ਸਾਰੇ ਜ਼ਿਲ੍ਹੇ",
    searchLandSubmitBtn: "ਜ਼ਮੀਨ ਲੱਭੋ",
    searchResultsHeading: "ਖੋਜ ਨਤੀਜੇ",
    parcelCardSurveyLabel: "ਖਸਰਾ ਨੰਬਰ:",
    parcelCardVillageLabel: "ਪਿੰਡ ਅਤੇ ਜ਼ਿਲ੍ਹਾ:",
    parcelCardAreaLabel: "ਨੋਟੀਫਾਈਡ ਰਕਬਾ:",
    parcelCardOwnerLabel: "ਮਾਲਕ ਦਾ ਨਾਮ:",
    parcelCardProjectLabel: "ਪ੍ਰੋਜੈਕਟ:",
    parcelCardStageLabel: "ਮੌਜੂਦਾ ਪੜਾਅ:",
    parcelCardCompLabel: "ਨਿਰਧਾਰਤ ਮੁਆਵਜ਼ਾ:",
    viewGisMapBtn: "GIS ਨਕਸ਼ੇ ਤੇ ਵੇਖੋ",
    viewCompDetailsBtn: "ਮੁਆਵਜ਼ਾ ਵੇਰਵੇ",
    noSearchResultsTitle: "ਕੋਈ ਜ਼ਮੀਨ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ",
    noSearchResultsDesc: "ਸਹੀ ਖਸਰਾ ਨੰਬਰ ਅਤੇ ਪਿੰਡ ਜਾਂਚ ਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    gisTitle: "ਇੰਟਰਐਕਟਿਵ GIS ਪ੍ਰੋਜੈਕਟ ਹੱਦ ਨਕਸ਼ਾ",
    gisSubtitle: "ਪ੍ਰਾਪਤੀ ਅਲਾਈਨਮੈਂਟ, ਬਫਰ ਜ਼ੋਨ ਅਤੇ ਨਾਲ ਲੱਗਦੇ ਖਸਰਾ ਨੰਬਰ ਵੇਖੋ।",
    legendTitle: "ਨਕਸ਼ਾ ਸੂਚਕ",
    legendAcquired: "ਨੋਟੀਫਾਈਡ ਪ੍ਰਾਪਤੀ ਖੇਤਰ",
    legendBuffer: "ਪ੍ਰੋਜੈਕਟ ਬਫਰ ਜ਼ੋਨ (50 ਮੀਟਰ)",
    legendYourLand: "ਤੁਹਾਡਾ ਖਸਰਾ ਨੰਬਰ (#1042)",
    legendAdjacent: "ਨਾਲ ਲੱਗਦੇ ਖਸਰਾ ਨੰਬਰ",
    mapLayerControl: "ਨਕਸ਼ਾ ਪਰਤਾਂ",
    layerSatellite: "ਸੈਟੇਲਾਈਟ ਦ੍ਰਿਸ਼",
    layerCadastral: "ਮਾਲ ਰਿਕਾਰਡ ਨਕਸ਼ਾ (Cadastral)",
    layerProjectAlign: "ਪ੍ਰੋਜੈਕਟ ਅਲਾਈਨਮੈਂਟ ਲਾਈਨ",
    parcelInfoPanelTitle: "ਚੁਣੇ ਹੋਏ ਖਸਰੇ ਦੀ ਜਾਣਕਾਰੀ",
    infoSurveyNo: "ਖਸਰਾ ਨੰਬਰ",
    infoVillage: "ਪਿੰਡ ਅਤੇ ਤਹਿਸੀਲ",
    infoTotalArea: "ਕੁੱਲ ਰਕਬਾ",
    infoAcquiredArea: "ਐਕਵਾਇਰ ਰਕਬਾ",
    infoOwner: "ਮਾਲਕ ਦਾ ਨਾਮ",
    infoStatus: "ਪ੍ਰਾਪਤੀ ਸਥਿਤੀ",
    infoEstimatedVal: "ਨਿਰਧਾਰਤ ਮੁਆਵਜ਼ਾ",
    measureDistanceBtn: "ਦੂਰੀ ਮਿਣੋ",
    measureAreaBtn: "ਰਕਬਾ ਮਿਣੋ",
    clearMeasureBtn: "ਮਿਣਤੀ ਸਾਫ਼ ਕਰੋ",
    docIntelTitleFull: "AI ਸਰਕਾਰੀ ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ ਇੰਜਣ",
    docIntelSubtitle: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਗਜ਼ਟ ਨੋਟਿਸਾਂ ਦੀ ਸਰਲ ਭਾਸ਼ਾ ਵਿੱਚ ਸਮਝ ਪ੍ਰਾਪਤ ਕਰੋ।",
    uploadZoneTitle: "ਨੋਟਿਸ ਜਾਂ ਅਵਾਰਡ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
    uploadZoneSubtitle: "PDF, JPG ਜਾਂ PNG ਫਾਈਲ ਚੁਣੋ (ਵੱਧ ਤੋਂ ਵੱਧ 25MB)",
    sampleNoticesTitle: "ਜਾਂ ਨਮੂਨਾ ਨੋਟਿਸ ਪਰਖੋ:",
    sampleSec11Btn: "📄 ਧਾਰਾ 11(1) ਨੋਟਿਸ (ਖਸਰਾ #1042)",
    sampleAwardBtn: "📄 ਧਾਰਾ 23 ਅਵਾਰਡ ਹੁਕਮ",
    sampleSec19Btn: "📄 ਧਾਰਾ 19(1) ਘੋਸ਼ਣਾ ਨੋਟਿਸ",
    analysisResultsTitle: "AI ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ ਸਾਰੰਸ਼",
    docTypeDetected: "ਦਸਤਾਵੇਜ਼ ਦੀ ਕਿਸਮ",
    gazetteRefNo: "ਗਜ਼ਟ ਹਵਾਲਾ ਨੰਬਰ",
    issuingAuthority: "ਜਾਰੀਕਰਤਾ ਅਥਾਰਟੀ",
    issueDate: "ਪ੍ਰਕਾਸ਼ਨ ਮਿਤੀ",
    affectedVillage: "ਪ੍ਰਭਾਵਿਤ ਪਿੰਡ ਅਤੇ ਜ਼ਿਲ੍ਹਾ",
    statutorySection: "ਲਾਗੂ ਕਾਨੂੰਨੀ ਧਾਰਾ",
    keyFindingsHeading: "ਮੁੱਖ ਨੁਕਤੇ (ਸਰਲ ਭਾਸ਼ਾ ਵਿੱਚ):",
    detectedDiscrepanciesTitle: "⚠️ ਪਾਏ ਗਏ ਅੰਤਰ ਅਤੇ ਇਤਰਾਜ਼:",
    actionableStepsHeading: "ਤੁਹਾਡੇ ਲਈ ਅਗਲੇ ਕਦਮ:",
    confidenceScoreLabel: "AI ਸ਼ੁੱਧਤਾ ਦਰ:",
    downloadAnalysisReportBtn: "ਪੂਰੀ AI ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ",
    fileObjectionFromDocBtn: "ਇਸ ਨੋਟਿਸ ਤੇ ਇਤਰਾਜ਼ ਦਰਜ ਕਰੋ",
    compPageTitle: "ਕਾਨੂੰਨੀ ਮੁਆਵਜ਼ਾ ਅਤੇ ਮੁੜ ਵਸੇਬਾ (R&R) ਲਾਭ",
    compPageSubtitle: "RFCTLARR ਐਕਟ 2013 ਅਨੁਸਾਰ ਪੂਰਾ ਮੁਆਵਜ਼ਾ, ਸੋਲੇਸ਼ੀਅਮ ਅਤੇ DBT ਅਦਾਇਗੀ।",
    assessedLandValueCard: "ਮੂਲ ਜ਼ਮੀਨ ਮੁਲਾਂਕਣ",
    solatium100Card: "100% ਸੋਲੇਸ਼ੀਅਮ (ਤਸੱਲੀ ਰਕਮ)",
    statutoryInterestCard: "12% ਵਾਧੂ ਸਾਲਾਨਾ ਵਿਆਜ",
    totalCompensationCard: "ਕੁੱਲ ਅਵਾਰਡ ਮੁਆਵਜ਼ਾ",
    compBreakdownTitle: "ਮੁਆਵਜ਼ਾ ਗਣਨਾ ਦਾ ਪੂਰਾ ਵੇਰਵਾ (RFCTLARR ਅਨੁਸੂਚੀ 1)",
    colComponent: "ਘਟਕ",
    colStatutoryBasis: "ਕਾਨੂੰਨੀ ਆਧਾਰ",
    colCalculation: "ਗਣਨਾ ਵਿਧੀ",
    colAmount: "ਰਕਮ (₹)",
    rowBaseLandVal: "ਮੂਲ ਮਾਰਕੀਟ ਮੁੱਲ",
    rowBaseLandValDesc: "ਪਿਛਲੇ 3 ਸਾਲਾਂ ਦੇ ਔਸਤ ਰਜਿਸਟਰੀ ਮੁੱਲ ਦੇ ਆਧਾਰ ਤੇ",
    rowMultiFactor: "ਪੇਂਡੂ ਗੁਣਕ ਕਾਰਕ (1.5x)",
    rowMultiFactorDesc: "RFCTLARR ਐਕਟ ਦੀ ਧਾਰਾ 26(2) ਪੇਂਡੂ ਨਿਯਮ",
    rowSolatium: "100% ਲਾਜ਼ਮੀ ਸੋਲੇਸ਼ੀਅਮ",
    rowSolatiumDesc: "ਧਾਰਾ 30(1) ਅਨੁਸਾਰ ਬਰਾਬਰ ਸੋਲੇਸ਼ੀਅਮ ਰਕਮ",
    rowInterest: "12% ਵਾਧੂ ਸਾਲਾਨਾ ਵਿਆਜ",
    rowInterestDesc: "ਧਾਰਾ 30(3) ਅਨੁਸਾਰ ਨੋਟੀਫਿਕੇਸ਼ਨ ਤੋਂ ਅਵਾਰਡ ਤੱਕ",
    rowStructures: "ਇਮਾਰਤਾਂ ਅਤੇ ਢਾਂਚਿਆਂ ਦਾ ਮੁਆਵਜ਼ਾ",
    rowStructuresDesc: "ਲੋਕ ਨਿਰਮਾਣ ਵਿਭਾਗ ਦਾ ਮੁਲਾਂਕਣ",
    rowTrees: "ਦਰੱਖਤਾਂ ਅਤੇ ਫ਼ਸਲਾਂ ਦਾ ਮੁਆਵਜ਼ਾ",
    rowTreesDesc: "ਜੰਗਲਾਤ ਅਤੇ ਬਾਗਬਾਨੀ ਵਿਭਾਗ ਦਾ ਮੁਲਾਂਕਣ",
    rowTotalNet: "ਕੁੱਲ ਸ਼ੁੱਧ ਅਵਾਰਡ ਮੁਆਵਜ਼ਾ",
    paymentDistributionTitle: "PFMS ਸਿੱਧਾ ਲਾਭ ਤਬਾਦਲਾ (DBT) ਵੰਡ",
    linkedBankCard: "ਜੁੜਿਆ ਆਧਾਰ ਬੈਂਕ ਖਾਤਾ:",
    ifscCard: "IFSC ਕੋਡ:",
    pfmsTxnCard: "PFMS ਲੈਣ-ਦੇਣ ID:",
    disbursedDateCard: "ਜਮ੍ਹਾਂ ਹੋਣ ਦੀ ਮਿਤੀ:",
    paymentProgressLabel: "ਵੰਡ ਪ੍ਰਗਤੀ:",
    rrEntitlementsTitle: "ਮੁੜ ਵਸੇਬਾ ਅਤੇ ਪੁਨਰਵਾਸ (R&R) ਲਾਭ (ਅਨੁਸੂਚੀ 2)",
    rrResettlementHouse: "ਬਦਲਵਾਂ ਮਕਾਨ / ਪਲਾਟ ਅਲਾਟਮੈਂਟ",
    rrResettlementHouseDesc: "ਪ੍ਰਧਾਨ ਮੰਤਰੀ ਆਵਾਸ ਯੋਜਨਾ ਅਨੁਸਾਰ ਪੱਕਾ ਮਕਾਨ ਜਾਂ ਬਰਾਬਰ ਮੁਆਵਜ਼ਾ ਰਕਮ।",
    rrSubsistence: "ਗੁਜ਼ਾਰਾ ਗ੍ਰਾਂਟ (ਮਹੀਨਾਵਾਰ ਭੱਤਾ)",
    rrSubsistenceDesc: "ਪ੍ਰਭਾਵਿਤ ਪਰਿਵਾਰ ਨੂੰ ₹3,000 ਪ੍ਰਤੀ ਮਹੀਨਾ 12 ਮਹੀਨਿਆਂ ਲਈ।",
    rrTransport: "ਬਦਲੀ ਅਤੇ ਢੋਆ-ਢੁਆਈ ਭੱਤਾ",
    rrTransportDesc: "ਘਰੇਲੂ ਸਾਮਾਨ ਦੀ ਢੋਆ-ਢੁਆਈ ਲਈ ਇਕਮੁਸ਼ਤ ₹50,000।",
    rrSkill: "ਹੁਨਰ ਸਿਖਲਾਈ ਅਤੇ ਰੋਜ਼ਗਾਰ",
    rrSkillDesc: "ਪਰਿਵਾਰ ਦੇ ਇੱਕ ਮੈਂਬਰ ਨੂੰ ਹੁਨਰ ਵਿਕਾਸ ਸਿਖਲਾਈ ਅਤੇ ਰੋਜ਼ਗਾਰ ਸਹਾਇਤਾ।",
    disputeNoticeText: "ਯਾਦ ਰੱਖੋ: ਗਣਨਾ ਤੇ ਇਤਰਾਜ਼ ਹੋਵੇ ਤਾਂ ਅਵਾਰਡ ਜਾਰੀ ਹੋਣ ਦੇ 60 ਦਿਨਾਂ ਵਿੱਚ ਲੈਂਡ ਅਥਾਰਟੀ (LARRA) ਕੋਲ ਅਪੀਲ ਕੀਤੀ ਜਾ ਸਕਦੀ ਹੈ।",
    fileCompGrievanceBtn: "ਮੁਆਵਜ਼ੇ ਤੇ ਇਤਰਾਜ਼ / ਅਪੀਲ ਦਾਇਰ ਕਰੋ",
    documentsPageTitle: "ਡਿਜੀਟਲ ਦਸਤਾਵੇਜ਼ ਲਾਕਰ",
    documentsPageSubtitle: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਨਾਲ ਸਬੰਧਤ ਸਾਰੇ ਪੜਤਾਲੇ ਸਰਕਾਰੀ ਦਸਤਾਵੇਜ਼।",
    uploadDocBtn: "ਨਵਾਂ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
    allDocTypesFilter: "ਸਾਰੀਆਂ ਦਸਤਾਵੇਜ਼ ਕਿਸਮਾਂ",
    docTitleLandRecords: "ਜ਼ਮੀਨ ਮਲਕੀਅਤ ਰਿਕਾਰਡ (ਫ਼ਰਦ / ਜਮ੍ਹਾਂਬੰਦੀ)",
    docGovNotice: "ਸਰਕਾਰੀ ਗਜ਼ਟ ਨੋਟੀਫਿਕੇਸ਼ਨ",
    docIdentityProof: "ਪਛਾਣ ਅਤੇ ਪਤੇ ਦਾ ਸਬੂਤ",
    docTitleBankPassbook: "ਬੈਂਕ ਖਾਤਾ ਵੇਰਵੇ",
    docTitleClaimReceipts: "ਦਾਅਵਾ ਰਸੀਦਾਂ ਅਤੇ ਅਵਾਰਡ ਹੁਕਮ",
    docTableColName: "ਦਸਤਾਵੇਜ਼ ਦਾ ਨਾਮ",
    docTableColType: "ਸ਼੍ਰੇਣੀ",
    docTableColDate: "ਅੱਪਲੋਡ ਮਿਤੀ",
    docTableColStatus: "ਪੜਤਾਲ ਸਥਿਤੀ",
    docTableColActions: "ਕਾਰਵਾਈਆਂ",
    viewDocumentAction: "ਵੇਖੋ",
    downloadDocumentAction: "ਡਾਊਨਲੋਡ",
    explainWithAiAction: "AI ਨਾਲ ਸਮਝੋ",
    deleteDocumentAction: "ਮਿਟਾਓ",
    docStatusVerified: "ਪੜਤਾਲਿਆ",
    docStatusPending: "ਪੜਤਾਲ ਅਧੀਨ",
    actionCenterPageTitle: "ਨਾਗਰਿਕ ਕਾਰਵਾਈ ਕੇਂਦਰ ਅਤੇ ਮਿਆਦਾਂ",
    actionCenterPageSubtitle: "ਤੁਹਾਡੇ ਵੱਲੋਂ ਬਕਾਇਆ ਕੰਮ, ਸਰਕਾਰੀ ਨੋਟਿਸ ਅਤੇ ਕਾਨੂੰਨੀ ਸਮਾਂ-ਸੀਮਾ ਦਾ ਪ੍ਰਬੰਧਨ।",
    urgentActionsTitle: "ਜ਼ਰੂਰੀ ਕਾਨੂੰਨੀ ਕਾਰਵਾਈਆਂ",
    upcomingDeadlinesTitle: "ਆਉਣ ਵਾਲੀਆਂ ਮਿਆਦਾਂ ਅਤੇ ਸੁਣਵਾਈਆਂ",
    completedHistoryTitle: "ਮੁਕੰਮਲ ਕੀਤੀਆਂ ਕਾਰਵਾਈਆਂ",
    actionDueLabel: "ਆਖ਼ਰੀ ਮਿਤੀ:",
    daysLeftLabel: "ਦਿਨ ਬਾਕੀ",
    actionCompletedBadge: "ਮੁਕੰਮਲ",
    actionPendingBadge: "ਕਾਰਵਾਈ ਲੋੜੀਂਦੀ",
    btnCompleteAction: "ਕਾਰਵਾਈ ਮੁਕੰਮਲ ਕਰੋ",
    btnViewNoticeDetails: "ਨੋਟਿਸ ਵੇਰਵੇ",
    grievancesPageTitle: "ਨਾਗਰਿਕ ਸ਼ਿਕਾਇਤਾਂ ਅਤੇ ਧਾਰਾ 15 ਇਤਰਾਜ਼",
    grievancesPageSubtitle: "ਪ੍ਰਾਪਤੀ ਪ੍ਰਕਿਰਿਆ, ਰਕਬਾ ਜਾਂ ਮੁਆਵਜ਼ੇ ਤੇ ਇਤਰਾਜ਼ ਦਰਜ ਕਰੋ।",
    submitNewGrievanceBtn: "ਨਵਾਂ ਇਤਰਾਜ਼ / ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
    trackGrievancesHeading: "ਦਰਜ ਕੀਤੇ ਇਤਰਾਜ਼ਾਂ ਦੀ ਸਥਿਤੀ",
    grievanceModalTitle: "ਨਵਾਂ ਇਤਰਾਜ਼ ਦਰਜ ਕਰੋ",
    grievanceTypeLabel: "ਇਤਰਾਜ਼ ਦੀ ਸ਼੍ਰੇਣੀ",
    selectGrievanceTypePlaceholder: "ਸ਼੍ਰੇਣੀ ਚੁਣੋ",
    optCompensationDispute: "ਮੁਆਵਜ਼ਾ ਰਕਮ ਬਾਰੇ ਇਤਰਾਜ਼",
    optAreaDiscrepancy: "ਰਕਬਾ ਮਿਣਤੀ ਵਿੱਚ ਅੰਤਰ (ਧਾਰਾ 15)",
    optOwnershipDispute: "ਮਲਕੀਅਤ ਹੱਕ ਜਾਂ ਨਾਮ ਦਰੁਸਤੀ",
    optPaymentDelay: "ਮੁਆਵਜ਼ਾ ਮਿਲਣ ਵਿੱਚ ਦੇਰੀ (DBT/PFMS)",
    optRRDispute: "ਮੁੜ ਵਸੇਬਾ ਲਾਭ (R&R) ਨਾ ਮਿਲਣਾ",
    optOther: "ਹੋਰ ਪ੍ਰਸ਼ਾਸਕੀ ਮਸਲੇ",
    grievanceDescLabel: "ਇਤਰਾਜ਼ ਦਾ ਪੂਰਾ ਵੇਰਵਾ",
    grievanceDescPlaceholder: "ਆਪਣੀ ਸਮੱਸਿਆ ਵਿਸਥਾਰ ਨਾਲ ਲਿਖੋ...",
    supportingDocsLabel: "ਸਬੂਤ ਦਸਤਾਵੇਜ਼ ਨੱਥੀ ਕਰੋ (PDF, JPG - ਵੱਧ ਤੋਂ ਵੱਧ 10MB)",
    submitGrievanceConfirmBtn: "ਦਰਜ ਕਰੋ",
    grievanceTicketLabel: "ਟੋਕਨ ਨੰਬਰ:",
    assignedOfficerLabel: "ਨਿਵਾਰਨ ਅਧਿਕਾਰੀ:",
    expectedResolutionLabel: "ਸੰਭਾਵਿਤ ਹੱਲ ਮਿਤੀ:",
    hearingScheduleLabel: "ਸੁਣਵਾਈ ਮਿਤੀ:",
    officerRemarksLabel: "ਅਧਿਕਾਰੀ ਦੀ ਟਿੱਪਣੀ:",
    noticesPageTitle: "ਸੂਚਨਾਵਾਂ ਅਤੇ ਸਰਕਾਰੀ ਗਜ਼ਟ ਐਲਾਨ",
    noticesPageSubtitle: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਨਾਲ ਸਬੰਧਤ ਤਾਜ਼ਾ ਸਰਕਾਰੀ ਸੂਚਨਾਵਾਂ।",
    filterUnreadOnly: "ਨਾ-ਪੜ੍ਹੀਆਂ ਸੂਚਨਾਵਾਂ",
    btnMarkAllAsRead: "ਸਭ ਪੜ੍ਹੀਆਂ ਵਜੋਂ ਚਿੰਨ੍ਹਿਤ ਕਰੋ",
    noticeCardDateLabel: "ਮਿਤੀ:",
    noticeCardSectionLabel: "ਕਾਨੂੰਨੀ ਧਾਰਾ:",
    noticeCardDownloadGazetteBtn: "ਗਜ਼ਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    noticeCardExplainAiBtn: "AI ਨਾਲ ਸਮਝੋ",
    officerDashboardTitle: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਅਧਿਕਾਰੀ (LAO) ਕੰਟਰੋਲ ਕੇਂਦਰ",
    officerDashboardSubtitle: "ਪ੍ਰੋਜੈਕਟ ਖਸਰੇ, ਧਾਰਾ 15 ਇਤਰਾਜ਼ ਅਤੇ ਮੁਆਵਜ਼ਾ ਵੰਡ ਪ੍ਰਬੰਧਨ।",
    metricTotalAcquisitions: "ਕੁੱਲ ਪ੍ਰਾਪਤੀ ਪ੍ਰੋਜੈਕਟ",
    metricTotalParcels: "ਨੋਟੀਫਾਈਡ ਖਸਰਾ ਨੰਬਰ",
    metricDisbursedBudget: "ਵੰਡਿਆ ਮੁਆਵਜ਼ਾ ਬਜਟ",
    metricPendingReviews: "ਸਮੀਖਿਆ ਅਧੀਨ ਫਾਈਲਾਂ",
    officerSectionCases: "ਪ੍ਰੋਜੈਕਟ ਕੇਸ ਰਜਿਸਟਰੀ",
    officerSectionGrievances: "ਨਾਗਰਿਕ ਇਤਰਾਜ਼ ਅਤੇ ਸੁਣਵਾਈ ਕਤਾਰ",
    tableColCaseId: "ਕੇਸ ID",
    tableColProject: "ਪ੍ਰੋਜੈਕਟ ਦਾ ਨਾਮ",
    tableColVillage: "ਪਿੰਡ",
    tableColLandowner: "ਮਾਲਕ",
    tableColSurvey: "ਖਸਰਾ ਨੰ.",
    tableColArea: "ਰਕਬਾ (ਹੈਕਟੇਅਰ)",
    tableColStage: "ਕਾਨੂੰਨੀ ਪੜਾਅ",
    tableColCompStatus: "ਮੁਆਵਜ਼ਾ ਸਥਿਤੀ",
    tableColAction: "ਕਾਰਵਾਈਆਂ",
    btnReviewCase: "ਕੇਸ ਜਾਂਚੋ",
    btnUpdateStatus: "ਸਥਿਤੀ ਬਦਲੋ",
    btnScheduleHearing: "ਸੁਣਵਾਈ ਮਿਤੀ ਤੈਅ ਕਰੋ",
    btnDisbursePayment: "DBT ਫੰਡ ਮਨਜ਼ੂਰ ਕਰੋ",
    resolveGrievanceBtn: "ਨਿਪਟਾਰਾ ਹੁਕਮ ਜਾਰੀ ਕਰੋ",
    officerCasesTitle: "ਪ੍ਰੋਜੈਕਟ ਕੇਸਾਂ ਦੀ ਮਾਸਟਰ ਰਜਿਸਟਰੀ",
    officerCasesSub: "ਗਜ਼ਟ ਨੋਟਿਸ, ਮਿਣਤੀ ਅਤੇ ਮੁਆਵਜ਼ਾ ਅਵਾਰਡ ਪ੍ਰਬੰਧਨ ਪ੍ਰਣਾਲੀ।",
    searchCasePlaceholder: "ਕੇਸ ID, ਖਸਰਾ ਨੰਬਰ ਜਾਂ ਮਾਲਕ ਦੇ ਨਾਮ ਨਾਲ ਖੋਜੋ...",
    filterAllStages: "ਸਾਰੇ ਕਾਨੂੰਨੀ ਪੜਾਅ",
    stageVerification: "ਪੜਤਾਲ ਪੜਾਅ",
    stageHearing: "ਧਾਰਾ 15 ਸੁਣਵਾਈ",
    stageAward: "ਧਾਰਾ 23 ਅਵਾਰਡ ਹੁਕਮ",
    stagePayment: "DBT ਫੰਡ ਤਬਾਦਲਾ",
    stagePossession: "ਕਬਜ਼ਾ ਲੈਣਾ",
    caseOfficerNotesLabel: "ਅਧਿਕਾਰੀ ਦੀ ਟਿੱਪਣੀ ਅਤੇ ਹੁਕਮ ਵੇਰਵੇ",
    saveStatusUpdateBtn: "ਸੰਭਾਲੋ",
    noticeLabel: "ਅਹਿਮ ਨੋਟਿਸ:",
    tickerAdvisory: "ਨਾਗਰਿਕ ਸੁਨੇਹਾ: ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ ਸਥਿਤੀ ਅਤੇ ਮੁਆਵਜ਼ਾ ਆਨਲਾਈਨ ਜਾਂਚੋ।",
    tickerDocIntel: "ਨਵੀਂ ਸਹੂਲਤ: ਗਜ਼ਟ ਨੋਟਿਸ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ AI ਸਰਲ ਵਿਆਖਿਆ ਪ੍ਰਾਪਤ ਕਰੋ।",
    tickerObjections: "ਕਾਨੂੰਨੀ ਚੇਤਾਵਨੀ: ਧਾਰਾ 11(1) ਪ੍ਰਕਾਸ਼ਨ ਤੋਂ 60 ਦਿਨਾਂ ਵਿੱਚ ਧਾਰਾ 15 ਇਤਰਾਜ਼ ਦਰਜ ਕਰੋ।",
    tickerDbt: "PFMS DBT: ਮੁਆਵਜ਼ਾ ਰਕਮ ਸਿੱਧੀ ਆਧਾਰ ਲਿੰਕ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਜਮ੍ਹਾਂ ਹੁੰਦੀ ਹੈ।",
    footerTagline: "ਜ਼ਮੀਨ ਪ੍ਰਾਪਤੀ, ਮੁਆਵਜ਼ਾ ਅਤੇ ਮੁੜ ਵਸੇਬੇ ਦਾ ਪਾਰਦਰਸ਼ੀ ਰਾਸ਼ਟਰੀ ਨਾਗਰਿਕ ਪੋਰਟਲ",
    footerDescription: "RFCTLARR ਐਕਟ 2013 ਅਧੀਨ ਚਲਾਈ ਜਾਣ ਵਾਲੀ ਪਾਰਦਰਸ਼ੀ ਨਾਗਰਿਕ ਸੂਚਨਾ ਪ੍ਰਣਾਲੀ।",
    footerHelplineLabel: "ਰਾਸ਼ਟਰੀ ਜ਼ਮੀਨ ਅਧਿਕਾਰ ਹੈਲਪਲਾਈਨ:",
    footerServicesTitle: "ਨਾਗਰਿਕ ਸੇਵਾਵਾਂ",
    footerServiceFindLand: "ਜ਼ਮੀਨ ਲੱਭੋ",
    footerServiceDocIntel: "AI ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ",
    footerServiceGis: "GIS ਨਕਸ਼ਾ",
    footerServiceComp: "ਮੁਆਵਜ਼ਾ ਮੁਲਾਂਕਣ",
    footerServiceActions: "ਕਾਰਵਾਈ ਕੇਂਦਰ",
    footerServiceGrievances: "ਧਾਰਾ 15 ਇਤਰਾਜ਼",
    footerStatutoryTitle: "ਕਾਨੂੰਨੀ ਉਪਬੰਧ",
    footerStatutoryAct: "RFCTLARR ਐਕਟ, 2013",
    footerStatutorySec11: "ਧਾਰਾ 11(1) ਮੁੱਢਲੀ ਨੋਟੀਫਿਕੇਸ਼ਨ",
    footerStatutorySec15: "ਧਾਰਾ 15 ਇਤਰਾਜ਼ ਦਾ ਹੱਕ",
    footerStatutorySec19: "ਧਾਰਾ 19 ਅੰਤਿਮ ਘੋਸ਼ਣਾ",
    footerStatutorySec23: "ਧਾਰਾ 23 ਮੁਆਵਜ਼ਾ ਅਵਾਰਡ",
    footerStatutoryPfms: "PFMS ਸਿੱਧਾ ਲਾਭ ਤਬਾਦਲਾ",
    footerAssistanceTitle: "ਮਦਦ ਅਤੇ ਸੰਪਰਕ",
    footerAddress: "ਕੇਂਦਰੀ ਭੂਮੀ ਮਾਲ ਅਤੇ ਰਾਸ਼ਟਰੀ ਰਾਜਮਾਰਗ ਅਥਾਰਟੀ, ਨਵੀਂ ਦਿੱਲੀ",
    footerTollFree: "ਟੋਲ ਫ੍ਰੀ ਹੈਲਪਲਾਈਨ: 1800-180-LAND (5263)",
    footerEmail: "ਈਮੇਲ: support@sahaay.gov.in",
    footerCopyright: "© 2026 ਸਹਾਏ (SAHAAY) • ਭਾਰਤ ਸਰਕਾਰ। ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।",
    footerDemoDisclaimer: "ਇਹ ਪੋਰਟਲ ਨਮੂਨਾ ਜਾਣਕਾਰੀ ਵਾਲਾ ਅਧਿਕਾਰਤ ਨਾਗਰਿਕ ਸੇਵਾ ਮੰਚ ਹੈ।"
  };

  writeLocaleFile('pa', 'Punjabi (ਪੰਜਾਬੀ)', t);
}

generateBengali();
generateMarathi();
generateGujarati();
generatePunjabi();

