import { writeLocale, allKeys } from './locale-base.js';
import { TranslationSchema } from '../src/locales/types.js';

// ============================================================================
// 1. BODO (बड़ो - brx)
// ============================================================================
export function generateBodo() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: 'सहाय (SAHAAY)',
    emblemLetter: 'स',
    tagline: 'नोंथांनि हा। नोंथांनि खथियान। नोंथांनि हक।',
    heroSub: 'हा आजावनाय आरो सोरखारि खतिपुरननि थाखाय सुबुं खौरां पर्टेल',
    portalSubtitle: 'हा • खतिपुरन • फोसाबनाय • आजिर • खथियान ट्रेकिं',
    citizenPortal: 'सुबुं पर्टेल',
    officerPortal: 'हा आजावग्रा अफिसार पर्टेल',
    demoMode: 'डेमो मड चोलिगासिनो दं',
    signIn: 'साइन इन खालाम',
    signOut: 'साइन आउट',
    landowner: 'हानि बिगोमा',
    landOfficer: 'हा आजावग्रा अफिसार (LAO)',
    switchRole: 'बिबान सोलाय',
    switchCitizen: 'नागरिक (राजेश शर्मा)',
    switchOfficer: 'हा आजावग्रा अफिसार (विक्रम चौहान)',
    welcomeBack: 'बरायबाय',
    navHome: 'गाहाय बिलाइ',
    navFindLand: 'आंनि हा नागिर',
    navGisMap: 'GIS हानि नक्सा',
    navDocIntel: 'लेखा बिसार (AI)',
    navCompensation: 'खतिपुरन आरो फोसाबनाय (R&R)',
    navDocuments: 'लेखा बाकस',
    navActionCenter: 'मावथां जायगा',
    navGrievances: 'आजिर सुस्रांनाय',
    navNotices: 'फोरमायथि आरो हुसियार',
    navOfficerDashboard: 'अफिसार डेसबर्ड',
    navCasesRegistry: 'खथियान रेजिस्टार',
    navGrievancesQueue: 'आजिर सारि',
    citizenServices: 'सुबुं हा सिबिथाय',
    quickActions: 'गोख्रै मावनाय',
    submit: 'गथाय',
    save: 'थिन',
    cancel: 'दानखार',
    edit: 'सुद्राय',
    delete: 'हुखुमोर',
    search: 'नागिर',
    filter: 'सायख’',
    back: 'उनफारसे',
    next: 'सिगांफारसे',
    close: 'बन्द खालाम',
    view: 'नाय',
    download: 'दाउनलड',
    upload: 'आपलड खालाम',
    export: 'दैथायहर',
    refresh: 'गोदान खालाम',
    print: 'साफा खालाम',
    loading: 'लड जाबाय थादों...',
    actions: 'मावनाय',
    details: 'गुवारै',
    status: 'थासारि',
    viewDetails: 'गुवारै नाय',
    viewOnMap: 'नक्सायाव नाय',
    viewCase: 'गासै खथियान नाय',
    trackProgress: 'थासारि संदान',
    proceed: 'सिगां बाहाय',
    confirm: 'थार खालाम',
    retry: 'फिन नाजा',
    clearAll: 'गासै हुखुमोर',
    applyFilter: 'सायख’नाय बाहाय',
    active: 'चोलिगासिनो',
    pending: 'नेनाय / थाथ’नाय',
    completed: 'जोबबाय',
    rejected: 'नेवसिबाय',
    verified: 'थार बिजिरबाय',
    underReview: 'नायबिजिरगासिनो',
    urgent: 'गोनांथार',
    optional: 'खुसिबादि',
    required: 'नांगौथार',
    discrepancy: 'गोरोन्थि / फरक नुदों',
    findMyLand: 'आंनि हा नागिर',
    myLand: 'आंनि हा',
    surveyNo: 'दाग / खसरा नम्बर',
    enterSurveyNo: 'उदा. १०४२ एबा ४५/A लिर',
    village: 'गामि / मौजा',
    district: 'जिल्ला',
    state: 'रायजो',
    taluka: 'सार्केल / महकुमा',
    selectState: 'रायजो सायख’',
    selectDistrict: 'जिल्ला सायख’',
    selectVillage: 'गामि सायख’',
    recordedArea: 'रेकर्ड थानाय दानि',
    acquiredArea: 'आजावनाय दानि',
    remainingArea: 'थालांनाय दानि',
    landClassification: 'हानि रोखोम',
    ownershipType: 'बिगोमाथि रोखोम',
    marketValueRate: 'बजार बेसेन',
    hectares: 'हेक्टर',
    acres: 'बिगा / एकर',
    sqMeters: 'बर्ग मिटार',
    parcelStatus: 'दाग हानि थासारि',
    searchLandPrompt: 'नोंथांनि फोरमायथिनि दाग नम्बर होनानै थासारि नाय',
    searchLandBtn: 'हानि गुवारै नागिर',
    noLandFound: 'बे गुवारै जों जेबो हानि रेकर्ड मोनाविसै।',
    searchPlaceholder: 'दाग नं, गामि एबा फोरमायथि ID जों नागिर...',
    exactMatchFound: 'थार मिलन मोनबाय',
    gisMapTitle: 'GIS हाजो आरो दाग नक्सा',
    gisMapDesc: 'आजावनाय सिमा, गोहोम गोग्लैनाय ओनसोल आरो सेरफां नाय',
    satelliteView: 'सेटेलाइट दृश्य',
    streetView: 'लामा दृश्य',
    topographyView: 'हाजो-हाला दृश्य',
    legend: 'नक्सा सिन',
    acquiredZone: 'फोसावनाय आजावनाय ओनसोल',
    bufferZone: 'गोहोम गोग्लैनाय ओनसोल',
    yourParcel: 'नोंथांनि बिजिरनाय दाग',
    adjacentParcels: 'सेरफां दागफोर',
    zoomIn: 'गेदेर खालाम',
    zoomOut: 'फिसा खालाम',
    resetView: 'नक्सा फिन फज’',
    fullscreen: 'गासै स्क्रिन',
    parcelId: 'दाग ID',
    coordinates: 'भौगोलिक कोअर्डिनेट',
    distanceToProject: 'हाबाफारि लायननिफ्राय गोजानथि',
    measurementTool: 'ज’नाय आयदा',
    mapLayers: 'नक्सा लेयार',
    overlayCadastral: 'राजह नक्सा लेयार दाजाब',
    totalCompensation: 'गासै थि खतिपुरन',
    assessedValue: 'गाहाय हानि बेसेन',
    solatium: '१००% सोलेशियम (तोषण अनसुंथाय)',
    solatiumDesc: 'RFCTLARR आइन २०१३ दफा ३०(१) बादियै १००% खतिपुरन',
    interestAmount: 'बांसिन सुद आरो अनसुंथाय',
    structureValue: 'न’ / बिफां / सम्पत्ति खतिपुरन',
    calculatedTotal: 'गासै होनांगौ खतिपुरन रां',
    paymentStatus: 'PFMS रां राननाय थासारि',
    dbtStatus: 'DBT बैंक एकाउन्ट दाजाबनाय थासारि',
    disbursed: 'एकाउन्टआव जमा जाबाय',
    disbursedAmount: 'होनाय रां',
    remainingAmount: 'थालांनाय रां',
    bankAccount: 'दाजाबनाय बैंक एकाउन्ट',
    ifscCode: 'IFSC कोड',
    paymentRefNo: 'PFMS / ट्रेजारि ट्रानजेक्सन नम्बर',
    claimCompensation: 'दाबि आरज बिलाइ गथाय',
    downloadAwardLetter: 'अवार्ड आदेश दाउनलड खालाम (फर्म ११)',
    rrTitle: 'पुनर्वास आरो फोसाबनाय (R&R) सुबिदाफोर',
    rrEntitlement: 'R&R मोनथाय पेकेज',
    rrStatus: 'पुनर्वास मावफुं थासारि',
    resettlementHouse: 'सोलाय न’ / हा बाहागो',
    subsistenceGrant: 'थांना थानाय अनसुंथाय (दानारि)',
    transportAllowance: 'जायगा सोलायनाय लामा खरसा',
    trainingSkill: 'रंगौथि सोलोंथाय आरो खामानि',
    rrOfficerAssigned: 'थिसननाय R&R नोडल अफिसार',
    rrTimeline: 'R&R आवगायनाय समाव',
    docIntelTitle: 'AI लेखा बिसार इन्जिन',
    docIntelSub: 'सोरखारि आजावनाय फोरमायथि आरो गेजेट आदेश स्क्रेन खालामो',
    uploadNotice: 'फोरमायथि एबा अवार्ड लेखा आपलड खालाम',
    dragDropDoc: 'PDF, JPG एबा PNG फाइल एयाव लाबो एबा ब्राउज खालाम',
    supportedFormats: 'मान्य महर: PDF, JPEG, PNG (सीमा: २५MB)',
    analyzingDoc: 'AI लेखा बिसारगासिनो दं...',
    extractedData: 'लेखानिफ्राय मोननाय गुबै खौरां',
    legalClause: 'लागू आइन आरो दफा',
    section4_1: 'दफा ४(१) - गुदुं फोरमायथि',
    section11_1: 'दफा ११(१) - गुदुं संदान फोरमायथि',
    section19_1: 'दफा १९(१) - आजावनाय फोसावनाय',
    section21_2: 'दफा २१(२) - रायजोनि खोनासंनाय फोरमायथि',
    section23: 'दफा २३ - कमिसनारनि जोबथा अवार्ड',
    potentialDiscrepancy: 'गोरोन्थि / फरक नुजाबाय',
    discrepancyFound: 'फोरमायथि आरो राजह रेकर्डआव फरक दं',
    discrepancyDesc: 'फोरमायथिनि दानि सोरखारि रेकर्डनिफ्राय खम। गोख्रैनो आजिर गथाय।',
    reportDiscrepancy: 'आजिर / अजत गथाय',
    aiConfidenceScore: 'AI बिसारनि थारथि रेटिं',
    plainLanguageSummary: 'गोरलै रावआव गुसुं बिसार',
    actionDeadline: 'खामानि मावनायनि जोबथा सान',
    documentLocker: 'डिजिटेल लेखा बाकस',
    allDocuments: 'गासै थार नायनाय लेखाफोर',
    verifiedDocuments: 'सोरखारि गनायथि लेखाफोर',
    pendingVerification: 'नायबिजिरनो थाबावनाय',
    uploadNewDoc: 'गोदान लेखा आपलड खालाम',
    docType: 'लेखानि रोखोम',
    selectDocType: 'लेखा रोखोम सायख’',
    docLandTitle: 'हानि बिगोमाथि लेखा (पट्टा / खथियान)',
    docGovNotice: 'सोरखारि हा आजावनाय फोरमायथि',
    docIdentityProof: 'सिनथि बिलाइ (आधार / पेन कार्ड)',
    docBankPassbook: 'बैंक पासबुक / केन्सेल चेक',
    docGrievanceProof: 'आजिरनि साखि लेखा',
    fileSize: 'फाइलनि महर',
    uploadDate: 'आपलड खालामनाय सान',
    viewDoc: 'लेखा नाय',
    downloadDoc: 'लेखा दाउनलड खालाम',
    deleteDoc: 'लेखा हुखुमोर',
    confirmDeleteDoc: 'नोंथाङा थारैनो बे लेखाखौ हुखुमोरनो लुबैदों नामा?',
    grievancesTitle: 'सुबुं आजिर आरो खथियान सुस्रांनाय राहा',
    submitGrievance: 'गोदान आजिर गथाय',
    grievanceType: 'आजिरनि रोखोम',
    selectGrievanceType: 'आजिर थाखो सायख’',
    typeCompensationAmount: 'खतिपुरन साननायनि सायाव अजत',
    typeAreaDiscrepancy: 'दानि नापआव गोरोन्थि',
    typeOwnershipDispute: 'बिगोमाथि दाबि एबा मुं सुद्रायनाय',
    typePaymentDelay: 'खतिपुरन रां मोननायाव लामजिनाय',
    typeRRNonReceipt: 'पुनर्वास सुबिदा मोनै',
    typeOther: 'गुबुन हाबाफारि जेंना',
    grievanceSubject: 'आजिरनि आयदा',
    grievanceDesc: 'आजिरनि गासै गुवारै',
    grievanceDescPlaceholder: 'नोंथांनि जेंनाखौ गुवारै लिर...',
    attachEvidence: 'साखि लेखा दाजाब',
    grievanceStatus: 'आजिर सुस्रां थासारि',
    ticketNumber: 'टोकन नम्बर',
    assignedToOfficer: 'थिसननाय सुस्रांग्रा अफिसार',
    expectedResolutionDate: 'सुस्रां मिजिं सान',
    hearingDate: 'साखाथि खोनासंनाय सान',
    officerRemarks: 'अफिसारनि सोरखारि फिननाय',
    resolutionSummary: 'जोबथा सुस्रां गुसुं',
    actionCenterTitle: 'सुबुं मावथां जायगा आरो आइन समाव',
    pendingActions: 'नोंथांनि मावनो थानाय हाबाफोर',
    completedActions: 'जोबनाय हाबाफोर',
    urgentDeadlines: 'आइन समावनि हुसियार',
    actObjectionPeriod: 'दफा १५(१) बादियै आजिरनि ६० सान समाव',
    actSubmitBankDocs: 'खतिपुरननि थाखाय बैंक खौरां गथाय',
    actAttendHearing: 'कमिसनारनि खोनासंनायाव बाहागो ला',
    markCompleted: 'जोबबाय होनना सिन हो',
    daysRemaining: 'सान थाबावदों',
    expiredDeadline: 'समाव जोबबाय',
    notificationTitle: 'फोरमायथि आरो सोरखारि फोसावनाय',
    allNotifications: 'गासै फोरमायथिफोर',
    unreadOnly: 'परायै ल’',
    markAllRead: 'गासै फरायबाय होनना सिन हो',
    noNotifications: 'दानि जेबो गोदान फोरमायथि गैया।',
    officerTitle: 'हा आजावग्रा अफिसार (LAO) सामलाय जायगा',
    officerCasesRegistry: 'हाबाफारि खथियान गाहाय रेजिस्टार',
    totalAcquisitions: 'गासै आजावनाय हाबाफारि',
    activeParcels: 'चोलिगासिनो दागफोर',
    totalDisbursedBudget: 'गासै राननाय बजेट',
    pendingApprovals: 'गनायथिनो थाबावनाय फाइल',
    caseId: 'खथियान ID',
    caseName: 'हाबाफारिनि मुं',
    affectedLandowners: 'गोहोम गोग्लैनाय हानि बिगोमाफोर',
    stage: 'दानि आइन थाखो',
    stage1_Survey: 'थाखो १: समाजारि गोहोम आरो संदान',
    stage2_Notification: 'थाखो २: दफा ११(१) गुदुं फोरमायथि',
    stage3_Objections: 'थाखो ३: दफा १५ खोनासंनाय आरो आजिर',
    stage4_Declaration: 'थाखो ४: दफा १९ आजावनाय फोसावनाय',
    stage5_Award: 'थाखो ५: दफा २३ अवार्ड आरो खतिपुरन थि',
    stage6_Payment: 'थाखो ६: PFMS खतिपुरन राननाय',
    stage7_Possession: 'थाखो ७: हा खाबनाय आरो R&R मावफुं',
    approve: 'गनायथि हो',
    reject: 'नेवसि',
    forwardToUpper: 'गेदेर अफिसारनो दैथायहर',
    scheduleHearing: 'खोनासंनाय सान थि खालाम',
    issueNotice: 'आइन फोरमायथि हगार',
    disburseFunds: 'रां हगार',
    officerRemarksPlaceholder: 'सोरखारि नायबिजिरनाय नोट लिर...',
    saveDecision: 'थि खालामनाय थिन',
    step: 'आगा',
    of: 'नि',
    surveyRequired: 'दाग नम्बर नांगौथार',
    enterValidSurvey: 'अननानै थार दाग नम्बर लिर',
    villageRequired: 'गामिनि मुं नांगौथार',
    districtRequired: 'जिल्लानि मुं नांगौथार',
    compensationBreakdown: 'खतिपुरननि गासै साननाय',
    marketValueCalculated: 'थि गाहाय हानि बेसेन',
    multiplicationFactor: 'गामि सानजाब गुदि (RFCTLARR फारिलाइ १)',
    additionalAssetValuation: 'बिफां, दै बाख्रि आरो न’नि बेसेन',
    statutoryInterest: 'दफा ३०(३) बादियै १२% बोसोराव बांसिन सुद',
    netEntitlement: 'गासै होनांगौ खतिपुरन रां',
    readyForPFMS: 'PFMS जों होनो साजायबाय',
    disbursementHistory: 'सिगांनि होनाय जारिमिन',
    noDisbursementsYet: 'दासिम जेबो रां होनाय जायाखै।',
    compensationDisputeHelp: 'साननायाव अजत थायोब्ला लेन्ड अथरिटि (LARR) आव आपिल खालामनो हागौ।',
    trackDisbursement: 'PFMS पर्टेलआव संदान',
    viewAllNotices: 'गासै गेजेट फोरमायथि नाय',
    noActionsPending: 'दानि नोंथांनि जेबो हाबा मावनो गैया।',
    officerQueueEmpty: 'थाबावनाय खथियान फारिलाइ लांदां।',
    discrepancyResolution: 'गोरोन्थि सुस्रां हाबाफारि',
    fileAppeal: 'लेन्ड एक्विजिसन अथरिटि (LARRA) आव आपिल गथाय',
    disputeDeadlineWarning: 'गोसोआव लाखि: अवार्ड हगारनायनि ६० साननि गेजेराव आपिल खालामनो हायो।',
    noticeDetails: 'फोरमायथिनि गासै गुवारै',
    gazetteDate: 'गेजेट फोसावनाय सान',
    competentAuthority: 'गनायथिगोनां बिबान (CALA / SDO)',
    projectAlignmentMap: 'गाहाय लामा / रेल लामा नक्सा',
    surveyBoundaries: 'राजह संदान सिमा',
    parcelAreaMismatch: 'दाग दानिआव फरक दं',
    expectedArea: 'राजह रेकर्ड दानि',
    noticeArea: 'फोरमायथिआव थानाय दानि',
    difference: 'फरक',
    takeImmediateAction: 'गोख्रैनो आगा ला',
    appealPeriodActive: 'आपिल समाव चोलिगासिनो दं',
    appealDaysLeft: 'आपिलनि थाखाय थानाय सान',
    submitClaimDocuments: 'दाबि लेखा गोख्रैनो गथाय',
    uploadSuccess: 'लेखा मोजाङै आपलड जाबाय!',
    uploadFailure: 'लेखा आपलड जायाखै। फिन नाजा।',
    deleteConfirmTitle: 'लेखा हुखुमोरनो?',
    deleteConfirmDesc: 'बे लेखाखौ हुखुमोरब्ला फिन मोनफिननाय नङा।',
    grievanceSubmittedSuccess: 'नोंथांनि आजिरा मोजाङै गथाय जाबाय!',
    grievanceTrackingTip: 'थासारि मिथिनो टोकन नम्बरखौ मोजाङै थिन।',
    hearingScheduledAlert: 'खोनासंनाय सान थि जाबाय।',
    attendHearingNotice: 'लेखाफोरजों लोगोसे थि समाव नुजाथिहै।',
    contactHelpdesk: 'मदत जायगाजों राब्ता खालाम',
    tollFreeNumber: 'खरसा गैयै नम्बर: १८००-१११-९९९९',
    helpdeskTiming: 'सोमबारनिफ्राय सुनिबार, फुंनि ९ निफ्राय बेलासे ६ बाजसिम',
    faqTitle: 'सोंबाय थानाय सोंलुफोर (FAQ)',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'नेम आरो सर्तफोर',
    accessibilityStatement: 'सुबिदा फोरमायथि',
    govtOfIndia: 'भारत सोरखार',
    ministryOfRuralDev: 'गामि जौगानाय आरो हा सम्पद मन्त्रालय',
    allRightsReserved: 'गासै मोनथाय लाखिनाय।',
    disclaimer: 'बे पर्टेला सांग्रांथि थाखाय। सोरखारि गेजेट फोरमायथियासो जोबथा।',
    heroTitle: 'नोंथांनि हानि खौरां रोखा खालामो।',
    heroDesc: 'हा आजावनाय हाबाफारिखौ मोजाङै संदान, १००% सोलेशियमजों थार खतिपुरन मोन आरो आजिरफोरखौ गोरलैयै सुस्रां।',
    findLandBtn: 'आंनि हा नागिर',
    trackCaseBtn: 'खथियान संदान',
    understandDocBtn: 'लेखा बिसार',
    exploreMapBtn: 'नक्सा नाय',
    tickerAdvisory: 'सुबुं खौरां: हा आजावनाय फोरमायथि मोननायनि ६० साननि गेजेराव दफा १५(१) बादियै आजिर गथायनो हायो।',
    noticeLabel: 'गोदान फोरमायथि:',
    feature1Title: 'थार हा नागिरनाय',
    feature1Desc: 'दाग नम्बरजों हानि दानि, सिमा आरो थासारि गोख्रैनो मिथि।',
    feature2Title: 'स्मार्ट लेखा बिसार',
    feature2Desc: 'फोरमायथिनि आइन आयदा, फरक आरो गोनां सानफोरखौ AI जों गोरलैयै बुजि।',
    feature3Title: '१००% खतिपुरन रोखाथि',
    feature3Desc: 'RFCTLARR आइन बादियै गासै सोलेशियम, सुद आरो DBT राननाय खौरां नाय।',
    feature4Title: 'गोरलै आजिर सुस्रांनाय',
    feature4Desc: 'दानि एबा खतिपुरनआव फरक थायोब्ला थोंजोङै अफिसारनो आजिर गथाय।',
    compensation: 'खतिपुरन',
    rr: 'पुनर्वास (R&R)',
    documents: 'लेखाफोर',
    grievances: 'आजिरफोर',
    actionRequired: 'हाबा मावनांगौ',
    inProgress: 'चोलिगासिनो',
    helpdesk: 'मदत केंद्र',
    dashboard: 'डेसबर्ड',
    home: 'गाहाय बिलाइ',
    profile: 'प्रोफाइल',
    settings: 'सेटिंफोर',
    notifications: 'फोरमायथिफोर',
    logout: 'साइन आउट',
    login: 'साइन इन',
    email: 'इमेल थं',
    password: 'पासवर्ड',
    forgotPassword: 'पासवर्ड बावबाय नामा?',
    register: 'रेजिस्टार खालाम',
    rememberMe: 'आंखौ गोसोआव लाखि',
    citizenLogin: 'नागरिक साइन इन',
    officerLogin: 'अफिसार साइन इन',
    demoCredentials: 'डेमो खौरां',
    enterEmail: 'नोंथांनि इमेल लिर',
    enterPassword: 'नोंथांनि पासवर्ड लिर',
    welcomeCitizen: 'नागरिक बरायबाय',
    welcomeOfficer: 'अफिसार बरायबाय',
    quickStats: 'गुसुं अनजिमा',
    totalCases: 'गासै खथियान',
    resolvedCases: 'सुस्रांनाय खथियान',
    pendingReviews: 'नायबिजिरनो थानाय',
    myParcels: 'आंनि हा दागफोर',
    caseTimeline: 'खथियान समाव-फारिलाइ',
    recentActivity: 'दानि हाबाफोर',
    downloadReport: 'रिपोर्ट दाउनलड खालाम',
    filterByStatus: 'थासारि बादियै सायख’',
    allStatuses: 'गासै थासारि',
    sortBy: 'फारिलाइ खालाम',
    newestFirst: 'गोदान सिगां',
    oldestFirst: 'गोदो सिगां',
    name: 'मुं',
    phone: 'फोन नम्बर',
    address: 'थं',
    remarks: 'फिननाय',
    category: 'थाखो',
    date: 'सान',
    time: 'समाव',
    type: 'रोखोम',
    viewAll: 'गासै नाय',
    clearFilters: 'सायख’नाय हुखुमोर',
    resultsFound: 'फिन मोनबाय',
    noResults: 'जेबो मोननाय जायाखै',
    fileUploadSuccess: 'फाइल मोजाङै आपलड जाबाय',
    fileUploadError: 'आपलड खालामाव गोरोन्थि जाबाय',
    fileDeleted: 'फाइल हुखुमोरबाय',
    changesSaved: 'सोलायनायफोरखौ थिनबाय',
    actionSuccess: 'हाबा जाफुंबाय',
    actionFailed: 'हाबा जायाखै',
    sessionExpired: 'समाव जोबबाय, फिन साइन इन खालाम',
    unauthorized: 'हुखुम गैनि हाबनाय',
    serverError: 'सार्भार गोरोन्थि, उनाव नाजा',
    networkError: 'नेटवर्क गोरोन्थि',
    tryAgain: 'फिन नाजा',
    goBack: 'उनफारसे थां',
    goToHome: 'गाहाय बिलाइयाव थां',
    viewMore: 'बांसिन नाय',
    viewLess: 'खम नाय',
    copied: 'कपि जाबाय!',
    copyToClipboard: 'क्लिपबोर्डआव कपि खालाम',
    yes: 'औ',
    no: 'नङा',
    ok: 'मोजां',
    help: 'मदत',
    feedback: 'मनाभाव',
    contactUs: 'राब्ता खालाम',
    aboutUs: 'जोंनि बागै',
    version: 'महर',
    systemStatus: 'सिस्टम थासारि',
    online: 'अनलाइन',
    offline: 'अफलाइन',
    connecting: 'दाजाबगासिनो दं...',
    syncing: 'सिंक जाबाय थादों...',
    lastUpdated: 'जोबथा गोदान खालामनाय',
    justNow: 'दानिखालि',
    minutesAgo: 'मिनिट सिगां',
    hoursAgo: 'घन्टा सिगां',
    daysAgo: 'सान सिगां',
    readMore: 'बांसिन फराय',
    showMore: 'बांसिन दिन्थि',
    showLess: 'खम दिन्थि',
    selectAll: 'गासै सायख’',
    deselectAll: 'गासै हुखुमोर',
    expandAll: 'गासै फेहेर',
    collapseAll: 'गासै समेट',
    openInNewTab: 'गोदान टेबआव खुलि',
    previous: 'सिगांनि',
    pageOf: 'बिलाइ',
    rowsPerPage: 'फारि प्रति बिलाइ',
    totalRecords: 'गासै रेकर्ड',
    noRecordsFound: 'जेबो रेकर्ड मोनाखै',
    pleaseWait: 'अननानै नेथ’...',
    somethingWentWrong: 'माबा गोरोन्थि जाबाय',
    fieldRequired: 'बे खथाया गोनांथार',
    invalidEmail: 'थार इमेल थं लिर',
    invalidPhone: 'थार १० अनजिमानि मबाइल नम्बर लिर',
    passwordTooShort: 'पासवर्ड खमसेखम ८ हांखोनि जानांगौ',
    passwordsDoNotMatch: 'पासवर्ड मिलायाखै',
    termsAgreement: 'आं नेम आरो सर्तफोरखौ मानियो',
    agreeToTerms: 'सिगां बाहायनो सर्तफोर गनाय',
    selectLanguage: 'राव सायख’',
    currentLanguage: 'दानि राव',
    languageChanged: 'राव मोजाङै सोलायबाय',
    autoDetectLocation: 'जायगा गावआरि संदान',
    locationAccessDenied: 'जायगा हुखुम नेवसिबाय',
    useManualSearch: 'अननानै गावनो नागिर',
    satelliteLayer: 'सेटेलाइट लेयार',
    cadastralLayer: 'राजह नक्सा लेयार',
    projectBufferLayer: 'हाबाफारि बफर लेयार',
    measuringDistance: 'गोजानथि ज’गासिनो दं',
    measuringArea: 'दानि ज’गासिनो दं',
    clickToMeasure: 'ज’नो नक्सायाव क्लिक खालाम',
    clearMeasurement: 'नाप हुखुमोर',
    totalDistance: 'गासै गोजानथि',
    totalArea: 'गासै दानि',
    meters: 'मिटार',
    kilometers: 'किमी',
    discrepancyDetails: 'गोरोन्थिनि गुवारै',
    affectedSections: 'गोहोम गोग्लैनाय दफाहरू',
    recommendedAction: 'सुबुरुन हाबा',
    fileGrievanceNow: 'दानोनो आजिर गथाय',
    viewDiscrepancyReport: 'गोरोन्थि रिपोर्ट नाय',
    aiConfidence: 'AI थारथि थाखो',
    highConfidence: 'गोबोर थारथि (९५%+)',
    mediumConfidence: 'गेजेर थारथि',
    lowConfidence: 'खम थारथि',
    extractedEntities: 'मोननाय खौरांफोर',
    officialGazetteNo: 'सोरखारि गेजेट नम्बर',
    notificationDate: 'फोरमायथि सान',
    competentAuthorityName: 'गनायथिगोनां अफिसारनि मुं',
    hearingVenue: 'खोनासंनाय जायगा',
    objectionDeadlineDate: 'आजिर गथायनायनि जोबथा सान',
    documentVerifiedBadge: 'सोरखारि थार बिजिरबाय',
    documentPendingBadge: 'बिजिरगासिनो दं',
    documentRejectedBadge: 'लेखा नेवसिबाय',
    reuploadDocument: 'लेखा फिन आपलड खालाम',
    reasonForRejection: 'नेवसिनायनि जाहोन',
    downloadCertificate: 'प्रमाणपत्र दाउनलड खालाम',
    shareDocument: 'लेखा सेयार खालाम',
    printSummary: 'गुसुं साफा खालाम',
    directBenefitTransfer: 'थोंजोङै अनसुंथाय सोलाय (DBT)',
    pfmsTrackingStatus: 'PFMS रां होनाय संदान',
    bankAccountVerified: 'बैंक एकाउन्ट थार बिजिरबाय',
    bankAccountPending: 'बैंक एकाउन्ट बिजिरनो थाबावनाय',
    treasuryRefNumber: 'ट्रेजारि रेफारेन्स नम्बर',
    disbursementDate: 'रां हगारनाय सान',
    installmentNumber: 'किस्ति नम्बर',
    partialPayment: 'खावसे रां',
    fullPayment: 'गासै रां',
    solatiumAmount: 'सोलेशियम रां (१००%)',
    baseCompensation: 'गाहाय हानि खतिपुरन',
    statutoryInterestValue: 'आइन सुद रां',
    totalAwardAmount: 'गासै अवार्ड रां',
    displacedFamilyId: 'जायगा सोलायनाय नखर ID',
    resettlementSiteName: 'पुनर्वास कलनिनि मुं',
    plotAllotmentStatus: 'हा बाहागो थासारि',
    housingGrantStatus: 'न’ अनसुंथाय थासारि',
    annuityBenefitStatus: 'दानारि पेन्सन थासारि',
    skillTrainingStatus: 'हुनर सोलोंथाय थासारि',
    livelihoodGrant: 'जिउ थांनाय अनसुंथाय',
    officerCaseManagement: 'खथियान सामलायनाय',
    citizenGrievanceQueue: 'सुबुं आजिर सारि',
    hearingManagement: 'खोनासंनाय सामलायनाय',
    awardDrafting: 'अवार्ड ड्राफ्ट आरो गनायथि',
    fundSanction: 'रां गनायथि आरो राननाय',
    reportsAndAnalytics: 'रिपोर्ट आरो बिसार',
    bulkNoticeGeneration: 'लोगोसे फोरमायथि हगार',
    cadastralSync: 'राजह नक्सा सिंक',
    exportToExcel: 'Excel प्रारूपआव दाउनलड',
    exportToPdf: 'PDF रिपोर्ट दाउनलड',
    auditLog: 'अडिट लग',
    loginHistory: 'साइन इन जारिमिन',
    officerBadge: 'सोरखारि अफिसार थाखो',
    citizenBadge: 'थार नागरिक',
    stepCompleted: 'बे आगा जोबबाय',
    stepInProgress: 'बे आगा चोलिगासिनो दं',
    stepPending: 'बे आगा थाबावदों',
    timelineOverview: 'आजावनाय जारिमिननि गासै नायनाय',
    legalDisclaimer: 'आइन फोरमायथि: बे खौराङा सुबुंनि सुबिदानि थाखाय। सोरखारि गेजेट फोरमायथियासो जोबथा।',
    closeModal: 'उइनडो बन्द खालाम',
    viewReceipt: 'रसिद नाय',
    downloadReceipt: 'रसिद दाउनलड खालाम',
    sendSMSAlert: 'SMS हुसियार दैथायहर',
    sendEmailAlert: 'इमेल हुसियार दैथायहर',
    optOutOfAlerts: 'हुसियार बन्द खालाम',
    helpdeskSupport: '२४/७ सुबुं मदत',
    quickGuide: 'बाहायग्रा लिरबिलाइ',
    termsText: 'सहाय पर्टेलनि सर्तफोर बादियै।',
  };

  writeLocale('brx', 'बड़ो', t);
}

// ============================================================================
// 2. SANTALI (ᱥᱟᱱᱛᱟᱲᱤ - sat / Ol Chiki)
// ============================================================================
export function generateSantali() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: 'ᱥᱟᱦᱟᱭ (SAHAAY)',
    emblemLetter: 'ᱥ',
    tagline: 'ᱟᱢᱟᱜ ᱦᱟᱥᱟ᱾ ᱟᱢᱟᱜ ᱢᱟᱢᱞᱟ᱾ ᱟᱢᱟᱜ ᱦᱚᱠ᱾',
    heroSub: 'ᱦᱟᱥᱟ ᱨᱮᱡ ᱟᱨ ᱟᱹᱭᱤᱱ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱞᱟᱹᱜᱤᱫ ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱵᱟᱰᱟᱭ ᱯᱚᱨᱴᱟᱞ',
    portalSubtitle: 'ᱦᱟᱥᱟ • ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ • ᱵᱟᱥᱟ ᱨᱩᱣᱟᱹᱲ • ᱦᱟᱨᱠᱷᱮᱛ • ᱢᱟᱢᱞᱟ ᱯᱟᱸᱡᱟ',
    citizenPortal: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱯᱚᱨᱴᱟᱞ',
    officerPortal: 'ᱦᱟᱥᱟ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱯᱚᱨᱴᱟᱞ',
    demoMode: 'ᱰᱮᱢᱳ ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜᱼᱟ',
    signIn: 'ᱵᱚᱞᱚᱱ ᱢᱮ',
    signOut: 'ᱚᱰᱚᱠᱚᱜ ᱢᱮ',
    landowner: 'ᱦᱟᱥᱟ ᱢᱟᱹᱞᱤᱠ',
    landOfficer: 'ᱦᱟᱥᱟ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ (LAO)',
    switchRole: 'ᱠᱟᱹᱢᱤ ᱵᱚᱫᱚᱞ',
    switchCitizen: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ (ᱨᱟᱡᱮᱥ ᱥᱚᱨᱢᱟ)',
    switchOfficer: 'ᱦᱟᱥᱟ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ (ᱵᱤᱠᱨᱚᱢ ᱪᱚᱣᱦᱟᱱ)',
    welcomeBack: 'ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ',
    navHome: 'ᱢᱩᱬᱩᱛ ᱥᱟᱠᱟᱢ',
    navFindLand: 'ᱤᱧᱟᱜ ᱦᱟᱥᱟ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    navGisMap: 'GIS ᱦᱟᱥᱟ ᱱᱚᱠᱥᱟ',
    navDocIntel: 'ᱠᱟᱜᱚᱡᱽ ᱵᱤᱪᱟᱹᱨ (AI)',
    navCompensation: 'ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱟᱨ ᱵᱟᱥᱟ ᱨᱩᱣᱟᱹᱲ (R&R)',
    navDocuments: 'ᱠᱟᱜᱚᱡᱽ ᱵᱟᱠᱥᱟ',
    navActionCenter: 'ᱠᱟᱹᱢᱤᱦᱚᱨᱟ ᱛᱟᱞᱢᱟ',
    navGrievances: 'ᱦᱟᱨᱠᱷᱮᱛ ᱥᱚᱞᱦᱮ',
    navNotices: 'ᱵᱟᱰᱟᱭ ᱟᱨ ᱦᱩᱥᱤᱭᱟᱹᱨ',
    navOfficerDashboard: 'ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱰᱮᱥᱵᱳᱨᱰ',
    navCasesRegistry: 'ᱢᱟᱢᱞᱟ ᱨᱮᱡᱤᱥᱴᱟᱨ',
    navGrievancesQueue: 'ᱦᱟᱨᱠᱷᱮᱛ ᱫᱷᱟᱲᱤ',
    citizenServices: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱦᱟᱥᱟ ᱥᱮᱵᱟ',
    quickActions: 'ᱞᱚᱜᱚᱱ ᱠᱟᱹᱢᱤ',
    submit: 'ᱮᱢ ᱢᱮ',
    save: 'ᱥᱟᱸᱪᱟᱣ ᱢᱮ',
    cancel: 'ᱵᱟᱹᱛᱤᱞ ᱢᱮ',
    edit: 'ᱥᱩᱫᱷᱨᱟᱹᱣ ᱢᱮ',
    delete: 'ᱜᱮᱫ ᱜᱤᱰᱤ',
    search: 'ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    filter: 'ᱪᱷᱟᱹᱱᱤ ᱢᱮ',
    back: 'ᱛᱟᱭᱚᱢ',
    next: 'ᱞᱟᱦᱟ',
    close: 'ᱵᱚᱸᱫᱽ ᱢᱮ',
    view: 'ᱧᱮᱞ ᱢᱮ',
    download: 'ᱰᱟᱣᱩᱱᱞᱳᱰ',
    upload: 'ᱟᱯᱞᱳᱰ ᱢᱮ',
    export: 'ᱵᱟᱦᱨᱮ ᱠᱩᱞ',
    refresh: 'ᱱᱟᱣᱟ ᱢᱮ',
    print: 'ᱪᱷᱟᱯᱟ ᱢᱮ',
    loading: 'ᱞᱟᱹᱫᱩᱜ ᱠᱟᱱᱟ...',
    actions: 'ᱠᱟᱹᱢᱤᱠᱚ',
    details: 'ᱵᱤᱵᱚᱨᱚᱬ',
    status: 'ᱦᱟᱞᱚᱛ',
    viewDetails: 'ᱵᱤᱵᱚᱨᱚᱬ ᱧᱮᱞ ᱢᱮ',
    viewOnMap: 'ᱱᱚᱠᱥᱟ ᱨᱮ ᱧᱮᱞ ᱢᱮ',
    viewCase: 'ᱯᱩᱨᱟᱹ ᱢᱟᱢᱞᱟ ᱧᱮᱞ ᱢᱮ',
    trackProgress: 'ᱞᱟᱦᱟᱱᱛᱤ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    proceed: 'ᱞᱟᱦᱟᱜ ᱢᱮ',
    confirm: 'ᱴᱷᱟᱹᱣᱠᱟᱹᱭ ᱢᱮ',
    retry: 'ᱫᱚᱦᱲᱟ ᱪᱮᱥᱴᱟᱭ ᱢᱮ',
    clearAll: 'ᱡᱚᱛᱚ ᱯᱷᱟᱨᱪᱟᱭ ᱢᱮ',
    applyFilter: 'ᱪᱷᱟᱹᱱᱤ ᱞᱟᱜᱟᱣ ᱢᱮ',
    active: 'ᱪᱟᱹᱞᱩ',
    pending: 'ᱛᱟᱺᱜᱤ ᱨᱮ',
    completed: 'ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ',
    rejected: 'ᱵᱟᱹᱛᱤᱞ ᱮᱱᱟ',
    verified: 'ᱯᱚᱨᱚᱠ ᱮᱱᱟ',
    underReview: 'ᱵᱤᱪᱟᱹᱨ ᱨᱮ',
    urgent: 'ᱞᱟᱹᱠᱛᱤᱭᱟᱱ',
    optional: 'ᱤᱪᱷᱟᱹ ᱞᱮᱠᱟ',
    required: 'ᱡᱟᱹᱨᱩᱲ ᱜᱮᱭᱟ',
    discrepancy: 'ᱯᱷᱟᱨᱟᱠ ᱧᱟᱢ ᱮᱱᱟ',
    findMyLand: 'ᱤᱧᱟᱜ ᱦᱟᱥᱟ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    myLand: 'ᱤᱧᱟᱜ ᱦᱟᱥᱟ',
    surveyNo: 'ᱠᱷᱮᱥᱨᱟ / ᱫᱟᱜᱽ ᱮᱞ',
    enterSurveyNo: 'ᱡᱮᱞᱮᱠᱟ ᱑᱐᱔᱒ ᱵᱟᱝᱠᱷᱟᱱ ᱔᱕/A ᱚᱞ ᱢᱮ',
    village: 'ᱟᱹᱛᱩ',
    district: 'ᱡᱤᱞᱟᱹ',
    state: 'ᱯᱚᱱᱚᱛ',
    taluka: 'ᱵᱞᱚᱠ / ᱛᱚᱦᱥᱤᱞ',
    selectState: 'ᱯᱚᱱᱚᱛ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    selectDistrict: 'ᱡᱤᱞᱟᱹ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    selectVillage: 'ᱟᱹᱛᱩ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    recordedArea: 'ᱚᱞ ᱟᱠᱟᱱ ᱡᱟᱭᱜᱟ',
    acquiredArea: 'ᱦᱟᱛᱟᱣ ᱟᱠᱟᱱ ᱡᱟᱭᱜᱟ',
    remainingArea: 'ᱥᱟᱨᱮᱡ ᱡᱟᱭᱜᱟ',
    landClassification: 'ᱦᱟᱥᱟ ᱨᱮᱱᱟᱜ ᱞᱮᱠᱟᱱ',
    ownershipType: 'ᱢᱟᱹᱞᱤᱠᱟᱱᱟ ᱞᱮᱠᱟᱱ',
    marketValueRate: 'ᱵᱟᱡᱟᱨ ᱫᱚᱨ',
    hectares: 'ᱦᱮᱠᱴᱟᱨ',
    acres: 'ᱮᱠᱚᱲ / ᱵᱤᱜᱷᱟ',
    sqMeters: 'ᱵᱟᱹᱨᱜᱩ ᱢᱤᱴᱟᱨ',
    parcelStatus: 'ᱦᱟᱥᱟ ᱦᱟᱞᱚᱛ',
    searchLandPrompt: 'ᱱᱳᱴᱤᱥ ᱨᱮᱱᱟᱜ ᱠᱷᱮᱥᱨᱟ ᱮᱞ ᱮᱢ ᱠᱟᱛᱮ ᱦᱟᱞᱚᱛ ᱧᱮᱞ ᱢᱮ',
    searchLandBtn: 'ᱦᱟᱥᱟ ᱵᱤᱵᱚᱨᱚᱬ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    noLandFound: 'ᱱᱚᱶᱟ ᱵᱤᱵᱚᱨᱚᱬ ᱛᱮ ᱪᱮᱫ ᱦᱟᱥᱟ ᱨᱮᱠᱚᱨᱰ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ᱾',
    searchPlaceholder: 'ᱠᱷᱮᱥᱨᱟ ᱮᱞ, ᱟᱹᱛᱩ ᱵᱟᱝᱠᱷᱟᱱ ᱱᱳᱴᱤᱥ ID ᱛᱮ ᱯᱟᱸᱡᱟᱭ ᱢᱮ...',
    exactMatchFound: 'ᱥᱟᱹᱨᱤ ᱢᱮᱞ ᱧᱟᱢ ᱮᱱᱟ',
    gisMapTitle: 'GIS ᱯᱨᱚᱡᱮᱠᱴ ᱥᱤᱢᱟᱹ ᱟᱨ ᱱᱚᱠᱥᱟ',
    gisMapDesc: 'ᱦᱟᱥᱟ ᱦᱟᱛᱟᱣ ᱰᱟᱦᱟᱨ, ᱮᱥᱮᱫ ᱟᱠᱟᱱ ᱥᱤᱢᱟᱹ ᱟᱨ ᱟᱰᱮᱯᱟᱥᱮ ᱧᱮᱞ ᱢᱮ',
    satelliteView: 'ᱥᱮᱴᱮᱞᱟᱭᱤᱴ ᱧᱮᱞ',
    streetView: 'ᱰᱟᱦᱟᱨ ᱧᱮᱞ',
    topographyView: 'ᱚᱛᱦᱟᱥᱟ ᱧᱮᱞ',
    legend: 'ᱱᱚᱠᱥᱟ ᱪᱤᱱᱦᱟᱹ',
    acquiredZone: 'ᱦᱟᱛᱟᱣ ᱟᱠᱟᱱ ᱮᱞᱟᱠᱟ',
    bufferZone: 'ᱮᱥᱮᱫ ᱮᱞᱟᱠᱟ',
    yourParcel: 'ᱟᱢᱟᱜ ᱦᱟᱥᱟ ᱫᱟᱜᱽ',
    adjacentParcels: 'ᱟᱰᱮᱯᱟᱥᱮ ᱦᱟᱥᱟ',
    zoomIn: 'ᱢᱟᱨᱟᱝ ᱢᱮ',
    zoomOut: 'ᱦᱩᱰᱤᱧ ᱢᱮ',
    resetView: 'ᱱᱚᱠᱥᱟ ᱨᱩᱣᱟᱹᱲ ᱢᱮ',
    fullscreen: 'ᱯᱩᱨᱟᱹ ᱯᱚᱨᱫᱟ',
    parcelId: 'ᱫᱟᱜᱽ ID',
    coordinates: 'ᱚᱛᱱᱚᱜ ᱴᱩᱰᱟᱹᱜ',
    distanceToProject: 'ᱯᱨᱚᱡᱮᱠᱴ ᱠᱷᱚᱱ ᱥᱟᱺᱜᱤᱧ',
    measurementTool: 'ᱡᱚᱠᱷᱟ ᱦᱟᱹᱛᱭᱟᱹᱨ',
    mapLayers: 'ᱱᱚᱠᱥᱟ ᱛᱷᱟᱨ',
    overlayCadastral: 'ᱠᱷᱟᱡᱽᱱᱟ ᱱᱚᱠᱥᱟ ᱡᱚᱲᱟᱣ ᱢᱮ',
    totalCompensation: 'ᱢᱩᱴ ᱴᱷᱟᱹᱣᱠᱟᱹ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ',
    assessedValue: 'ᱢᱩᱬ ᱦᱟᱥᱟ ᱜᱚᱱᱚᱝ',
    solatium: '᱑᱐᱐% ᱥᱳᱞᱮᱥᱤᱭᱟᱢ (ᱨᱟᱹᱥᱠᱟᱹ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ)',
    solatiumDesc: 'RFCTLARR ᱟᱹᱭᱤᱱ ᱒᱐᱑᱓ ᱫᱷᱟᱨᱟ ᱓᱐(᱑) ᱞᱮᱠᱟᱛᱮ ᱑᱐᱐% ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ',
    interestAmount: 'ᱵᱟᱹᱲᱛᱤ ᱥᱩᱫᱽ ᱟᱨ ᱵᱷᱟᱛᱟ',
    structureValue: 'ᱫᱟᱨᱮ / ᱚᱲᱟᱜ / ᱫᱷᱚᱱ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ',
    calculatedTotal: 'ᱢᱩᱴ ᱮᱢᱚᱜ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱴᱟᱠᱟ',
    paymentStatus: 'PFMS ᱯᱩᱭᱥᱟᱹ ᱦᱟᱹᱴᱤᱧ ᱦᱟᱞᱚᱛ',
    dbtStatus: 'DBT ᱵᱮᱸᱠ ᱠᱷᱟᱛᱟ ᱡᱚᱲᱟᱣ ᱦᱟᱞᱚᱛ',
    disbursed: 'ᱠᱷᱟᱛᱟ ᱨᱮ ᱡᱚᱢᱟ ᱮᱱᱟ',
    disbursedAmount: 'ᱮᱢ ᱟᱠᱟᱱ ᱴᱟᱠᱟ',
    remainingAmount: 'ᱥᱟᱨᱮᱡ ᱴᱟᱠᱟ',
    bankAccount: 'ᱡᱚᱲᱟᱣ ᱟᱠᱟᱱ ᱵᱮᱸᱠ ᱠᱷᱟᱛᱟ',
    ifscCode: 'IFSC ᱠᱳᱰ',
    paymentRefNo: 'PFMS / ᱴᱨᱮᱡᱟᱨᱤ ᱞᱮᱱ-ᱫᱮᱱ ᱮᱞ',
    claimCompensation: 'ᱫᱟᱹᱵᱤ ᱥᱟᱠᱟᱢ ᱮᱢ ᱢᱮ',
    downloadAwardLetter: 'ᱟᱣᱟᱨᱰ ᱦᱩᱠᱩᱢ ᱰᱟᱣᱩᱱᱞᱳᱰ ᱢᱮ (ᱯᱷᱚᱨᱢ ᱑᱑)',
    rrTitle: 'ᱵᱟᱥᱟ ᱨᱩᱣᱟᱹᱲ (R&R) ᱞᱟᱵᱷᱠᱚ',
    rrEntitlement: 'R&R ᱦᱚᱠ ᱯᱮᱠᱮᱡᱽ',
    rrStatus: 'ᱵᱟᱥᱟ ᱨᱩᱣᱟᱹᱲ ᱠᱟᱹᱢᱤ ᱦᱟᱞᱚᱛ',
    resettlementHouse: 'ᱮᱴᱟᱜ ᱚᱲᱟᱜ / ᱦᱟᱥᱟ ᱦᱟᱹᱴᱤᱧ',
    subsistenceGrant: 'ᱡᱤᱣᱤ ᱠᱷᱟᱸᱰᱟᱣ ᱜᱚᱲᱚ (ᱪᱟᱸᱫᱚᱠᱤᱭᱟᱹ)',
    transportAllowance: 'ᱩᱪᱟᱹᱲ ᱟᱨ ᱥᱮᱱᱚᱜ ᱠᱷᱚᱨᱚᱪ',
    trainingSkill: 'ᱦᱩᱱᱟᱹᱨ ᱥᱮᱪᱮᱫ ᱟᱨ ᱠᱟᱹᱢᱤ ᱜᱚᱲᱚ',
    rrOfficerAssigned: 'ᱵᱟᱦᱟᱞ ᱟᱠᱟᱱ R&R ᱱᱳᱰᱟᱞ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ',
    rrTimeline: 'R&R ᱞᱟᱦᱟᱱᱛᱤ ᱚᱠᱛᱚ',
    docIntelTitle: 'AI ᱠᱟᱜᱚᱡᱽ ᱵᱤᱪᱟᱹᱨ ᱤᱧᱡᱤᱱ',
    docIntelSub: 'ᱥᱚᱨᱠᱟᱨᱤ ᱦᱟᱥᱟ ᱦᱟᱛᱟᱣ ᱱᱳᱴᱤᱥ ᱟᱨ ᱜᱮᱡᱮᱴ ᱦᱩᱠᱩᱢ ᱵᱤᱪᱟᱹᱨᱟᱭ',
    uploadNotice: 'ᱱᱳᱴᱤᱥ ᱵᱟᱝᱠᱷᱟᱱ ᱟᱣᱟᱨᱰ ᱠᱟᱜᱚᱡᱽ ᱟᱯᱞᱳᱰ ᱢᱮ',
    dragDropDoc: 'PDF, JPG ᱵᱟᱝᱠᱷᱟᱱ PNG ᱯᱷᱟᱭᱤᱞ ᱱᱚᱸᱰᱮ ᱜᱚᱦᱚᱲ ᱢᱮ',
    supportedFormats: 'ᱜᱟᱱᱚᱜ ᱯᱷᱚᱨᱢᱮᱴ: PDF, JPEG, PNG (ᱢᱩᱪᱟᱹᱫ: ᱒᱕MB)',
    analyzingDoc: 'AI ᱠᱟᱜᱚᱡᱽ ᱵᱤᱪᱟᱹᱨ ᱮᱫᱟᱭ...',
    extractedData: 'ᱠᱟᱜᱚᱡᱽ ᱠᱷᱚᱱ ᱧᱟᱢ ᱟᱠᱟᱱ ᱢᱩᱬ ᱠᱟᱛᱷᱟ',
    legalClause: 'ᱞᱟᱹᱜᱩ ᱟᱹᱭᱤᱱ ᱟᱨ ᱫᱷᱟᱨᱟ',
    section4_1: 'ᱫᱷᱟᱨᱟ ᱔(᱑) - ᱮᱛᱚᱦᱚᱵ ᱵᱟᱰᱟᱭ',
    section11_1: 'ᱫᱷᱟᱨᱟ ᱑᱑(᱑) - ᱮᱛᱚᱦᱚᱵ ᱥᱟᱨᱵᱷᱮ ᱵᱟᱰᱟᱭ',
    section19_1: 'ᱫᱷᱟᱨᱟ ᱑᱙(᱑) - ᱦᱟᱥᱟ ᱦᱟᱛᱟᱣ ᱞᱟᱹᱭ',
    section21_2: 'ᱫᱷᱟᱨᱟ ᱒᱑(᱒) - ᱦᱚᱲ ᱟᱸᱡᱚᱢ ᱱᱳᱴᱤᱥ',
    section23: 'ᱫᱷᱟᱨᱟ ᱒᱓ - ᱠᱟᱞᱮᱠᱴᱚᱨ ᱟᱜ ᱢᱩᱪᱟᱹᱫ ᱟᱣᱟᱨᱰ',
    potentialDiscrepancy: 'ᱢᱟᱨᱟᱝ ᱯᱷᱟᱨᱟᱠ / ᱮᱯᱮᱨ ᱧᱟᱢ ᱮᱱᱟ',
    discrepancyFound: 'ᱱᱳᱴᱤᱥ ᱟᱨ ᱠᱷᱟᱡᱽᱱᱟ ᱨᱮᱠᱚᱨᱰ ᱨᱮ ᱯᱷᱟᱨᱟᱠ ᱢᱮᱱᱟᱜᱼᱟ',
    discrepancyDesc: 'ᱱᱳᱴᱤᱥ ᱨᱮᱱᱟᱜ ᱡᱟᱭᱜᱟ ᱥᱚᱨᱠᱟᱨᱤ ᱨᱮᱠᱚᱨᱰ ᱠᱷᱚᱱ ᱠᱚᱢ ᱜᱮᱭᱟ᱾ ᱞᱚᱜᱚᱱ ᱮᱯᱮᱨ ᱮᱢ ᱢᱮ᱾',
    reportDiscrepancy: 'ᱮᱯᱮᱨ / ᱦᱟᱨᱠᱷᱮᱛ ᱮᱢ ᱢᱮ',
    aiConfidenceScore: 'AI ᱵᱤᱪᱟᱹᱨ ᱥᱟᱹᱨᱤ ᱫᱚᱨ',
    plainLanguageSummary: 'ᱟᱞᱜᱟ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱥᱟᱨᱟᱝᱥᱚ',
    actionDeadline: 'ᱠᱟᱹᱢᱤ ᱨᱮᱱᱟᱜ ᱢᱩᱪᱟᱹᱫ ᱢᱟᱦᱟᱸ',
    documentLocker: 'ᱰᱤᱡᱤᱴᱟᱞ ᱠᱟᱜᱚᱡᱽ ᱵᱟᱠᱥᱟ',
    allDocuments: 'ᱡᱚᱛᱚ ᱯᱚᱨᱚᱠ ᱟᱠᱟᱱ ᱠᱟᱜᱚᱡᱽ',
    verifiedDocuments: 'ᱥᱚᱨᱠᱟᱨᱤ ᱢᱟᱱᱟᱣ ᱠᱟᱜᱚᱡᱽ',
    pendingVerification: 'ᱯᱚᱨᱚᱠ ᱞᱟᱹᱜᱤᱫ ᱵᱟᱹᱠᱤ',
    uploadNewDoc: 'ᱱᱟᱣᱟ ᱠᱟᱜᱚᱡᱽ ᱟᱯᱞᱳᱰ ᱢᱮ',
    docType: 'ᱠᱟᱜᱚᱡᱽ ᱞᱮᱠᱟᱱ',
    selectDocType: 'ᱠᱟᱜᱚᱡᱽ ᱞᱮᱠᱟᱱ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    docLandTitle: 'ᱦᱟᱥᱟ ᱢᱟᱹᱞᱤᱠ ᱠᱟᱜᱚᱡᱽ (ᱯᱟᱴᱴᱟ / ᱠᱷᱚᱛᱤᱭᱟᱱ)',
    docGovNotice: 'ᱥᱚᱨᱠᱟᱨᱤ ᱦᱟᱥᱟ ᱦᱟᱛᱟᱣ ᱱᱳᱴᱤᱥ',
    docIdentityProof: 'ᱩᱯᱨᱩᱢ ᱥᱟᱠᱟᱢ (ᱟᱫᱷᱟᱨ / ᱯᱮᱱ ᱠᱟᱨᱰ)',
    docBankPassbook: 'ᱵᱮᱸᱠ ᱯᱟᱥᱵᱩᱠ / ᱠᱮᱱᱥᱤᱞ ᱪᱮᱠ',
    docGrievanceProof: 'ᱦᱟᱨᱠᱷᱮᱛ ᱥᱟᱹᱵᱩᱛ ᱠᱟᱜᱚᱡᱽ',
    fileSize: 'ᱯᱷᱟᱭᱤᱞ ᱥᱟᱭᱤᱡᱽ',
    uploadDate: 'ᱟᱯᱞᱳᱰ ᱢᱟᱦᱟᱸ',
    viewDoc: 'ᱠᱟᱜᱚᱡᱽ ᱧᱮᱞ ᱢᱮ',
    downloadDoc: 'ᱠᱟᱜᱚᱡᱽ ᱰᱟᱣᱩᱱᱞᱳᱰ ᱢᱮ',
    deleteDoc: 'ᱠᱟᱜᱚᱡᱽ ᱜᱮᱫ ᱜᱤᱰᱤ',
    confirmDeleteDoc: 'ᱪᱮᱫ ᱟᱢ ᱥᱟᱹᱨᱤ ᱜᱮ ᱱᱚᱶᱟ ᱠᱟᱜᱚᱡᱽ ᱜᱮᱫ ᱜᱤᱰᱤ ᱥᱟᱱᱟᱭᱮᱫ ᱢᱮᱭᱟ?',
    grievancesTitle: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱦᱟᱨᱠᱷᱮᱛ ᱟᱨ ᱥᱚᱞᱦᱮ ᱵᱮᱵᱚᱥᱛᱟ',
    submitGrievance: 'ᱱᱟᱣᱟ ᱦᱟᱨᱠᱷᱮᱛ ᱮᱢ ᱢᱮ',
    grievanceType: 'ᱦᱟᱨᱠᱷᱮᱛ ᱞᱮᱠᱟᱱ',
    selectGrievanceType: 'ᱦᱟᱨᱠᱷᱮᱛ ᱛᱷᱚᱠ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    typeCompensationAmount: 'ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱦᱤᱥᱟᱹᱵᱽ ᱨᱮ ᱵᱟᱝ ᱠᱩᱥᱤ',
    typeAreaDiscrepancy: 'ᱡᱟᱭᱜᱟ ᱡᱚᱠᱷᱟ ᱨᱮ ᱯᱷᱟᱨᱟᱠ',
    typeOwnershipDispute: 'ᱢᱟᱹᱞᱤᱠᱟᱱᱟ ᱮᱯᱮᱨ ᱵᱟᱝᱠᱷᱟᱱ ᱧᱩᱛᱩᱢ ᱥᱩᱫᱷᱨᱟᱹᱣ',
    typePaymentDelay: 'ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱯᱩᱭᱥᱟᱹ ᱧᱟᱢ ᱨᱮ ᱵᱤᱞᱚᱢ',
    typeRRNonReceipt: 'ᱵᱟᱥᱟ ᱨᱩᱣᱟᱹᱲ ᱞᱟᱵᱷ ᱵᱟᱝ ᱧᱟᱢ',
    typeOther: 'ᱮᱴᱟᱜ ᱥᱟᱥᱚᱱᱤᱭᱟᱹ ᱮᱴᱠᱮᱴᱚᱬᱮ',
    grievanceSubject: 'ᱦᱟᱨᱠᱷᱮᱛ ᱵᱤᱥᱚᱭ',
    grievanceDesc: 'ᱦᱟᱨᱠᱷᱮᱛ ᱨᱮᱱᱟᱜ ᱯᱩᱨᱟᱹ ᱵᱤᱵᱚᱨᱚᱬ',
    grievanceDescPlaceholder: 'ᱟᱢᱟᱜ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱵᱤᱵᱚᱨᱚᱬ ᱛᱮ ᱚᱞ ᱢᱮ...',
    attachEvidence: 'ᱥᱟᱹᱵᱩᱛ ᱠᱟᱜᱚᱡᱽ ᱡᱚᱲᱟᱣ ᱢᱮ',
    grievanceStatus: 'ᱦᱟᱨᱠᱷᱮᱛ ᱥᱚᱞᱦᱮ ᱦᱟᱞᱚᱛ',
    ticketNumber: 'ᱴᱳᱠᱚᱱ ᱮᱞ',
    assignedToOfficer: 'ᱵᱟᱦᱟᱞ ᱟᱠᱟᱱ ᱥᱚᱞᱦᱮ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ',
    expectedResolutionDate: 'ᱥᱚᱞᱦᱮ ᱦᱩᱭᱩᱜ ᱢᱟᱦᱟᱸ',
    hearingDate: 'ᱥᱟᱢᱟᱝ ᱟᱸᱡᱚᱢ ᱢᱟᱦᱟᱸ',
    officerRemarks: 'ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱟᱜ ᱥᱚᱨᱠᱟᱨᱤ ᱢᱚᱛ',
    resolutionSummary: 'ᱢᱩᱪᱟᱹᱫ ᱥᱚᱞᱦᱮ ᱥᱟᱨᱟᱝᱥᱚ',
    actionCenterTitle: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ ᱛᱟᱞᱢᱟ ᱟᱨ ᱟᱹᱭᱤᱱ ᱚᱠᱛᱚ',
    pendingActions: 'ᱟᱢᱟᱜ ᱯᱟᱦᱴᱟ ᱠᱷᱚᱱ ᱵᱟᱹᱠᱤ ᱠᱟᱹᱢᱤ',
    completedActions: 'ᱯᱩᱨᱟᱹᱣ ᱟᱠᱟᱱ ᱠᱟᱹᱢᱤ',
    urgentDeadlines: 'ᱟᱹᱭᱤᱱ ᱚᱠᱛᱚ ᱦᱩᱥᱤᱭᱟᱹᱨ',
    actObjectionPeriod: 'ᱫᱷᱟᱨᱟ ᱑᱕(᱑) ᱞᱮᱠᱟᱛᱮ ᱮᱯᱮᱨ ᱮᱢ ᱨᱮᱱᱟᱜ ᱖᱐ ᱢᱟᱦᱟᱸ ᱚᱠᱛᱚ',
    actSubmitBankDocs: 'ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱞᱟᱹᱜᱤᱫ ᱵᱮᱸᱠ ᱵᱤᱵᱚᱨᱚᱬ ᱮᱢ ᱢᱮ',
    actAttendHearing: 'ᱠᱟᱞᱮᱠᱴᱚᱨ ᱟᱜ ᱦᱚᱲ ᱟᱸᱡᱚᱢ ᱨᱮ ᱥᱮᱞᱮᱫᱚᱜ ᱢᱮ',
    markCompleted: 'ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ ᱪᱤᱱᱦᱟᱹᱭ ᱢᱮ',
    daysRemaining: 'ᱢᱟᱦᱟᱸ ᱥᱟᱨᱮᱡ ᱢᱮᱱᱟᱜᱼᱟ',
    expiredDeadline: 'ᱚᱠᱛᱚ ᱯᱟᱨᱚᱢ ᱮᱱᱟ',
    notificationTitle: 'ᱵᱟᱰᱟᱭ ᱟᱨ ᱥᱚᱨᱠᱟᱨᱤ ᱞᱟᱹᱭ',
    allNotifications: 'ᱡᱚᱛᱚ ᱵᱟᱰᱟᱭ',
    unreadOnly: 'ᱵᱟᱝ ᱯᱟᱲᱦᱟᱣ ᱟᱠᱟᱱ',
    markAllRead: 'ᱡᱚᱛᱚ ᱯᱟᱲᱦᱟᱣ ᱮᱱᱟ ᱪᱤᱱᱦᱟᱹᱭ ᱢᱮ',
    noNotifications: 'ᱱᱤᱛᱚᱜ ᱪᱮᱫ ᱱᱟᱣᱟ ᱵᱟᱰᱟᱭ ᱵᱟᱹᱱᱩᱜᱼᱟ᱾',
    officerTitle: 'ᱦᱟᱥᱟ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ (LAO) ᱥᱟᱥᱚᱱ ᱛᱟᱞᱢᱟ',
    officerCasesRegistry: 'ᱯᱨᱚᱡᱮᱠᱴ ᱢᱟᱢᱞᱟ ᱨᱮᱡᱤᱥᱴᱟᱨ',
    totalAcquisitions: 'ᱢᱩᱴ ᱦᱟᱥᱟ ᱦᱟᱛᱟᱣ ᱯᱨᱚᱡᱮᱠᱴ',
    activeParcels: 'ᱪᱟᱹᱞᱩ ᱦᱟᱥᱟ ᱫᱟᱜᱽ',
    totalDisbursedBudget: 'ᱢᱩᱴ ᱮᱢ ᱟᱠᱟᱱ ᱵᱟᱡᱮᱴ',
    pendingApprovals: 'ᱢᱟᱱᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱵᱟᱹᱠᱤ ᱯᱷᱟᱭᱤᱞ',
    caseId: 'ᱢᱟᱢᱞᱟ ID',
    caseName: 'ᱯᱨᱚᱡᱮᱠᱴ ᱧᱩᱛᱩᱢ',
    affectedLandowners: 'ᱮᱥᱮᱫ ᱟᱠᱟᱱ ᱦᱟᱥᱟ ᱢᱟᱹᱞᱤᱠᱠᱚ',
    stage: 'ᱱᱤᱛᱚᱜᱟᱜ ᱟᱹᱭᱤᱱ ᱛᱷᱚᱠ',
    stage1_Survey: 'ᱛᱷᱚᱠ ᱑: ᱥᱟᱶᱛᱟ ᱮᱥᱮᱫ ᱟᱨ ᱥᱟᱨᱵᱷᱮ',
    stage2_Notification: 'ᱛᱷᱚᱠ ᱒: ᱫᱷᱟᱨᱟ ᱑᱑(᱑) ᱮᱛᱚᱦᱚᱵ ᱵᱟᱰᱟᱭ',
    stage3_Objections: 'ᱛᱷᱚᱠ ᱓: ᱫᱷᱟᱨᱟ ᱑᱕ ᱟᱸᱡᱚᱢ ᱟᱨ ᱮᱯᱮᱨ',
    stage4_Declaration: 'ᱛᱷᱚᱠ ᱔: ᱫᱷᱟᱨᱟ ᱑᱙ ᱦᱟᱥᱟ ᱦᱟᱛᱟᱣ ᱞᱟᱹᱭ',
    stage5_Award: 'ᱛᱷᱚᱠ ᱕: ᱫᱷᱟᱨᱟ ᱒᱓ ᱟᱣᱟᱨᱰ ᱟᱨ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱴᱷᱟᱹᱣᱠᱟᱹ',
    stage6_Payment: 'ᱛᱷᱚᱠ ᱖: PFMS ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱦᱟᱹᱴᱤᱧ',
    stage7_Possession: 'ᱛᱷᱚᱠ ᱗: ᱦᱟᱥᱟ ᱥᱟᱵ ᱟᱨ R&R ᱠᱟᱹᱢᱤ',
    approve: 'ᱢᱟᱱᱟᱣ ᱢᱮ',
    reject: 'ᱵᱟᱹᱛᱤᱞ ᱢᱮ',
    forwardToUpper: 'ᱢᱟᱨᱟᱝ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱴᱷᱮᱱ ᱠᱩᱞ ᱢᱮ',
    scheduleHearing: 'ᱟᱸᱡᱚᱢ ᱢᱟᱦᱟᱸ ᱴᱷᱟᱹᱣᱠᱟᱹᱭ ᱢᱮ',
    issueNotice: 'ᱟᱹᱭᱤᱱ ᱱᱳᱴᱤᱥ ᱡᱟᱨᱤ ᱢᱮ',
    disburseFunds: 'ᱯᱩᱭᱥᱟᱹ ᱮᱢ ᱢᱮ',
    officerRemarksPlaceholder: 'ᱥᱚᱨᱠᱟᱨᱤ ᱵᱤᱪᱟᱹᱨ ᱚᱞ ᱢᱮ...',
    saveDecision: 'ᱯᱷᱟᱹᱭᱥᱟᱞᱟ ᱥᱟᱸᱪᱟᱣ ᱢᱮ',
    step: 'ᱛᱷᱚᱠ',
    of: 'ᱨᱮᱱᱟᱜ',
    surveyRequired: 'ᱠᱷᱮᱥᱨᱟ ᱮᱞ ᱞᱟᱹᱠᱛᱤᱭᱟ',
    enterValidSurvey: 'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱥᱟᱹᱨᱤ ᱠᱷᱮᱥᱨᱟ ᱮᱞ ᱚᱞ ᱢᱮ',
    villageRequired: 'ᱟᱹᱛᱩ ᱧᱩᱛᱩᱢ ᱞᱟᱹᱠᱛᱤᱭᱟ',
    districtRequired: 'ᱡᱤᱞᱟᱹ ᱧᱩᱛᱩᱢ ᱞᱟᱹᱠᱛᱤᱭᱟ',
    compensationBreakdown: 'ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱨᱮᱱᱟᱜ ᱯᱩᱨᱟᱹ ᱞᱮᱠᱷᱟ',
    marketValueCalculated: 'ᱴᱷᱟᱹᱣᱠᱟᱹ ᱟᱠᱟᱱ ᱢᱩᱬ ᱦᱟᱥᱟ ᱜᱚᱱᱚᱝ',
    multiplicationFactor: 'ᱟᱹᱛᱩ ᱜᱩᱱᱟᱹᱱ (RFCTLARR ᱛᱟᱹᱞᱠᱟᱹ ᱑)',
    additionalAssetValuation: 'ᱫᱟᱨᱮ, ᱠᱩᱧ ᱟᱨ ᱚᱲᱟᱜ ᱜᱚᱱᱚᱝ',
    statutoryInterest: 'ᱫᱷᱟᱨᱟ ᱓᱐(᱓) ᱞᱮᱠᱟᱛᱮ ᱑᱒% ᱥᱮᱨᱢᱟᱠᱤᱭᱟᱹ ᱥᱩᱫᱽ',
    netEntitlement: 'ᱢᱩᱴ ᱮᱢᱚᱜ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱴᱟᱠᱟ',
    readyForPFMS: 'PFMS ᱛᱮ ᱮᱢ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱯᱲᱟᱣ ᱮᱱᱟ',
    disbursementHistory: 'ᱢᱟᱲᱟᱝ ᱮᱢ ᱟᱠᱟᱱ ᱞᱮᱱ-ᱫᱮᱱ ᱱᱟᱜᱟᱢ',
    noDisbursementsYet: 'ᱱᱤᱛᱚᱜ ᱫᱷᱟᱹᱵᱤᱡ ᱪᱮᱫ ᱯᱩᱭᱥᱟᱹ ᱵᱟᱝ ᱮᱢ ᱟᱠᱟᱱᱟ᱾',
    compensationDisputeHelp: 'ᱦᱤᱥᱟᱹᱵᱽ ᱨᱮ ᱮᱯᱮᱨ ᱛᱟᱦᱮᱸᱞᱮᱱᱠᱷᱟᱱ ᱞᱮᱱᱰ ᱚᱛᱷᱚᱨᱤᱴᱤ (LARR) ᱨᱮ ᱟᱯᱤᱞ ᱜᱟᱱᱚᱜᱼᱟ᱾',
    trackDisbursement: 'PFMS ᱯᱚᱨᱴᱟᱞ ᱨᱮ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    viewAllNotices: 'ᱡᱚᱛᱚ ᱜᱮᱡᱮᱴ ᱵᱟᱰᱟᱭ ᱧᱮᱞ ᱢᱮ',
    noActionsPending: 'ᱱᱤᱛᱚᱜ ᱟᱢᱟᱜ ᱪᱮᱫ ᱠᱟᱹᱢᱤ ᱵᱟᱹᱠᱤ ᱵᱟᱹᱱᱩᱜᱼᱟ᱾',
    officerQueueEmpty: 'ᱵᱟᱹᱠᱤ ᱢᱟᱢᱞᱟ ᱛᱟᱹᱞᱠᱟᱹ ᱠᱷᱟᱹᱞᱤ ᱜᱮᱭᱟ᱾',
    discrepancyResolution: 'ᱯᱷᱟᱨᱟᱠ ᱥᱚᱞᱦᱮ ᱠᱟᱹᱢᱤ',
    fileAppeal: 'ᱞᱮᱱᱰ ᱮᱠᱣᱤᱡᱤᱥᱚᱱ ᱚᱛᱷᱚᱨᱤᱴᱤ (LARRA) ᱨᱮ ᱟᱯᱤᱞ ᱮᱢ ᱢᱮ',
    disputeDeadlineWarning: 'ᱫᱤᱥᱟᱹᱭ ᱢᱮ: ᱟᱣᱟᱨᱰ ᱡᱟᱨᱤ ᱠᱷᱚᱱ ᱖᱐ ᱢᱟᱦᱟᱸ ᱵᱷᱤᱛᱨᱤ ᱨᱮ ᱟᱯᱤᱞ ᱮᱢ ᱦᱩᱭᱩᱜᱼᱟ᱾',
    noticeDetails: 'ᱱᱳᱴᱤᱥ ᱨᱮᱱᱟᱜ ᱯᱩᱨᱟᱹ ᱵᱤᱵᱚᱨᱚᱬ',
    gazetteDate: 'ᱜᱮᱡᱮᱴ ᱪᱷᱟᱯᱟ ᱢᱟᱦᱟᱸ',
    competentAuthority: 'ᱫᱟᱲᱮ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ (CALA / SDO)',
    projectAlignmentMap: 'ᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ ᱨᱟᱡᱽᱰᱟᱦᱟᱨ / ᱨᱮᱞ ᱰᱟᱦᱟᱨ ᱱᱚᱠᱥᱟ',
    surveyBoundaries: 'ᱠᱷᱟᱡᱽᱱᱟ ᱥᱟᱨᱵᱷᱮ ᱥᱤᱢᱟᱹ',
    parcelAreaMismatch: 'ᱡᱟᱭᱜᱟ ᱨᱮ ᱯᱷᱟᱨᱟᱠ ᱢᱮᱱᱟᱜᱼᱟ',
    expectedArea: 'ᱠᱷᱟᱡᱽᱱᱟ ᱨᱮᱠᱚᱨᱰ ᱡᱟᱭᱜᱟ',
    noticeArea: 'ᱱᱳᱴᱤᱥ ᱨᱮ ᱚᱞ ᱟᱠᱟᱱ ᱡᱟᱭᱜᱟ',
    difference: 'ᱯᱷᱟᱨᱟᱠ',
    takeImmediateAction: 'ᱞᱚᱜᱚᱱ ᱠᱟᱹᱢᱤ ᱢᱮ',
    appealPeriodActive: 'ᱟᱯᱤᱞ ᱚᱠᱛᱚ ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜᱼᱟ',
    appealDaysLeft: 'ᱟᱯᱤᱞ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱨᱮᱡ ᱢᱟᱦᱟᱸ',
    submitClaimDocuments: 'ᱫᱟᱹᱵᱤ ᱠᱟᱜᱚᱡᱽ ᱞᱚᱜᱚᱱ ᱮᱢ ᱢᱮ',
    uploadSuccess: 'ᱠᱟᱜᱚᱡᱽ ᱱᱟᱯᱟᱭ ᱛᱮ ᱟᱯᱞᱳᱰ ᱮᱱᱟ!',
    uploadFailure: 'ᱟᱯᱞᱳᱰ ᱵᱟᱝ ᱦᱩᱭ ᱞᱮᱱᱟ᱾ ᱫᱚᱦᱲᱟ ᱪᱮᱥᱴᱟᱭ ᱢᱮ᱾',
    deleteConfirmTitle: 'ᱠᱟᱜᱚᱡᱽ ᱜᱮᱫ ᱜᱤᱰᱤᱭᱟ?',
    deleteConfirmDesc: 'ᱱᱚᱶᱟ ᱠᱟᱜᱚᱡᱽ ᱜᱮᱫ ᱜᱤᱰᱤ ᱞᱮᱠᱷᱟᱱ ᱫᱚᱦᱲᱟ ᱵᱟᱝ ᱧᱟᱢᱚᱜᱼᱟ᱾',
    grievanceSubmittedSuccess: 'ᱟᱢᱟᱜ ᱦᱟᱨᱠᱷᱮᱛ ᱫᱟᱹᱨᱡᱽ ᱮᱱᱟ!',
    grievanceTrackingTip: 'ᱦᱟᱞᱚᱛ ᱵᱟᱰᱟᱭ ᱞᱟᱹᱜᱤᱫ ᱴᱳᱠᱚᱱ ᱮᱞ ᱥᱟᱸᱪᱟᱣ ᱢᱮ᱾',
    hearingScheduledAlert: 'ᱥᱟᱢᱟᱝ ᱟᱸᱡᱚᱢ ᱢᱟᱦᱟᱸ ᱴᱷᱟᱹᱣᱠᱟᱹ ᱮᱱᱟ᱾',
    attendHearingNotice: 'ᱠᱟᱜᱚᱡᱽ ᱥᱟᱶ ᱚᱠᱛᱚ ᱨᱮ ᱥᱮᱴᱮᱨᱚᱜ ᱢᱮ᱾',
    contactHelpdesk: 'ᱜᱚᱲᱚ ᱛᱟᱞᱢᱟ ᱨᱮ ᱥᱟᱹᱜᱟᱹᱭ ᱢᱮ',
    tollFreeNumber: 'ᱴᱳᱞ ᱯᱷᱨᱤ ᱮᱞ: ᱑᱘᱐᱐-᱑᱑᱑-᱙᱙᱙᱙',
    helpdeskTiming: 'ᱥᱚᱢᱵᱟᱨ ᱠᱷᱚᱱ ᱥᱩᱱᱤᱵᱟᱨ, ᱥᱮᱛᱟᱜ ᱙ ᱠᱷᱚᱱ ᱟᱹᱭᱩᱵ ᱖ ᱫᱷᱟᱹᱵᱤᱡ',
    faqTitle: 'ᱡᱟᱣᱜᱮ ᱠᱩᱠᱞᱤ (FAQ)',
    privacyPolicy: 'ᱩᱠᱩ ᱱᱤᱛᱤ',
    termsOfService: 'ᱱᱤᱭᱚᱢ ᱟᱨ ᱥᱚᱨᱛᱚᱠᱚ',
    accessibilityStatement: 'ᱥᱮᱴᱮᱨᱚᱜ ᱵᱟᱰᱟᱭ',
    govtOfIndia: 'ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨ',
    ministryOfRuralDev: 'ᱟᱹᱛᱩ ᱩᱛᱷᱱᱟᱹᱣ ᱟᱨ ᱦᱟᱥᱟ ᱫᱷᱚᱱ ᱢᱚᱱᱛᱨᱟᱲᱚᱭ',
    allRightsReserved: 'ᱡᱚᱛᱚ ᱦᱚᱠ ᱨᱟᱠᱷᱟ ᱢᱮᱱᱟᱜᱼᱟ᱾',
    disclaimer: 'ᱱᱚᱶᱟ ᱯᱚᱨᱴᱟᱞ ᱫᱚ ᱯᱷᱟᱨᱪᱟ ᱠᱟᱹᱢᱤ ᱞᱟᱹᱜᱤᱫ᱾ ᱥᱚᱨᱠᱟᱨᱤ ᱜᱮᱡᱮᱴ ᱜᱮ ᱢᱩᱪᱟᱹᱫ ᱢᱟᱱᱟᱣᱜᱼᱟ᱾',
    heroTitle: 'ᱟᱢᱟᱜ ᱦᱟᱥᱟ ᱵᱟᱵᱚᱛ ᱯᱷᱟᱨᱪᱟ ᱵᱟᱰᱟᱭ ᱢᱮ᱾',
    heroDesc: 'ᱦᱟᱥᱟ ᱦᱟᱛᱟᱣ ᱠᱟᱹᱢᱤ ᱯᱟᱸᱡᱟᱭ ᱢᱮ, ᱑᱐᱐% ᱥᱳᱞᱮᱥᱤᱭᱟᱢ ᱥᱟᱶ ᱥᱟᱹᱨᱤ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱧᱟᱢ ᱢᱮ ᱟᱨ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱞᱚᱜᱚᱱ ᱥᱚᱞᱦᱮᱭ ᱢᱮ᱾',
    findLandBtn: 'ᱤᱧᱟᱜ ᱦᱟᱥᱟ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    trackCaseBtn: 'ᱢᱟᱢᱞᱟ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    understandDocBtn: 'ᱠᱟᱜᱚᱡᱽ ᱵᱤᱪᱟᱹᱨ ᱢᱮ',
    exploreMapBtn: 'ᱱᱚᱠᱥᱟ ᱧᱮᱞ ᱢᱮ',
    tickerAdvisory: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱵᱟᱰᱟᱭ: ᱱᱳᱴᱤᱥ ᱧᱟᱢ ᱠᱷᱚᱱ ᱖᱐ ᱢᱟᱦᱟᱸ ᱵᱷᱤᱛᱨᱤ ᱨᱮ ᱫᱷᱟᱨᱟ ᱑᱕(᱑) ᱞᱮᱠᱟᱛᱮ ᱮᱯᱮᱨ ᱮᱢ ᱜᱟᱱᱚᱜᱼᱟ᱾',
    noticeLabel: 'ᱱᱟᱣᱟ ᱱᱳᱴᱤᱥ:',
    feature1Title: 'ᱥᱟᱹᱨᱤ ᱦᱟᱥᱟ ᱯᱟᱸᱡᱟ',
    feature1Desc: 'ᱠᱷᱮᱥᱨᱟ ᱮᱞ ᱛᱮ ᱦᱟᱥᱟ ᱡᱟᱭᱜᱟ, ᱥᱤᱢᱟᱹ ᱟᱨ ᱦᱟᱞᱚᱛ ᱞᱚᱜᱚᱱ ᱵᱟᱰᱟᱭ ᱢᱮ᱾',
    feature2Title: 'ᱥᱢᱟᱨᱴ ᱠᱟᱜᱚᱡᱽ ᱵᱤᱪᱟᱹᱨ',
    feature2Desc: 'ᱱᱳᱴᱤᱥ ᱨᱮᱱᱟᱜ ᱟᱹᱭᱤᱱ ᱠᱟᱛᱷᱟ, ᱯᱷᱟᱨᱟᱠ ᱟᱨ ᱢᱩᱬ ᱢᱟᱦᱟᱸ AI ᱛᱮ ᱟᱞᱜᱟ ᱛᱮ ᱵᱩᱡᱷᱟᱹᱣ ᱢᱮ᱾',
    feature3Title: '᱑᱐᱐% ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱯᱷᱟᱨᱪᱟ',
    feature3Desc: 'RFCTLARR ᱟᱹᱭᱤᱱ ᱞᱮᱠᱟᱛᱮ ᱯᱩᱨᱟᱹ ᱥᱳᱞᱮᱥᱤᱭᱟᱢ, ᱥᱩᱫᱽ ᱟᱨ DBT ᱦᱟᱹᱴᱤᱧ ᱧᱮᱞ ᱢᱮ᱾',
    feature4Title: 'ᱟᱞᱜᱟ ᱥᱚᱞᱦᱮ',
    feature4Desc: 'ᱡᱟᱭᱜᱟ ᱵᱟᱝᱠᱷᱟᱱ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ ᱨᱮ ᱯᱷᱟᱨᱟᱠ ᱛᱟᱦᱮᱸᱞᱮᱱᱠᱷᱟᱱ ᱥᱚᱡᱷᱮ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱴᱷᱮᱱ ᱦᱟᱨᱠᱷᱮᱛ ᱮᱢ ᱢᱮ᱾',
    compensation: 'ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ',
    rr: 'ᱵᱟᱥᱟ ᱨᱩᱣᱟᱹᱲ (R&R)',
    documents: 'ᱠᱟᱜᱚᱡᱽᱠᱚ',
    grievances: 'ᱦᱟᱨᱠᱷᱮᱛᱠᱚ',
    actionRequired: 'ᱠᱟᱹᱢᱤ ᱞᱟᱹᱠᱛᱤᱭᱟ',
    inProgress: 'ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜᱼᱟ',
    helpdesk: 'ᱜᱚᱲᱚ ᱛᱟᱞᱢᱟ',
    dashboard: 'ᱰᱮᱥᱵᱳᱨᱰ',
    home: 'ᱢᱩᱬᱩᱛ ᱥᱟᱠᱟᱢ',
    profile: 'ᱯᱨᱚᱯᱷᱟᱭᱤᱞ',
    settings: 'ᱥᱟᱡᱟᱣᱠᱚ',
    notifications: 'ᱵᱟᱰᱟᱭᱠᱚ',
    logout: 'ᱚᱰᱚᱠᱚᱜ ᱢᱮ',
    login: 'ᱵᱚᱞᱚᱱ ᱢᱮ',
    email: 'ᱤᱢᱮᱞ ᱴᱷᱟᱶ',
    password: 'ᱯᱟᱥᱣᱟᱨᱰ',
    forgotPassword: 'ᱯᱟᱥᱣᱟᱨᱰ ᱦᱤᱲᱤᱧ ᱮᱱᱟ?',
    register: 'ᱨᱮᱡᱤᱥᱴᱟᱨ ᱢᱮ',
    rememberMe: 'ᱤᱧ ᱫᱤᱥᱟᱹᱭᱤᱧ ᱢᱮ',
    citizenLogin: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱵᱚᱞᱚᱱ',
    officerLogin: 'ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱵᱚᱞᱚᱱ',
    demoCredentials: 'ᱰᱮᱢᱳ ᱵᱚᱞᱚᱱ ᱠᱟᱛᱷᱟ',
    enterEmail: 'ᱟᱢᱟᱜ ᱤᱢᱮᱞ ᱚᱞ ᱢᱮ',
    enterPassword: 'ᱟᱢᱟᱜ ᱯᱟᱥᱣᱟᱨᱰ ᱚᱞ ᱢᱮ',
    welcomeCitizen: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ',
    welcomeOfficer: 'ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ',
    quickStats: 'ᱠᱷᱟᱴᱚ ᱞᱮᱠᱷᱟ',
    totalCases: 'ᱢᱩᱴ ᱢᱟᱢᱞᱟ',
    resolvedCases: 'ᱥᱚᱞᱦᱮ ᱟᱠᱟᱱ ᱢᱟᱢᱞᱟ',
    pendingReviews: 'ᱵᱤᱪᱟᱹᱨ ᱞᱟᱹᱜᱤᱫ ᱵᱟᱹᱠᱤ',
    myParcels: 'ᱤᱧᱟᱜ ᱦᱟᱥᱟ ᱫᱟᱜᱽ',
    caseTimeline: 'ᱢᱟᱢᱞᱟ ᱚᱠᱛᱚ ᱛᱟᱹᱞᱠᱟᱹ',
    recentActivity: 'ᱱᱤᱛᱚᱜᱟᱜ ᱠᱟᱹᱢᱤᱠᱚ',
    downloadReport: 'ᱨᱤᱯᱳᱨᱴ ᱰᱟᱣᱩᱱᱞᱳᱰ ᱢᱮ',
    filterByStatus: 'ᱦᱟᱞᱚᱛ ᱞᱮᱠᱟᱛᱮ ᱪᱷᱟᱹᱱᱤ ᱢᱮ',
    allStatuses: 'ᱡᱚᱛᱚ ᱦᱟᱞᱚᱛ',
    sortBy: 'ᱥᱟᱡᱟᱣ ᱢᱮ',
    newestFirst: 'ᱱᱟᱣᱟ ᱯᱩᱭᱞᱩ',
    oldestFirst: 'ᱢᱟᱨᱮ ᱯᱩᱭᱞᱩ',
    name: 'ᱧᱩᱛᱩᱢ',
    phone: 'ᱯᱷᱳᱱ ᱮᱞ',
    address: 'ᱴᱷᱟᱶ',
    remarks: 'ᱢᱚᱛ',
    category: 'ᱛᱷᱚᱠ',
    date: 'ᱢᱟᱦᱟᱸ',
    time: 'ᱚᱠᱛᱚ',
    type: 'ᱞᱮᱠᱟᱱ',
    viewAll: 'ᱡᱚᱛᱚ ᱧᱮᱞ ᱢᱮ',
    clearFilters: 'ᱪᱷᱟᱹᱱᱤ ᱯᱷᱟᱨᱪᱟᱭ ᱢᱮ',
    resultsFound: 'ᱚᱨᱡᱚ ᱧᱟᱢ ᱮᱱᱟ',
    noResults: 'ᱪᱮᱫ ᱚᱨᱡᱚ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ',
    fileUploadSuccess: 'ᱯᱷᱟᱭᱤᱞ ᱱᱟᱯᱟᱭ ᱛᱮ ᱟᱯᱞᱳᱰ ᱮᱱᱟ',
    fileUploadError: 'ᱟᱯᱞᱳᱰ ᱨᱮ ᱵᱷᱩᱞ ᱮᱱᱟ',
    fileDeleted: 'ᱯᱷᱟᱭᱤᱞ ᱜᱮᱫ ᱜᱤᱰᱤ ᱮᱱᱟ',
    changesSaved: 'ᱵᱚᱫᱚᱞ ᱥᱟᱸᱪᱟᱣ ᱮᱱᱟ',
    actionSuccess: 'ᱠᱟᱹᱢᱤ ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ',
    actionFailed: 'ᱠᱟᱹᱢᱤ ᱵᱟᱝ ᱦᱩᱭ ᱞᱮᱱᱟ',
    sessionExpired: 'ᱚᱠᱛᱚ ᱪᱟᱵᱟ ᱮᱱᱟ, ᱫᱚᱦᱲᱟ ᱵᱚᱞᱚᱱ ᱢᱮ',
    unauthorized: 'ᱵᱟᱝ ᱦᱩᱠᱩᱢ ᱵᱚᱞᱚᱱ',
    serverError: 'ᱥᱟᱨᱵᱷᱟᱨ ᱵᱷᱩᱞ, ᱛᱟᱭᱚᱢ ᱛᱮ ᱪᱮᱥᱴᱟᱭ ᱢᱮ',
    networkError: 'ᱱᱮᱴᱣᱟᱨᱠ ᱵᱷᱩᱞ',
    tryAgain: 'ᱫᱚᱦᱲᱟ ᱪᱮᱥᱴᱟᱭ ᱢᱮ',
    goBack: 'ᱛᱟᱭᱚᱢ ᱥᱮᱱᱚᱜ ᱢᱮ',
    goToHome: 'ᱢᱩᱬᱩᱛ ᱥᱟᱠᱟᱢ ᱥᱮᱱᱚᱜ ᱢᱮ',
    viewMore: 'ᱵᱟᱹᱲᱛᱤ ᱧᱮᱞ ᱢᱮ',
    viewLess: 'ᱠᱚᱢ ᱧᱮᱞ ᱢᱮ',
    copied: 'ᱠᱚᱯᱤ ᱮᱱᱟ!',
    copyToClipboard: 'ᱠᱞᱤᱯᱵᱳᱨᱰ ᱨᱮ ᱠᱚᱯᱤ ᱢᱮ',
    yes: 'ᱦᱚᱭ',
    no: 'ᱵᱟᱝ',
    ok: 'ᱴᱷᱤᱠ ᱜᱮᱭᱟ',
    help: 'ᱜᱚᱲᱚ',
    feedback: 'ᱢᱚᱱᱮ ᱠᱟᱛᱷᱟ',
    contactUs: 'ᱥᱟᱹᱜᱟᱹᱭ ᱢᱮ',
    aboutUs: 'ᱟᱞᱮ ᱵᱟᱵᱚᱛ',
    version: 'ᱵᱷᱟᱨᱥᱚᱱ',
    systemStatus: 'ᱥᱤᱥᱴᱚᱢ ᱦᱟᱞᱚᱛ',
    online: 'ᱚᱱᱞᱟᱭᱤᱱ',
    offline: 'ᱚᱯᱷᱞᱟᱭᱤᱱ',
    connecting: 'ᱡᱚᱲᱟᱣᱜ ᱠᱟᱱᱟ...',
    syncing: 'ᱥᱤᱝᱠ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...',
    lastUpdated: 'ᱢᱩᱪᱟᱹᱫ ᱱᱟᱣᱟ',
    justNow: 'ᱱᱤᱛᱚᱜ ᱜᱮ',
    minutesAgo: 'ᱴᱤᱲᱤᱡ ᱢᱟᱲᱟᱝ',
    hoursAgo: 'ᱴᱟᱲᱟᱝ ᱢᱟᱲᱟᱝ',
    daysAgo: 'ᱢᱟᱦᱟᱸ ᱢᱟᱲᱟᱝ',
    readMore: 'ᱵᱟᱹᱲᱛᱤ ᱯᱟᱲᱦᱟᱣ ᱢᱮ',
    showMore: 'ᱵᱟᱹᱲᱛᱤ ᱩᱫᱩᱜ ᱢᱮ',
    showLess: 'ᱠᱚᱢ ᱩᱫᱩᱜ ᱢᱮ',
    selectAll: 'ᱡᱚᱛᱚ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    deselectAll: 'ᱡᱚᱛᱚ ᱵᱟᱹᱛᱤᱞ ᱢᱮ',
    expandAll: 'ᱡᱚᱛᱚ ᱯᱟᱥᱱᱟᱣ ᱢᱮ',
    collapseAll: 'ᱡᱚᱛᱚ ᱠᱷᱟᱴᱚᱭ ᱢᱮ',
    openInNewTab: 'ᱱᱟᱣᱟ ᱴᱮᱵᱽ ᱨᱮ ᱡᱷᱤᱡ ᱢᱮ',
    previous: 'ᱢᱟᱲᱟᱝ',
    pageOf: 'ᱥᱟᱠᱟᱢ',
    rowsPerPage: 'ᱫᱷᱟᱲᱤ ᱯᱤᱪᱷᱤ ᱥᱟᱠᱟᱢ',
    totalRecords: 'ᱢᱩᱴ ᱨᱮᱠᱚᱨᱰ',
    noRecordsFound: 'ᱪᱮᱫ ᱨᱮᱠᱚᱨᱰ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ',
    pleaseWait: 'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱛᱟᱺᱜᱤ ᱢᱮ...',
    somethingWentWrong: 'ᱪᱮᱫ ᱪᱚ ᱵᱷᱩᱞ ᱮᱱᱟ',
    fieldRequired: 'ᱱᱚᱶᱟ ᱴᱷᱟᱶ ᱞᱟᱹᱠᱛᱤᱭᱟ',
    invalidEmail: 'ᱥᱟᱹᱨᱤ ᱤᱢᱮᱞ ᱚᱞ ᱢᱮ',
    invalidPhone: 'ᱥᱟᱹᱨᱤ ᱑᱐ ᱮᱞ ᱨᱮᱱᱟᱜ ᱢᱳᱵᱟᱭᱤᱞ ᱮᱞ ᱚᱞ ᱢᱮ',
    passwordTooShort: 'ᱯᱟᱥᱣᱟᱨᱰ ᱠᱚᱢ ᱠᱷᱚᱱ ᱠᱚᱢ ᱘ ᱟᱠᱷᱚᱨ ᱦᱩᱭᱩᱜ ᱢᱟ',
    passwordsDoNotMatch: 'ᱯᱟᱥᱣᱟᱨᱰ ᱵᱟᱝ ᱢᱤᱞᱟᱹᱣᱜ ᱠᱟᱱᱟ',
    termsAgreement: 'ᱤᱧ ᱱᱤᱭᱚᱢ ᱟᱨ ᱥᱚᱨᱛᱚᱠᱚ ᱢᱟᱱᱟᱣ ᱮᱫᱟᱹᱧ',
    agreeToTerms: 'ᱞᱟᱦᱟᱜ ᱞᱟᱹᱜᱤᱫ ᱥᱚᱨᱛᱚ ᱢᱟᱱᱟᱣ ᱢᱮ',
    selectLanguage: 'ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    currentLanguage: 'ᱱᱤᱛᱚᱜᱟᱜ ᱯᱟᱹᱨᱥᱤ',
    languageChanged: 'ᱯᱟᱹᱨᱥᱤ ᱵᱚᱫᱚᱞ ᱮᱱᱟ',
    autoDetectLocation: 'ᱴᱷᱟᱶ ᱟᱡᱛᱮ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    locationAccessDenied: 'ᱴᱷᱟᱶ ᱦᱩᱠᱩᱢ ᱵᱟᱹᱛᱤᱞ ᱮᱱᱟ',
    useManualSearch: 'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱟᱢᱛᱮ ᱯᱟᱸᱡᱟᱭ ᱢᱮ',
    satelliteLayer: 'ᱥᱮᱴᱮᱞᱟᱭᱤᱴ ᱛᱷᱟᱨ',
    cadastralLayer: 'ᱠᱷᱟᱡᱽᱱᱟ ᱱᱚᱠᱥᱟ ᱛᱷᱟᱨ',
    projectBufferLayer: 'ᱯᱨᱚᱡᱮᱠᱴ ᱵᱟᱯᱷᱟᱨ ᱛᱷᱟᱨ',
    measuringDistance: 'ᱥᱟᱺᱜᱤᱧ ᱡᱚᱠᱷᱟᱜ ᱠᱟᱱᱟ',
    measuringArea: 'ᱡᱟᱭᱜᱟ ᱡᱚᱠᱷᱟᱜ ᱠᱟᱱᱟ',
    clickToMeasure: 'ᱡᱚᱠᱷᱟ ᱞᱟᱹᱜᱤᱫ ᱱᱚᱠᱥᱟ ᱨᱮ ᱚᱛᱟᱭ ᱢᱮ',
    clearMeasurement: 'ᱡᱚᱠᱷᱟ ᱯᱷᱟᱨᱪᱟᱭ ᱢᱮ',
    totalDistance: 'ᱢᱩᱴ ᱥᱟᱺᱜᱤᱧ',
    totalArea: 'ᱢᱩᱴ ᱡᱟᱭᱜᱟ',
    meters: 'ᱢᱤᱴᱟᱨ',
    kilometers: 'ᱠᱤᱞᱳᱢᱤᱴᱟᱨ',
    discrepancyDetails: 'ᱯᱷᱟᱨᱟᱠ ᱵᱤᱵᱚᱨᱚᱬ',
    affectedSections: 'ᱮᱥᱮᱫ ᱟᱠᱟᱱ ᱫᱷᱟᱨᱟᱠᱚ',
    recommendedAction: 'ᱥᱚᱞᱦᱮ ᱠᱟᱹᱢᱤ',
    fileGrievanceNow: 'ᱱᱤᱛᱚᱜ ᱜᱮ ᱦᱟᱨᱠᱷᱮᱛ ᱮᱢ ᱢᱮ',
    viewDiscrepancyReport: 'ᱯᱷᱟᱨᱟᱠ ᱨᱤᱯᱳᱨᱴ ᱧᱮᱞ ᱢᱮ',
    aiConfidence: 'AI ᱥᱟᱹᱨᱤ ᱛᱷᱚᱠ',
    highConfidence: 'ᱩᱥᱩᱞ ᱥᱟᱹᱨᱤ (᱙᱕%+)',
    mediumConfidence: 'ᱛᱟᱞᱟ ᱥᱟᱹᱨᱤ',
    lowConfidence: 'ᱠᱚᱢ ᱥᱟᱹᱨᱤ',
    extractedEntities: 'ᱧᱟᱢ ᱟᱠᱟᱱ ᱠᱟᱛᱷᱟᱠᱚ',
    officialGazetteNo: 'ᱥᱚᱨᱠᱟᱨᱤ ᱜᱮᱡᱮᱴ ᱮᱞ',
    notificationDate: 'ᱵᱟᱰᱟᱭ ᱢᱟᱦᱟᱸ',
    competentAuthorityName: 'ᱫᱟᱲᱮ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ',
    hearingVenue: 'ᱟᱸᱡᱚᱢ ᱴᱷᱟᱶ',
    objectionDeadlineDate: 'ᱮᱯᱮᱨ ᱮᱢ ᱨᱮᱱᱟᱜ ᱢᱩᱪᱟᱹᱫ ᱢᱟᱦᱟᱸ',
    documentVerifiedBadge: 'ᱥᱚᱨᱠᱟᱨᱤ ᱯᱚᱨᱚᱠ ᱮᱱᱟ',
    documentPendingBadge: 'ᱯᱚᱨᱚᱠ ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜᱼᱟ',
    documentRejectedBadge: 'ᱠᱟᱜᱚᱡᱽ ᱵᱟᱹᱛᱤᱞ ᱮᱱᱟ',
    reuploadDocument: 'ᱠᱟᱜᱚᱡᱽ ᱫᱚᱦᱲᱟ ᱟᱯᱞᱳᱰ ᱢᱮ',
    reasonForRejection: 'ᱵᱟᱹᱛᱤᱞ ᱨᱮᱱᱟᱜ ᱠᱟᱨᱚᱱ',
    downloadCertificate: 'ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱰᱟᱣᱩᱱᱞᱳᱰ ᱢᱮ',
    shareDocument: 'ᱠᱟᱜᱚᱡᱽ ᱦᱟᱹᱴᱤᱧ ᱢᱮ',
    printSummary: 'ᱥᱟᱨᱟᱝᱥᱚ ᱪᱷᱟᱯᱟ ᱢᱮ',
    directBenefitTransfer: 'ᱥᱚᱡᱷᱮ ᱞᱟᱵᱷ ᱩᱪᱟᱹᱲ (DBT)',
    pfmsTrackingStatus: 'PFMS ᱯᱩᱭᱥᱟᱹ ᱯᱟᱸᱡᱟ',
    bankAccountVerified: 'ᱵᱮᱸᱠ ᱠᱷᱟᱛᱟ ᱯᱚᱨᱚᱠ ᱮᱱᱟ',
    bankAccountPending: 'ᱵᱮᱸᱠ ᱠᱷᱟᱛᱟ ᱯᱚᱨᱚᱠ ᱵᱟᱹᱠᱤ',
    treasuryRefNumber: 'ᱴᱨᱮᱡᱟᱨᱤ ᱨᱮᱯᱷᱟᱨᱮᱱᱥ ᱮᱞ',
    disbursementDate: 'ᱯᱩᱭᱥᱟᱹ ᱮᱢ ᱢᱟᱦᱟᱸ',
    installmentNumber: 'ᱠᱤᱥᱛᱤ ᱮᱞ',
    partialPayment: 'ᱛᱟᱨᱟ ᱯᱩᱭᱥᱟᱹ',
    fullPayment: 'ᱯᱩᱨᱟᱹ ᱯᱩᱭᱥᱟᱹ',
    solatiumAmount: 'ᱥᱳᱞᱮᱥᱤᱭᱟᱢ ᱴᱟᱠᱟ (᱑᱐᱐%)',
    baseCompensation: 'ᱢᱩᱬ ᱦᱟᱥᱟ ᱠᱷᱚᱛᱤᱯᱩᱨᱚᱬ',
    statutoryInterestValue: 'ᱟᱹᱭᱤᱱ ᱥᱩᱫᱽ ᱴᱟᱠᱟ',
    totalAwardAmount: 'ᱢᱩᱴ ᱟᱣᱟᱨᱰ ᱴᱟᱠᱟ',
    displacedFamilyId: 'ᱚᱲᱟᱜ ᱵᱟᱹᱜᱤ ᱜᱷᱟᱨᱚᱸᱡᱽ ID',
    resettlementSiteName: 'ᱵᱟᱥᱟ ᱨᱩᱣᱟᱹᱲ ᱴᱚᱞᱟ ᱧᱩᱛᱩᱢ',
    plotAllotmentStatus: 'ᱦᱟᱥᱟ ᱦᱟᱹᱴᱤᱧ ᱦᱟᱞᱚᱛ',
    housingGrantStatus: 'ᱚᱲᱟᱜ ᱜᱚᱲᱚ ᱦᱟᱞᱚᱛ',
    annuityBenefitStatus: 'ᱪᱟᱸᱫᱚᱠᱤᱭᱟᱹ ᱯᱮᱱᱥᱚᱱ ᱦᱟᱞᱚᱛ',
    skillTrainingStatus: 'ᱦᱩᱱᱟᱹᱨ ᱥᱮᱪᱮᱫ ᱦᱟᱞᱚᱛ',
    livelihoodGrant: 'ᱡᱤᱣᱤ ᱠᱷᱟᱸᱰᱟᱣ ᱜᱚᱲᱚ',
    officerCaseManagement: 'ᱢᱟᱢᱞᱟ ᱥᱟᱥᱚᱱ ᱛᱟᱞᱢᱟ',
    citizenGrievanceQueue: 'ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱦᱟᱨᱠᱷᱮᱛ ᱫᱷᱟᱲᱤ',
    hearingManagement: 'ᱟᱸᱡᱚᱢ ᱥᱟᱥᱚᱱ',
    awardDrafting: 'ᱟᱣᱟᱨᱰ ᱰᱨᱟᱯᱷᱴ ᱟᱨ ᱢᱟᱱᱟᱣ',
    fundSanction: 'ᱯᱩᱭᱥᱟᱹ ᱢᱟᱱᱟᱣ ᱟᱨ ᱦᱟᱹᱴᱤᱧ',
    reportsAndAnalytics: 'ᱨᱤᱯᱳᱨᱴ ᱟᱨ ᱵᱤᱪᱟᱹᱨ',
    bulkNoticeGeneration: 'ᱢᱤᱫ ᱥᱟᱶᱛᱮ ᱱᱳᱴᱤᱥ ᱡᱟᱨᱤ',
    cadastralSync: 'ᱠᱷᱟᱡᱽᱱᱟ ᱱᱚᱠᱥᱟ ᱥᱤᱝᱠ',
    exportToExcel: 'Excel ᱛᱮ ᱰᱟᱣᱩᱱᱞᱳᱰ',
    exportToPdf: 'PDF ᱨᱤᱯᱳᱨᱴ ᱰᱟᱣᱩᱱᱞᱳᱰ',
    auditLog: 'ᱚᱰᱤᱴ ᱞᱚᱜᱽ',
    loginHistory: 'ᱵᱚᱞᱚᱱ ᱱᱟᱜᱟᱢ',
    officerBadge: 'ᱥᱚᱨᱠᱟᱨᱤ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱛᱷᱚᱠ',
    citizenBadge: 'ᱯᱚᱨᱚᱠ ᱟᱠᱟᱱ ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ',
    stepCompleted: 'ᱱᱚᱶᱟ ᱛᱷᱚᱠ ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ',
    stepInProgress: 'ᱱᱚᱶᱟ ᱛᱷᱚᱠ ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜᱼᱟ',
    stepPending: 'ᱱᱚᱶᱟ ᱛᱷᱚᱠ ᱵᱟᱹᱠᱤ ᱢᱮᱱᱟᱜᱼᱟ',
    timelineOverview: 'ᱦᱟᱥᱟ ᱦᱟᱛᱟᱣ ᱱᱟᱜᱟᱢ ᱨᱮᱱᱟᱜ ᱯᱩᱨᱟᱹ ᱧᱮᱞ',
    legalDisclaimer: 'ᱟᱹᱭᱤᱱ ᱵᱟᱰᱟᱭ: ᱱᱚᱶᱟ ᱠᱟᱛᱷᱟ ᱫᱚ ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱥᱩᱵᱤᱫᱷᱟ ᱞᱟᱹᱜᱤᱫ᱾ ᱥᱚᱨᱠᱟᱨᱤ ᱜᱮᱡᱮᱴ ᱜᱮ ᱢᱩᱪᱟᱹᱫ ᱢᱟᱱᱟᱣᱜᱼᱟ᱾',
    closeModal: 'ᱡᱷᱤᱡ ᱥᱟᱠᱟᱢ ᱵᱚᱸᱫᱽ ᱢᱮ',
    viewReceipt: 'ᱨᱚᱥᱤᱫᱽ ᱧᱮᱞ ᱢᱮ',
    downloadReceipt: 'ᱨᱚᱥᱤᱫᱽ ᱰᱟᱣᱩᱱᱞᱳᱰ ᱢᱮ',
    sendSMSAlert: 'SMS ᱦᱩᱥᱤᱭᱟᱹᱨ ᱠᱩᱞ ᱢᱮ',
    sendEmailAlert: 'ᱤᱢᱮᱞ ᱦᱩᱥᱤᱭᱟᱹᱨ ᱠᱩᱞ ᱢᱮ',
    optOutOfAlerts: 'ᱦᱩᱥᱤᱭᱟᱹᱨ ᱵᱚᱸᱫᱽ ᱢᱮ',
    helpdeskSupport: '᱒᱔/᱗ ᱱᱟᱜᱟᱹᱨᱤᱭᱟᱹ ᱜᱚᱲᱚ',
    quickGuide: 'ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ ᱫᱤᱥᱟᱹ',
    termsText: 'ᱥᱟᱦᱟᱭ ᱯᱚᱨᱴᱟᱞ ᱨᱮᱱᱟᱜ ᱥᱚᱨᱛᱚᱠᱚ ᱞᱮᱠᱟᱛᱮ᱾',
  };

  writeLocale('sat', 'ᱥᱟᱱᱛᱟᱲᱤ', t);
}

// ============================================================================
// 3. MANIPURI (মৈতৈলোন / Manipuri - mni)
// ============================================================================
export function generateManipuri() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: 'সহায় (SAHAAY)',
    emblemLetter: 'স',
    tagline: 'নহাক্কী লম। নহাক্কী কেস। নহাক্কী হক।',
    heroSub: 'লম লৌখৎপা অমসুং লোকেল কম্পেন্সেসনগীদমক প্রজা পাউ পৱার্টেল',
    portalSubtitle: 'লম • ক্ষতিপূরণ • পুনর্স্থাপন • ৱাকৎ • কেস ত্রেকিং',
    citizenPortal: 'প্রজা পৱার্টেল',
    officerPortal: 'লম লৌখৎপা ওফিসার পৱার্টেল',
    demoMode: 'দেমো মোদ চৎথরি',
    signIn: 'সাইন ইন তৌবীয়ু',
    signOut: 'সাইন আউত',
    landowner: 'লমগী মপু',
    landOfficer: 'লম লৌখৎপা ওফিসার (LAO)',
    switchRole: 'থৌদাং ওন্থোকপু',
    switchCitizen: 'প্রজা (রাজেশ শৰ্মা)',
    switchOfficer: 'লম লৌখৎপা ওফিসার (বিক্রম চৌহান)',
    welcomeBack: 'তরাম্না ওকচরি',
    navHome: 'য়ুমলৈ',
    navFindLand: 'ঐগী লম থিবীয়ু',
    navGisMap: 'GIS লমগী মেপ',
    navDocIntel: 'চে-চাং নৈনব (AI)',
    navCompensation: 'ক্ষতিপূরণ অমসুং পুনর্স্থাপন (R&R)',
    navDocuments: 'চে-চাং বাকস',
    navActionCenter: 'থবক পায়বা মফম',
    navGrievances: 'ৱাকৎ লাকশিনব',
    navNotices: 'নোতিস অমসুং চেকশিনৱা',
    navOfficerDashboard: 'ওফিসার দেসবোর্দ',
    navCasesRegistry: 'কেস রেজিস্ত্রী',
    navGrievancesQueue: 'ৱাকৎ পরেং',
    citizenServices: 'প্রজা লমগী সেবা',
    quickActions: 'য়াংনা তৌবা থবক',
    submit: 'শীন্নবীয়ু',
    save: 'কনবীয়ু',
    cancel: 'তোকপীয়ু',
    edit: 'শেমদোকপু',
    delete: 'মুত্থৎপু',
    search: 'থিবীয়ু',
    filter: 'খনবীয়ু',
    back: 'হন্দোকপু',
    next: 'মাংলোই',
    close: 'থিংজিনবীয়ু',
    view: 'য়েংবীয়ু',
    download: 'দাউনলোদ',
    upload: 'অপলোদ তৌবীয়ু',
    export: 'মপান্দা থাবীয়ু',
    refresh: 'অনৌবা তৌবীয়ু',
    print: 'নম্বীয়ু',
    loading: 'লোদ তৌরি...',
    actions: 'থবকশিং',
    details: 'অকুপ্পা মরোল',
    status: 'ফীভম',
    viewDetails: 'অকুপ্পা মরোল য়েংবীয়ু',
    viewOnMap: 'মেপ্তা য়েংবীয়ু',
    viewCase: 'কেস পুম্নমক য়েংবীয়ু',
    trackProgress: 'চাউখৎলকপবু য়েংশিনবীয়ু',
    proceed: 'মাংদা চংশিল্লু',
    confirm: 'চেৎশিনহনবীয়ু',
    retry: 'অমুক হন্না হোৎনবীয়ু',
    clearAll: 'পুম্নমক শেংদোকপু',
    applyFilter: 'ফিল্তর চৎনহনবীয়ু',
    active: 'চৎনরিবা',
    pending: 'ঙাইরিবা / ৱারোইশিন পুদ্রিবা',
    completed: 'লোইশিনখ্রে',
    rejected: 'য়াদ্রে',
    verified: 'চেক তৌরে',
    underReview: 'নৈনরি',
    urgent: 'য়াম্না মরুওইবা',
    optional: 'পাম্বদা',
    required: 'মথৌ তাবা',
    discrepancy: 'খেৎনব উরে',
    findMyLand: 'ঐগী লম থিবীয়ু',
    myLand: 'ঐগী লম',
    surveyNo: 'দাগ / খসরা নম্বর',
    enterSurveyNo: 'খুদম ওইনা ১০৪২ নত্রগা ৪৫/A ইবীয়ু',
    village: 'খুঙ্গং / মৌজা',
    district: 'জিলা',
    state: 'রাজ্য',
    taluka: 'সব-ডিভিজন / তহসিল',
    selectState: 'রাজ্য খনবীয়ু',
    selectDistrict: 'জিলা খনবীয়ু',
    selectVillage: 'খুঙ্গং খনবীয়ু',
    recordedArea: 'রেকোর্ত্তা য়াওবা মফম',
    acquiredArea: 'লৌখৎখিবা মফম',
    remainingArea: 'লেমহৌবা মফম',
    landClassification: 'লমগী মখল',
    ownershipType: 'মপু ওইবগী মখল',
    marketValueRate: 'কৈথেলগী মমল',
    hectares: 'হেক্তের',
    acres: 'একর / পরি',
    sqMeters: 'স্ক্বার মীতর',
    parcelStatus: 'লমগী দাগ ফীভম',
    searchLandPrompt: 'নহাক্কী নোতিসকী দাগ নম্বর থাদুনা ফীভম চেক তৌবীয়ু',
    searchLandBtn: 'লমগী অকুপ্পা মরোল থিবীয়ু',
    noLandFound: 'মসিগী মরোল অসিনা লমগী রেকোর্ত অমত্তা ফংদ্রে।',
    searchPlaceholder: 'দাগ নম্বৰ, খুঙ্গং নত্রগা নোতিস ID না থিবীয়ু...',
    exactMatchFound: 'চুম্না চান্নবা ফংলে',
    gisMapTitle: 'GIS প্রোজেক্ত অমসুং লমগী মেপ',
    gisMapDesc: 'লৌখৎপা ঙমখৈ, শোকহল্লবা মফম অমসুং নাকলশিং য়েংবীয়ু',
    satelliteView: 'সেতেলাইত উবা',
    streetView: 'লম্বী উবা',
    topographyView: 'মৈরোং উবা',
    legend: 'মেপকী খুদম',
    acquiredZone: 'লৌখৎনবা লাওথোক্লবা মফম',
    bufferZone: 'শোকহল্লবা মফম',
    yourParcel: 'নহাক্কী দাগ',
    adjacentParcels: 'নাকলগী দাগশিং',
    zoomIn: 'চাউথোকহনবীয়ু',
    zoomOut: 'পীমহনবীয়ু',
    resetView: 'মেপ হন্না শেমজিনবীয়ু',
    fullscreen: 'স্ক্ৰীন পুম্নমক',
    parcelId: 'দাগ ID',
    coordinates: 'ভৌগোলিক কোওর্দিনেত',
    distanceToProject: 'প্রোজেক্তকী লম্বীদা লৈবা অরাপ্পা',
    measurementTool: 'চাং য়েংবা খুৎশু',
    mapLayers: 'মেপকী লেয়রশিং',
    overlayCadastral: 'রেভিনিউ মেপকী লেয়র হাপচিনবীয়ু',
    totalCompensation: 'অপুনবা থমখিবা ক্ষতিপূরণ',
    assessedValue: 'লমগী মপুং ওইবা মমল',
    solatium: '১০০% সোলেসিয়ম (আইনগী সান্ত্বনা)',
    solatiumDesc: 'RFCTLARR এক্ত ২০১৩ গী সেক্সন ৩০(১) গী মখাদা ১০০% য়াওদবা য়াদবা ক্ষতিপূরণ',
    interestAmount: 'হেনগৎলকপা শেন্দোই অমসুং এলাৱেন্স',
    structureValue: 'য়ুম / উপাল / লন-থুমগী ক্ষতিপূরণ',
    calculatedTotal: 'অপুনবা পীগদবা ক্ষতিপূরণগী শেনফম',
    paymentStatus: 'PFMS শেন য়েন্থোকপগী ফীভম',
    dbtStatus: 'DBT বেঙ্ক একাউন্ত পুনশিনবগী ফীভম',
    disbursed: 'একাউন্ততা হাপখ্রে',
    disbursedAmount: 'পীখিবা শেনফম',
    remainingAmount: 'লেমহৌবা শেনফম',
    bankAccount: 'পুনশিল্লবা বেঙ্ক একাউন্ত',
    ifscCode: 'IFSC কোদ',
    paymentRefNo: 'PFMS / ত্রেজরি ত্রাঞ্জেক্সন নম্বর',
    claimCompensation: 'দাবী দরখাস্ত শীন্নবীয়ু',
    downloadAwardLetter: 'অৱার্দ ওর্দর দাউনলোদ তৌবীয়ু (ফোর্ম ১১)',
    rrTitle: 'পুনর্স্থাপন অমসুং মফম হোংদোকপগী (R&R) কান্নবশিং',
    rrEntitlement: 'R&R হক্কী পেকেজ',
    rrStatus: 'পুনর্স্থাপন থবক পাংথোকপগী ফীভম',
    resettlementHouse: 'মহুত শিনবা য়ুম / লম য়েন্থোকপা',
    subsistenceGrant: 'হিংনবগী এলাৱেন্স (থাগী)',
    transportAllowance: 'মফম হোংদোকপা অমসুং চৎ-থোক্কী এলাৱেন্স',
    trainingSkill: 'হৈশিংবা তম্বা অমসুং থবক ফংহনবা',
    rrOfficerAssigned: 'থৌদাং লৌরিবা R&R নোদাল ওফিসার',
    rrTimeline: 'R&R চাউখৎলকপগী মতম',
    docIntelTitle: 'AI চে-চাং নৈনবা ইঞ্জিন',
    docIntelSub: 'লম লৌখৎপগী নোতিস অমসুং গেজেত ওর্দরশিং নৈনৈ',
    uploadNotice: 'নোতিস নত্রগা অৱার্দ চে-চাং অপলোদ তৌবীয়ু',
    dragDropDoc: 'PDF, JPG নত্রগা PNG ফাইল মফমসিদা চিংশিল্লু নত্রগা থিবীয়ু',
    supportedFormats: 'য়ারিবা মখল: PDF, JPEG, PNG (অচৌবা: ২৫MB)',
    analyzingDoc: 'AI না চে-চাং নৈনরি...',
    extractedData: 'চে-চাংদগী লৌথোকপা মরুওইবা পাউ',
    legalClause: 'চৎনরিবা আইন অমসুং সেক্সন',
    section4_1: 'সেক্সন ৪(১) - অহানবা লাওথোকপা',
    section11_1: 'সেক্সন ১১(১) - অহানবা সর্ভে নোতিস',
    section19_1: 'সেক্সন ১৯(১) - লৌখৎপগী লাওথোকপা',
    section21_2: 'সেক্সন ২১(২) - মীয়ামগী তারবা নোতিস',
    section23: 'সেক্সন ২৩ - দিপুতী কমিসনারগী অরোইবা অৱার্দ',
    potentialDiscrepancy: 'মরুওইবা খেৎনব / ৱাকৎ উরে',
    discrepancyFound: 'নোতিস অমসুং রেভিনিউ রেকোর্তকী মরক্তা খেৎনব লৈরে',
    discrepancyDesc: 'নোতিসতা য়াওবা মফমসি রেকোর্ততগী হন্থৈ। অথুবা মতমদা ৱাকৎ থাবীয়ু।',
    reportDiscrepancy: 'ৱাকৎ / অপিল থাবীয়ু',
    aiConfidenceScore: 'AI নৈনবগী অচুম্বা রেতিং',
    plainLanguageSummary: 'চমবা লোলদা শম্লপ',
    actionDeadline: 'থবক লৌখৎপগী অরোইবা মতম',
    documentLocker: 'দিজিতেল চে-চাং বাকস',
    allDocuments: 'চেক তৌরবা চে-চাং পুম্নমক',
    verifiedDocuments: 'সরকারনা অয়াবা পীরবা চে-চাং',
    pendingVerification: 'চেক তৌনবা ঙাইরিবা',
    uploadNewDoc: 'অনৌবা চে-চাং অপলোদ তৌবীয়ু',
    docType: 'চে-চাংগী মখল',
    selectDocType: 'চে-চাং মখল খনবীয়ু',
    docLandTitle: 'লম মপু ওইবগী চে (পত্তা / জমাবন্দী)',
    docGovNotice: 'সরকারগী লম লৌখৎপা নোতিস',
    docIdentityProof: 'শকখঙ চে (আধার / প্যান কার্দ)',
    docBankPassbook: 'বেঙ্ক পাসবুক / কেন্সেল চেক',
    docGrievanceProof: 'ৱাকৎকী প্রুফ চে-চাং',
    fileSize: 'ফাইলগী অচৌবা',
    uploadDate: 'অপলোদ তৌখিবা তারিখ',
    viewDoc: 'চে-চাং য়েংবীয়ু',
    downloadDoc: 'চে-চাং দাউনলোদ তৌবীয়ু',
    deleteDoc: 'চে-চাং মুত্থৎপু',
    confirmDeleteDoc: 'নহাক্না চে-চাং অসি তশেংনা মুত্থৎপা পাম্ব্রা?',
    grievancesTitle: 'প্রজা ৱাকৎ অমসুং ৱারোইশিন পুথোকপা',
    submitGrievance: 'অনৌবা ৱাকৎ থাবীয়ু',
    grievanceType: 'ৱাকৎকী মখল',
    selectGrievanceType: 'ৱাকৎ মখল খনবীয়ু',
    typeCompensationAmount: 'ক্ষতিপূরণ শেনফম মশিং থিবদা পেন্দবা',
    typeAreaDiscrepancy: 'মফম চাং য়েংবদা খেৎনব লৈবা',
    typeOwnershipDispute: 'মপু ওইবগী ঈরাং নত্রগা মমিং শেমদোকপা',
    typePaymentDelay: 'ক্ষতিপূরণ শেনফম ফংবদা থেন্থবা',
    typeRRNonReceipt: 'পুনর্স্থাপন কান্নব ফংদবা',
    typeOther: 'অতোপ্পা ওফিসকী ৱাকৎ',
    grievanceSubject: 'ৱাকৎকী হীরম',
    grievanceDesc: 'ৱাকৎকী অকুপ্পা মরোল',
    grievanceDescPlaceholder: 'নহাক্কী ৱাকৎ মরোল কুপ্না ইবীয়ু...',
    attachEvidence: 'প্রুফ চে-চাং হাপচিল্লু',
    grievanceStatus: 'ৱাকৎ ৱারোইশিনগী ফীভম',
    ticketNumber: 'তোকেন নম্বর',
    assignedToOfficer: 'থৌদাং লৌরিবা ওফিসার',
    expectedResolutionDate: 'ৱারোইশিন ফংগদবা তারিখ',
    hearingDate: 'ময়েক শেংনা তান্নবা তারিখ',
    officerRemarks: 'ওফিসারগী চৎনবী মত',
    resolutionSummary: 'অরোইবা ৱারোইশিন শম্লপ',
    actionCenterTitle: 'প্রজা থবক পায়বা মফম অমসুং মতম',
    pendingActions: 'নহাক্না তৌগদবা থবকশিং',
    completedActions: 'লোইশিনখ্রবা থবকশিং',
    urgentDeadlines: 'আইনগী মতম লোইবগী চেকশিনৱা',
    actObjectionPeriod: 'সেক্সন ১৫(১) গী মখাদা ৱাকৎ থাবগী নুমিৎ ৬০ গী মতম',
    actSubmitBankDocs: 'ক্ষতিপূরণগীদমক বেঙ্ককী অকুপ্পা মরোল শীন্নবীয়ু',
    actAttendHearing: 'দিপুতী কমিসনারগী মীয়ামগী তান্নবদা শরুক য়াবীয়ু',
    markCompleted: 'লোইরে হায়না খুত্থাম পীবীয়ু',
    daysRemaining: 'নুমিৎ লেমহৌরি',
    expiredDeadline: 'মতম লোইখ্রে',
    notificationTitle: 'পাউ অমসুং সরকারগী লাওথোকপা',
    allNotifications: 'পাউ পুম্নমক',
    unreadOnly: 'পাদ্রিবা খক্তা',
    markAllRead: 'পুম্নমক পারে হায়না খুত্থাম পীবীয়ু',
    noNotifications: 'হৌজিক ওইনা অনৌবা পাউ অমত্তা লৈত্ৰি।',
    officerTitle: 'লম লৌখৎপা ওফিসার (LAO) কন্ত্রোল মফম',
    officerCasesRegistry: 'প্রোজেক্ত কেস রেজিস্ত্রী',
    totalAcquisitions: 'অপুনবা লৌখৎপা প্রোজেক্ত',
    activeParcels: 'চৎনরিবা দাগশিং',
    totalDisbursedBudget: 'অপুনবা য়েন্থোকখিবা বজেত',
    pendingApprovals: 'অয়াবা পীনবা ঙাইরিবা ফাইল',
    caseId: 'কেস ID',
    caseName: 'প্রোজেক্তকী মমিং',
    affectedLandowners: 'শোকহল্লবা লমগী মপুশিং',
    stage: 'হৌজিক্কী আইনগী তাংকক',
    stage1_Survey: 'তাংকক ১: সমাচারি গোম অমসুং সর্ভে',
    stage2_Notification: 'তাংকক ২: সেক্সন ১১(১) অহানবা নোতিস',
    stage3_Objections: 'তাংকক ৩: সেক্সন ১৫ তান্নবা অমসুং ৱাকৎ',
    stage4_Declaration: 'তাংকক ৪: সেক্সন ১৯ লৌখৎপগী লাওথোকপা',
    stage5_Award: 'তাংকক ৫: সেক্সন ২৩ অৱার্দ অমসুং ক্ষতিপূরণ থমবা',
    stage6_Payment: 'তাংকক ৬: PFMS ক্ষতিপূরণ য়েন্থোকপা',
    stage7_Possession: 'তাংকক ৭: লম পায়বা অমসুং R&R চৎনহনবা',
    approve: 'অয়াবা পীবীয়ু',
    reject: 'য়াদ্রে হায়বীয়ু',
    forwardToUpper: 'মথক্কী ওফিসারদা থাবীয়ু',
    scheduleHearing: 'তান্নবা নুমিৎ লেপপু',
    issueNotice: 'আইনগী নোতিস থাবীয়ু',
    disburseFunds: 'শেন থাদোকপু',
    officerRemarksPlaceholder: 'ওফিসারগী য়েংশিনবা মত ইবীয়ু...',
    saveDecision: 'ৱারেপ কনবীয়ু',
    step: 'খোঙথাং',
    of: 'গী',
    surveyRequired: 'দাগ নম্বর মথৌ তাই',
    enterValidSurvey: 'অনবা চুম্বা দাগ নম্বর ইবীয়ু',
    villageRequired: 'খুঙ্গংগী মমিং মথৌ তাই',
    districtRequired: 'জিলাগী মমিং মথৌ তাই',
    compensationBreakdown: 'ক্ষতিপূরণ মশিং থিবগী অকুপ্পা মরোল',
    marketValueCalculated: 'থমখিবা লমগী মমল',
    multiplicationFactor: 'খুঙ্গংগী ফেক্তর (RFCTLARR সেদ্যুল ১)',
    additionalAssetValuation: 'উপাল, থরোই অমসুং য়ুমগী মমল',
    statutoryInterest: 'সেক্সন ৩০(৩) গী মখাদা ১২% চহীগী হেনগৎলকপা শেন্দোই',
    netEntitlement: 'অপুনবা পীগদবা ক্ষতিপূরণ শেনফম',
    readyForPFMS: 'PFMS না পীথোক্নবা শেম-শারে',
    disbursementHistory: 'মমাংদা পীখিবা ত্রাঞ্জেক্সনগী পুৱারি',
    noDisbursementsYet: 'হৌজিক ফাওবা শেন অমত্তা থাদোক্ত্রি।',
    compensationDisputeHelp: 'মশিং থিবদা পেন্দবা লৈরগদি লেন্দ ওথোরিতি (LARR) দা অপিল তৌবা য়াই।',
    trackDisbursement: 'PFMS পৱার্টেলদা য়েংশিনবীয়ু',
    viewAllNotices: 'গেজেত নোতিস পুম্নমক য়েংবীয়ু',
    noActionsPending: 'হৌজিক্কী ওইনা নহাক্না তৌগদবা থবক লৈত্ৰি।',
    officerQueueEmpty: 'ঙাইরিবা কেসকী পরেং হাংলে।',
    discrepancyResolution: 'খেৎনব শেমদোকপগী খোঙথাং',
    fileAppeal: 'লেন্দ একুইজিসন ওথোরিতি (LARRA) দা অপিল থাবীয়ু',
    disputeDeadlineWarning: 'নীংশিংবীয়ু: অৱার্দ থোক্লবা নুমিৎ ৬০ গী মনুংদা অপিল তৌবা য়াই।',
    noticeDetails: 'নোতিসকী অকুপ্পা মরোল',
    gazetteDate: 'গেজেত ফোংখিবা তারিখ',
    competentAuthority: 'থৌদাং লৈবা ওথোরিতি (CALA / SDO)',
    projectAlignmentMap: 'হাইভয়ে / রেলৱে লম্বীগী মেপ',
    surveyBoundaries: 'রেভিনিউ সর্ভে ঙমখৈ',
    parcelAreaMismatch: 'দাগকী মফমদা খেৎনব লৈরে',
    expectedArea: 'রেভিনিউ রেকোর্তকী মফম',
    noticeArea: 'নোতিসতা য়াওবা মফম',
    difference: 'খেৎনব',
    takeImmediateAction: 'অথুবা খোঙথাং লৌবীয়ু',
    appealPeriodActive: 'অপিলগী মতম চৎথরি',
    appealDaysLeft: 'অপিল তৌনবা লেমহৌরিবা নুমিৎ',
    submitClaimDocuments: 'দাবী চে-চাং অথুবদা শীন্নবীয়ু',
    uploadSuccess: 'চে-চাং মপুং ফানা অপলোদ তৌরে!',
    uploadFailure: 'অপলোদ তৌবা মাইপাকদ্রে। অমুক হন্না হোৎনবীয়ু।',
    deleteConfirmTitle: 'চে-চাং মুত্থৎকদরা?',
    deleteConfirmDesc: 'চে-চাং অসি মুত্থৎলবদি অমুক হন্না ফংবা য়ারোই।',
    grievanceSubmittedSuccess: 'নহাক্কী ৱাকৎ মাইপাক্না থাখ্রে!',
    grievanceTrackingTip: 'ফীভম খঙনবা তোকেন নম্বর কান্না থম্বীয়ু।',
    hearingScheduledAlert: 'তান্নবা নুমিৎ লেপখ্রে।',
    attendHearingNotice: 'চে-চাংশಿꯡগা লোয়ননা মতম চারকপদা শরুক য়াবীয়ু।',
    contactHelpdesk: 'তেংবাং মফমদা পাউ ফাওবীয়ু',
    tollFreeNumber: 'তোল ফ্রী নম্বর: ১৮০০-১১১-৯৯৯৯',
    helpdeskTiming: 'নিংথৌকাবুদা শনিচার ফাওবা, অয়ুক ৯ দগী নুমিদাং ৬ ফাওবা',
    faqTitle: 'হন্না-হন্না হংবা ৱাহংশಿꯡ (FAQ)',
    privacyPolicy: 'লৈবাক্কী নিয়ম',
    termsOfService: 'নিয়ম অমসুং শর্তশিং',
    accessibilityStatement: 'পাউ ফংহনবগী ৱারোল',
    govtOfIndia: 'ভারত সরকার',
    ministryOfRuralDev: 'খুঙ্গং চাউখৎ-থৌরাং অমসুং লমগী মন্ত্রালয়',
    allRightsReserved: 'হক পুম্নমক কনরে।',
    disclaimer: 'পৱার্টেল অসি ফীভম শেংহন্নবনি। সরকারগী গেজেত নোতিসখক্তমক অরোইবনি।',
    heroTitle: 'নহাক্কী লমগী মতাংদা ময়েক শেংনা খঙবীয়ু।',
    heroDesc: 'লম লৌখৎপগী থৌওংদা চেকশিন্না য়েংশিল্লু, ১০০% সোলেসিয়মগা লোয়ননা চপ চাবা ক্ষতিপূরণ ফংউ অমসুং ৱাকৎশিং য়াংনা লোইশিনবীয়ু।',
    findLandBtn: 'ঐগী লম থিবীয়ু',
    trackCaseBtn: 'কেস য়েংশিনবীয়ু',
    understandDocBtn: 'চে-চাং নৈনবীয়ু',
    exploreMapBtn: 'মেপ য়েংবীয়ু',
    tickerAdvisory: 'প্রজা পাউ: নোতিস ফংলবা নুমিৎ ৬০ গী মনুংদা সেক্সন ১৫(১) গী মখাদা ৱাকৎ থাবা য়াই।',
    noticeLabel: 'অনৌবা নোতিস:',
    feature1Title: 'চুম্না লম থিবা',
    feature1Desc: 'দাগ নম্বরনা লমগী মফম, ঙমখৈ অমসুং ফীভম অথুবদা খঙবীয়ু।',
    feature2Title: 'স্মার্ত চে-চাং নৈনবা',
    feature2Desc: 'নোতিসকী আইনগী মশক, খেৎনব অমসুং মরুওইবা তারিখশিং AI না লায়না বুঝিগনি।',
    feature3Title: '১০০% ক্ষতিপূরণ শেংবা',
    feature3Desc: 'RFCTLARR আইনগী মতুংইন্না অপুনবা সোলেসিয়ম, শেন্দোই অমসুং DBT পাউ য়েংবীয়ু।',
    feature4Title: 'লায়না ৱারোইশিন পুথোকপা',
    feature4Desc: 'মফম নত্রগা ক্ষতিপূরণদা খেৎনব লৈরগদি হকথেংননা ওফিসারশিংদা ৱাকৎ থাবীয়ু।',
    compensation: 'ক্ষতিপূরণ',
    rr: 'পুনর্স্থাপন (R&R)',
    documents: 'চে-চাং',
    grievances: 'ৱাকৎশিং',
    actionRequired: 'থবক পায়বা মথৌ তাই',
    inProgress: 'চৎথরি',
    helpdesk: 'তেংবাং মফম',
    dashboard: 'দেসবোর্দ',
    home: 'য়ুমলৈ',
    profile: 'প্রোফাইল',
    settings: 'সেতিংশিং',
    notifications: 'পাউশিং',
    logout: 'সাইন আউত',
    login: 'সাইন ইন',
    email: 'ইমেল লৈফম',
    password: 'পাসৱার্দ',
    forgotPassword: 'পাসৱার্দ কাউখ্রব্রা?',
    register: 'রেজিস্তার তৌবীয়ু',
    rememberMe: 'ঐবু নীংশিংবীয়ু',
    citizenLogin: 'প্রজা সাইন ইন',
    officerLogin: 'ওফিসার সাইন ইন',
    demoCredentials: 'দেমো সাইন ইন পাউ',
    enterEmail: 'নহাক্কী ইমেল ইবীয়ু',
    enterPassword: 'নহাক্কী পাসৱার্দ ইবীয়ু',
    welcomeCitizen: 'প্রজা তরাম্না ওকচরি',
    welcomeOfficer: 'ওফিসার তরাম্না ওকচরি',
    quickStats: 'শম্লপ মশিং',
    totalCases: 'অপুনবা কেস',
    resolvedCases: 'ৱারোইশিন পুথোক্লবা কেস',
    pendingReviews: 'নৈননবা ঙাইরিবা',
    myParcels: 'ঐগী লম দাগশিং',
    caseTimeline: 'কেস মতম পরেং',
    recentActivity: 'হৌদোক্লিবা থবকশিং',
    downloadReport: 'রিপোর্ত দাউনলোদ তৌবীয়ু',
    filterByStatus: 'ফীভম মতুংইন্না খনবীয়ু',
    allStatuses: 'ফীভম পুম্নমক',
    sortBy: 'পরেং শেম্বীয়ু',
    newestFirst: 'অনৌবা অহানবা',
    oldestFirst: 'অরিবদা অহানবা',
    name: 'মমিং',
    phone: 'ফোন নম্বর',
    address: 'লৈফম',
    remarks: 'মতমত',
    category: 'মখল',
    date: 'তারিখ',
    time: 'মতম',
    type: 'মখল',
    viewAll: 'পুম্নমক য়েংবীয়ু',
    clearFilters: 'ফিল্তর লৌথোকপু',
    resultsFound: 'ফল ফংলে',
    noResults: 'ফল অমত্তা ফংদ্রে',
    fileUploadSuccess: 'ফাইল অপলোদ তৌরে',
    fileUploadError: 'অপলোদ তৌবদা অশোয়বা লৈরে',
    fileDeleted: 'ফাইল মুত্থৎখে',
    changesSaved: 'অহোংবশিং কনরে',
    actionSuccess: 'থবক মাইপাক্লে',
    actionFailed: 'থবক মাইপাকদ্রে',
    sessionExpired: 'মতম লোইরে, অমুক হন্না সাইন ইন তৌবীয়ু',
    unauthorized: 'য়াহনদবা চংবা',
    serverError: 'সার্ভারগী অশোয়বা, তুংদা হোৎনবীয়ু',
    networkError: 'নেতৱার্ক্কী অশোয়বা',
    tryAgain: 'অমুক হন্না হোৎনবীয়ু',
    goBack: 'হন্দোকপু',
    goToHome: 'য়ুমলৈদা চৎলু',
    viewMore: 'হেন্না য়েংবীয়ু',
    viewLess: 'হন্থনা য়েংবীয়ু',
    copied: 'কোপি তৌরে!',
    copyToClipboard: 'ক্লিপবোর্দতা কোপি তৌবীয়ু',
    yes: 'হোই',
    no: 'নত্তে',
    ok: 'য়ারনি',
    help: 'তেংবাং',
    feedback: 'ফীদবেক',
    contactUs: 'পাউ ফাওবীয়ু',
    aboutUs: 'ঐখোয়গী মতাংদা',
    version: 'ভার্সন',
    systemStatus: 'সিস্তেম ফীভম',
    online: 'ওনলাইন',
    offline: 'ওফলাইন',
    connecting: 'পুনশিল্লি...',
    syncing: 'সিংক তৌরি...',
    lastUpdated: 'অরোইবা অনৌবা শেম্বা',
    justNow: 'হৌজিকমক',
    minutesAgo: 'মিনিত্কী মমাংদা',
    hoursAgo: 'পুংগী মমাংদা',
    daysAgo: 'নুমিৎকী মমাংদা',
    readMore: 'হেন্না পারু',
    showMore: 'হেন্না উৎপু',
    showLess: 'হন্থনা উৎপু',
    selectAll: 'পুম্নমক খনবীয়ু',
    deselectAll: 'পুম্নমক লৌথোকপু',
    expandAll: 'পুম্নমক সান্থোকপু',
    collapseAll: 'পুম্নমক শমজিনপু',
    openInNewTab: 'অনৌবা তাব্দা হাংবীয়ু',
    previous: 'মমাংগী',
    pageOf: 'লামায়',
    rowsPerPage: 'লামায়দা লৈবা পরেং',
    totalRecords: 'অপুনবা রেকোর্ত',
    noRecordsFound: 'রেকোর্ত অমত্তা ফংদ্রে',
    pleaseWait: 'অনবা ঙাইহাক ঙাইবীয়ু...',
    somethingWentWrong: 'মালেমদা অশোয়বা থোক্লে',
    fieldRequired: 'মসি ইবা মথৌ তাই',
    invalidEmail: 'চুম্বা ইমেল লৈফম ইবীয়ু',
    invalidPhone: 'চুম্বা ১০ ডিজিটকী মোবাইল নম্বর ইবীয়ু',
    passwordTooShort: 'পাসৱার্দ অসি য়ামদ্রবদা ময়েক ৮ ওইগদবনি',
    passwordsDoNotMatch: 'পাসৱার্দ চান্নদ্রে',
    termsAgreement: 'ঐনা নিয়ম অমসুং শর্তশিং য়ারে',
    agreeToTerms: 'মাংদা চংশিন্নবা শর্তশিং য়াবীয়ু',
    selectLanguage: 'লোল খনবীয়ু',
    currentLanguage: 'হৌজিক চৎনরিবা লোল',
    languageChanged: 'লোল মপুং ফানা হোংলে',
    autoDetectLocation: 'মফম মশামক থিবীয়ু',
    locationAccessDenied: 'মফম উনবা য়াহনদ্রে',
    useManualSearch: 'অনবা খুৎনা থিবীয়ু',
    satelliteLayer: 'সেতেলাইত লেয়র',
    cadastralLayer: 'রেভিনিউ মেপ লেয়র',
    projectBufferLayer: 'প্রোজেক্ত বফর লেয়র',
    measuringDistance: 'অরাপ্পা চাং য়েংলি',
    measuringArea: 'মফম চাং য়েংলি',
    clickToMeasure: 'চাং য়েংনবা মেপ্তা ওতাবীয়ু',
    clearMeasurement: 'চাং য়েংবা মুত্থৎপু',
    totalDistance: 'অপুনবা অরাপ্পা',
    totalArea: 'অপুনবা মফম',
    meters: 'মীতর',
    kilometers: 'কিমি',
    discrepancyDetails: 'খেৎনবগী অকুপ্পা মরোল',
    affectedSections: 'শোকহল্লবা সেক্সনশিং',
    recommendedAction: 'পাম্বৈ খোঙথাং',
    fileGrievanceNow: 'হৌজিকমক ৱাকৎ থাবীয়ু',
    viewDiscrepancyReport: 'খেৎনবগী রিপোর্ত য়েংবীয়ু',
    aiConfidence: 'AI চুম্বগী থাক',
    highConfidence: 'ৱাংবা চুম্বা (৯৫%+)',
    mediumConfidence: 'ময়ায় ওম্বা চুম্বা',
    lowConfidence: 'নেম্বা চুম্বা',
    extractedEntities: 'ফংলবা পাউশিং',
    officialGazetteNo: 'সরকারগী গেজেত নম্বর',
    notificationDate: 'লাওথোকখিবা তারিখ',
    competentAuthorityName: 'ওথোরিতী ওফিসারগী মমিং',
    hearingVenue: 'তান্নবা মফম',
    objectionDeadlineDate: 'ৱাকৎ থাবগী অরোইবা তারিখ',
    documentVerifiedBadge: 'সরকারনা চেক তৌরে',
    documentPendingBadge: 'চেক তৌরি',
    documentRejectedBadge: 'চে-চাং য়াদ্রে',
    reuploadDocument: 'চে-চাং অমুক হন্না অপলোদ তৌবীয়ু',
    reasonForRejection: 'য়াদবগী মরম',
    downloadCertificate: 'সার্তিফিকেত দাউনলোদ তৌবীয়ু',
    shareDocument: 'চে-চাং শিয়র তৌবীয়ু',
    printSummary: 'শম্লপ নম্বীয়ু',
    directBenefitTransfer: 'হকথেংননা কান্নবা য়েন্থোকপা (DBT)',
    pfmsTrackingStatus: 'PFMS শেন য়েন্থোকপা য়েংশিনবা',
    bankAccountVerified: 'বেঙ্ক একাউন্ত চেক তৌরে',
    bankAccountPending: 'বেঙ্ক একাউন্ত চেক তৌনবা ঙাইরি',
    treasuryRefNumber: 'ত্রেজরি রেফরেন্স নম্বর',
    disbursementDate: 'শেন থাদোকখিবা তারিখ',
    installmentNumber: 'ইনস্তোলমেন্ত নম্বর',
    partialPayment: 'অখাইবা শেন',
    fullPayment: 'মপুং ফাবা শেন',
    solatiumAmount: 'সোলেসিয়ম শেনফম (১০০%)',
    baseCompensation: 'লমগী মপুং ক্ষতিপূরণ',
    statutoryInterestValue: 'আইনগী শেন্দোই শেনফম',
    totalAwardAmount: 'অপুনবা অৱার্দ শেনফম',
    displacedFamilyId: 'মফম হোংলবা ইমুং ID',
    resettlementSiteName: 'পুনর্স্থাপন খুঙ্গংগী মমিং',
    plotAllotmentStatus: 'লম য়েন্থোকপগী ফীভم',
    housingGrantStatus: 'য়ুম শানবা গ্রান্তকী ফীভম',
    annuityBenefitStatus: 'থাগী পেন্সনগী ফীভম',
    skillTrainingStatus: 'হৈশিংবা তম্বগী ফীভম',
    livelihoodGrant: 'হিংনবগী গ্রান্ত',
    officerCaseManagement: 'কেস য়েংশিনবগী কন্ত্রোল',
    citizenGrievanceQueue: 'প্রজা ৱাকৎ পরেং',
    hearingManagement: 'তান্নবা য়েংশিনবা',
    awardDrafting: 'অৱার্দ শেম্বা অমসুং অয়াবা পীব',
    fundSanction: 'শেনফম অয়াবা অমসুং য়েন্থোকপ',
    reportsAndAnalytics: 'রিপোর্ত অমসুং নৈনব',
    bulkNoticeGeneration: 'নোতিস পুননা থোকহনব',
    cadastralSync: 'রেভিনিউ মেপ সিংক',
    exportToExcel: 'Excel দা দাউনলোদ',
    exportToPdf: 'PDF রিপোর্ত দাউনলোদ',
    auditLog: 'ওদিত লোগ',
    loginHistory: 'লোগিন পুৱারি',
    officerBadge: 'সরকারগী ওফিসার থাক',
    citizenBadge: 'চেক তৌরবা প্রজা',
    stepCompleted: 'খোঙথাং অসি লোইরে',
    stepInProgress: 'খোঙথাং অসি চৎথরি',
    stepPending: 'খোঙথাং অসি ঙাইরি',
    timelineOverview: 'লম লৌখৎপগী মতমগী মপুং ফাবা য়েংবা',
    legalDisclaimer: 'আইনগী পাউ: পাউ অসি প্রজাগী খুদোংচাবনি। সরকারগী গেজেত নোতিসখক্তমক অরোইবনি।',
    closeModal: 'ৱিন্দো থিংজিনবীয়ু',
    viewReceipt: 'রসিদ য়েংবীয়ু',
    downloadReceipt: 'রসিদ দাউনলোদ তৌবীয়ু',
    sendSMSAlert: 'SMS চেকশিনৱা থাবীয়ু',
    sendEmailAlert: 'ইমেল চেকশিনৱা থাবীয়ু',
    optOutOfAlerts: 'চেকশিনৱা লেপপু',
    helpdeskSupport: '২৪/৭ প্রজা তেংবাং',
    quickGuide: 'শীজিন্নরিবগী লমজিং',
    termsText: 'সহায় পৱার্টেলগী শর্তশিংগী মখাদা।',
  };

  writeLocale('mni', 'মৈতৈলোন', t);
}
