import { writeLocale, allKeys } from './locale-base.js';
import { en } from '../src/locales/en.js';
import { TranslationSchema } from '../src/locales/types.js';

// ============================================================================
// 1. TAMIL (தமிழ் - ta)
// ============================================================================
export function generateTamil() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: 'சஹாய் (SAHAAY)',
    emblemLetter: 'ச',
    tagline: 'உங்கள் நிலம். உங்கள் வழக்கு. உங்கள் உரிமை.',
    heroSub: 'நில எடுப்பு மற்றும் சட்டப்பூர்வ இழப்பீட்டுக்கான குடிமக்கள் தகவல் தளம்',
    portalSubtitle: 'நிலம் • இழப்பீடு • மறுவாழ்வு • குறைகள் • வழக்கு கண்காணிப்பு',
    citizenPortal: 'குடிமக்கள் தளம்',
    officerPortal: 'நில எடுப்பு அதிகாரி தளம்',
    demoMode: 'டெமோ பயன்முறை செயலில் உள்ளது',
    signIn: 'உள்நுழைக',
    signOut: 'வெளியேறு',
    landowner: 'நில உரிமையாளர்',
    landOfficer: 'நில எடுப்பு அதிகாரி (LAO)',
    switchRole: 'பங்கு மாற்றம்',
    switchCitizen: 'குடிமகன் (ராஜேஷ் சர்மா)',
    switchOfficer: 'நில எடுப்பு அதிகாரி (விக்ரம் சவுகான்)',
    welcomeBack: 'மீண்டும் வருக',
    navHome: 'முகப்பு',
    navFindLand: 'என் நிலத்தைக் காண்க',
    navGisMap: 'GIS நில வரைபடம்',
    navDocIntel: 'ஆவண நுண்ணறிவு (AI)',
    navCompensation: 'இழப்பீடு & மறுவாழ்வு (R&R)',
    navDocuments: 'ஆவணங்கள் பெட்டகம்',
    navActionCenter: 'நடவடிக்கை மையம்',
    navGrievances: 'குறைதீர்ப்பு & பிரிவுகள்',
    navNotices: 'அறிவிப்புகள் & எச்சரிக்கைகள்',
    navOfficerDashboard: 'அதிகாரி கட்டுப்பாட்டு அறை',
    navCasesRegistry: 'வழக்குகள் பதிவேடு',
    navGrievancesQueue: 'மனுக்கள் வரிசை',
    citizenServices: 'குடிமக்கள் நில சேவைகள்',
    quickActions: 'விரைவு நடவடிக்கைகள்',
    submit: 'சமர்ப்பி',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    search: 'தேடுக',
    filter: 'வடிகட்டு',
    back: 'பின்செல்',
    next: 'அடுத்து',
    close: 'மூடு',
    view: 'பார்வையிடு',
    download: 'பதிவிறக்கு',
    upload: 'பதிவேற்று',
    export: 'ஏற்றுமதி',
    refresh: 'புதுப்பி',
    print: 'அச்சிடு',
    loading: 'ஏற்றுகிறது...',
    actions: 'நடவடிக்கைகள்',
    details: 'விவரங்கள்',
    status: 'நிலை',
    viewDetails: 'விவரங்களைக் காண்க',
    viewOnMap: 'வரைபடத்தில் காண்க',
    viewCase: 'முழு வழக்கை காண்க',
    trackProgress: 'முன்னேற்றத்தைக் காண்க',
    proceed: 'தொடரவும்',
    confirm: 'உறுதி செய்',
    retry: 'மீண்டும் முயற்சிக்கவும்',
    clearAll: 'அனைத்தையும் அழி',
    applyFilter: 'வடிகட்டியைப் பயன்படுத்து',
    active: 'செயலில்',
    pending: 'நிலுவையில்',
    completed: 'முடிந்தது',
    resolved: 'தீர்வு செய்யப்பட்டது',
    inProgress: 'செயல்பாட்டில்',
    actionRequired: 'நடவடிக்கை தேவை',
    verified: 'சரிபார்க்கப்பட்டது',
    all: 'அனைத்தும்',
    noData: 'தகவல் இல்லை',
    noResults: 'முடிவுகள் எதுவும் கிடைக்கவில்லை',
    loadingData: 'சமீபத்திய பதிவுகள் பெறப்படுகின்றன...',
    somethingWentWrong: 'ஏதோ பிழை ஏற்பட்டது',
    tryAgain: 'சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்',
    errorOccurred: 'எதிர்பாராத பிழை நிகழ்ந்தது',
    help: 'உதவி & அடிக்கடி கேட்கப்படும் கேள்விகள்',
    helpdesk: 'உதவி மையம்',
    helpline: '1800-180-LAND',
    tollFree: 'இலவச தேசிய உதவி எண்',
    rightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை',
    status_ACTIVE: 'செயலில் உள்ளது',
    status_COMPLETED: 'நிறைவடைந்தது',
    status_VERIFIED: 'சரிபார்க்கப்பட்டது',
    status_PAID: 'வழங்கப்பட்டது (DBT)',
    status_SANCTIONED: 'அனுமதிக்கப்பட்டது',
    status_RESOLVED: 'தீர்வு செய்யப்பட்டது',
    status_ELIGIBLE: 'தகுதியானது',
    status_VERIFICATION: 'சரிபார்ப்பு நிலை',
    status_IN_PROGRESS: 'செயல்பாட்டில் உள்ளது',
    status_UNDER_REVIEW: 'மதிப்பாய்வில் உள்ளது',
    status_CURRENT: 'தற்போதைய நிலை',
    status_PROCESSING: 'செயலாக்கத்தில் உள்ளது',
    status_ACTION_REQUIRED: 'நடவடிக்கை தேவை',
    status_UPCOMING: 'வரவிருக்கும் நிலை',
    status_PENDING: 'நிலுவையில் உள்ளது',
    status_REJECTED: 'நிராகரிக்கப்பட்டது',
    status_FAILED: 'தோல்வியடைந்தது',
    status_DEPOSITED_PFMS: 'PFMS மூலம் வரவு வைக்கப்பட்டது',
    status_CLAIM_SUBMITTED: 'கோரிக்கை சமர்ப்பிக்கப்பட்டது',
    status_DISCREPANCY_FLAGGED: 'முரண்பாடு கண்டறியப்பட்டது',
    status_RESPONSE_ADDED: 'பதில் சேர்க்கப்பட்டது',
    status_AWAITING_HEARING: 'விசாரணைக்கு காத்திருக்கிறது',
    status_CLOSED: 'வழக்கு முடிக்கப்பட்டது',
    status_ASSESSED: 'மதிப்பிடப்பட்டது',
    status_APPROVED: 'ஒப்புதல் அளிக்கப்பட்டது',
    status_DISCREPANCY_FOUND: 'முரண்பாடு உள்ளது',
    status_DISPUTED: 'சர்ச்சைக்குரியது',
    status_HIGH: 'அதிமுக்கியம்',
    status_SUBMITTED: 'சமர்ப்பிக்கப்பட்டது',
    status_UNPAID: 'செலுத்தப்படாதது',
    status_PROPOSAL: 'திட்ட முன்மொழிவு',
    status_NOTIFICATION: 'அறிவிப்பு நிலை',
    welcomeTitle: 'சஹாய் தளம் உங்களை வரவேற்கிறது',
    welcomeSub: 'உங்கள் நிலத்தின் சட்டப்பூர்வ ஆவணங்கள் மற்றும் இழப்பீட்டைக் கண்காணிக்க உள்நுழைக.',
    demoAccountsTitle: 'டெமோ கணக்குகளைத் தேர்ந்தெடுக்கவும்',
    demoBadge: 'டெமோ பயன்முறை',
    demoCitizenTitle: '🌾 குடிமகன் / நில உரிமையாளர்',
    demoCitizenSub: 'ராஜேஷ் சர்மா (சர்வே #1042)',
    demoOfficerTitle: '🏛️ நில எடுப்பு அதிகாரி (LAO)',
    demoOfficerSub: 'விக்ரம் சவுகான் (போபால் வட்டம்)',
    tabSignIn: 'உள்நுழைக',
    tabRegister: 'புதிய குடிமக்கள் பதிவு',
    fullNameLabel: 'முழுப் பெயர் (வருவாய் ஆவணத்தின்படி)',
    fullNamePlaceholder: 'எ.கா. ராஜேஷ் சர்மா',
    villageLabel: 'கிராமம்',
    districtLabel: 'மாவட்டம்',
    emailLabel: 'மின்னஞ்சல் / பதிவு செய்யப்பட்ட கைபேசி எண்',
    emailPlaceholder: 'name@sahaay.demo',
    passwordLabel: 'கடவுச்சொல்',
    passwordPlaceholder: '••••••••',
    verifyingBtn: 'சரிபார்க்கிறது...',
    createAccountBtn: 'புதிய கணக்கு உருவாக்கு',
    signInBtn: 'பாதுகாப்பாக உள்நுழைக',
    trustBadge: 'இந்திய அரசு • சட்டப்பூர்வ டிஜிட்டல் நில பாதுகாப்பு தளம்',
    authFailedError: 'உள்நுழைவு தோல்வியடைந்தது. மின்னஞ்சல் மற்றும் கடவுச்சொல்லை சரிபார்க்கவும்.',
    heroBadge: 'RFCTLARR சட்டம், 2013 சட்டப்பூர்வ தளம்',
    heroTitle: 'உங்கள் நிலத்திற்கு என்ன நடக்கிறது என்பதைத் தெளிவாக அறிந்துகொள்ளுங்கள்.',
    heroDesc: 'நில எடுப்பு நிலையை உடனுக்குடன் கண்காணிக்கவும், அரசிதழ் அறிவிப்புகளை எளிய மொழியில் புரிந்து கொள்ளவும், 100% சோலேஷியத்துடன் இழப்பீட்டைச் சரிபார்க்கவும், பிரிவு 15 மறுப்புகளை நேரடியாகத் தெரிவிக்கவும்.',
    findLandBtn: 'என் நிலத்தைக் காண்க',
    trackCaseBtn: 'வழக்கை கண்காணிக்கவும்',
    understandDocBtn: 'ஆவணத்தைப் புரிந்து கொள்ளவும்',
    badgeStatutoryFormula: '100% சட்டப்பூர்வ இழப்பீட்டு சூத்திரம்',
    badgeCertifiedKhasra: 'சான்றளிக்கப்பட்ட நிலப்பதிவேடு வரைபடம்',
    badgeSection15: 'பிரிவு 15 டிஜிட்டல் ஆட்சேபனை',
    surveyParcelLabel: 'சர்வே எண் / புல எண்',
    villageTehsilLabel: 'கிராமம் & வட்டம்',
    currentStageLabel: 'தற்போதைய சட்ட நிலை',
    currentStage: 'தற்போதைய நிலை',
    viewCadastralMapBtn: 'வரைபடத்தில் காண்க (GIS)',
    discrepancyBannerTitle: 'அரசிதழ் அறிவிப்பில் நிலப் பரப்பு முரண்பாடு கண்டறியப்பட்டது',
    discrepancyBannerDesc: 'பிரிவு 11(1) அறிவிப்பில் 2.73 ஹெக்டேர் எனக் குறிப்பிடப்பட்டுள்ளது, ஆனால் வருவாய் பதிவேட்டில் 2.43 ஹெக்டேர் மட்டுமே உள்ளது. பிரிவு 15-ன் கீழ் நீங்கள் ஆட்சேபனை தெரிவிக்கலாம்.',
    reviewDiscrepancyBtn: 'முரண்பாட்டைச் சரிபார்த்து ஆட்சேபனை தெரிவிக்கவும்',
    timelineSectionTitle: 'சட்டப்பூர்வ நில எடுப்பு வாழ்க்கைச் சுழற்சி',
    timelineSectionSub: 'RFCTLARR சட்டம் 2013-ன் படி ஆரம்ப அறிவிப்பு முதல் நிலம் ஒப்படைப்பு வரை 8 நிலைகளைக் கண்காணிக்கவும்.',
    stage1Name: 'பிரிவு 11(1) பூர்வாங்க அறிவிப்பு',
    stage2Name: 'பிரிவு 15 சட்ட ஆட்சேபனைகள்',
    stage3Name: 'பிரிவு 19 இறுதிப் பிரகடனம்',
    stage4Name: 'கூட்டு நில அளவீடு & எல்லை நிர்ணயம்',
    stage5Name: 'பிரிவு 23 இழப்பீட்டு ஆணை',
    stage6Name: 'DBT இழப்பீட்டுத் தொகை வழங்கல்',
    stage7Name: 'மறுவாழ்வு & மீள்குடியேற்றப் பலன்கள்',
    stage8Name: 'நிலம் ஒப்படைப்பு & இறுதி முடிவு',
    stage1Desc: 'பொது நோக்கத்திற்காக நிலம் கையகப்படுத்துவதற்கான ஆரம்ப அரசிதழ் அறிவிப்பு வெளியிடப்பட்டது.',
    stage2Desc: 'நில உரிமையாளர்கள் அறிவிப்பு வெளியான 60 நாட்களுக்குள் ஆட்சேபனைகளை சமர்ப்பிக்கலாம்.',
    stage3Desc: 'ஆட்சேபனைகள் பரிசீலிக்கப்பட்டு திட்டத்திற்கான இறுதி அறிவிப்பு பிரகடனம் செய்யப்படுகிறது.',
    stage4Desc: 'வருவாய்த்துறை அதிகாரிகள் மூலம் நிலத்தின் கள அளவீடு மற்றும் வரைபட எல்லை சரிபார்ப்பு.',
    stage5Desc: 'வழிகாட்டி மதிப்பு, பெருக்கல் காரணி மற்றும் 100% சோலேஷியம் சேர்த்து இழப்பீடு நிர்ணயம்.',
    stage6Desc: 'ஆதார் இணைக்கப்பட்ட வங்கிக் கணக்கிற்கு PFMS மூலம் இழப்பீட்டுத் தொகை நேரடியாக வரவு.',
    stage7Desc: 'குடும்பங்களுக்கான மறுவாழ்வு உதவித்தொகை மற்றும் மாற்று குடியிருப்பு உதவிகள் வழங்கல்.',
    stage8Desc: 'அரசிடம் நிலம் முறைப்படி ஒப்படைக்கப்பட்டு புதிய திட்டத்திற்கு உரிமை மாற்றம் செய்யப்படுகிறது.',
    servicesSectionTitle: 'குடிமக்கள் நிலச் சேவைகள்',
    servicesSectionSub: 'நில எடுப்பின் ஒவ்வொரு நிலையையும் வெளிப்படையாகவும் எளிமையாகவும் மாற்ற வடிவமைக்கப்பட்ட சேவைகள்.',
    serviceFindLandTitle: 'என் நிலத்தைக் காண்க',
    serviceFindLandDesc: 'சர்வே எண் மூலம் தேடி எல்லைகள் மற்றும் உரிமையாளர் விவரங்களை அறியவும்',
    serviceTrackCaseTitle: 'வழக்கை கண்காணிக்கவும்',
    serviceTrackCaseDesc: '8 சட்டப்பூர்வ நிலைகளில் உங்கள் வழக்கின் தற்போதைய முன்னேற்றத்தைக் காணவும்',
    serviceUnderstandDocTitle: 'ஆவணங்களை புரிந்துகொள்ளவும்',
    serviceUnderstandDocDesc: 'அரசு அறிவிப்புகளை பதிவேற்றி எளிய மொழி விளக்கத்தைப் பெறவும்',
    serviceCheckCompTitle: 'இழப்பீட்டை கணக்கிடவும்',
    serviceCheckCompDesc: 'வழிகாட்டி மதிப்பு, 100% சோலேஷியம் மற்றும் DBT நிலையை அறியவும்',
    serviceRRTitle: 'மறுவாழ்வு பலன்கள்',
    serviceRRDesc: 'வாழ்வாதார நிதி மற்றும் மாற்று வீட்டு உதவிகளைக் கண்காணிக்கவும்',
    serviceDiscrepancyTitle: 'முரண்பாட்டை தெரிவிக்கவும்',
    serviceDiscrepancyDesc: 'அறிவிக்கப்பட்ட பரப்பளவிற்கும் வருவாய் பதிவேட்டிற்கும் உள்ள வேறுபாட்டை ஒப்பிடவும்',
    serviceGrievanceTitle: 'மனு தாக்கல் செய்யவும்',
    serviceGrievanceDesc: 'நில எடுப்பு அதிகாரியிடம் பிரிவு 15 ஆட்சேபனைகளை சமர்ப்பிக்கவும்',
    serviceNoticesTitle: 'அறிவிப்புகள் & செய்திகள்',
    serviceNoticesDesc: 'விசாரணை தேதிகள், ஆணை விவரங்கள் மற்றும் சரிபார்ப்பு செய்திகள்',
    cadastralMapTitle: 'GIS ஊடாடும் நில வரைபடம்',
    cadastralMapSub: 'உங்கள் நில எல்லைகள் மற்றும் திட்ட வழித்தடத்தை வரைபடத்தில் துல்லியமாகக் காணவும்.',
    openFullMapBtn: 'முழு GIS தளத்தைத் திறக்கவும்',
    recentNoticesTitle: 'சமீபத்திய அதிகாரப்பூர்வ அறிவிப்புகள்',
    recentNoticesSub: 'உங்கள் நிலம் மற்றும் வழக்கு தொடர்பான அரசு அறிவிப்புகள்',
    viewAllNoticesBtn: 'அனைத்து அறிவிப்புகளையும் காண்க',
    noticeHearingTitle: 'பிரிவு 15 பொது விசாரணை அறிவிப்பு',
    noticeHearingDesc: 'சர்வே எண் 1042 தொடர்பான ஆட்சேபனை விசாரணை சார் ஆட்சியர் அலுவலகத்தில் நடைபெற உள்ளது.',
    noticeGazetteTitle: 'பிரிவு 11(1) பூர்வாங்க அரசிதழ் அறிவிப்பு வெளியிடப்பட்டது',
    noticeGazetteDesc: 'தேசிய நெடுஞ்சாலை விரிவாக்கத் திட்டத்திற்கான நில எடுப்பு அறிவிப்பு வெளியிடப்பட்டது.',
    noticeAwardTitle: 'பிரிவு 23 சட்டப்பூர்வ இழப்பீட்டு ஆணை பிறப்பிக்கப்பட்டது',
    noticeAwardDesc: 'நில உரிமையாளருக்கான மொத்த இழப்பீட்டுத் தொகை ரூ. 44,77,500 நிர்ணயிக்கப்பட்டு ஒப்புதல் அளிக்கப்பட்டது.',
    noticeDateLabel: 'அறிவிப்பு நாள்',
    supportSectionTitle: 'குடிமக்கள் உதவி & ஆதரவு மையம்',
    supportSectionDesc: 'நில எடுப்பு சட்ட வழிகாட்டுதல்கள் மற்றும் இழப்பீட்டு உதவிக்கு எங்களைத் தொடர்பு கொள்ளவும்.',
    supportHelplineTitle: 'தேசிய நில உரிமைகள் கட்டணமில்லா உதவி எண்',
    supportHelplineSub: 'திங்கள் முதல் சனி வரை காலை 9 மணி முதல் மாலை 6 மணி வரை',
    callNowBtn: 'உடனடி அழைப்பு: 1800-180-LAND',
    supportFaqTitle: 'சட்டப்பூர்வ அடிக்கடி கேட்கப்படும் கேள்விகள்',
    supportFaqSub: 'RFCTLARR சட்டம், 2013 தொடர்பான எளிய விளக்கங்கள்',
    viewFaqBtn: 'அனைத்து கேள்விகளையும் காண்க',
    findMyLand: 'என் நிலத்தைக் காண்க',
    myLand: 'என் நிலம்',
    surveyNo: 'சர்வே எண்',
    khasraNo: 'புல எண்',
    village: 'கிராமம்',
    tehsil: 'வட்டம் (தாலுகா)',
    district: 'மாவட்டம்',
    state: 'மாநிலம்',
    recordedArea: 'பதிவு செய்யப்பட்ட பரப்பு',
    documentArea: 'அரசிதழ் அறிவிப்பு பரப்பு',
    project: 'திட்டம்',
    department: 'துறை',
    caseReference: 'வழக்கு குறிப்பு எண்',
    noticeDate: 'அறிவிப்பு நாள்',
    notificationSection: 'அறிவிப்புப் பிரிவு',
    timeline: 'காலவரிசை',
    viewOnGis: 'GIS வரைபடத்தில் காண்க',
    landSearchTitle: 'அரசு நிலப் பதிவேடு மற்றும் கையகப்படுத்தல் தேடல்',
    landSearchSub: 'சர்வே எண், கிராமம் அல்லது மாவட்டம் உள்ளிட்டு உங்கள் நில விவரங்களை உடனடியாகத் தெரிந்து கொள்ளுங்கள்.',
    searchBySurveyTitle: 'சர்வே எண் மூலம் தேடுக',
    enterSurveyPlaceholder: 'சர்வே எண் உள்ளிடவும் (எ.கா. 1042)...',
    searchLandBtn: 'நிலப் பதிவுகளைத் தேடுக',
    searchingLandBtn: 'தேடப்படுகிறது...',
    filterByVillage: 'கிராமம் வாரியாக வடிகட்டவும்',
    filterByDistrict: 'மாவட்டம் வாரியாக வடிகட்டவும்',
    allVillages: 'அனைத்து கிராமங்களும்',
    allDistricts: 'அனைத்து மாவட்டங்களும்',
    searchResultsHeading: 'தேடல் முடிவுகள்',
    parcelsFoundCount: 'நிலப் பதிவுகள் கண்டறியப்பட்டன',
    noParcelsFoundTitle: 'நிலப் பதிவுகள் எதுவும் கிடைக்கவில்லை',
    noParcelsFoundDesc: 'சர்வே எண் அல்லது கிராமப் பெயரைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    parcelSurveyNo: 'சர்வே எண்',
    parcelKhasraNo: 'புல எண்',
    parcelVillage: 'கிராமம்',
    parcelDistrict: 'மாவட்டம்',
    parcelArea: 'பரப்பளவு',
    parcelLandType: 'நில வகை',
    parcelStatus: 'அதி முக்கிய நிலை',
    associatedProject: 'தொடர்புடைய திட்டம்',
    viewCadastralGis: 'GIS வரைபடத்தில் காண்க',
    viewAcquisitionCase: 'முழு வழக்கை காண்க',
    quickTipTitle: 'குடிமக்களுக்கான முக்கிய குறிப்பு',
    quickTipDesc: 'அரசிதழ் அறிவிப்பில் உள்ள பரப்பளவிற்கும் உங்கள் சான்றளிக்கப்பட்ட பட்டாவிற்கும் வேறுபாடு இருப்பின், உடனடியாக பிரிவு 15 மனு தாக்கல் செய்யவும்.',
    gisTitle: 'GIS ஊடாடும் நில வரைபட தளம்',
    gisSub: 'உங்கள் நில எல்லைகள் மற்றும் கையகப்படுத்தப்படும் வழித்தடத்தை செயற்கைக்கோள் வரைபடத்தில் காணவும்.',
    legendTitle: 'வரைபடக் குறியீடுகள்',
    legendNotified: 'அறிவிக்கப்பட்ட கையகப்படுத்தல் பகுதி',
    legendCadastral: 'சான்றளிக்கப்பட்ட நில எல்லைகள்',
    legendHighway: 'நெடுஞ்சாலை விரிவாக்க வழித்தடம்',
    legendDisputed: 'முரண்பாடு உள்ள நிலப் பகுதி',
    layerSatellite: 'செயற்கைக்கோள் காட்சி',
    layerCadastral: 'நில வரைபட எல்லைகள்',
    layerProjectCorridor: 'திட்ட கையகப்படுத்தல் எல்லை',
    parcelInfoTitle: 'தேர்ந்தெடுக்கப்பட்ட நிலப் புலத்தின் விவரங்கள்',
    clickParcelPrompt: 'விவரங்களைக் காண வரைபடத்தில் உள்ள ஏதேனும் ஒரு நிலப் புலத்தைக் கிளிக் செய்யவும்.',
    selectedSurveyNo: 'சர்வே எண்',
    selectedKhasra: 'புல எண்',
    selectedVillage: 'கிராமம்',
    selectedDistrict: 'மாவட்டம்',
    selectedRecordedArea: 'பதிவு செய்யப்பட்ட பரப்பு',
    selectedLandType: 'நில வகைப்பாடு',
    selectedStatus: 'சட்ட நிலை',
    openCaseBtn: 'முழு வழக்கை காண்க',
    measureDistance: 'தூரத்தை அளவிடு',
    resetMap: 'தொடக்க நிலைக்குத் திரும்பு',
    caseDetailTitle: 'அதிகாரப்பூர்வ நில எடுப்பு வழக்கு கோப்பு',
    caseDetailSub: 'சட்டப்பூர்வ 8 நிலைகள், இழப்பீட்டு ஆணை, ஆவணங்கள் மற்றும் குறைதீர்ப்பு நிலை.',
    caseId: 'வழக்கு எண்',
    projectTitle: 'திட்டத்தின் பெயர்',
    departmentTitle: 'பொறுப்பான துறை / முகமை',
    notifiedSectionLabel: 'அறிவிக்கப்பட்ட சட்டப்பிரிவு',
    gazetteDateLabel: 'அரசிதழ் அறிவிப்பு நாள்',
    projectDescTitle: 'திட்டத்தின் நோக்கம் & விவரங்கள்',
    financialSummaryTitle: 'சட்டப்பூர்வ நிதி இழப்பீட்டு சுருக்கம்',
    totalAssessedComp: 'நிர்ணயிக்கப்பட்ட மொத்த இழப்பீடு',
    disbursedComp: 'வழங்கப்பட்ட தொகை (DBT)',
    balanceComp: 'நிலுவையில் உள்ள தொகை',
    compensationNoticeBadge: '100% சோலேஷியம் சேர்க்கப்பட்டுள்ளது',
    discrepancyAlertSectionTitle: 'சரிபார்ப்பு முரண்பாட்டு எச்சரிக்கை',
    officialDocumentsTitle: 'சான்றளிக்கப்பட்ட வழக்கின் ஆவணங்கள்',
    noticeDocumentName: 'பிரிவு 11(1) அரசிதழ் அறிவிப்பு',
    khasraDocumentName: 'வருவாய் பட்டா சிட்டா ஆவணம்',
    awardDocumentName: 'பிரிவு 23 இழப்பீட்டு ஆணை நகல்',
    statutoryRightsTitle: 'உங்கள் சட்டப்பூர்வ உரிமைகள்',
    statutoryRightsDesc: 'RFCTLARR சட்டம் 2013 பிரிவு 15-ன் கீழ் ஆட்சேபனை தெரிவிக்கவும், பிரிவு 30-ன் கீழ் 100% சோலேஷியம் பெறவும் உங்களுக்கு முழு உரிமை உண்டு.',
    fileSection15GrievanceBtn: 'பிரிவு 15 மனு தாக்கல் செய்',
    docIntelTitle: 'ஆவண நுண்ணறிவு & AI ஆய்வு (Document Intelligence)',
    docIntelSub: 'அரசு நில எடுப்பு அறிவிப்புகள் மற்றும் பட்டா ஆவணங்களைப் பதிவேற்றி எளிய விளக்கத்தைப் பெறுங்கள்.',
    uploadNotice: 'அறிவிப்பை பதிவேற்றவும்',
    understandDocument: 'ஆவணத்தைப் புரிந்து கொள்ளுங்கள்',
    potentialDiscrepancy: 'முரண்பாடு கண்டறியப்பட்டது',
    reportDiscrepancy: 'முரண்பாட்டை தெரிவிக்கவும்',
    plainSummary: 'எளிய மொழிச் சுருக்கம்',
    aiAnalysis: 'AI சட்ட ஆய்வு',
    uploadDropzoneTitle: 'அரசிதழ் அறிவிப்பு அல்லது பட்டா நகலைப் பதிவேற்றவும் (PDF, JPG, PNG 15MB வரை)',
    uploadDropzoneSub: 'பிரிவு 11(1) பூர்வாங்க அறிவிப்பு, 7/12 பட்டா சிட்டா, பிரிவு 23 இழப்பீட்டு ஆணை',
    supportedFormatsText: 'ஆதரிக்கப்படும் ஆவணங்கள்: அரசிதழ் அறிவிப்பு, பட்டா, இழப்பீட்டு ஆணை',
    analyzingDocumentText: 'ஆவணம் OCR முறையில் வருவாய் பதிவேடுகளுடன் சரிபார்க்கப்படுகிறது...',
    sampleDocumentsTitle: 'உடனடி சரிபார்ப்பிற்கான மாதிரி ஆவணங்கள்:',
    loadSample1Title: 'பிரிவு 11(1) அரசிதழ் அறிவிப்பு — சர்வே #1042',
    loadSample1Desc: '2.73 ஹெக் vs 2.43 ஹெக் பரப்பளவு முரண்பாடு சரிபார்ப்பு',
    loadSample2Title: 'சான்றளிக்கப்பட்ட வருவாய் பட்டா — சர்வே #1042',
    loadSample2Desc: 'சான்றளிக்கப்பட்ட நில உரிமைப் பதிவு (2.43 ஹெக்)',
    analysisCompleteTitle: 'ஆவண பகுப்பாய்வு முடிந்தது',
    documentTypeLabel: 'ஆவண வகை',
    confidenceScoreLabel: 'நம்பகத்தன்மை அளவு',
    extractedInfoTitle: 'ஆவணத் தகவல்கள் & மெட்டாடேட்டா',
    notifiedAreaLabel: 'அறிவிக்கப்பட்ட பரப்பு',
    certifiedAreaLabel: 'சான்றளிக்கப்பட்ட பரப்பு',
    varianceDetectedBadge: 'பரப்பளவில் மாறுபாடு உள்ளது',
    discrepancySummaryTitle: 'சட்டப்பூர்வ முரண்பாட்டு சுருக்கம்',
    plainSummaryTitle: 'எளிய மொழி சட்ட விளக்கம் (Plain-Language Explanation)',
    actionRecommendationsTitle: 'பரிந்துரைக்கப்படும் அடுத்த கட்ட நடவடிக்கை:',
    saveToLockerBtn: 'பெட்டகத்தில் சேமி',
    fileGrievanceBtn: 'பிரிவு 15 மனு சமர்ப்பி',
    documents: 'ஆவணங்கள்',
    lockerTitle: 'டிஜிட்டல் ஆவணப் பெட்டகம் (Digital Locker)',
    lockerSub: 'சான்றளிக்கப்பட்ட அரசிதழ் அறிவிப்புகள், பட்டாக்கள் மற்றும் இழப்பீட்டு ஆணைகளின் பாதுகாப்பான களஞ்சியம்.',
    uploadNewDocBtn: 'புதிய ஆவணத்தை ஆய்வு செய்து சேர்',
    filterAllDocs: 'அனைத்து ஆவணங்களும்',
    filterNotices: 'அரசிதழ் அறிவிப்புகள்',
    filterRecords: 'வருவாய் பதிவேடுகள்',
    filterAwards: 'இழப்பீட்டு ஆணைகள்',
    docNameHeader: 'ஆவணப் பெயர்',
    docTypeHeader: 'வகை',
    docDateHeader: 'பதிவேற்றிய தேதி',
    docSizeHeader: 'அளவு',
    docActionHeader: 'செயல்',
    downloadDocBtn: 'பதிவிறக்கு',
    viewDocBtn: 'பார்வையிடு',
    noDocsInLockerTitle: 'பெட்டகத்தில் ஆவணங்கள் எதுவும் இல்லை',
    noDocsInLockerDesc: 'உங்கள் நிலம் தொடர்பான ஆவணங்களைப் பதிவேற்றி பாதுகாப்பாக வைத்துக் கொள்ளலாம்.',
    compensation: 'இழப்பீடு',
    rr: 'மறுவாழ்வு & மீள்குடியேற்றம் (R&R)',
    totalCompensation: 'மொத்த இழப்பீட்டுத் தொகை',
    solatium: '100% சோலேஷியம் (பிரிவு 30)',
    solatiumDesc: 'சட்டப்பூர்வ கட்டாய இழப்பீட்டுத் தொகை',
    dbtStatus: 'DBT நிலை (PFMS)',
    disbursedAmount: 'வழங்கப்பட்ட தொகை',
    remainingAmount: 'நிலுவைத் தொகை',
    bankAccount: 'வங்கிக் கணக்கு',
    rehabilitationBenefits: 'மறுவாழ்வுப் பலன்கள்',
    compTitle: 'சட்டப்பூர்வ இழப்பீடு & மறுவாழ்வு மதிப்பீடு',
    compSub: 'RFCTLARR சட்டம், 2013-ன் முதல் மற்றும் இரண்டாம் அட்டவணையின்படி கணக்கிடப்பட்ட வெளிப்படையான விவரங்கள்.',
    assessedCardTitle: 'நிர்ணயிக்கப்பட்ட இழப்பீடு',
    disbursedCardTitle: 'வங்கியில் செலுத்தப்பட்ட தொகை',
    pendingCardTitle: 'நிலுவையில் உள்ள தொகை',
    breakdownTitle: 'இழப்பீட்டு ஆணை விரிவான கணக்கீடு',
    breakdownSub: 'RFCTLARR சட்டம் 2013 பிரிவு 26 முதல் 30 வரையிலான சூத்திரப் படி கணக்கீடு.',
    circleRateLabel: 'வழிகாட்டி சந்தை மதிப்பு (Circle Rate)',
    multiplierFactorLabel: 'கிராமப்புறப் பெருக்கல் காரணி (Multiplier)',
    baseMarketValueLabel: 'அடிப்படை நில மதிப்பு',
    solatium100Label: '100% சோலேஷியம் (பிரிவு 30)',
    solatium100Sub: 'அடிப்படை மதிப்பிற்கு நிகரான 100% கூடுதல் தொகை',
    additionalInterestLabel: 'கூடுதல் வட்டித் தொகை (பிரிவு 30(3))',
    netAwardCompensation: 'மொத்த இழப்பீட்டு ஆணைத் தொகை',
    dbtPfmsTitle: 'PFMS நேரடிப் பணப் பரிமாற்ற விவரங்கள்',
    dbtPfmsSub: 'ஆதார் இணைக்கப்பட்ட வங்கிக் கணக்கிற்கு அரசு நேரடியாக செலுத்தும் முறை.',
    bankNameLabel: 'வங்கிப் பெயர்',
    accountNoLabel: 'கணக்கு எண்',
    ifscCodeLabel: 'IFSC குறியீடு',
    dbtStatusLabel: 'பரிவர்த்தனை நிலை',
    transactionRefLabel: 'PFMS குறிப்பு எண்',
    rrTitle: 'மறுவாழ்வு & மீள்குடியேற்றப் பலன்கள் (அட்டவணை II)',
    rrSub: 'பாதிக்கப்பட்ட குடும்பங்களுக்கான சட்டப்பூர்வ வாழ்வாதார உதவிகள்.',
    rrHouseTitle: 'மாற்று வீட்டு வசதி உதவி',
    rrHouseDesc: 'பிரதமர் ஆவாஸ் யோஜனா அல்லது கட்டப்பட்ட மாற்று குடியிருப்பு',
    rrLivelihoodTitle: 'வாழ்வாதார மானியம்',
    rrLivelihoodDesc: 'குடும்பத்திற்கு ஒருமுறை வழங்கப்படும் வாழ்வாதார உதவித் தொகை',
    rrResettlementTitle: 'இடம்பெயர்வு உதவித்தொகை',
    rrResettlementDesc: 'வீட்டு உபயோகப் பொருட்கள் மற்றும் கால்நடைகள் இடமாற்ற உதவி',
    rrSkillTitle: 'திறன் மேம்பாட்டுப் பயிற்சி',
    rrSkillDesc: 'வேலைவாய்ப்பு மற்றும் சுயதொழில் தொடங்குவதற்கான இலவசப் பயிற்சி',
    downloadScheduleBtn: 'முழு இழப்பீட்டு அட்டவணையைப் பதிவிறக்குக',
    actionCenterTitle: 'சட்டப்பூர்வ நடவடிக்கை மையம் (Action Center)',
    actionCenterSub: 'நில உரிமையாளர்கள் முடிக்க வேண்டிய கட்டாய சரிபார்ப்புகள், கூட்டு அளவீட்டு தேதிகள் மற்றும் காலக்கெடு.',
    filterAllActions: 'அனைத்து நடவடிக்கைகள்',
    filterPendingActions: 'நிலுவையில் உள்ளவை',
    filterCompletedActions: 'முடிக்கப்பட்டவை',
    actionDeadlineLabel: 'சட்டப்பூர்வ காலக்கெடு',
    statutorySectionLabel: 'சட்டப் பிரிவு',
    markCompleteBtn: 'முடிக்கப்பட்டதாகக் குறி',
    viewStepGuideBtn: 'வழிகாட்டியைக் காண்க',
    actionVerifyBoundaryTitle: 'நில எல்லை & கள அளவீட்டை சரிபார்க்கவும்',
    actionVerifyBoundaryDesc: 'கிராம நிர்வாக அலுவலர் மற்றும் நில அளவையருடன் இணைந்து கூட்டு அளவீட்டில் பங்கேற்கவும்.',
    actionSubmitBankTitle: 'ஆதார் இணைக்கப்பட்ட வங்கிக் கணக்கு விவரங்களை சமர்ப்பிக்கவும்',
    actionSubmitBankDesc: 'PFMS மூலம் DBT இழப்பீட்டைப் பெற ரத்து செய்யப்பட்ட காசோலை மற்றும் ஆதார் நகலை வழங்கவும்.',
    actionSection15Title: 'பிரிவு 15 ஆட்சேபனை தாக்கல் செய்வதற்கான இறுதி நாள்',
    actionSection15Desc: 'அரசிதழ் அறிவிப்பில் ஏதேனும் பிழை இருப்பின் 60 நாட்களுக்குள் மனு தாக்கல் செய்ய வேண்டும்.',
    noPendingActionsTitle: 'நடவடிக்கைகள் அனைத்தும் புதுப்பிப்பில் உள்ளன',
    noPendingActionsDesc: 'தற்போது உங்கள் வசம் நிலுவையில் உள்ள நடவடிக்கைகள் எதுவும் இல்லை.',
    grievances: 'குறைகள் & ஆட்சேபனைகள்',
    raiseGrievance: 'ஆட்சேபனை பதிவு செய்',
    grievanceType: 'ஆட்சேபனை வகை',
    objections: 'சட்ட ஆட்சேபனைகள்',
    grievanceTitle: 'பிரிவு 15 ஆட்சேபனை & குறைதீர்ப்பு தளம்',
    grievanceSub: 'RFCTLARR சட்டம், 2013 பிரிவு 15-ன் கீழ் நில எடுப்பு அதிகாரியிடம் நேரடியாக மனுக்களைச் சமர்ப்பிக்கவும்.',
    raiseNewGrievanceBtn: 'புதிய ஆட்சேபனை பதிவு செய்க',
    myGrievancesListTitle: 'என் மனுக்கள் மற்றும் அதிகாரியின் தீர்வுகள் பதிவேடு',
    newGrievanceFormTitle: 'சட்டப்பூர்வ பிரிவு 15 ஆட்சேபனைப் படிவம்',
    newGrievanceFormSub: 'உங்கள் ஆட்சேபனை விவரங்களைத் துல்லியமாக உள்ளிட்டு நில எடுப்பு அதிகாரிக்கு அனுப்பவும்.',
    selectCaseLabel: 'வழக்கைத் தேர்ந்தெடுக்கவும்',
    grievanceCategoryLabel: 'ஆட்சேபனைப் பிரிவு',
    catWrongArea: 'நிலப் பரப்பளவு முரண்பாடு (Wrong Area Measurement)',
    catCompensation: 'இழப்பீட்டுத் தொகை மதிப்பீட்டு ஆட்சேபனை (Compensation Issue)',
    catSolatium: 'சோலேஷியம் மற்றும் வட்டி கணக்கீட்டுப் பிழை (Solatium Issue)',
    catDbt: 'DBT வங்கிக் கணக்கு வரவு சிக்கல் (PFMS DBT Issue)',
    catRR: 'மறுவாழ்வு & மீள்குடியேற்ற உதவி கோருதல் (R&R Entitlement)',
    catDelay: 'காலதாமதம் மற்றும் அளவீட்டு ஆட்சேபனை (Process Delay)',
    catOther: 'பிற சட்ட விளக்கக் கோரிக்கைகள் (Other Legal Request)',
    grievanceSubjectLabel: 'மனுவின் தலைப்பு / பொருள் *',
    grievanceSubjectPlaceholder: 'எ.கா. அரசிதழ் அறிவிப்பு மற்றும் வருவாய் பதிவேட்டிற்கு இடையேயான பரப்பு முரண்பாடு (சர்வே #1042)...',
    grievanceDescLabel: 'ஆட்சேபனையின் விரிவான காரணங்கள் & விவரங்கள் *',
    grievanceDescPlaceholder: 'உங்கள் ஆட்சேபனையைத் தெளிவாக விவரிக்கவும். எ.கா. அரசிதழ் அறிவிப்பில் 2.73 ஹெக் உள்ளது, ஆனால் சான்றளிக்கப்பட்ட பட்டாவில் 2.43 ஹெக் மட்டுமே உள்ளது. கள அளவீடு கோரப்படுகிறது.',
    attachNoticeLabel: 'சான்று ஆவணங்களை இணைக்கவும்',
    submitGrievanceBtn: 'நில எடுப்பு அதிகாரிக்கு மனுவை சமர்ப்பிக்கவும்',
    submittingGrievanceBtn: 'மனு சமர்ப்பிக்கப்படுகிறது...',
    cancelGrievanceBtn: 'படிவத்தை மூடுக',
    grievanceSuccessToast: 'ஆட்சேபனை வெற்றிகரமாகப் பதிவு செய்யப்பட்டது! சட்டப்பூர்வ கண்காணிப்பு எண்:',
    ticketNoHeader: 'மனு எண்',
    ticketCategoryHeader: 'பிரிவு',
    ticketDateHeader: 'பதிவு செய்த தேதி',
    ticketStatusHeader: 'நிலை',
    ticketOfficerResponseHeader: 'நில எடுப்பு அதிகாரியின் உத்தியோகபூர்வ ஆணை',
    noGrievancesTitle: 'பதிவு செய்யப்பட்ட ஆட்சேபனைகள் எதுவும் இல்லை',
    noGrievancesDesc: 'ஏதேனும் பிழைகள் இருப்பின் புதிய ஆட்சேபனையைப் பதிவு செய்யலாம்.',
    notifications: 'அறிவிப்புகள்',
    notificationsTitle: 'அதிகாரப்பூர்வ அறிவிப்புகள் & எச்சரிக்கைகள் பதிவு',
    notificationsSub: 'விசாரணை தேதிகள், அதிகாரி தீர்ப்புகள் மற்றும் DBT இழப்பீட்டு வரவு பற்றிய உடனடி தகவல்கள்.',
    markAllReadBtn: 'அனைத்தையும் வாசித்ததாகக் குறி',
    filterAllNotices: 'அனைத்து அறிவிப்புகளும்',
    filterUnreadNotices: 'படிக்காதவை மட்டும்',
    hearingNoticeTitle: 'பிரிவு 15 பொது விசாரணை அறிவிப்பு',
    hearingNoticeDesc: 'சர்வே #1042 தொடர்பான ஆட்சேபனை விசாரணை சார் ஆட்சியர் அலுவலகத்தில் நடைபெற உள்ளது.',
    gazetteNoticeTitle: 'பிரிவு 11(1) பூர்வாங்க அரசிதழ் அறிவிப்பு வெளியிடப்பட்டது',
    gazetteNoticeDesc: 'தேசிய நெடுஞ்சாலை விரிவாக்கத் திட்டத்திற்கான நில எடுப்பு அறிவிப்பு வெளியிடப்பட்டது.',
    dbtNoticeTitle: 'PFMS DBT இழப்பீட்டுத் தொகை விடுவிக்கப்பட்டது',
    dbtNoticeDesc: 'சான்றளிக்கப்பட்ட நில உரிமையாளர்களுக்கு அரசு இழப்பீட்டுத் தொகையை வங்கியில் வரவு வைத்துள்ளது.',
    viewNoticeCaseBtn: 'தொடர்புடைய வழக்கைக் காண்க',
    noNotificationsTitle: 'புதிய அறிவிப்புகள் எதுவும் இல்லை',
    noNotificationsDesc: 'தற்போது உங்களுக்கு வரவிருக்கும் எச்சரிக்கைகள் எதுவும் இல்லை.',
    officerDashTitle: 'நில எடுப்பு அதிகாரி (LAO) பணியிடம்',
    officerDashSub: 'வழக்குகள் ஆய்வு, பிரிவு 15 ஆட்சேபனை தீர்வு மற்றும் இழப்பீட்டு ஆணை மேலாண்மை.',
    metricTotalCases: 'மொத்த செயலில் உள்ள வழக்குகள்',
    metricPendingVerification: 'கள அளவீட்டு சரிபார்ப்பு நிலுவை',
    metricDisbursedAmount: 'வழங்கப்பட்ட DBT இழப்பீடு',
    metricOpenGrievances: 'நிலுவையில் உள்ள ஆட்சேபனைகள்',
    quickCaseReviewTitle: 'ஆய்விற்குரிய நில எடுப்பு வழக்குகள்',
    recentGrievancesTitle: 'பிரிவு 15 ஆட்சேபனை விசாரணை வரிசை',
    reviewCaseBtn: 'வழக்கை ஆய்வு செய்க',
    scheduleHearingBtn: 'விசாரணை தேதியை நிர்ணயி',
    approveVerificationBtn: 'எல்லை அளவீட்டை அங்கீகரி',
    rejectGrievanceBtn: 'மனுவை நிராகரி',
    resolveGrievanceBtn: 'தீர்வு ஆணை வெளியிடுக',
    officerCasesTitle: 'திட்ட நில எடுப்பு வழக்குகள் முதன்மைப் பதிவேடு',
    officerCasesSub: 'அரசிதழ் அறிவிப்புகள், கள அளவீடுகள் மற்றும் இழப்பீட்டு ஆணைகளின் அதிகாரப்பூர்வ தகவல் தளம்.',
    searchCasePlaceholder: 'வழக்கு எண், சர்வே எண் அல்லது பட்டாதாரர் பெயர் கொண்டு தேடுக...',
    filterAllStages: 'அனைத்து சட்ட நிலைகளும்',
    stageVerification: 'சரிபார்ப்பு நிலை',
    stageHearing: 'பிரிவு 15 விசாரணை',
    stageAward: 'பிரிவு 23 இழப்பீட்டு ஆணை',
    stagePayment: 'DBT பணப் பரிமாற்றம்',
    stagePossession: 'நிலம் ஒப்படைப்பு',
    caseOfficerNotesLabel: 'அதிகாரியின் தீர்ப்பு & ஆணை விவரங்கள்',
    saveStatusUpdateBtn: 'நிலை மாற்றத்தை உறுதி செய்',
    noticeLabel: 'முக்கிய அறிவிப்பு:',
    tickerAdvisory: 'குடிமக்கள் அறிவிப்பு: உங்கள் நிலத்தின் இழப்பீடு மற்றும் வழக்குகளின் நிலையை இணையத்தில் சரிபார்க்கலாம்.',
    tickerDocIntel: 'புதிய வசதி: அரசு அரசிதழ் அறிவிப்பை பதிவேற்றி AI மூலம் எளிய மொழி விளக்கத்தைப் பெறுங்கள்.',
    tickerObjections: 'சட்ட எச்சரிக்கை: பிரிவு 11(1) வெளியான 60 நாட்களுக்குள் பிரிவு 15 ஆட்சேபனைகளை சமர்ப்பிக்கவும்.',
    tickerDbt: 'PFMS DBT: இழப்பீட்டுத் தொகை நேரடியாக ஆதார் இணைக்கப்பட்ட வங்கிக் கணக்கில் வரவு வைக்கப்படும்.',
    footerTagline: 'நில எடுப்பு, இழப்பீடு மற்றும் மறுவாழ்வுக்கான வெளிப்படையான தேசிய தளம்',
    footerDescription: 'நில எடுப்பில் நியாயமான இழப்பீடு மற்றும் வெளிப்படைத்தன்மை உரிமை சட்டம், 2013 (RFCTLARR)-ன் கீழ் இயங்கும் குடிமக்கள் தகவல் அமைப்பு.',
    footerHelplineLabel: 'தேசிய நில உரிமைகள் உதவி எண்:',
    footerServicesTitle: 'குடிமக்கள் சேவைகள்',
    footerServiceFindLand: 'நிலத்தைக் கண்டறிதல்',
    footerServiceDocIntel: 'ஆவண நுண்ணறிவு',
    footerServiceGis: 'GIS நில வரைபடம்',
    footerServiceComp: 'இழப்பீட்டு மதிப்பீடு',
    footerServiceActions: 'நடவடிக்கை மையம்',
    footerServiceGrievances: 'பிரிவு 15 ஆட்சேபனைகள்',
    footerStatutoryTitle: 'சட்டப்பூர்வ இணக்கம்',
    footerStatutoryAct: 'RFCTLARR சட்டம், 2013',
    footerStatutorySec11: 'பிரிவு 11(1) பூர்வாங்க அறிவிப்பு',
    footerStatutorySec15: 'பிரிவு 15 ஆட்சேபனை உரிமை',
    footerStatutorySec19: 'பிரிவு 19 இறுதிப் பிரகடனம்',
    footerStatutorySec23: 'பிரிவு 23 இழப்பீட்டு ஆணை',
    footerStatutoryPfms: 'PFMS நேரடிப் பணப் பரிமாற்றம்',
    footerAssistanceTitle: 'உதவி & தொடர்பு',
    footerAddress: 'மத்திய நில வருவாய் & நெடுஞ்சாலைத்துறை ஆணையம், புதுதில்லி',
    footerTollFree: 'இலவச உதவி: 1800-180-LAND (5263)',
    footerEmail: 'மின்னஞ்சல்: support@sahaay.gov.in',
    footerCopyright: '© 2026 சஹாய் (SAHAAY) • இந்திய அரசு. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    footerDemoDisclaimer: 'இந்த தளம் மாதிரி தரவுகளைக் கொண்ட அதிகாரப்பூர்வ நடைமுறைப் பதிப்பாகும்.',
  };

  writeLocale('ta', 'Tamil (தமிழ்)', t);
}

// Execute generator
generateTamil();
