import { writeLocale, allKeys } from './locale-base.js';
import { TranslationSchema } from '../src/locales/types.js';

// ============================================================================
// 1. TELUGU (తెలుగు - te)
// ============================================================================
export function generateTelugu() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: 'సహాయ్ (SAHAAY)',
    emblemLetter: 'స',
    tagline: 'మీ భూమి. మీ కేసు. మీ హక్కు.',
    heroSub: 'భూసేకరణ మరియు చట్టబద్ధమైన పరిహారం కోసం పౌర సహాయ పోర్టల్',
    portalSubtitle: 'భూమి • పరిహారం • పునరావాసం • ఫిర్యాదులు • కేసు ట్రాకింగ్',
    citizenPortal: 'పౌర పోర్టల్',
    officerPortal: 'భూసేకరణ అధికారి పోర్టల్',
    demoMode: 'డెమో మోడ్ సక్రియంగా ఉంది',
    signIn: 'లాగిన్ అవ్వండి',
    signOut: 'లాగ్ అవుట్',
    landowner: 'భూ యజమాని',
    landOfficer: 'భూసేకరణ అధికారి (LAO)',
    switchRole: 'పాత్ర మార్చు',
    switchCitizen: 'పౌరుడు (రాజేష్ శర్మ)',
    switchOfficer: 'భూసేకరణ అధికారి (విక్రమ్ చౌహాన్)',
    welcomeBack: 'తిరిగి స్వాగతం',
    navHome: 'హోమ్',
    navFindLand: 'నా భూమిని కనుగొనండి',
    navGisMap: 'GIS భూమి పటం',
    navDocIntel: 'పత్ర విశ్లేషణ (AI)',
    navCompensation: 'పరిహారం & పునరావాసం (R&R)',
    navDocuments: 'పత్రాల లాకర్',
    navActionCenter: 'చర్య కేంద్రం',
    navGrievances: 'ఫిర్యాదులు & వివాదాలు',
    navNotices: 'నోటీసులు & హెచ్చరికలు',
    navOfficerDashboard: 'అధికారి డ్యాష్‌బోర్డ్',
    navCasesRegistry: 'కేసుల రిజిస్ట్రీ',
    navGrievancesQueue: 'ఫిర్యాదుల క్యూ',
    citizenServices: 'పౌర భూసేవలు',
    quickActions: 'త్వరిత చర్యలు',
    submit: 'సమర్పించండి',
    save: 'భద్రపరచండి',
    cancel: 'రద్దు చేయండి',
    edit: 'సవరించండి',
    delete: 'తొలగించండి',
    search: 'శోధించండి',
    filter: 'ఫిల్టర్',
    back: 'వెనుకకు',
    next: 'తరువాత',
    close: 'మూసివేయండి',
    view: 'వీక్షించండి',
    download: 'డౌన్‌లోడ్',
    upload: 'అప్‌లోడ్ చేయండి',
    export: 'ఎగుమతి',
    refresh: 'రిఫ్రెష్',
    print: 'ప్రింట్ చేయండి',
    loading: 'లోడ్ అవుతోంది...',
    actions: 'చర్యలు',
    details: 'వివరాలు',
    status: 'స్థితి',
    viewDetails: 'వివరాలు చూడండి',
    viewOnMap: 'మ్యాప్‌లో చూడండి',
    viewCase: 'పూర్తి కేసు చూడండి',
    trackProgress: 'పురోగతిని ట్రాక్ చేయండి',
    proceed: 'కొనసాగించండి',
    confirm: 'నిర్ధారించండి',
    retry: 'మళ్లీ ప్రయత్నించండి',
    clearAll: 'అన్నీ క్లియర్ చేయండి',
    applyFilter: 'ఫిల్టర్ వర్తింపజేయండి',
    active: 'సక్రియం',
    pending: 'పెండింగ్‌లో ఉంది',
    completed: 'పూర్తయింది',
    rejected: 'తిరస్కరించబడింది',
    verified: 'ధృవీకరించబడింది',
    underReview: 'సమీక్షలో ఉంది',
    urgent: 'అత్యవసరం',
    optional: 'ఐచ్ఛికం',
    required: 'తప్పనిసరి',
    discrepancy: 'వ్యత్యాసం కనుగొనబడింది',
    findMyLand: 'నా భూమిని కనుగొనండి',
    myLand: 'నా భూమి',
    surveyNo: 'సర్వే నంబర్ / ప్లాట్ నంబర్',
    enterSurveyNo: 'ఉదా. 1042 లేదా 45/A నమోదు చేయండి',
    village: 'గ్రామం',
    district: 'జిల్లా',
    state: 'రాష్ట్రం',
    taluka: 'తాలూకా / మండలం',
    selectState: 'రాష్ట్రాన్ని ఎంచుకోండి',
    selectDistrict: 'జిల్లాను ఎంచుకోండి',
    selectVillage: 'గ్రామాన్ని ఎంచుకోండి',
    recordedArea: 'రికార్డ్ చేయబడిన విస్తీర్ణం',
    acquiredArea: 'సేకరించబడిన విస్తీర్ణం',
    remainingArea: 'మిగిలిన విస్తీర్ణం',
    landClassification: 'భూమి వర్గీకరణ',
    ownershipType: 'యాజమాన్య రకం',
    marketValueRate: 'మార్కెట్ విలువ రేటు',
    hectares: 'హెక్టార్లు',
    acres: 'ఎకరాలు',
    sqMeters: 'చదరపు మీటర్లు',
    parcelStatus: 'భూమి పార్సెల్ స్థితి',
    searchLandPrompt: 'మీ నోటీసులో ఉన్న సర్వే వివరాలను నమోదు చేసి స్థితిని కనుగొనండి',
    searchLandBtn: 'భూమి వివరాలను శోధించండి',
    noLandFound: 'ఈ వివరాలతో ఎలాంటి భూమి రికార్డు కనుగొనబడలేదు.',
    searchPlaceholder: 'సర్వే నం, గ్రామం లేదా నోటీస్ ID ద్వారా శోధించండి...',
    exactMatchFound: 'ఖచ్చితమైన సరిపోలిక కనుగొనబడింది',
    gisMapTitle: 'ఇంటరాక్టివ్ GIS ప్రాజెక్ట్ సరిహద్దు & పార్సెల్ మ్యాప్',
    gisMapDesc: 'సేకరణ అలైన్‌మెంట్, ప్రభావిత సరిహద్దులు మరియు పరిసర ప్రాంతాలను చూడండి',
    satelliteView: 'శాటిలైట్ వీక్షణ',
    streetView: 'వీధి వీక్షణ',
    topographyView: 'టోపోగ్రఫీ వీక్షణ',
    legend: 'మ్యాప్ సూచిక',
    acquiredZone: 'నోటిఫై చేయబడిన సేకరణ జోన్',
    bufferZone: 'బఫర్ / ప్రభావ ప్రాంతం',
    yourParcel: 'మీ సర్వే చేయబడిన పార్సెల్',
    adjacentParcels: 'పక్కనే ఉన్న పార్సెల్‌లు',
    zoomIn: 'జూమ్ ఇన్',
    zoomOut: 'జూమ్ అవుట్',
    resetView: 'వీక్షణను రీసెట్ చేయండి',
    fullscreen: 'పూర్తి స్క్రీన్',
    parcelId: 'పార్సెల్ ID',
    coordinates: 'భౌగోళిక కోఆర్డినేట్లు',
    distanceToProject: 'ప్రాజెక్ట్ అలైన్‌మెంట్‌కు దూరం',
    measurementTool: 'కొలత సాధనం',
    mapLayers: 'మ్యాప్ లేయర్‌లు',
    overlayCadastral: 'రెవెన్యూ క్యాడస్ట్రల్ మ్యాప్‌ను అమర్చండి',
    totalCompensation: 'మొత్తం నిర్ణయించబడిన పరిహారం',
    assessedValue: 'మూల భూమి నిర్ధారణ విలువ',
    solatium: '100% సోలేషియం (చట్టబద్ధమైన ప్రోత్సాహకం)',
    solatiumDesc: 'RFCTLARR చట్టం 2013 సెక్షన్ 30(1) ప్రకారం 100% తప్పనిసరి పరిహారం',
    interestAmount: 'అదనపు వడ్డీ & అనుబంధ భత్యం',
    structureValue: 'కట్టడాలు / చెట్లు / ఆస్తుల పరిహారం',
    calculatedTotal: 'మొత్తం చెల్లించవలసిన పరిహార మొత్తం',
    paymentStatus: 'PFMS చెల్లింపు పంపిణీ స్థితి',
    dbtStatus: 'DBT బ్యాంక్ ఖాతా లింకేజ్ స్థితి',
    disbursed: 'ఖాతాలో జమ చేయబడింది',
    disbursedAmount: 'జమ చేయబడిన మొత్తం',
    remainingAmount: 'మిగిలిన బ్యాలెన్స్ మొత్తం',
    bankAccount: 'లింక్ చేయబడిన బ్యాంక్ ఖాతా',
    ifscCode: 'IFSC కోడ్',
    paymentRefNo: 'PFMS / ట్రెజరీ లావాదేవీ నంబర్',
    claimCompensation: 'క్లెయిమ్ అప్లికేషన్ సమర్పించండి',
    downloadAwardLetter: 'అవార్డు ఆర్డర్ డౌన్‌లోడ్ చేయండి (ఫారం 11)',
    rrTitle: 'పునరావాసం మరియు పునఃస్థాపన (R&R) ప్రయోజనాలు',
    rrEntitlement: 'R&R అర్హత ప్యాకేజీ',
    rrStatus: 'పునరావాస అమలు స్థితి',
    resettlementHouse: 'ప్రత్యామ్నాయ గృహం / స్థలం కేటాయింపు',
    subsistenceGrant: 'జీవనాధార గ్రాంట్ (నెలవారీ చెల్లింపు)',
    transportAllowance: 'తరలింపు & రవాణా భత్యం',
    trainingSkill: 'నైపుణ్య శిక్షణ / ఉపాధి సహాయం',
    rrOfficerAssigned: 'కేటాయించబడిన R&R నోడల్ అధికారి',
    rrTimeline: 'R&R పురోగతి కాలక్రమం',
    docIntelTitle: 'ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ పత్ర విశ్లేషణ ఇంజిన్',
    docIntelSub: 'ప్రభుత్వ భూసేకరణ నోటీసులు, ఫారాలు మరియు గెజిట్ ఆర్డర్‌లను స్కాన్ చేసి విశ్లేషిస్తుంది',
    uploadNotice: 'నోటీస్ లేదా అవార్డు పత్రాన్ని అప్‌లోడ్ చేయండి',
    dragDropDoc: 'PDF, JPG లేదా PNG పత్రాన్ని ఇక్కడ లాగండి లేదా బ్రౌజ్ చేయండి',
    supportedFormats: 'మద్దతు ఉన్న ఫార్మాట్‌లు: PDF, JPEG, PNG (గరిష్ట పరిమాణం: 25MB)',
    analyzingDoc: 'పత్రంలోని సమాచారాన్ని AI విశ్లేషిస్తోంది...',
    extractedData: 'పత్రం నుండి వెలికితీసిన ముఖ్య సమాచారం',
    legalClause: 'వర్తించే చట్టం & సెక్షన్',
    section4_1: 'సెక్షన్ 4(1) - ప్రాథమిక నోటిఫికేషన్',
    section11_1: 'సెక్షన్ 11(1) - ప్రాథమిక సర్వే నోటిఫికేషన్',
    section19_1: 'సెక్షన్ 19(1) - సేకరణ ప్రకటన',
    section21_2: 'సెక్షన్ 21(2) - ప్రజా విచారణ నోటీసు',
    section23: 'సెక్షన్ 23 - కలెక్టర్ తుది అవార్డు',
    potentialDiscrepancy: 'తీవ్రమైన వ్యత్యాసం / అభ్యంతరం గుర్తించబడింది',
    discrepancyFound: 'నోటీసు వివరాలు మరియు భూ రికార్డు మధ్య తేడా ఉంది',
    discrepancyDesc: 'నోటీసులోని విస్తీర్ణం అధికారిక రెవెన్యూ రికార్డు కంటే భిన్నంగా ఉంది. వెంటనే అభ్యంతరం దాఖలు చేయండి.',
    reportDiscrepancy: 'అభ్యంతరం / ఫిర్యాదు నమోదు చేయండి',
    aiConfidenceScore: 'AI విశ్లేషణ విశ్వసనీయత రేటింగ్',
    plainLanguageSummary: 'సాధారణ భాషా సారాంశం',
    actionDeadline: 'చర్య తీసుకోవడానికి గడువు తేదీ',
    documentLocker: 'డిజిటల్ పత్రాల ఖజానా',
    allDocuments: 'అన్ని ధృవీకరించబడిన పత్రాలు',
    verifiedDocuments: 'అధికారికంగా ఆమోదించబడిన పత్రాలు',
    pendingVerification: 'ధృవీకరణ పెండింగ్‌లో ఉన్న పత్రాలు',
    uploadNewDoc: 'కొత్త పత్రాన్ని అప్‌లోడ్ చేయండి',
    docType: 'పత్రం రకం',
    selectDocType: 'పత్రం రకాన్ని ఎంచుకోండి',
    docLandTitle: 'భూమి యాజమాన్య పత్రం (పట్టాదారు పాస్‌బుక్ / 7-12)',
    docGovNotice: 'ప్రభుత్వ సేకరణ నోటీసు',
    docIdentityProof: 'గుర్తింపు రుజువు (ఆధార్ / పాన్ కార్డ్)',
    docBankPassbook: 'బ్యాంక్ పాస్‌బుక్ రద్దు చేసిన చెక్కు',
    docGrievanceProof: 'ఫిర్యాదు మద్దతు పత్రం',
    fileSize: 'ఫైల్ పరిమాణం',
    uploadDate: 'అప్‌లోడ్ చేసిన తేదీ',
    viewDoc: 'పత్రాన్ని వీక్షించండి',
    downloadDoc: 'పత్రాన్ని డౌన్‌లోడ్ చేయండి',
    deleteDoc: 'పత్రాన్ని తొలగించండి',
    confirmDeleteDoc: 'మీరు నిజంగా ఈ పత్రాన్ని తొలగించాలనుకుంటున్నారా?',
    grievancesTitle: 'పౌర ఫిర్యాదులు & వివాద పరిష్కార వ్యవస్థ',
    submitGrievance: 'కొత్త ఫిర్యాదును నమోదు చేయండి',
    grievanceType: 'ఫిర్యాదు రకం',
    selectGrievanceType: 'ఫిర్యాదు వర్గాన్ని ఎంచుకోండి',
    typeCompensationAmount: 'పరిహార మొత్తం లెక్కింపుపై వివాదం',
    typeAreaDiscrepancy: 'సర్వే విస్తీర్ణం కొలతలో వ్యత్యాసం',
    typeOwnershipDispute: 'యాజమాన్య హక్కు లేదా పేరు దిద్దుబాటు',
    typePaymentDelay: 'పరిహార చెల్లింపు పంపిణీ ఆలస్యం',
    typeRRNonReceipt: 'పునరావాస ప్రయోజనాలు అందకపోవడం',
    typeOther: 'ఇతర పరిపాలనా సమస్యలు',
    grievanceSubject: 'ఫిర్యాదు ముఖ్యాంశం',
    grievanceDesc: 'ఫిర్యాదు యొక్క పూర్తి వివరాలు',
    grievanceDescPlaceholder: 'మీ సమస్యను స్పష్టంగా వివరించండి...',
    attachEvidence: 'మద్దతు పత్రాలను జత చేయండి',
    grievanceStatus: 'ఫిర్యాదు పరిష్కార స్థితి',
    ticketNumber: 'ఫిర్యాదు టోకెన్ సంఖ్య',
    assignedToOfficer: 'కేటాయించబడిన పరిష్కార అధికారి',
    expectedResolutionDate: 'ఆశించిన పరిష్కార తేదీ',
    hearingDate: 'వ్యక్తిగత విచారణ షెడ్యూల్',
    officerRemarks: 'అధికారి అధికారిక వ్యాఖ్యలు',
    resolutionSummary: 'తుది పరిష్కార సారాంశం',
    actionCenterTitle: 'పౌర కార్యాచరణ కేంద్రం & చట్టబద్ధమైన గడువులు',
    pendingActions: 'మీరు పూర్తి చేయవలసిన పనులు',
    completedActions: 'పూర్తయిన పనులు',
    urgentDeadlines: 'చట్టబద్ధమైన కాలపరిమితి హెచ్చరికలు',
    actObjectionPeriod: 'సెక్షన్ 15(1) కింద అభ్యంతరం దాఖలు చేయడానికి 60 రోజుల గడువు',
    actSubmitBankDocs: 'పరిహార చెల్లింపు కోసం బ్యాంక్ వివరాలు సమర్పించండి',
    actAttendHearing: 'జిల్లా కలెక్టర్ ప్రజా విచారణకు హాజరుకావాలి',
    markCompleted: 'పూర్తయినట్లు గుర్తించండి',
    daysRemaining: 'రోజులు మిగిలి ఉన్నాయి',
    expiredDeadline: 'గడువు ముగిసింది',
    notificationTitle: 'నోటిఫికేషన్లు & అధికారిక ప్రకటనలు',
    allNotifications: 'అన్ని నోటిఫికేషన్లు',
    unreadOnly: 'చదవనివి మాత్రమే',
    markAllRead: 'అన్నీ చదివినట్లు గుర్తించండి',
    noNotifications: 'ప్రస్తుతం ఎలాంటి కొత్త నోటిఫికేషన్లు లేవు.',
    officerTitle: 'భూసేకరణ అధికారి (LAO) పరిపాలనా నియంత్రణ కేంద్రం',
    officerCasesRegistry: 'ప్రాజెక్ట్ సేకరణ కేసుల మాస్టర్ రిజిస్ట్రీ',
    totalAcquisitions: 'మొత్తం సేకరణ ప్రాజెక్టులు',
    activeParcels: 'సక్రియ సర్వే పార్సెల్‌లు',
    totalDisbursedBudget: 'మొత్తం పంపిణీ చేసిన బడ్జెట్',
    pendingApprovals: 'ఆమోదం కోసం పెండింగ్‌లో ఉన్న ఫైళ్లు',
    caseId: 'సేకరణ కేసు ID',
    caseName: 'ప్రాజెక్ట్ సేకరణ పేరు',
    affectedLandowners: 'ప్రభావిత భూ యజమానులు',
    stage: 'ప్రస్తుత చట్టబద్ధమైన దశ',
    stage1_Survey: 'దశ 1: సామాజిక ప్రభావ అంచనా & సర్వే',
    stage2_Notification: 'దశ 2: సెక్షన్ 11(1) ప్రాథమిక నోటిఫికేషన్',
    stage3_Objections: 'దశ 3: సెక్షన్ 15 విచారణ & అభ్యంతరాలు',
    stage4_Declaration: 'దశ 4: సెక్షన్ 19 సేకరణ ప్రకటన',
    stage5_Award: 'దశ 5: సెక్షన్ 23 అవార్డు & పరిహార నిర్ణయం',
    stage6_Payment: 'దశ 6: PFMS పరిహార పంపిణీ',
    stage7_Possession: 'దశ 7: భూమి స్వాధీనం & R&R అమలు',
    approve: 'ఆమోదించండి',
    reject: 'తిరస్కరించండి',
    forwardToUpper: 'ఉన్నతాధికారికి పంపండి',
    scheduleHearing: 'విచారణ తేదీని నిర్ణయించండి',
    issueNotice: 'చట్టబద్ధమైన నోటీసు జారీ చేయండి',
    disburseFunds: 'నిధులను విడుదల చేయండి',
    officerRemarksPlaceholder: 'అధికారిక పరిశీలన నోట్స్ నమోదు చేయండి...',
    saveDecision: 'నిర్ణయాన్ని భద్రపరచండి',
    step: 'దశ',
    of: 'యొక్క',
    surveyRequired: 'సర్వే నంబర్ అవసరం',
    enterValidSurvey: 'దయచేసి సరైన సర్వే నంబర్ నమోదు చేయండి',
    villageRequired: 'గ్రామం పేరు అవసరం',
    districtRequired: 'జిల్లా పేరు అవసరం',
    compensationBreakdown: 'పరిహార పూర్తి వివరాల విభజన',
    marketValueCalculated: 'లెక్కింపబడిన మూల భూమి విలువ',
    multiplicationFactor: 'గ్రామీణ గుణకం కారకం (RFCTLARR షెడ్యూల్ 1)',
    additionalAssetValuation: 'చెట్లు, బావులు, భవనాల లెక్కింపు విలువ',
    statutoryInterest: 'సెక్షన్ 30(3) కింద 12% అదనపు వార్షిక వడ్డీ',
    netEntitlement: 'మొత్తం నికర చెల్లింపు మొత్తం',
    readyForPFMS: 'PFMS ద్వారా చెల్లింపుకు సిద్ధంగా ఉంది',
    disbursementHistory: 'గతంలో జమ చేసిన లావాదేవీల చరిత్ర',
    noDisbursementsYet: 'ఇంకా ఎలాంటి నిధులు జమ చేయబడలేదు.',
    compensationDisputeHelp: 'లెక్కింపుపై అభ్యంతరం ఉంటే ల్యాండ్ అథారిటీ (LARR) కు రిఫర్ చేయవచ్చు.',
    trackDisbursement: 'PFMS పోర్టల్‌లో లావాదేవీని ట్రాక్ చేయండి',
    viewAllNotices: 'అన్ని అధికారిక గెజిట్ నోటీసులను చూడండి',
    noActionsPending: 'ప్రస్తుతం మీ వైపు ఎలాంటి పెండింగ్ పనులు లేవు.',
    officerQueueEmpty: 'ప్రస్తుతం పెండింగ్ కేసుల జాబితా ఖాళీగా ఉంది.',
    discrepancyResolution: 'వ్యత్యాస పరిష్కార చర్య',
    fileAppeal: 'ల్యాండ్ అక్విజిషన్ అథారిటీ (LARRA) వద్ద అప్పీల్ దాఖలు చేయండి',
    disputeDeadlineWarning: 'గమనిక: అవార్డు జారీ అయిన 60 రోజుల్లోపు మాత్రమే అప్పీల్ దాఖలు చేయాలి.',
    noticeDetails: 'నోటీసు యొక్క పూర్తి వివరాలు',
    gazetteDate: 'గెజిట్ ప్రచురణ తేదీ',
    competentAuthority: 'సమర్థ అధికారి (CALA / SDO)',
    projectAlignmentMap: 'జాతీయ హైవే / రైల్వే అలైన్‌మెంట్ పటం',
    surveyBoundaries: 'రెవెన్యూ సర్వే సరిహద్దులు',
    parcelAreaMismatch: 'సర్వే నంబర్ వైశాల్యంలో వ్యత్యాసం ఉంది',
    expectedArea: 'రెవెన్యూ రికార్డు వైశాల్యం',
    noticeArea: 'సేకరణ నోటీసులో పేర్కొన్న వైశాల్యం',
    difference: 'తేడా',
    takeImmediateAction: 'వెంటనే చర్య తీసుకోండి',
    appealPeriodActive: 'అప్పీల్ సమయం నడుస్తోంది',
    appealDaysLeft: 'అప్పీల్ దాఖలుకు మిగిలిన రోజులు',
    submitClaimDocuments: 'క్లెయిమ్ పత్రాలను వెంటనే సమర్పించండి',
    uploadSuccess: 'పత్రం విజయవంతంగా అప్‌లోడ్ చేయబడింది!',
    uploadFailure: 'పత్రం అప్‌లోడ్ విఫలమైంది. మళ్లీ ప్రయత్నించండి.',
    deleteConfirmTitle: 'పత్రాన్ని తొలగించాలా?',
    deleteConfirmDesc: 'ఈ పత్రాన్ని తొలగిస్తే తిరిగి పొందలేరు.',
    grievanceSubmittedSuccess: 'మీ ఫిర్యాదు విజయవంతంగా నమోదు చేయబడింది!',
    grievanceTrackingTip: 'మీ ఫిర్యాదు పురోగతిని ట్రాక్ చేయడానికి టోకెన్ సంఖ్యను భద్రపరుచుకోండి.',
    hearingScheduledAlert: 'వ్యక్తిగత విచారణ తేదీ ఖరారు చేయబడింది.',
    attendHearingNotice: 'దయచేసి సంబంధిత పత్రాలతో సమయానికి హాజరుకావాలి.',
    contactHelpdesk: 'సహాయ కేంద్రం సంప్రదించండి',
    tollFreeNumber: 'టోల్ ఫ్రీ నంబర్: 1800-111-9999',
    helpdeskTiming: 'సోమవారం నుండి శనివారం, ఉదయం 9 నుండి సాయంత్రం 6 వరకు',
    faqTitle: 'తరచుగా అడిగే ప్రశ్నలు (FAQ)',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'నిబంధనలు మరియు షరతులు',
    accessibilityStatement: 'యాక్సెసిబిలిటీ ప్రకటన',
    govtOfIndia: 'భారత ప్రభుత్వం',
    ministryOfRuralDev: 'గ్రామీణాభివృద్ధి మరియు భూవనరుల మంత్రిత్వ శాఖ',
    allRightsReserved: 'సర్వహక్కులు ప్రత్యేకించబడ్డాయి.',
    disclaimer: 'ఈ పోర్టల్ సమాచార పారదర్శకత కొరకు మాత్రమే. అధికారిక వివాదాలకు గెజిట్ నోటిఫికేషన్లే ప్రామాణికం.',
    heroTitle: 'మీ భూమికి సంబంధించి ఏమి జరుగుతుందో తెలుసుకోండి.',
    heroDesc: 'భూసేకరణ ప్రక్రియను పారదర్శకంగా ట్రాక్ చేయండి, 100% సోలేషియంతో సరైన పరిహారం పొందండి మరియు మీ సమస్యలను సులభంగా పరిష్కరించుకోండి.',
    findLandBtn: 'నా భూమిని కనుగొనండి',
    trackCaseBtn: 'కేసును ట్రాక్ చేయండి',
    understandDocBtn: 'పత్రాన్ని విశ్లేషించండి',
    exploreMapBtn: 'భూమి మ్యాప్ చూడండి',
    tickerAdvisory: 'పౌర సమాచారం: భూసేకరణ నోటీసు వచ్చిన 60 రోజుల్లోపు సెక్షన్ 15(1) కింద అభ్యంతరాలు దాఖలు చేయవచ్చు.',
    noticeLabel: 'తాజా నోటీస్:',
    feature1Title: 'ఖచ్చితమైన భూమి శోధన',
    feature1Desc: 'సర్వే నంబర్ ద్వారా మీ భూమి సరిహద్దులు, విస్తీర్ణం మరియు ప్రస్తుత స్థితిని వెంటనే తెలుసుకోండి.',
    feature2Title: 'స్మార్ట్ పత్ర విశ్లేషణ',
    feature2Desc: 'నోటీసులలో ఉన్న చట్టపరమైన అంశాలు, తేడాలు మరియు ముఖ్య తేదీలను AI ద్వారా సులభంగా అర్థం చేసుకోండి.',
    feature3Title: '100% పరిహార పారదర్శకత',
    feature3Desc: 'RFCTLARR చట్టం ప్రకారం పూర్తి సోలేషియం, వడ్డీ మరియు DBT పంపిణీ వివరాలను పారదర్శకంగా తనిఖీ చేయండి.',
    feature4Title: 'సులభమైన వివాద పరిష్కారం',
    feature4Desc: 'విస్తీర్ణం లేదా పరిహారంలో తేడాలు ఉంటే నేరుగా అధికారులకు ఫిర్యాదు చేసి పరిష్కారం పొందండి.',
    compensation: 'పరిహారం',
    rr: 'పునరావాసం (R&R)',
    documents: 'పత్రాలు',
    grievances: 'ఫిర్యాదులు',
    actionRequired: 'చర్య అవసరం',
    inProgress: 'పురోగతిలో ఉంది',
    helpdesk: 'సహాయ కేంద్రం',
    dashboard: 'డ్యాష్‌బోర్డ్',
    home: 'హోమ్',
    profile: 'ప్రొఫైల్',
    settings: 'సెట్టింగ్‌లు',
    notifications: 'నోటిఫికేషన్‌లు',
    logout: 'లాగ్ అవుట్',
    login: 'లాగిన్',
    email: 'ఈమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    register: 'నమోదు చేసుకోండి',
    rememberMe: 'నన్ను గుర్తుంచుకో',
    citizenLogin: 'పౌర లాగిన్',
    officerLogin: 'అధికారి లాగిన్',
    demoCredentials: 'డెమో ఆధారాలు',
    enterEmail: 'మీ ఈమెయిల్ నమోదు చేయండి',
    enterPassword: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    welcomeCitizen: 'పౌర స్వాగతం',
    welcomeOfficer: 'అధికారి స్వాగతం',
    quickStats: 'త్వరిత గణాంకాలు',
    totalCases: 'మొత్తం కేసులు',
    resolvedCases: 'పరిష్కరించబడిన కేసులు',
    pendingReviews: 'పెండింగ్ సమీక్షలు',
    myParcels: 'నా భూమి పార్సెల్‌లు',
    caseTimeline: 'కేసు కాలక్రమం',
    recentActivity: 'ఇటీవలి కార్యకలాపాలు',
    downloadReport: 'నివేదికను డౌన్‌లోడ్ చేయండి',
    filterByStatus: 'స్థితి ఆధారంగా ఫిల్టర్ చేయండి',
    allStatuses: 'అన్ని స్థితులు',
    sortBy: 'క్రమబద్ధీకరించు',
    newestFirst: 'సరికొత్తది ముందుగా',
    oldestFirst: 'పురాతనమైనది ముందుగా',
    name: 'పేరు',
    phone: 'ఫోన్ నంబర్',
    address: 'చిరునామా',
    remarks: 'వ్యాఖ్యలు',
    category: 'వర్గం',
    date: 'తేదీ',
    time: 'సమయం',
    type: 'రకం',
    viewAll: 'అన్నీ చూడండి',
    clearFilters: 'ఫిల్టర్‌లను తొలగించండి',
    resultsFound: 'ఫలితాలు కనుగొనబడ్డాయి',
    noResults: 'ఎలాంటి ఫలితాలు కనుగొనబడలేదు',
    fileUploadSuccess: 'ఫైల్ విజయవంతంగా అప్‌లోడ్ చేయబడింది',
    fileUploadError: 'ఫైల్ అప్‌లోడ్ చేయడంలో లోపం సంభవించింది',
    fileDeleted: 'ఫైల్ తొలగించబడింది',
    changesSaved: 'మార్పులు విజయవంతంగా భద్రపరచబడ్డాయి',
    actionSuccess: 'చర్య విజయవంతంగా పూర్తయింది',
    actionFailed: 'చర్య విఫలమైంది',
    sessionExpired: 'సెషన్ ముగిసింది, దయచేసి మళ్లీ లాగిన్ అవ్వండి',
    unauthorized: 'అనధికార ప్రాప్యత',
    serverError: 'సర్వర్ లోపం సంభవించింది, దయచేసి తర్వాత ప్రయత్నించండి',
    networkError: 'నెట్‌వర్క్ కనెక్షన్ లోపం',
    tryAgain: 'మళ్లీ ప్రయత్నించండి',
    goBack: 'వెనుకకు వెళ్లండి',
    goToHome: 'హోమ్‌కి వెళ్లండి',
    viewMore: 'మరిన్ని చూడండి',
    viewLess: 'తక్కువ చూడండి',
    copied: 'కాపీ చేయబడింది!',
    copyToClipboard: 'క్లిప్‌బోర్డ్‌కి కాపీ చేయండి',
    yes: 'అవును',
    no: 'కాదు',
    ok: 'సరే',
    help: 'సహాయం',
    feedback: 'అభిప్రాయం',
    contactUs: 'మమ్మల్ని సంప్రదించండి',
    aboutUs: 'మా గురించి',
    version: 'వెర్షన్',
    systemStatus: 'సిస్టమ్ స్థితి',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    connecting: 'కనెక్ట్ అవుతోంది...',
    syncing: 'సమకాలీకరిస్తోంది...',
    lastUpdated: 'చివరిగా నవీకరించబడింది',
    justNow: 'ఇప్పుడే',
    minutesAgo: 'నిమిషాల క్రితం',
    hoursAgo: 'గంటల క్రితం',
    daysAgo: 'రోజుల క్రితం',
    readMore: 'మరింత చదవండి',
    showMore: 'మరిన్ని చూపించు',
    showLess: 'తక్కువ చూపించు',
    selectAll: 'అన్నీ ఎంచుకోండి',
    deselectAll: 'అన్నింటినీ తీసివేయండి',
    expandAll: 'అన్నీ విస్తరించండి',
    collapseAll: 'అన్నీ కుదించండి',
    openInNewTab: 'కొత్త ట్యాబ్‌లో తెరవండి',
    previous: 'మునుపటి',
    pageOf: 'పేజీ',
    rowsPerPage: 'పేజీకి వరుసలు',
    totalRecords: 'మొత్తం రికార్డులు',
    noRecordsFound: 'రికార్డులు ఏవీ కనుగొనబడలేదు',
    pleaseWait: 'దయచేసి వేచి ఉండండి...',
    somethingWentWrong: 'ఏదో తప్పు జరిగింది',
    fieldRequired: 'ఈ ఫీల్డ్ తప్పనిసరి',
    invalidEmail: 'సరైన ఈమెయిల్ చిరునామాను నమోదు చేయండి',
    invalidPhone: 'సరైన 10 అంకెల ఫోన్ నంబర్‌ను నమోదు చేయండి',
    passwordTooShort: 'పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి',
    passwordsDoNotMatch: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
    termsAgreement: 'నేను నిబంధనలు మరియు షరతులను అంగీకరిస్తున్నాను',
    agreeToTerms: 'కొనసాగడానికి దయచేసి నిబంధనలను అంగీకరించండి',
    selectLanguage: 'భాషను ఎంచుకోండి',
    currentLanguage: 'ప్రస్తుత భాష',
    languageChanged: 'భాష విజయవంతంగా మార్చబడింది',
    autoDetectLocation: 'స్థానాన్ని స్వయంచాలకంగా గుర్తించండి',
    locationAccessDenied: 'స్థాన అనుమతి నిరాకరించబడింది',
    useManualSearch: 'దయచేసి మాన్యువల్ శోధనను ఉపయోగించండి',
    satelliteLayer: 'శాటిలైట్ లేయర్',
    cadastralLayer: 'క్యాడస్ట్రల్ లేయర్',
    projectBufferLayer: 'ప్రాజెక్ట్ బఫర్ లేయర్',
    measuringDistance: 'దూరాన్ని కొలుస్తోంది',
    measuringArea: 'వైశాల్యాన్ని కొలుస్తోంది',
    clickToMeasure: 'కొలవడం ప్రారంభించడానికి మ్యాప్‌పై క్లిక్ చేయండి',
    clearMeasurement: 'కొలతను క్లియర్ చేయండి',
    totalDistance: 'మొత్తం దూరం',
    totalArea: 'మొత్తం వైశాల్యం',
    meters: 'మీటర్లు',
    kilometers: 'కిలోమీటర్లు',
    discrepancyDetails: 'వ్యత్యాస వివరాలు',
    affectedSections: 'ప్రభావిత విభాగాలు',
    recommendedAction: 'సిఫార్సు చేయబడిన చర్య',
    fileGrievanceNow: 'ఇప్పుడే అధికారిక ఫిర్యాదు చేయండి',
    viewDiscrepancyReport: 'వ్యత్యాస నివేదికను చూడండి',
    aiConfidence: 'AI విశ్వసనీయత స్థాయి',
    highConfidence: 'అధిక విశ్వసనీయత (95%+)',
    mediumConfidence: 'మధ్యస్థ విశ్వసనీయత',
    lowConfidence: 'తక్కువ విశ్వసనీయత',
    extractedEntities: 'వెలికితీసిన అంశాలు',
    officialGazetteNo: 'అధికారిక గెజిట్ సంఖ్య',
    notificationDate: 'నోటిఫికేషన్ తేదీ',
    competentAuthorityName: 'సమర్థ ప్రాధికారిక అధికారి పేరు',
    hearingVenue: 'ప్రజా విచారణ వేదిక',
    objectionDeadlineDate: 'అభ్యంతరాల సమర్పణ తుది తేదీ',
    documentVerifiedBadge: 'అధికారికంగా ధృవీకరించబడింది',
    documentPendingBadge: 'ధృవీకరణ పురోగతిలో ఉంది',
    documentRejectedBadge: 'పత్రం తిరస్కరించబడింది',
    reuploadDocument: 'పత్రాన్ని మళ్లీ అప్‌లోడ్ చేయండి',
    reasonForRejection: 'తిరస్కరణకు కారణం',
    downloadCertificate: 'ధృవీకరణ పత్రాన్ని డౌన్‌లోడ్ చేయండి',
    shareDocument: 'పత్రాన్ని భాగస్వామ్యం చేయండి',
    printSummary: 'సారాంశాన్ని ప్రింట్ చేయండి',
    directBenefitTransfer: 'ప్రత్యక్ష నగదు బదిలీ (DBT)',
    pfmsTrackingStatus: 'PFMS చెల్లింపు ట్రాకింగ్',
    bankAccountVerified: 'బ్యాంక్ ఖాతా ధృవీకరించబడింది',
    bankAccountPending: 'బ్యాంక్ ఖాతా ధృవీకరణ పెండింగ్‌లో ఉంది',
    treasuryRefNumber: 'ట్రెజరీ సూచన సంఖ్య',
    disbursementDate: 'నిధుల విడుదల తేదీ',
    installmentNumber: 'వాయిదా సంఖ్య',
    partialPayment: 'పాక్షిక చెల్లింపు',
    fullPayment: 'పూర్తి చెల్లింపు',
    solatiumAmount: 'సోలేషియం మొత్తం (100%)',
    baseCompensation: 'ప్రాథమిక భూమి పరిహారం',
    statutoryInterestValue: 'చట్టబద్ధమైన వడ్డీ మొత్తం',
    totalAwardAmount: 'మొత్తం అవార్డు మొత్తం',
    displacedFamilyId: 'నిరాశ్రయులైన కుటుంబ ID',
    resettlementSiteName: 'పునరావాస కాలనీ పేరు',
    plotAllotmentStatus: 'ప్లాట్ కేటాయింపు స్థితి',
    housingGrantStatus: 'గృహ నిర్మాణ గ్రాంట్ స్థితి',
    annuityBenefitStatus: 'నెలవారీ పెన్షన్ / యాన్యుటీ స్థితి',
    skillTrainingStatus: 'నైపుణ్య అభివృద్ధి శిక్షణ స్థితి',
    livelihoodGrant: 'జీవనోపాధి పునరుద్ధరణ గ్రాంట్',
    officerCaseManagement: 'కేసు నిర్వహణ నియంత్రణ',
    citizenGrievanceQueue: 'పౌర ఫిర్యాదుల సమీక్ష క్యూ',
    hearingManagement: 'విచారణల నిర్వహణ',
    awardDrafting: 'అవార్డు తయారీ & ఆమోదం',
    fundSanction: 'నిధుల మంజూరు & పంపిణీ',
    reportsAndAnalytics: 'నివేదికలు & విశ్లేషణలు',
    bulkNoticeGeneration: 'బల్క్ నోటీసుల జారీ',
    cadastralSync: 'రెవెన్యూ క్యాడస్ట్రల్ సమకాలీకరణ',
    exportToExcel: 'ఎక్సెల్ ఫార్మాట్‌లో డౌన్‌లోడ్ చేయండి',
    exportToPdf: 'PDF నివేదికను డౌన్‌లోడ్ చేయండి',
    auditLog: 'సిస్టమ్ ఆడిట్ లాగ్',
    loginHistory: 'లాగిన్ చరిత్ర',
    officerBadge: 'అధికారిక అధికారి హోదా',
    citizenBadge: 'ధృవీకరించబడిన పౌరుడు',
    stepCompleted: 'ఈ దశ పూర్తయింది',
    stepInProgress: 'ఈ దశ పురోగతిలో ఉంది',
    stepPending: 'ఈ దశ పెండింగ్‌లో ఉంది',
    timelineOverview: 'మొత్తం సేకరణ కాలక్రమం సమగ్ర వీక్షణ',
    legalDisclaimer: 'చట్టపరమైన హెచ్చరిక: ఈ సమాచారం పోర్టల్ ద్వారా పౌరుల సౌలభ్యం కొరకు అందించబడుతుంది. అధికారిక ఉత్తర్వులే తుది తీర్పు.',
    closeModal: 'విండోను మూసివేయండి',
    viewReceipt: 'రసీదును వీక్షించండి',
    downloadReceipt: 'రసీదును డౌన్‌లోడ్ చేయండి',
    sendSMSAlert: 'SMS హెచ్చరిక పంపండి',
    sendEmailAlert: 'ఈమెయిల్ హెచ్చరిక పంపండి',
    optOutOfAlerts: 'హెచ్చరికలను నిలిపివేయండి',
    helpdeskSupport: '24/7 పౌర హెల్ప్‌లైన్ సహాయం',
    quickGuide: 'త్వరిత వినియోగ గైడ్',
    termsText: 'సహాయ్ పోర్టల్ నియమ నిబంధనలకు లోబడి పనిచేస్తుంది.',
  };

  writeLocale('te', 'తెలుగు', t);
}

// ============================================================================
// 2. KANNADA (ಕನ್ನಡ - kn)
// ============================================================================
export function generateKannada() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: 'ಸಹಾಯ್ (SAHAAY)',
    emblemLetter: 'ಸ',
    tagline: 'ನಿಮ್ಮ ಭೂಮಿ. ನಿಮ್ಮ ಪ್ರಕರಣ. ನಿಮ್ಮ ಹಕ್ಕು.',
    heroSub: 'ಭೂಸ್ವಾಧೀನ ಮತ್ತು ಶಾಸನಬದ್ಧ ಪರಿಹಾರಕ್ಕಾಗಿ ನಾಗರಿಕ ಮಾಹಿತಿ ಪೋರ್ಟಲ್',
    portalSubtitle: 'ಭೂಮಿ • ಪರಿಹಾರ • ಪುನರ್ವಸತಿ • ಕುಂದುಕೊರತೆಗಳು • ಪ್ರಕರಣ ಟ್ರ್ಯಾಕಿಂಗ್',
    citizenPortal: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    officerPortal: 'ಭೂಸ್ವಾಧೀನ ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್',
    demoMode: 'ಡೆಮೊ ಮೋಡ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    signIn: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signOut: 'ಸೈನ್ ಔಟ್',
    landowner: 'ಭೂಮಾಲೀಕ',
    landOfficer: 'ಭೂಸ್ವಾಧೀನ ಅಧಿಕಾರಿ (LAO)',
    switchRole: 'ಪಾತ್ರ ಬದಲಾಯಿಸಿ',
    switchCitizen: 'ನಾಗರಿಕ (ರಾಜೇಶ್ ಶರ್ಮಾ)',
    switchOfficer: 'ಭೂಸ್ವಾಧೀನ ಅಧಿಕಾರಿ (ವಿಕ್ರಮ್ ಚೌಹಾಣ್)',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ',
    navHome: 'ಮುಖಪುಟ',
    navFindLand: 'ನನ್ನ ಭೂಮಿ ಹುಡುಕಿ',
    navGisMap: 'GIS ಭೂ ನಕ್ಷೆ',
    navDocIntel: 'ದಾಖಲೆ ವಿಶ್ಲೇಷಣೆ (AI)',
    navCompensation: 'ಪರಿಹಾರ & ಪುನರ್ವಸತಿ (R&R)',
    navDocuments: 'ದಾಖಲೆಗಳ ಕೋಶ',
    navActionCenter: 'ಕ್ರಮ ಕೇಂದ್ರ',
    navGrievances: 'ಕುಂದುಕೊರತೆ & ವ್ಯಾಜ್ಯಗಳು',
    navNotices: 'ನೋಟಿಸ್ & ಎಚ್ಚರಿಕೆಗಳು',
    navOfficerDashboard: 'ಅಧಿಕಾರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    navCasesRegistry: 'ಪ್ರಕರಣಗಳ ನೋಂದಣಿ',
    navGrievancesQueue: 'ದೂರುಗಳ ಸರತಿ ಸಾಲು',
    citizenServices: 'ನಾಗರಿಕ ಭೂ ಸೇವೆಗಳು',
    quickActions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    submit: 'ಸಲ್ಲಿಸಿ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    edit: 'ತಿದ್ದುಪಡಿ',
    delete: 'ಅಳಿಸಿ',
    search: 'ಹುಡುಕಿ',
    filter: 'ಫಿಲ್ಟರ್',
    back: 'ಹಿಂದಕ್ಕೆ',
    next: 'ಮುಂದೆ',
    close: 'ಮುಚ್ಚಿ',
    view: 'ವೀಕ್ಷಿಸಿ',
    download: 'ಡೌನ್‌ಲೋಡ್',
    upload: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    export: 'ರಫ್ತು ಮಾಡಿ',
    refresh: 'ರಿಫ್ರೆಶ್',
    print: 'ಮುದ್ರಿಸಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    actions: 'ಕ್ರಮಗಳು',
    details: 'ವಿವರಗಳು',
    status: 'ಸ್ಥಿತಿ',
    viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    viewOnMap: 'ನಕ್ಷೆಯಲ್ಲಿ ನೋಡಿ',
    viewCase: 'ಪೂರ್ಣ ಪ್ರಕರಣ ವೀಕ್ಷಿಸಿ',
    trackProgress: 'ಪ್ರಗತಿ ಪರಿಶೀಲಿಸಿ',
    proceed: 'ಮುಂದುವರಿಯಿರಿ',
    confirm: 'ಖಚಿತಪಡಿಸಿ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    clearAll: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    applyFilter: 'ಫಿಲ್ಟರ್ ಅನ್ವಯಿಸಿ',
    active: 'ಸಕ್ರಿಯ',
    pending: 'ಬಾಕಿ ಉಳಿದಿದೆ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    verified: 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    underReview: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    urgent: 'ತುರ್ತು',
    optional: 'ಐಚ್ಛಿಕ',
    required: 'ಅಗತ್ಯವಿದೆ',
    discrepancy: 'ವ್ಯತ್ಯಾಸ ಪತ್ತೆಯಾಗಿದೆ',
    findMyLand: 'ನನ್ನ ಭೂಮಿ ಹುಡುಕಿ',
    myLand: 'ನನ್ನ ಭೂಮಿ',
    surveyNo: 'ಸರ್ವೇ ನಂಬರ್ / ಪ್ಲಾಟ್ ನಂಬರ್',
    enterSurveyNo: 'ಉದಾ. 1042 ಅಥವಾ 45/A ನಮೂದಿಸಿ',
    village: 'ಗ್ರಾಮ',
    district: 'ಜಿಲ್ಲೆ',
    state: 'ರಾಜ್ಯ',
    taluka: 'ತಾಲೂಕು',
    selectState: 'ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ',
    selectDistrict: 'ಜಿಲ್ಲೆ ಆಯ್ಕೆಮಾಡಿ',
    selectVillage: 'ಗ್ರಾಮ ಆಯ್ಕೆಮಾಡಿ',
    recordedArea: 'ದಾಖಲಿತ ವಿಸ್ತೀರ್ಣ',
    acquiredArea: 'ಸ್ವಾಧೀನಪಡಿಸಿಕೊಂಡ ವಿಸ್ತೀರ್ಣ',
    remainingArea: 'ಉಳಿದ ವಿಸ್ತೀರ್ಣ',
    landClassification: 'ಭೂಮಿ ವರ್ಗೀಕರಣ',
    ownershipType: 'ಮಾಲೀಕತ್ವದ ಪ್ರಕಾರ',
    marketValueRate: 'ಮಾರುಕಟ್ಟೆ ಮೌಲ್ಯ ದರ',
    hectares: 'ಹೆಕ್ಟೇರ್',
    acres: 'ಎಕರೆ',
    sqMeters: 'ಚದರ ಮೀಟರ್',
    parcelStatus: 'ಭೂ ಪಾರ್ಸೆಲ್ ಸ್ಥಿತಿ',
    searchLandPrompt: 'ನಿಮ್ಮ ನೋಟಿಸ್‌ನಲ್ಲಿರುವ ಸರ್ವೇ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
    searchLandBtn: 'ಭೂಮಿ ವಿವರಗಳನ್ನು ಹುಡುಕಿ',
    noLandFound: 'ಈ ವಿವರಗಳೊಂದಿಗೆ ಯಾವುದೇ ಭೂ ದಾಖಲೆ ಕಂಡುಬಂದಿಲ್ಲ.',
    searchPlaceholder: 'ಸರ್ವೇ ನಂ, ಗ್ರಾಮ ಅಥವಾ ನೋಟಿಸ್ ID ಮೂಲಕ ಹುಡುಕಿ...',
    exactMatchFound: 'ನಿಖರವಾದ ಹೊಂದಾಣಿಕೆ ಕಂಡುಬಂದಿದೆ',
    gisMapTitle: 'ಇಂಟರಾಕ್ಟಿವ್ GIS ಯೋಜನಾ ಗಡಿ & ನಕ್ಷೆ',
    gisMapDesc: 'ಸ್ವಾಧೀನ ಮಾರ್ಗ, ಬಾಧಿತ ಗಡಿಗಳು ಮತ್ತು ಸುತ್ತಮುತ್ತಲಿನ ಪ್ರದೇಶಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    satelliteView: 'ಉಪಗ್ರಹ ನೋಟ',
    streetView: 'ರಸ್ತೆ ನೋಟ',
    topographyView: 'ಸ್ಥಳಾಕೃತಿ ನೋಟ',
    legend: 'ನಕ್ಷೆ ಸೂಚ್ಯಂಕ',
    acquiredZone: 'ಅಧಿಸೂಚಿತ ಸ್ವಾಧೀನ ವಲಯ',
    bufferZone: 'ಬಫರ್ / ಪ್ರಭಾವಿತ ವಲಯ',
    yourParcel: 'ನಿಮ್ಮ ಸರ್ವೇ ಪಾರ್ಸೆಲ್',
    adjacentParcels: 'ಪಕ್ಕದ ಪಾರ್ಸೆಲ್‌ಗಳು',
    zoomIn: 'ಝೂಮ್ ಇನ್',
    zoomOut: 'ಝೂಮ್ ಔಟ್',
    resetView: 'ವೀಕ್ಷಣೆ ಮರುಹೊಂದಿಸಿ',
    fullscreen: 'ಪೂರ್ಣ ಪರದೆ',
    parcelId: 'ಪಾರ್ಸೆಲ್ ID',
    coordinates: 'ಭೌಗೋಳಿಕ ನಿರ್ದೇಶಾಂಕಗಳು',
    distanceToProject: 'ಯೋಜನಾ ಮಾರ್ಗಕ್ಕೆ ಇರುವ ದೂರ',
    measurementTool: 'ಅಳತೆ ಸಾಧನ',
    mapLayers: 'ನಕ್ಷೆ ಪದರಗಳು',
    overlayCadastral: 'ಕಂದಾಯ ನಕ್ಷೆಯನ್ನು ಅಳವಡಿಸಿ',
    totalCompensation: 'ಒಟ್ಟು ನಿರ್ಧರಿಸಲಾದ ಪರಿಹಾರ',
    assessedValue: 'ಮೂಲ ಭೂ ಮೌಲ್ಯಮಾಪನ',
    solatium: '100% ಸೋಲೇಟಿಯಮ್ (ಕಡ್ಡಾಯ ಸಾಂತ್ವನ ಮೊತ್ತ)',
    solatiumDesc: 'RFCTLARR ಕಾಯ್ದೆ 2013 ರ ಕಲಂ 30(1) ರ ಪ್ರಕಾರ 100% ಕಡ್ಡಾಯ ಪರಿಹಾರ',
    interestAmount: 'ಹೆಚ್ಚುವರಿ ಬಡ್ಡಿ ಮತ್ತು ಭತ್ಯೆ',
    structureValue: 'ಕಟ್ಟಡಗಳು / ಮರಗಳು / ಆಸ್ತಿಗಳ ಪರಿಹಾರ',
    calculatedTotal: 'ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಪರಿಹಾರ ಮೊತ್ತ',
    paymentStatus: 'PFMS ಪಾವತಿ ವಿತರಣಾ ಸ್ಥಿತಿ',
    dbtStatus: 'DBT ಬ್ಯಾಂಕ್ ಖಾತೆ ಜೋಡಣೆ ಸ್ಥಿತಿ',
    disbursed: 'ಖಾತೆಗೆ ಜಮೆ ಮಾಡಲಾಗಿದೆ',
    disbursedAmount: 'ಜಮೆಯಾದ ಮೊತ್ತ',
    remainingAmount: 'ಬಾಕಿ ಉಳಿದ ಮೊತ್ತ',
    bankAccount: 'ಜೋಡಿಸಲಾದ ಬ್ಯಾಂಕ್ ಖಾತೆ',
    ifscCode: 'IFSC ಕೋಡ್',
    paymentRefNo: 'PFMS / ಖಜಾನೆ ವಹಿವಾಟು ಸಂಖ್ಯೆ',
    claimCompensation: 'ಪರಿಹಾರ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    downloadAwardLetter: 'ಅವಾರ್ಡ್ ಆದೇಶ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (ಫಾರ್ಮ್ 11)',
    rrTitle: 'ಪುನರ್ವಸತಿ ಮತ್ತು ಪುನರ್ವ್ಯವಸ್ಥಾಪನೆ (R&R) ಸೌಲಭ್ಯಗಳು',
    rrEntitlement: 'R&R ಹಕ್ಕುಗಳ ಪ್ಯಾಕೇಜ್',
    rrStatus: 'ಪುನರ್ವಸತಿ ಜಾರಿ ಸ್ಥಿತಿ',
    resettlementHouse: 'ಪರ್ಯಾಯ ಮನೆ / ನಿವೇಶನ ಹಂಚಿಕೆ',
    subsistenceGrant: 'ಜೀವನಾಧಾರ ಅನುದಾನ (ಮಾಸಿಕ ಪಾವತಿ)',
    transportAllowance: 'ಸ್ಥಳಾಂತರ & ಸಾರಿಗೆ ಭತ್ಯೆ',
    trainingSkill: 'ಕೌಶಲ್ಯ ತರಬೇತಿ / ಉದ್ಯೋಗ ನೆರವು',
    rrOfficerAssigned: 'ನಿಯೋಜಿತ R&R ನೋಡಲ್ ಅಧಿಕಾರಿ',
    rrTimeline: 'R&R ಪ್ರಗತಿ ಕಾಲಮಿತಿ',
    docIntelTitle: 'ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ ದಾಖಲೆ ವಿಶ್ಲೇಷಣಾ ಇಂಜಿನ್',
    docIntelSub: 'ಸರ್ಕಾರಿ ಭೂಸ್ವಾಧೀನ ನೋಟಿಸ್‌ಗಳು ಮತ್ತು ಗೆಜೆಟ್ ಆದೇಶಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ವಿಶ್ಲೇಷಿಸುತ್ತದೆ',
    uploadNotice: 'ನೋಟಿಸ್ ಅಥವಾ ಅವಾರ್ಡ್ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    dragDropDoc: 'PDF, JPG ಅಥವಾ PNG ಫೈಲ್ ಅನ್ನು ಇಲ್ಲಿ ಎಳೆಯಿರಿ ಅಥವಾ ಬ್ರೌಸ್ ಮಾಡಿ',
    supportedFormats: 'ಬೆಂಬಲಿತ ಮಾದರಿಗಳು: PDF, JPEG, PNG (ಗರಿಷ್ಠ ಗಾತ್ರ: 25MB)',
    analyzingDoc: 'ದಾಖಲೆಯ ವಿವರಗಳನ್ನು AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
    extractedData: 'ದಾಖಲೆಯಿಂದ ಹೊರತೆಗೆಯಲಾದ ಪ್ರಮುಖ ಮಾಹಿತಿ',
    legalClause: 'ಅನ್ವಯವಾಗುವ ಕಾಯ್ದೆ & ಕಲಂ',
    section4_1: 'ಕಲಂ 4(1) - ಪ್ರಾಥಮಿಕ ಅಧಿಸೂಚನೆ',
    section11_1: 'ಕಲಂ 11(1) - ಪ್ರಾಥಮಿಕ ಸರ್ವೇ ಅಧಿಸೂಚನೆ',
    section19_1: 'ಕಲಂ 19(1) - ಸ್ವಾಧೀನ ಘೋಷಣೆ',
    section21_2: 'ಕಲಂ 21(2) - ಸಾರ್ವಜನಿಕ ವಿಚಾರಣೆ ನೋಟಿಸ್',
    section23: 'ಕಲಂ 23 - ಜಿಲ್ಲಾಧಿಕಾರಿ ಅಂತಿಮ ಅವಾರ್ಡ್',
    potentialDiscrepancy: 'ಗಂಭೀರ ವ್ಯತ್ಯಾಸ / ಆಕ್ಷೇಪಣೆ ಪತ್ತೆಯಾಗಿದೆ',
    discrepancyFound: 'ನೋಟಿಸ್ ವಿವರ ಮತ್ತು ಭೂ ದಾಖಲೆ ನಡುವೆ ವ್ಯತ್ಯಾಸವಿದೆ',
    discrepancyDesc: 'ನೋಟಿಸ್‌ನಲ್ಲಿರುವ ವಿಸ್ತೀರ್ಣ ಕಂದಾಯ ದಾಖಲೆಗಿಂತ ಭಿನ್ನವಾಗಿದೆ. ತಕ್ಷಣ ಆಕ್ಷೇಪಣೆ ಸಲ್ಲಿಸಿ.',
    reportDiscrepancy: 'ಆಕ್ಷೇಪಣೆ / ದೂರು ದಾಖಲಿಸಿ',
    aiConfidenceScore: 'AI ವಿಶ್ಲೇಷಣಾ ನಿಖರತೆ ರೇಟಿಂಗ್',
    plainLanguageSummary: 'ಸರಳ ಭಾಷೆಯ ಸಾರಾಂಶ',
    actionDeadline: 'ಕ್ರಮ ಕೈಗೊಳ್ಳಲು ಕೊನೆಯ ದಿನಾಂಕ',
    documentLocker: 'ಡಿಜಿಟಲ್ ದಾಖಲೆಗಳ ಭಂಡಾರ',
    allDocuments: 'ಎಲ್ಲಾ ಪರಿಶೀಲಿಸಿದ ದಾಖಲೆಗಳು',
    verifiedDocuments: 'ಅಧಿಕೃತವಾಗಿ ಅಂಗೀಕೃತ ದಾಖಲೆಗಳು',
    pendingVerification: 'ಪರಿಶೀಲನೆ ಬಾಕಿ ಇರುವ ದಾಖಲೆಗಳು',
    uploadNewDoc: 'ಹೊಸ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    docType: 'ದಾಖಲೆಯ ಪ್ರಕಾರ',
    selectDocType: 'ದಾಖಲೆಯ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ',
    docLandTitle: 'ಭೂ ಮಾಲೀಕತ್ವದ ದಾಖಲೆ (ಪಹಣಿ / RTC / ಪಟ್ಟಾ)',
    docGovNotice: 'ಸರ್ಕಾರಿ ಭೂಸ್ವಾಧೀನ ನೋಟಿಸ್',
    docIdentityProof: 'ಗುರುತಿನ ಚೀಟಿ (ಆಧಾರ್ / ಪ್ಯಾನ್)',
    docBankPassbook: 'ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್ / ರದ್ದಾದ ಚೆಕ್',
    docGrievanceProof: 'ಕುಂದುಕೊರತೆ ಪೂರಕ ದಾಖಲೆ',
    fileSize: 'ಫೈಲ್ ಗಾತ್ರ',
    uploadDate: 'ಅಪ್‌ಲೋಡ್ ದಿನಾಂಕ',
    viewDoc: 'ದಾಖಲೆ ವೀಕ್ಷಿಸಿ',
    downloadDoc: 'ದಾಖಲೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    deleteDoc: 'ದಾಖಲೆ ಅಳಿಸಿ',
    confirmDeleteDoc: 'ನೀವು ನಿಜವಾಗಿಯೂ ಈ ದಾಖಲೆಯನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?',
    grievancesTitle: 'ನಾಗರಿಕ ಕುಂದುಕೊರತೆ & ವ್ಯಾಜ್ಯ ಪರಿಹಾರ ವ್ಯವಸ್ಥೆ',
    submitGrievance: 'ಹೊಸ ದೂರು ದಾಖಲಿಸಿ',
    grievanceType: 'ದೂರಿನ ಪ್ರಕಾರ',
    selectGrievanceType: 'ದೂರಿನ ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    typeCompensationAmount: 'ಪರಿಹಾರ ಮೊತ್ತ ಲೆಕ್ಕಾಚಾರದ ಕುರಿತು ಆಕ್ಷೇಪಣೆ',
    typeAreaDiscrepancy: 'ಸರ್ವೇ ವಿಸ್ತೀರ್ಣ ಅಳತೆಯಲ್ಲಿ ವ್ಯತ್ಯಾಸ',
    typeOwnershipDispute: 'ಮಾಲೀಕತ್ವ ಹಕ್ಕು ಅಥವಾ ಹೆಸರು ತಿದ್ದುಪಡಿ',
    typePaymentDelay: 'ಪರಿಹಾರ ಪಾವತಿ ವಿತರಣೆಯಲ್ಲಿ ವಿಳಂಬ',
    typeRRNonReceipt: 'ಪುನರ್ವಸತಿ ಸೌಲಭ್ಯಗಳು ಸಿಗದಿರುವುದು',
    typeOther: 'ಇತರ ಆಡಳಿತಾತ್ಮಕ ಸಮಸ್ಯೆಗಳು',
    grievanceSubject: 'ದೂರಿನ ವಿಷಯ',
    grievanceDesc: 'ದೂರಿನ ಸಂಪೂರ್ಣ ವಿವರಣೆ',
    grievanceDescPlaceholder: 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರವಾಗಿ ಬರೆಯಿರಿ...',
    attachEvidence: 'ಪೂರಕ ಪುರಾವೆಗಳನ್ನು ಲಗತ್ತಿಸಿ',
    grievanceStatus: 'ದೂರು ಪರಿಹಾರದ ಸ್ಥಿತಿ',
    ticketNumber: 'ದೂರು ಟೋಕನ್ ಸಂಖ್ಯೆ',
    assignedToOfficer: 'ನಿಯೋಜಿತ ಪರಿಹಾರ ಅಧಿಕಾರಿ',
    expectedResolutionDate: 'ನಿರೀಕ್ಷಿತ ಪರಿಹಾರ ದಿನಾಂಕ',
    hearingDate: 'ವೈಯಕ್ತಿಕ ವಿಚಾರಣೆ ದಿನಾಂಕ',
    officerRemarks: 'ಅಧಿಕಾರಿಯ ಅಧಿಕೃತ ಟಿಪ್ಪಣಿಗಳು',
    resolutionSummary: 'ಅಂತಿಮ ಪರಿಹಾರದ ಸಾರಾಂಶ',
    actionCenterTitle: 'ನಾಗರಿಕ ಕ್ರಮ ಕೇಂದ್ರ ಮತ್ತು ಶಾಸನಬದ್ಧ ಗಡುವುಗಳು',
    pendingActions: 'ನೀವು ಪೂರ್ಣಗೊಳಿಸಬೇಕಾದ ಕಾರ್ಯಗಳು',
    completedActions: 'ಪೂರ್ಣಗೊಂಡ ಕಾರ್ಯಗಳು',
    urgentDeadlines: 'ಶಾಸನಬದ್ಧ ಗಡುವಿನ ಎಚ್ಚರಿಕೆಗಳು',
    actObjectionPeriod: 'ಕಲಂ 15(1) ಅಡಿಯಲ್ಲಿ ಆಕ್ಷೇಪಣೆ ಸಲ್ಲಿಸಲು 60 ದಿನಗಳ ಗಡುವು',
    actSubmitBankDocs: 'ಪರಿಹಾರ ಪಾವತಿಗಾಗಿ ಬ್ಯಾಂಕ್ ದಾಖಲೆಗಳನ್ನು ಸಲ್ಲಿಸಿ',
    actAttendHearing: 'ಜಿಲ್ಲಾಧಿಕಾರಿಗಳ ಸಾರ್ವಜನಿಕ ವಿಚಾರಣೆಗೆ ಹಾಜರಾಗಿ',
    markCompleted: 'ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    daysRemaining: 'ದಿನಗಳು ಬಾಕಿ ಇವೆ',
    expiredDeadline: 'ಗಡುವು ಮುಗಿದಿದೆ',
    notificationTitle: 'ಅಧಿಸೂಚನೆಗಳು ಮತ್ತು ಅಧಿಕೃತ ಪ್ರಕಟಣೆಗಳು',
    allNotifications: 'ಎಲ್ಲಾ ಅಧಿಸೂಚನೆಗಳು',
    unreadOnly: 'ಓದದಿರುವವು ಮಾತ್ರ',
    markAllRead: 'ಎಲ್ಲವನ್ನೂ ಓದಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    noNotifications: 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ.',
    officerTitle: 'ಭೂಸ್ವಾಧೀನ ಅಧಿಕಾರಿ (LAO) ಆಡಳಿತ ನಿಯಂತ್ರಣ ಕೇಂದ್ರ',
    officerCasesRegistry: 'ಯೋಜನಾ ಸ್ವಾಧೀನ ಪ್ರಕರಣಗಳ ಮಾಸ್ಟರ್ ರಿಜಿಸ್ಟ್ರಿ',
    totalAcquisitions: 'ಒಟ್ಟು ಸ್ವಾಧೀನ ಯೋಜನೆಗಳು',
    activeParcels: 'ಸಕ್ರಿಯ ಸರ್ವೇ ಪಾರ್ಸೆಲ್‌ಗಳು',
    totalDisbursedBudget: 'ಒಟ್ಟು ವಿತರಿಸಲಾದ ಬಜೆಟ್',
    pendingApprovals: 'ಅನುಮೋದನೆಗೆ ಬಾಕಿ ಇರುವ ಕಡತಗಳು',
    caseId: 'ಸ್ವಾಧೀನ ಪ್ರಕರಣ ID',
    caseName: 'ಯೋಜನೆಯ ಹೆಸರು',
    affectedLandowners: 'ಬಾಧಿತ ಭೂಮಾಲೀಕರು',
    stage: 'ಪ್ರಸ್ತುತ ಶಾಸನಬದ್ಧ ಹಂತ',
    stage1_Survey: 'ಹಂತ 1: ಸಾಮಾಜಿಕ ಪರಿಣಾಮ ಮೌಲ್ಯಮಾಪನ & ಸರ್ವೇ',
    stage2_Notification: 'ಹಂತ 2: ಕಲಂ 11(1) ಪ್ರಾಥಮಿಕ ಅಧಿಸೂಚನೆ',
    stage3_Objections: 'ಹಂತ 3: ಕಲಂ 15 ವಿಚಾರಣೆ & ಆಕ್ಷೇಪಣೆಗಳು',
    stage4_Declaration: 'ಹಂತ 4: ಕಲಂ 19 ಸ್ವಾಧೀನ ಘೋಷಣೆ',
    stage5_Award: 'ಹಂತ 5: ಕಲಂ 23 ಅವಾರ್ಡ್ & ಪರಿಹಾರ ನಿರ್ಧಾರ',
    stage6_Payment: 'ಹಂತ 6: PFMS ಪರಿಹಾರ ವಿತರಣೆ',
    stage7_Possession: 'ಹಂತ 7: ಭೂಸ್ವಾಧೀನ & R&R ಜಾರಿ',
    approve: 'ಅನುಮೋದಿಸಿ',
    reject: 'ತಿರಸ್ಕರಿಸಿ',
    forwardToUpper: 'ಮೇಲಧಿಕಾರಿಗೆ ಕಳುಹಿಸಿ',
    scheduleHearing: 'ವಿಚಾರಣೆ ದಿನಾಂಕ ನಿಗದಿಪಡಿಸಿ',
    issueNotice: 'ಶಾಸನಬದ್ಧ ನೋಟಿಸ್ ಜಾರಿಗೊಳಿಸಿ',
    disburseFunds: 'ಹಣ ಬಿಡುಗಡೆ ಮಾಡಿ',
    officerRemarksPlaceholder: 'ಅಧಿಕೃತ ಪರಿಶೀಲನಾ ಟಿಪ್ಪಣಿಗಳನ್ನು ನಮೂದಿಸಿ...',
    saveDecision: 'ನಿರ್ಧಾರವನ್ನು ಉಳಿಸಿ',
    step: 'ಹಂತ',
    of: 'ರ',
    surveyRequired: 'ಸರ್ವೇ ನಂಬರ್ ಅಗತ್ಯವಿದೆ',
    enterValidSurvey: 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಸರ್ವೇ ನಂಬರ್ ನಮೂದಿಸಿ',
    villageRequired: 'ಗ್ರಾಮದ ಹೆಸರು ಅಗತ್ಯವಿದೆ',
    districtRequired: 'ಜಿಲ್ಲೆಯ ಹೆಸರು ಅಗತ್ಯವಿದೆ',
    compensationBreakdown: 'ಪರಿಹಾರದ ಸಂಪೂರ್ಣ ವಿವರಣೆ',
    marketValueCalculated: 'ಲೆಕ್ಕಹಾಕಿದ ಮೂಲ ಭೂ ಮೌಲ್ಯ',
    multiplicationFactor: 'ಗ್ರಾಮೀಣ ಗುಣಕ ಅಂಶ (RFCTLARR ಅನುಸೂಚಿ 1)',
    additionalAssetValuation: 'ಮರಗಳು, ಬಾವಿಗಳು, ಕಟ್ಟಡಗಳ ಮೌಲ್ಯಮಾಪನ',
    statutoryInterest: 'ಕಲಂ 30(3) ಅಡಿಯಲ್ಲಿ 12% ಹೆಚ್ಚುವರಿ ವಾರ್ಷಿಕ ಬಡ್ಡಿ',
    netEntitlement: 'ಒಟ್ಟು ನಿವ್ವಳ ಪಾವತಿ ಮೊತ್ತ',
    readyForPFMS: 'PFMS ಮೂಲಕ ಪಾವತಿಗೆ ಸಿದ್ಧವಾಗಿದೆ',
    disbursementHistory: 'ಹಿಂದಿನ ಪಾವತಿಗಳ ಇತಿಹಾಸ',
    noDisbursementsYet: 'ಇನ್ನೂ ಯಾವುದೇ ಹಣ ಬಿಡುಗಡೆಯಾಗಿಲ್ಲ.',
    compensationDisputeHelp: 'ಲೆಕ್ಕಾಚಾರದ ಕುರಿತು ಆಕ್ಷೇಪಣೆಯಿದ್ದರೆ ಭೂ ಪ್ರಾಧಿಕಾರಕ್ಕೆ (LARR) ಮೇಲ್ಮನವಿ ಸಲ್ಲಿಸಬಹುದು.',
    trackDisbursement: 'PFMS ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ವಹಿವಾಟು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    viewAllNotices: 'ಎಲ್ಲಾ ಗೆಜೆಟ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    noActionsPending: 'ಪ್ರಸ್ತುತ ನಿಮ್ಮ ಕಡೆಯಿಂದ ಯಾವುದೇ ಬಾಕಿ ಕಾರ್ಯಗಳಿಲ್ಲ.',
    officerQueueEmpty: 'ಪ್ರಸ್ತುತ ಬಾಕಿ ಪ್ರಕರಣಗಳ ಪಟ್ಟಿ ಖಾಲಿಯಾಗಿದೆ.',
    discrepancyResolution: 'ವ್ಯತ್ಯಾಸ ಪರಿಹಾರ ಕ್ರಮ',
    fileAppeal: 'ಭೂಸ್ವಾಧೀನ ಪ್ರಾಧಿಕಾರಕ್ಕೆ (LARRA) ಮೇಲ್ಮನವಿ ಸಲ್ಲಿಸಿ',
    disputeDeadlineWarning: 'ಗಮನಿಸಿ: ಅವಾರ್ಡ್ ಜಾರಿಯಾದ 60 ದಿನಗಳೊಳಗೆ ಮಾತ್ರ ಮೇಲ್ಮನವಿ ಸಲ್ಲಿಸಬಹುದು.',
    noticeDetails: 'ನೋಟಿಸ್‌ನ ಪೂರ್ಣ ವಿವರಗಳು',
    gazetteDate: 'ಗೆಜೆಟ್ ಪ್ರಕಟಣೆಯ ದಿನಾಂಕ',
    competentAuthority: 'ಸಕ್ಷಮ ಪ್ರಾಧಿಕಾರ (CALA / SDO)',
    projectAlignmentMap: 'ರಾಷ್ಟ್ರೀಯ ಹೆದ್ದಾರಿ / ರೈಲ್ವೆ ಮಾರ್ಗ ನಕ್ಷೆ',
    surveyBoundaries: 'ಕಂದಾಯ ಸರ್ವೇ ಗಡಿಗಳು',
    parcelAreaMismatch: 'ಸರ್ವೇ ನಂಬರ್ ವಿಸ್ತೀರ್ಣದಲ್ಲಿ ವ್ಯತ್ಯಾಸವಿದೆ',
    expectedArea: 'ಕಂದಾಯ ದಾಖಲೆಯ ವಿಸ್ತೀರ್ಣ',
    noticeArea: 'ಸ್ವಾಧೀನ ನೋಟಿಸ್‌ನಲ್ಲಿರುವ ವಿಸ್ತೀರ್ಣ',
    difference: 'ವ್ಯತ್ಯಾಸ',
    takeImmediateAction: 'ತಕ್ಷಣ ಕ್ರಮ ಕೈಗೊಳ್ಳಿ',
    appealPeriodActive: 'ಮೇಲ್ಮನವಿ ಅವಧಿ ಚಾಲ್ತಿಯಲ್ಲಿದೆ',
    appealDaysLeft: 'ಮೇಲ್ಮನವಿ ಸಲ್ಲಿಸಲು ಉಳಿದ ದಿನಗಳು',
    submitClaimDocuments: 'ಕ್ಲೈಮ್ ದಾಖಲೆಗಳನ್ನು ತಕ್ಷಣ ಸಲ್ಲಿಸಿ',
    uploadSuccess: 'ದಾಖಲೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ!',
    uploadFailure: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    deleteConfirmTitle: 'ದಾಖಲೆಯನ್ನು ಅಳಿಸುವುದೇ?',
    deleteConfirmDesc: 'ಈ ದಾಖಲೆಯನ್ನು ಅಳಿಸಿದರೆ ಮರುಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ.',
    grievanceSubmittedSuccess: 'ನಿಮ್ಮ ದೂರನ್ನು ಯಶಸ್ವಿಯಾಗಿ ದಾಖಲಿಸಲಾಗಿದೆ!',
    grievanceTrackingTip: 'ನಿಮ್ಮ ದೂರಿನ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಟೋಕನ್ ಸಂಖ್ಯೆಯನ್ನು ಇರಿಸಿಕೊಳ್ಳಿ.',
    hearingScheduledAlert: 'ವೈಯಕ್ತಿಕ ವಿಚಾರಣೆ ದಿನಾಂಕ ನಿಗದಿಯಾಗಿದೆ.',
    attendHearingNotice: 'ದಯವಿಟ್ಟು ಸಂಬಂಧಿತ ದಾಖಲೆಗಳೊಂದಿಗೆ ನಿಗದಿತ ಸಮಯಕ್ಕೆ ಹಾಜರಾಗಿ.',
    contactHelpdesk: 'ಸಹಾಯವಾಣಿ ಸಂಪರ್ಕಿಸಿ',
    tollFreeNumber: 'ಉಚಿತ ಸಹಾಯವಾಣಿ: 1800-111-9999',
    helpdeskTiming: 'ಸೋಮವಾರದಿಂದ ಶನಿವಾರ, ಬೆಳಿಗ್ಗೆ 9 ರಿಂದ ಸಂಜೆ 6 ರವರೆಗೆ',
    faqTitle: 'ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು (FAQ)',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    termsOfService: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    accessibilityStatement: 'ಲಭ್ಯತೆ ಹೇಳಿಕೆ',
    govtOfIndia: 'ಭಾರತ ಸರ್ಕಾರ',
    ministryOfRuralDev: 'ಗ್ರಾಮೀಣಾಭಿವೃದ್ಧಿ ಮತ್ತು ಭೂಸಂಪನ್ಮೂಲಗಳ ಸಚಿವಾಲಯ',
    allRightsReserved: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    disclaimer: 'ಈ ಪೋರ್ಟಲ್ ಪಾರದರ್ಶಕತೆಗಾಗಿ ಮಾತ್ರ. ಅಧಿಕೃತ ವಿವಾದಗಳಿಗೆ ಗೆಜೆಟ್ ಅಧಿಸೂಚನೆಗಳೇ ಅಂತಿಮ.',
    heroTitle: 'ನಿಮ್ಮ ಭೂಮಿಯ ಬಗ್ಗೆ ನಿಖರ ಮಾಹಿತಿ ಪಡೆಯಿರಿ.',
    heroDesc: 'ಭೂಸ್ವಾಧೀನ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪಾರದರ್ಶಕವಾಗಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, 100% ಸೋಲೇಟಿಯಮ್‌ನೊಂದಿಗೆ ಸರಿಯಾದ ಪರಿಹಾರ ಪಡೆಯಿರಿ ಮತ್ತು ಸಮಸ್ಯೆಗಳನ್ನು ಸುಲಭವಾಗಿ ಪರಿಹರಿಸಿಕೊಳ್ಳಿ.',
    findLandBtn: 'ನನ್ನ ಭೂಮಿ ಹುಡುಕಿ',
    trackCaseBtn: 'ಪ್ರಕರಣ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    understandDocBtn: 'ದಾಖಲೆ ವಿಶ್ಲೇಷಿಸಿ',
    exploreMapBtn: 'ಭೂ ನಕ್ಷೆ ವೀಕ್ಷಿಸಿ',
    tickerAdvisory: 'ನಾಗರಿಕ ಸಲಹೆ: ಭೂಸ್ವಾಧೀನ ನೋಟಿಸ್ ಬಂದ 60 ದಿನಗಳೊಳಗೆ ಕಲಂ 15(1) ರ ಅಡಿಯಲ್ಲಿ ಆಕ್ಷೇಪಣೆ ಸಲ್ಲಿಸಬಹುದು.',
    noticeLabel: 'ತಾಜಾ ನೋಟಿಸ್:',
    feature1Title: 'ನಿಖರ ಭೂ ಹುಡುಕಾಟ',
    feature1Desc: 'ಸರ್ವೇ ನಂಬರ್ ಮೂಲಕ ನಿಮ್ಮ ಭೂಮಿಯ ಗಡಿ, ವಿಸ್ತೀರ್ಣ ಮತ್ತು ಪ್ರಸ್ತುತ ಸ್ಥಿತಿಯನ್ನು ತಕ್ಷಣ ತಿಳಿಯಿರಿ.',
    feature2Title: 'ಸ್ಮಾರ್ಟ್ ದಾಖಲೆ ವಿಶ್ಲೇಷಣೆ',
    feature2Desc: 'ನೋಟಿಸ್‌ಗಳಲ್ಲಿರುವ ಕಾನೂನು ಅಂಶಗಳು, ವ್ಯತ್ಯಾಸಗಳು ಮತ್ತು ಪ್ರಮುಖ ದಿನಾಂಕಗಳನ್ನು AI ಮೂಲಕ ಸುಲಭವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    feature3Title: '100% ಪರಿಹಾರ ಪಾರದರ್ಶಕತೆ',
    feature3Desc: 'RFCTLARR ಕಾಯ್ದೆಯನ್ವಯ ಪೂರ್ಣ ಸಾಂತ್ವನ ಮೊತ್ತ, ಬಡ್ಡಿ ಮತ್ತು DBT ಪಾವತಿ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    feature4Title: 'ಸುಲಭ ವ್ಯಾಜ್ಯ ಪರಿಹಾರ',
    feature4Desc: 'ವಿಸ್ತೀರ್ಣ ಅಥವಾ ಪರಿಹಾರದಲ್ಲಿ ವ್ಯತ್ಯಾಸವಿದ್ದರೆ ನೇರವಾಗಿ ಅಧಿಕಾರಿಗಳಿಗೆ ದೂರು ಸಲ್ಲಿಸಿ ಪರಿಹಾರ ಕಂಡುಕೊಳ್ಳಿ.',
    compensation: 'ಪರಿಹಾರ',
    rr: 'ಪುನರ್ವಸತಿ (R&R)',
    documents: 'ದಾಖಲೆಗಳು',
    grievances: 'ಕುಂದುಕೊರತೆಗಳು',
    actionRequired: 'ಕ್ರಮ ಅಗತ್ಯವಿದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    helpdesk: 'ಸಹಾಯವಾಣಿ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    home: 'ಮುಖಪುಟ',
    profile: 'ಪ್ರೊಫೈಲ್',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    login: 'ಲಾಗಿನ್',
    email: 'ಇಮೇಲ್ ವಿಳಾಸ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    register: 'ನೋಂದಾಯಿಸಿ',
    rememberMe: 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    citizenLogin: 'ನಾಗರಿಕ ಲಾಗಿನ್',
    officerLogin: 'ಅಧಿಕಾರಿ ಲಾಗಿನ್',
    demoCredentials: 'ಡೆಮೊ ರುಜುವಾತುಗಳು',
    enterEmail: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    enterPassword: 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    welcomeCitizen: 'ನಾಗರಿಕರಿಗೆ ಸ್ವಾಗತ',
    welcomeOfficer: 'ಅಧಿಕಾರಿಗಳಿಗೆ ಸ್ವಾಗತ',
    quickStats: 'ತ್ವರಿತ ಅಂಕಿಅಂಶಗಳು',
    totalCases: 'ಒಟ್ಟು ಪ್ರಕರಣಗಳು',
    resolvedCases: 'ಪರಿಹಾರವಾದ ಪ್ರಕರಣಗಳು',
    pendingReviews: 'ಬಾಕಿ ಪರಿಶೀಲನೆಗಳು',
    myParcels: 'ನನ್ನ ಭೂ ಪಾರ್ಸೆಲ್‌ಗಳು',
    caseTimeline: 'ಪ್ರಕರಣದ ಕಾಲಮಿತಿ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    downloadReport: 'ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    filterByStatus: 'ಸ್ಥಿತಿಯ ಆಧಾರದ ಮೇಲೆ ಫಿಲ್ಟರ್ ಮಾಡಿ',
    allStatuses: 'ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    newestFirst: 'ಹೊಸದು ಮೊದಲು',
    oldestFirst: 'ಹಳೆಯದು ಮೊದಲು',
    name: 'ಹೆಸರು',
    phone: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
    address: 'ವಿಳಾಸ',
    remarks: 'ಷರಾ',
    category: 'ವರ್ಗ',
    date: 'ದಿನಾಂಕ',
    time: 'ಸಮಯ',
    type: 'ಪ್ರಕಾರ',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    clearFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
    resultsFound: 'ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿವೆ',
    noResults: 'ಯಾವುದೇ ಫಲಿತಾಂಶ ಕಂಡುಬಂದಿಲ್ಲ',
    fileUploadSuccess: 'ಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ',
    fileUploadError: 'ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ ಸಂಭವಿಸಿದೆ',
    fileDeleted: 'ಫೈಲ್ ಅಳಿಸಲಾಗಿದೆ',
    changesSaved: 'ಬದಲಾವಣೆಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ',
    actionSuccess: 'ಕ್ರಮ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ',
    actionFailed: 'ಕ್ರಮ ವಿಫಲವಾಗಿದೆ',
    sessionExpired: 'ಅಧಿವೇಶನದ ಅವಧಿ ಮುಗಿದಿದೆ, ದಯವಿಟ್ಟು ಮತ್ತೆ ಲಾಗಿನ್ ಮಾಡಿ',
    unauthorized: 'ಅನಧಿಕೃತ ಪ್ರವೇಶ',
    serverError: 'ಸರ್ವರ್ ದೋಷ ಸಂಭವಿಸಿದೆ, ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ',
    networkError: 'ನೆಟ್‌ವರ್ಕ್ ಸಂಪರ್ಕ ದೋಷ',
    tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    goBack: 'ಹಿಂದಕ್ಕೆ ಹೋಗಿ',
    goToHome: 'ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ',
    viewMore: 'ಹೆಚ್ಚು ನೋಡಿ',
    viewLess: 'ಕಡಿಮೆ ನೋಡಿ',
    copied: 'ಕಾಪಿ ಮಾಡಲಾಗಿದೆ!',
    copyToClipboard: 'ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ಕಾಪಿ ಮಾಡಿ',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    ok: 'ಸರಿ',
    help: 'ಸಹಾಯ',
    feedback: 'ಅಭಿಪ್ರಾಯ',
    contactUs: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
    version: 'ಆವೃತ್ತಿ',
    systemStatus: 'ವ್ಯವಸ್ಥೆಯ ಸ್ಥಿತಿ',
    online: 'ಆನ್‌ಲೈನ್',
    offline: 'ಆಫ್‌ಲೈನ್',
    connecting: 'ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
    syncing: 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
    lastUpdated: 'ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    justNow: 'ಈಗಷ್ಟೇ',
    minutesAgo: 'ನಿಮಿಷಗಳ ಹಿಂದೆ',
    hoursAgo: 'ಗಂಟೆಗಳ ಹಿಂದೆ',
    daysAgo: 'ದಿನಗಳ ಹಿಂದೆ',
    readMore: 'ಇನ್ನಷ್ಟು ಓದಿ',
    showMore: 'ಹೆಚ್ಚು ತೋರಿಸಿ',
    showLess: 'ಕಡಿಮೆ ತೋರಿಸಿ',
    selectAll: 'ಎಲ್ಲವನ್ನೂ ಆಯ್ಕೆಮಾಡಿ',
    deselectAll: 'ಎಲ್ಲವನ್ನೂ ರದ್ದುಮಾಡಿ',
    expandAll: 'ಎಲ್ಲವನ್ನೂ ವಿಸ್ತರಿಸಿ',
    collapseAll: 'ಎಲ್ಲವನ್ನೂ ಕುಗ್ಗಿಸಿ',
    openInNewTab: 'ಹೊಸ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ',
    previous: 'ಹಿಂದಿನ',
    pageOf: 'ಪುಟ',
    rowsPerPage: 'ಪ್ರತಿ ಪುಟದ ಸಾಲುಗಳು',
    totalRecords: 'ಒಟ್ಟು ದಾಖಲೆಗಳು',
    noRecordsFound: 'ಯಾವುದೇ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    pleaseWait: 'ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...',
    somethingWentWrong: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    fieldRequired: 'ಈ ಕ್ಷೇತ್ರ ಅಗತ್ಯವಿದೆ',
    invalidEmail: 'ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
    invalidPhone: 'ಮಾನ್ಯವಾದ 10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    passwordTooShort: 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳಿರಬೇಕು',
    passwordsDoNotMatch: 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
    termsAgreement: 'ನಾನು ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಒಪ್ಪುತ್ತೇನೆ',
    agreeToTerms: 'ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ನಿಯಮಗಳನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಿ',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    currentLanguage: 'ಪ್ರಸ್ತುತ ಭಾಷೆ',
    languageChanged: 'ಭಾಷೆ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಗಿದೆ',
    autoDetectLocation: 'ಸ್ಥಳವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪತ್ತೆಹಚ್ಚಿ',
    locationAccessDenied: 'ಸ್ಥಳ ಪ್ರವೇಶ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ',
    useManualSearch: 'ದಯವಿಟ್ಟು ಹಸ್ತಚಾಲಿತ ಹುಡುಕಾಟವನ್ನು ಬಳಸಿ',
    satelliteLayer: 'ಉಪಗ್ರಹ ಪದರ',
    cadastralLayer: 'ಕಂದಾಯ ನಕ್ಷೆ ಪದರ',
    projectBufferLayer: 'ಯೋಜನಾ ಬಫರ್ ಪದರ',
    measuringDistance: 'ದೂರವನ್ನು ಅಳೆಯಲಾಗುತ್ತಿದೆ',
    measuringArea: 'ವಿಸ್ತೀರ್ಣವನ್ನು ಅಳೆಯಲಾಗುತ್ತಿದೆ',
    clickToMeasure: 'ಅಳೆಯಲು ನಕ್ಷೆಯ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ',
    clearMeasurement: 'ಅಳತೆಯನ್ನು ತೆರವುಗೊಳಿಸಿ',
    totalDistance: 'ಒಟ್ಟು ದೂರ',
    totalArea: 'ಒಟ್ಟು ವಿಸ್ತೀರ್ಣ',
    meters: 'ಮೀಟರ್‌ಗಳು',
    kilometers: 'ಕಿಲೋಮೀಟರ್‌ಗಳು',
    discrepancyDetails: 'ವ್ಯತ್ಯಾಸದ ವಿವರಗಳು',
    affectedSections: 'ಬಾಧಿತ ವಿಭಾಗಗಳು',
    recommendedAction: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ',
    fileGrievanceNow: 'ಈಗಲೇ ಅಧಿಕೃತ ದೂರು ದಾಖಲಿಸಿ',
    viewDiscrepancyReport: 'ವ್ಯತ್ಯಾಸ ವರದಿಯನ್ನು ನೋಡಿ',
    aiConfidence: 'AI ನಿಖರತೆಯ ಮಟ್ಟ',
    highConfidence: 'ಹೆಚ್ಚಿನ ನಿಖರತೆ (95%+)',
    mediumConfidence: 'ಮಧ್ಯಮ ನಿಖರತೆ',
    lowConfidence: 'ಕಡಿಮೆ ನಿಖರತೆ',
    extractedEntities: 'ಹೊರತೆಗೆಯಲಾದ ಅಂಶಗಳು',
    officialGazetteNo: 'ಅಧಿಕೃತ ಗೆಜೆಟ್ ಸಂಖ್ಯೆ',
    notificationDate: 'ಅಧಿಸೂಚನೆ ದಿನಾಂಕ',
    competentAuthorityName: 'ಸಕ್ಷಮ ಪ್ರಾಧಿಕಾರದ ಅಧಿಕಾರಿಯ ಹೆಸರು',
    hearingVenue: 'ಸಾರ್ವಜನಿಕ ವಿಚಾರಣಾ ಸ್ಥಳ',
    objectionDeadlineDate: 'ಆಕ್ಷೇಪಣೆ ಸಲ್ಲಿಕೆಗೆ ಅಂತಿಮ ದಿನಾಂಕ',
    documentVerifiedBadge: 'ಅಧಿಕೃತವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    documentPendingBadge: 'ಪರಿಶೀಲನೆ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    documentRejectedBadge: 'ದಾಖಲೆ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    reuploadDocument: 'ದಾಖಲೆಯನ್ನು ಮರು-ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    reasonForRejection: 'ತಿರಸ್ಕರಿಸಲು ಕಾರಣ',
    downloadCertificate: 'ಪ್ರಮಾಣಪತ್ರ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    shareDocument: 'ದಾಖಲೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    printSummary: 'ಸಾರಾಂಶವನ್ನು ಮುದ್ರಿಸಿ',
    directBenefitTransfer: 'ನೇರ ನಗದು ವರ್ಗಾವಣೆ (DBT)',
    pfmsTrackingStatus: 'PFMS ಪಾವತಿ ಟ್ರ್ಯಾಕಿಂಗ್',
    bankAccountVerified: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    bankAccountPending: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ',
    treasuryRefNumber: 'ಖಜಾನೆ ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ',
    disbursementDate: 'ಹಣ ಬಿಡುಗಡೆ ದಿನಾಂಕ',
    installmentNumber: 'ಕಂತು ಸಂಖ್ಯೆ',
    partialPayment: 'ಭಾಗಶಃ ಪಾವತಿ',
    fullPayment: 'ಪೂರ್ಣ ಪಾವತಿ',
    solatiumAmount: 'ಸಾಂತ್ವನ ಮೊತ್ತ (100%)',
    baseCompensation: 'ಮೂಲ ಭೂ ಪರಿಹಾರ',
    statutoryInterestValue: 'ಶಾಸನಬದ್ಧ ಬಡ್ಡಿ ಮೊತ್ತ',
    totalAwardAmount: 'ಒಟ್ಟು ಅವಾರ್ಡ್ ಮೊತ್ತ',
    displacedFamilyId: 'ಸ್ಥಳಾಂತರಗೊಂಡ ಕುಟುಂಬ ID',
    resettlementSiteName: 'ಪುನರ್ವಸತಿ ಕಾಲೋನಿ ಹೆಸರು',
    plotAllotmentStatus: 'ನಿವೇಶನ ಹಂಚಿಕೆ ಸ್ಥಿತಿ',
    housingGrantStatus: 'ಮನೆ ನಿರ್ಮಾಣ ಅನುದಾನ ಸ್ಥಿತಿ',
    annuityBenefitStatus: 'ಮಾಸಿಕ ಪಿಂಚಣಿ / ವರ್ಷಾಶನ ಸ್ಥಿತಿ',
    skillTrainingStatus: 'ಕೌಶಲ್ಯ ತರಬೇತಿ ಸ್ಥಿತಿ',
    livelihoodGrant: 'ಜೀವನೋಪಾಯ ಮರುಸ್ಥಾಪನೆ ಅನುದಾನ',
    officerCaseManagement: 'ಪ್ರಕರಣ ನಿರ್ವಹಣಾ ನಿಯಂತ್ರಣ',
    citizenGrievanceQueue: 'ನಾಗರಿಕ ದೂರುಗಳ ಸರತಿ ಸಾಲು',
    hearingManagement: 'ವಿಚಾರಣೆಗಳ ನಿರ್ವಹಣೆ',
    awardDrafting: 'ಅವಾರ್ಡ್ ಕರಡು ಮತ್ತು ಅನುಮೋದನೆ',
    fundSanction: 'ನಿಧಿ ಮಂಜೂರಾತಿ ಮತ್ತು ವಿತರಣೆ',
    reportsAndAnalytics: 'ವರದಿಗಳು ಮತ್ತು ವಿಶ್ಲೇಷಣೆ',
    bulkNoticeGeneration: 'ಸಾಮೂಹಿಕ ನೋಟಿಸ್ ಜಾರಿ',
    cadastralSync: 'ಕಂದಾಯ ನಕ್ಷೆ ಸಿಂಕ್ರೊನೈಸೇಶನ್',
    exportToExcel: 'ಎಕ್ಸೆಲ್ ಫೈಲ್ ಆಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    exportToPdf: 'PDF ವರದಿಯಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    auditLog: 'ಆಡಿಟ್ ಲಾಗ್',
    loginHistory: 'ಲಾಗಿನ್ ಇತಿಹಾಸ',
    officerBadge: 'ಅಧಿಕೃತ ಅಧಿಕಾರಿ ದರ್ಜೆ',
    citizenBadge: 'ದೃಢೀಕೃತ ನಾಗರಿಕ',
    stepCompleted: 'ಈ ಹಂತ ಪೂರ್ಣಗೊಂಡಿದೆ',
    stepInProgress: 'ಈ ಹಂತ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    stepPending: 'ಈ ಹಂತ ಬಾಕಿ ಉಳಿದಿದೆ',
    timelineOverview: 'ಸಮಗ್ರ ಸ್ವಾಧೀನ ಕಾಲಮಿತಿ ಅವಲೋಕನ',
    legalDisclaimer: 'ಕಾನೂನು ಹಕ್ಕುತ್ಯಾಗ: ಈ ಮಾಹಿತಿಯನ್ನು ನಾಗರಿಕರ ಅನುಕೂಲಕ್ಕಾಗಿ ಒದಗಿಸಲಾಗಿದೆ. ಗೆಜೆಟ್ ಪ್ರಕಟಣೆಯೇ ಅಂತಿಮ.',
    closeModal: 'ವಿಂಡೋ ಮುಚ್ಚಿ',
    viewReceipt: 'ರಶೀದಿ ವೀಕ್ಷಿಸಿ',
    downloadReceipt: 'ರಶೀದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    sendSMSAlert: 'SMS ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ',
    sendEmailAlert: 'ಇಮೇಲ್ ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ',
    optOutOfAlerts: 'ಎಚ್ಚರಿಕೆಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
    helpdeskSupport: '24/7 ನಾಗರಿಕ ಸಹಾಯವಾಣಿ ಬೆಂಬಲ',
    quickGuide: 'ತ್ವರಿತ ಬಳಕೆ ಮಾರ್ಗದರ್ಶಿ',
    termsText: 'ಸಹಾಯ್ ಪೋರ್ಟಲ್ ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳಿಗೆ ಬದ್ಧವಾಗಿದೆ.',
  };

  writeLocale('kn', 'ಕನ್ನಡ', t);
}

// ============================================================================
// 3. MALAYALAM (മലയാളം - ml)
// ============================================================================
export function generateMalayalam() {
  const t: Record<keyof TranslationSchema, string> = {
    appName: 'സഹായ് (SAHAAY)',
    emblemLetter: 'സ',
    tagline: 'നിങ്ങളുടെ ഭൂമി. നിങ്ങളുടെ കേസ്. നിങ്ങളുടെ അവകാശം.',
    heroSub: 'ഭൂമി ഏറ്റെടുക്കലും നിയമാനുസൃത നഷ്ടപരിഹാരത്തിനുമുള്ള പൗര വിവര പോർട്ടൽ',
    portalSubtitle: 'ഭൂമി • നഷ്ടപരിഹാരം • പുനരധിവാസം • പരാതികൾ • കേസ് ട്രാക്കിംഗ്',
    citizenPortal: 'പൗര പോർട്ടൽ',
    officerPortal: 'ഭൂമി ഏറ്റെടുക്കൽ ഉദ്യോഗസ്ഥ പോർട്ടൽ',
    demoMode: 'ഡെമോ മോഡ് സജീവമാണ്',
    signIn: 'ലോഗിൻ ചെയ്യുക',
    signOut: 'ലോഗ് ഔട്ട്',
    landowner: 'ഭൂവുടമ',
    landOfficer: 'ഭൂമി ഏറ്റെടുക്കൽ ഓഫീസർ (LAO)',
    switchRole: 'റോൾ മാറ്റുക',
    switchCitizen: 'പൗരൻ (രാജേഷ് ശർമ്മ)',
    switchOfficer: 'ഭൂമി ഏറ്റെടുക്കൽ ഓഫീസർ (വിക്രം ചൗഹാൻ)',
    welcomeBack: 'വീണ്ടും സ്വാഗതം',
    navHome: 'ഹോം',
    navFindLand: 'എന്റെ ഭൂമി കണ്ടെത്തുക',
    navGisMap: 'GIS ഭൂമി ഭൂപടം',
    navDocIntel: 'രേഖ വിശകലനം (AI)',
    navCompensation: 'നഷ്ടപരിഹാരവും പുനരധിവാസവും (R&R)',
    navDocuments: 'രേഖാ ലോക്കർ',
    navActionCenter: 'കർമ്മ കേന്ദ്രം',
    navGrievances: 'പരാതി പരിഹാരം',
    navNotices: 'നോട്ടീസുകളും മുന്നറിയിപ്പുകളും',
    navOfficerDashboard: 'ഉദ്യോഗസ്ഥ ഡാഷ്‌ബോർഡ്',
    navCasesRegistry: 'കേസ് രജിസ്ട്രി',
    navGrievancesQueue: 'പരാതികളുടെ നിര',
    citizenServices: 'പൗര ഭൂമി സേവനങ്ങൾ',
    quickActions: 'ദ്രുത നടപടികൾ',
    submit: 'സമർപ്പിക്കുക',
    save: 'സംരക്ഷിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    edit: 'തിരുത്തുക',
    delete: 'ഇല്ലാതാക്കുക',
    search: 'തിരയുക',
    filter: 'ഫിൽട്ടർ',
    back: 'പിന്നോട്ട്',
    next: 'അടുത്തത്',
    close: 'അടയ്ക്കുക',
    view: 'കാണുക',
    download: 'ഡൗൺലോഡ്',
    upload: 'അപ്‌ലോഡ് ചെയ്യുക',
    export: 'കയറ്റുമതി',
    refresh: 'പുതുക്കുക',
    print: 'പ്രിന്റ് ചെയ്യുക',
    loading: 'ലഭ്യമാക്കുന്നു...',
    actions: 'നടപടികൾ',
    details: 'വിശദാംശങ്ങൾ',
    status: 'നിലവിലെ സ്ഥിതി',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    viewOnMap: 'ഭൂപടത്തിൽ കാണുക',
    viewCase: 'പൂർണ്ണ കേസ് കാണുക',
    trackProgress: 'പുരോഗതി പരിശോധിക്കുക',
    proceed: 'തുടരുക',
    confirm: 'സ്ഥിരീകരിക്കുക',
    retry: 'വീണ്ടും ശ്രമിക്കുക',
    clearAll: 'എല്ലാം മായ്‌ക്കുക',
    applyFilter: 'ഫിൽട്ടർ പ്രയോഗിക്കുക',
    active: 'സജീവം',
    pending: 'തീർപ്പുകൽപ്പിക്കാത്തത്',
    completed: 'പൂർത്തിയായി',
    rejected: 'നിരസിച്ചു',
    verified: 'പരിശോധിച്ചുറപ്പിച്ചു',
    underReview: 'പരിശോധനയിലാണ്',
    urgent: 'അടിയന്തിരം',
    optional: 'ഐച്ഛികം',
    required: 'ആവശ്യമാണ്',
    discrepancy: 'വ്യത്യാസം കണ്ടെത്തി',
    findMyLand: 'എന്റെ ഭൂമി കണ്ടെത്തുക',
    myLand: 'എന്റെ ഭൂമി',
    surveyNo: 'സർവേ നമ്പർ / പ്ലോട്ട് നമ്പർ',
    enterSurveyNo: 'ഉദാ: 1042 അല്ലെങ്കിൽ 45/A നൽകുക',
    village: 'വില്ലേജ്',
    district: 'ജില്ല',
    state: 'സംസ്ഥാനം',
    taluka: 'താലൂക്ക്',
    selectState: 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
    selectDistrict: 'ജില്ല തിരഞ്ഞെടുക്കുക',
    selectVillage: 'വില്ലേജ് തിരഞ്ഞെടുക്കുക',
    recordedArea: 'രേഖപ്പെടുത്തിയ വിസ്തീർണ്ണം',
    acquiredArea: 'ഏറ്റെടുത്ത വിസ്തീർണ്ണം',
    remainingArea: 'ബാക്കി വിസ്തീർണ്ണം',
    landClassification: 'ഭൂമി തരംതിരിവ്',
    ownershipType: 'ഉടമസ്ഥാവകാശ തരം',
    marketValueRate: 'വിപണി മൂല്യ നിരക്ക്',
    hectares: 'ഹെക്ടർ',
    acres: 'ഏക്കർ',
    sqMeters: 'ചതുരശ്ര മീറ്റർ',
    parcelStatus: 'ഭൂമി പാർസൽ സ്ഥിതി',
    searchLandPrompt: 'നോട്ടീസിലെ സർവേ വിവരങ്ങൾ നൽകി നിലവിലെ സ്ഥിതി പരിശോധിക്കുക',
    searchLandBtn: 'ഭൂമി വിവരങ്ങൾ തിരയുക',
    noLandFound: 'ഈ വിവരങ്ങളുള്ള ഭൂമി രേഖകൾ കണ്ടെത്താനായില്ല.',
    searchPlaceholder: 'സർവേ നമ്പർ, വില്ലേജ് അല്ലെങ്കിൽ നോട്ടീസ് ID വഴി തിരയുക...',
    exactMatchFound: 'ശരിയായ പൊരുത്തം കണ്ടെത്തി',
    gisMapTitle: 'ഇന്ററാക്ടീവ് GIS പ്രോജക്ട് ഭൂപടം',
    gisMapDesc: 'ഏറ്റെടുക്കൽ അതിരുകളും ബാധിക്കപ്പെട്ട പ്രദേശങ്ങളും മാപ്പിൽ കാണുക',
    satelliteView: 'സാറ്റലൈറ്റ് കാഴ്ച',
    streetView: 'സ്ട്രീറ്റ് കാഴ്ച',
    topographyView: 'ടോപ്പോഗ്രാഫി കാഴ്ച',
    legend: 'മാപ്പ് സൂചിക',
    acquiredZone: 'ഏറ്റെടുക്കൽ വിജ്ഞാപനം ചെയ്ത മേഖല',
    bufferZone: 'ബഫർ / ബാധിത മേഖല',
    yourParcel: 'നിങ്ങളുടെ സർവേ പാർസൽ',
    adjacentParcels: 'സമീപ പാർസലുകൾ',
    zoomIn: 'വലുതാക്കുക',
    zoomOut: 'ചെറുതാക്കുക',
    resetView: 'കാഴ്ച പുനഃക്രമീകരിക്കുക',
    fullscreen: 'പൂർണ്ണ സ്‌ക്രീൻ',
    parcelId: 'പാർസൽ ID',
    coordinates: 'ഭൂമിശാസ്ത്ര നിർദ്ദേശാങ്കങ്ങൾ',
    distanceToProject: 'പദ്ധതിയിലേക്കുള്ള ദൂരം',
    measurementTool: 'അളക്കൽ ഉപകരണം',
    mapLayers: 'മാപ്പ് ലെയറുകൾ',
    overlayCadastral: 'റവന്യൂ കാഡസ്ട്രൽ മാപ്പ് ചേർക്കുക',
    totalCompensation: 'ആകെ നിശ്ചയിച്ച നഷ്ടപരിഹാരം',
    assessedValue: 'അടിസ്ഥാന ഭൂമി മൂല്യം',
    solatium: '100% സോളാറ്റിയം (നിയമാനുസൃത സാന്ത്വന തുക)',
    solatiumDesc: 'RFCTLARR നിയമം 2013 വകുപ്പ് 30(1) പ്രകാരം 100% നിർബന്ധിത നഷ്ടപരിഹാരം',
    interestAmount: 'അധിക പലിശയും അനുബന്ധ ആനുകൂല്യങ്ങളും',
    structureValue: 'കെട്ടിടങ്ങൾ / മരങ്ങൾ എന്നിവയ്ക്കുള്ള നഷ്ടപരിഹാരം',
    calculatedTotal: 'ആകെ നൽകേണ്ട നഷ്ടപരിഹാര തുക',
    paymentStatus: 'PFMS പേയ്‌മെന്റ് വിതരണ സ്ഥിതി',
    dbtStatus: 'DBT ബാങ്ക് അക്കൗണ്ട് ബന്ധിപ്പിക്കൽ സ്ഥിതി',
    disbursed: 'അക്കൗണ്ടിൽ നിക്ഷേപിച്ചു',
    disbursedAmount: 'നൽകിയ തുക',
    remainingAmount: 'ബാക്കി തുക',
    bankAccount: 'ബന്ധിപ്പിച്ച ബാങ്ക് അക്കൗണ്ട്',
    ifscCode: 'IFSC കോഡ്',
    paymentRefNo: 'PFMS / ട്രഷറി ഇടപാട് നമ്പർ',
    claimCompensation: 'നഷ്ടപരിഹാര അപേക്ഷ സമർപ്പിക്കുക',
    downloadAwardLetter: 'അവാർഡ് ഉത്തരവ് ഡൗൺലോഡ് ചെയ്യുക (ഫോം 11)',
    rrTitle: 'പുനരധിവാസവും പുനഃസ്ഥാപനവും (R&R) ആനുകൂല്യങ്ങൾ',
    rrEntitlement: 'R&R അർഹതാ പാക്കേജ്',
    rrStatus: 'പുനരധിവാസ നടപ്പാക്കൽ സ്ഥിതി',
    resettlementHouse: 'പകരമുള്ള വീട് / പ്ലോട്ട് അനുവദിക്കൽ',
    subsistenceGrant: 'ഉപജീവന ഗ്രാന്റ് (പ്രതിമാസ സഹായം)',
    transportAllowance: 'താമസമാറ്റ യാത്രാ ബത്ത',
    trainingSkill: 'തൊഴിൽ പരിശീലനം / തൊഴിൽ സഹായം',
    rrOfficerAssigned: 'നിയോഗിക്കപ്പെട്ട R&R നോഡൽ ഓഫീസർ',
    rrTimeline: 'R&R പുരോഗതി സമയക്രമം',
    docIntelTitle: 'ആർട്ടിഫിഷ്യൽ ഇന്റലിജൻസ് രേഖ വിശകലനം',
    docIntelSub: 'സർക്കാർ ഭൂമി ഏറ്റെടുക്കൽ നോട്ടീസുകളും ഗസറ്റ് ഉത്തരവുകളും വിശകലനം ചെയ്യുന്നു',
    uploadNotice: 'നോട്ടീസ് അല്ലെങ്കിൽ അവാർഡ് രേഖ അപ്‌ലോഡ് ചെയ്യുക',
    dragDropDoc: 'PDF, JPG അല്ലെങ്കിൽ PNG ഫയലുകൾ ഇവിടെ ഇടുക അല്ലെങ്കിൽ ബ്രൗസ് ചെയ്യുക',
    supportedFormats: 'പിന്തുണയ്ക്കുന്ന ഫോർമാറ്റുകൾ: PDF, JPEG, PNG (പരമാവധി വലുപ്പം: 25MB)',
    analyzingDoc: 'രേഖയിലെ വിവരങ്ങൾ AI വിശകലനം ചെയ്യുന്നു...',
    extractedData: 'രേഖയിൽ നിന്ന് ശേഖരിച്ച പ്രധാന വിവരങ്ങൾ',
    legalClause: 'ബാധകമായ നിയമവും വകുപ്പും',
    section4_1: 'വകുപ്പ് 4(1) - പ്രാഥമിക വിജ്ഞാപനം',
    section11_1: 'വകുപ്പ് 11(1) - പ്രാഥമിക സർവേ വിജ്ഞാപനം',
    section19_1: 'വകുപ്പ് 19(1) - ഏറ്റെടുക്കൽ പ്രഖ്യാപനം',
    section21_2: 'വകുപ്പ് 21(2) - പബ്ലിക് ഹിയറിംഗ് നോട്ടീസ്',
    section23: 'വകുപ്പ് 23 - കളക്ടറുടെ അന്തിമ അവാർഡ്',
    potentialDiscrepancy: 'ഗുരുതരമായ വ്യത്യാസം / തർക്കം കണ്ടെത്തി',
    discrepancyFound: 'നോട്ടീസും റവന്യൂ രേഖയും തമ്മിൽ വ്യത്യാസമുണ്ട്',
    discrepancyDesc: 'നോട്ടീസിലെ വിസ്തീർണ്ണം റവന്യൂ രേഖയേക്കാൾ കുറവാണ്. ഉടൻ ആക്ഷേപം ഫയൽ ചെയ്യുക.',
    reportDiscrepancy: 'ആക്ഷേപം / പരാതി രേഖപ്പെടുത്തുക',
    aiConfidenceScore: 'AI വിശകലന കൃത്യത റേറ്റിംഗ്',
    plainLanguageSummary: 'ലളിത ഭാഷാ സംഗ്രഹം',
    actionDeadline: 'നടപടി സ്വീകരിക്കേണ്ട അവസാന തീയതി',
    documentLocker: 'ഡിജിറ്റൽ രേഖാ കലവറ',
    allDocuments: 'എല്ലാ രേഖകളും',
    verifiedDocuments: 'പരിശോധിച്ചുറപ്പിച്ച രേഖകൾ',
    pendingVerification: 'പരിശോധന ബാക്കിയുള്ള രേഖകൾ',
    uploadNewDoc: 'പുതിയ രേഖ അപ്‌ലോഡ് ചെയ്യുക',
    docType: 'രേഖയുടെ തരം',
    selectDocType: 'രേഖയുടെ തരം തിരഞ്ഞെടുക്കുക',
    docLandTitle: 'ഭൂവുടമസ്ഥാവകാശ രേഖ (പട്ടയം / തണ്ടപ്പേര്)',
    docGovNotice: 'സർക്കാർ ഭൂമി ഏറ്റെടുക്കൽ നോട്ടീസ്',
    docIdentityProof: 'തിരിച്ചറിയൽ രേഖ (ആധാർ / പാൻ കാർഡ്)',
    docBankPassbook: 'ബാങ്ക് പാസ്സ്ബുക്ക് / ക്യാൻസൽ ചെയ്ത ചെക്ക്',
    docGrievanceProof: 'പരാതി സഹായ രേഖകൾ',
    fileSize: 'ഫയൽ വലുപ്പം',
    uploadDate: 'അപ്‌ലോഡ് ചെയ്ത തീയതി',
    viewDoc: 'രേഖ കാണുക',
    downloadDoc: 'രേഖ ഡൗൺലോഡ് ചെയ്യുക',
    deleteDoc: 'രേഖ ഇല്ലാതാക്കുക',
    confirmDeleteDoc: 'ഈ രേഖ നീക്കം ചെയ്യാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?',
    grievancesTitle: 'പൗര പരാതി പരിഹാര സംവിധാനം',
    submitGrievance: 'പുതിയ പരാതി സമർപ്പിക്കുക',
    grievanceType: 'പരാതിയുടെ തരം',
    selectGrievanceType: 'പരാതി വിഭാഗം തിരഞ്ഞെടുക്കുക',
    typeCompensationAmount: 'നഷ്ടപരിഹാര തുക കണക്കാക്കലിലെ തർക്കം',
    typeAreaDiscrepancy: 'സർവേ വിസ്തീർണ്ണത്തിലെ വ്യത്യാസം',
    typeOwnershipDispute: 'ഉടമസ്ഥാവകാശ തർക്കം അല്ലെങ്കിൽ പേര് തിരുത്തൽ',
    typePaymentDelay: 'നഷ്ടപരിഹാരം ലഭിക്കുന്നതിലെ കാലതാമസം',
    typeRRNonReceipt: 'പുനരധിവാസ ആനുകൂല്യങ്ങൾ ലഭിക്കാത്തത്',
    typeOther: 'മറ്റ് ഭരണപരമായ പ്രശ്നങ്ങൾ',
    grievanceSubject: 'പരാതി വിഷയം',
    grievanceDesc: 'പരാതിയുടെ പൂർണ്ണ വിവരണം',
    grievanceDescPlaceholder: 'നിങ്ങളുടെ പ്രശ്നം വ്യക്തമായി എഴുതുക...',
    attachEvidence: 'തെളിവ് രേഖകൾ ചേർക്കുക',
    grievanceStatus: 'പരാതി പരിഹാര സ്ഥിതി',
    ticketNumber: 'പരാതി ടോക്കൺ നമ്പർ',
    assignedToOfficer: 'ചുമതലപ്പെടുത്തിയ ഉദ്യോഗസ്ഥൻ',
    expectedResolutionDate: 'തീർപ്പാക്കൽ പ്രതീക്ഷിക്കുന്ന തീയതി',
    hearingDate: 'നേരിട്ടുള്ള ഹിയറിംഗ് തീയതി',
    officerRemarks: 'ഉദ്യോഗസ്ഥന്റെ കുറിപ്പുകൾ',
    resolutionSummary: 'അന്തിമ പരിഹാര സംഗ്രഹം',
    actionCenterTitle: 'പൗര കർമ്മ കേന്ദ്രവും സമയപരിധികളും',
    pendingActions: 'നിങ്ങൾ ചെയ്യേണ്ട കാര്യങ്ങൾ',
    completedActions: 'പൂർത്തിയായ കാര്യങ്ങൾ',
    urgentDeadlines: 'നിയമാനുസൃത സമയപരിധി മുന്നറിയിപ്പുകൾ',
    actObjectionPeriod: 'വകുപ്പ് 15(1) പ്രകാരം ആക്ഷേപം സമർപ്പിക്കാൻ 60 ദിവസത്തെ സമയം',
    actSubmitBankDocs: 'നഷ്ടപരിഹാര വിതരണത്തിനായി ബാങ്ക് രേഖകൾ സമർപ്പിക്കുക',
    actAttendHearing: 'ജില്ലാ കളക്ടറുടെ പബ്ലിക് ഹിയറിംഗിൽ പങ്കെടുക്കുക',
    markCompleted: 'പൂർത്തിയായി എന്ന് അടയാളപ്പെടുത്തുക',
    daysRemaining: 'ദിവസങ്ങൾ ബാക്കി',
    expiredDeadline: 'സമയപരിധി കഴിഞ്ഞു',
    notificationTitle: 'അറിയിപ്പുകളും ഔദ്യോഗിക വിവരങ്ങളും',
    allNotifications: 'എല്ലാ അറിയിപ്പുകളും',
    unreadOnly: 'വായിക്കാത്തവ മാത്രം',
    markAllRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
    noNotifications: 'നിലവിൽ പുതിയ അറിയിപ്പുകൾ ഒന്നുമില്ല.',
    officerTitle: 'ഭൂമി ഏറ്റെടുക്കൽ ഓഫീസർ ഭരണ നിയന്ത്രണ കേന്ദ്രം',
    officerCasesRegistry: 'പദ്ധതി ഏറ്റെടുക്കൽ കേസുകളുടെ മാസ്റ്റർ രജിസ്ട്രി',
    totalAcquisitions: 'ആകെ ഏറ്റെടുക്കൽ പദ്ധതികൾ',
    activeParcels: 'സജീവ സർവേ പാർസലുകൾ',
    totalDisbursedBudget: 'ആകെ വിതരണം ചെയ്ത തുക',
    pendingApprovals: 'തീർപ്പാക്കാനുള്ള ഫയലുകൾ',
    caseId: 'കേസ് ID',
    caseName: 'പദ്ധതിയുടെ പേര്',
    affectedLandowners: 'ബാധിക്കപ്പെട്ട ഭൂവുടമകൾ',
    stage: 'നിലവിലെ നിയമപരമായ ഘട്ടം',
    stage1_Survey: 'ഘട്ടം 1: സാമൂഹിക ആഘാത പഠനവും സർവേയും',
    stage2_Notification: 'ഘട്ടം 2: വകുപ്പ് 11(1) പ്രാഥമിക വിജ്ഞാപനം',
    stage3_Objections: 'ഘട്ടം 3: വകുപ്പ് 15 ഹിയറിംഗും ആക്ഷേപങ്ങളും',
    stage4_Declaration: 'ഘട്ടം 4: വകുപ്പ് 19 ഏറ്റെടുക്കൽ പ്രഖ്യാപനം',
    stage5_Award: 'ഘട്ടം 5: വകുപ്പ് 23 അവാർഡും നഷ്ടപരിഹാര നിർണ്ണയവും',
    stage6_Payment: 'ഘട്ടം 6: PFMS നഷ്ടപരിഹാര വിതരണം',
    stage7_Possession: 'ഘട്ടം 7: ഭൂമി കൈവശപ്പെടുത്തലും R&R നടപ്പാക്കലും',
    approve: 'അംഗീകരിക്കുക',
    reject: 'നിരസിക്കുക',
    forwardToUpper: 'ഉന്നത ഉദ്യോഗസ്ഥന് കൈമാറുക',
    scheduleHearing: 'ഹിയറിംഗ് തീയതി നിശ്ചയിക്കുക',
    issueNotice: 'നിയമാനുസൃത നോട്ടീസ് അയയ്ക്കുക',
    disburseFunds: 'തുക അനുവദിക്കുക',
    officerRemarksPlaceholder: 'ഔദ്യോഗിക നിരീക്ഷണ കുറിപ്പുകൾ നൽകുക...',
    saveDecision: 'തീരുമാനം സംരക്ഷിക്കുക',
    step: 'ഘട്ടം',
    of: 'ന്റെ',
    surveyRequired: 'സർവേ നമ്പർ ആവശ്യമാണ്',
    enterValidSurvey: 'സാധുവായ സർവേ നമ്പർ നൽകുക',
    villageRequired: 'വില്ലേജ് പേര് ആവശ്യമാണ്',
    districtRequired: 'ജില്ല പേര് ആവശ്യമാണ്',
    compensationBreakdown: 'നഷ്ടപരിഹാര കണക്കുകൂട്ടൽ വിവരണം',
    marketValueCalculated: 'കണക്കാക്കിയ അടിസ്ഥാന ഭൂമി മൂല്യം',
    multiplicationFactor: 'ഗ്രാമീണ ഗുണന ഘടകം (RFCTLARR ഷെഡ്യൂൾ 1)',
    additionalAssetValuation: 'മരങ്ങൾ, കിണറുകൾ, കെട്ടിടങ്ങൾ എന്നിവയുടെ മൂല്യം',
    statutoryInterest: 'വകുപ്പ് 30(3) പ്രകാരം 12% വാർഷിക പലിശ',
    netEntitlement: 'ആകെ അർഹമായ നഷ്ടപരിഹാരം',
    readyForPFMS: 'PFMS വഴി വിതരണത്തിന് തയ്യാറാണ്',
    disbursementHistory: 'മുൻകാല ഇടപാട് ചരിത്രം',
    noDisbursementsYet: 'ഇതുവരെ പണം കൈമാറിയിട്ടില്ല.',
    compensationDisputeHelp: 'കണക്കുകൂട്ടലിൽ തർക്കമുണ്ടെങ്കിൽ ലാൻഡ് അഥോറിറ്റിക്ക് (LARR) അപ്പീൽ നൽകാം.',
    trackDisbursement: 'PFMS പോർട്ടലിൽ ഇടപാട് ട്രാക്ക് ചെയ്യുക',
    viewAllNotices: 'എല്ലാ ഗസറ്റ് വിജ്ഞാപനങ്ങളും കാണുക',
    noActionsPending: 'നിലവിൽ നിങ്ങളുടെ ഭാഗത്ത് നിന്ന് ചെയ്യേണ്ട കാര്യങ്ങൾ ഒന്നുമില്ല.',
    officerQueueEmpty: 'തീർപ്പാക്കാനുള്ള കേസുകളുടെ പട്ടിക ശൂന്യമാണ്.',
    discrepancyResolution: 'വ്യത്യാസ പരിഹാര നടപടി',
    fileAppeal: 'ഭൂമി ഏറ്റെടുക്കൽ അതോറിറ്റിയിൽ (LARRA) അപ്പീൽ നൽകുക',
    disputeDeadlineWarning: 'ശ്രദ്ധിക്കുക: അവാർഡ് ഉത്തരവ് വന്ന് 60 ദിവസത്തിനകം മാത്രമേ അപ്പീൽ നൽകാവൂ.',
    noticeDetails: 'നോട്ടീസിന്റെ പൂർണ്ണ വിവരങ്ങൾ',
    gazetteDate: 'ഗസറ്റ് പ്രസിദ്ധീകരിച്ച തീയതി',
    competentAuthority: 'സക്ഷമ അതോറിറ്റി (CALA / SDO)',
    projectAlignmentMap: 'ദേശീയപാത / റെയിൽവേ അലൈൻമെന്റ് ഭൂപടം',
    surveyBoundaries: 'റവന്യൂ സർവേ അതിരുകൾ',
    parcelAreaMismatch: 'സർവേ നമ്പർ വിസ്തീർണ്ണത്തിൽ വ്യത്യാസമുണ്ട്',
    expectedArea: 'റവന്യൂ രേഖയിലെ വിസ്തീർണ്ണം',
    noticeArea: 'നോട്ടീസിൽ രേഖപ്പെടുത്തിയ വിസ്തീർണ്ണം',
    difference: 'വ്യത്യാസം',
    takeImmediateAction: 'ഉടൻ നടപടി സ്വീകരിക്കുക',
    appealPeriodActive: 'അപ്പീൽ കാലാവധി നിലവിലുണ്ട്',
    appealDaysLeft: 'അപ്പീൽ നൽകാൻ ബാക്കിയുള്ള ദിവസങ്ങൾ',
    submitClaimDocuments: 'ക്ലെയിം രേഖകൾ ഉടൻ സമർപ്പിക്കുക',
    uploadSuccess: 'രേഖ വിജയകരമായി അപ്‌ലോഡ് ചെയ്തു!',
    uploadFailure: 'രേഖ അപ്‌ലോഡ് പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുക.',
    deleteConfirmTitle: 'രേഖ ഇല്ലാതാക്കണോ?',
    deleteConfirmDesc: 'ഈ രേഖ നീക്കം ചെയ്താൽ വീണ്ടെടുക്കാനാകില്ല.',
    grievanceSubmittedSuccess: 'നിങ്ങളുടെ പരാതി വിജയകരമായി സമർപ്പിച്ചു!',
    grievanceTrackingTip: 'പരാതിയുടെ അവസ്ഥ അറിയാൻ ടോക്കൺ നമ്പർ സൂക്ഷിക്കുക.',
    hearingScheduledAlert: 'ഹിയറിംഗ് തീയതി നിശ്ചയിച്ചിട്ടുണ്ട്.',
    attendHearingNotice: 'രേഖകളുമായി യഥാസമയം ഹിയറിംഗിൽ പങ്കെടുക്കുക.',
    contactHelpdesk: 'ഹെൽപ്പ് ഡെസ്കുമായി ബന്ധപ്പെടുക',
    tollFreeNumber: 'ടോൾ ഫ്രീ നമ്പർ: 1800-111-9999',
    helpdeskTiming: 'തിങ്കൾ മുതൽ ശനി വരെ, രാവിലെ 9 മുതൽ വൈകിട്ട് 6 വരെ',
    faqTitle: 'പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ (FAQ)',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    termsOfService: 'നിബന്ധനകളും വ്യവസ്ഥകളും',
    accessibilityStatement: 'ആക്‌സസിബിലിറ്റി പ്രസ്താവന',
    govtOfIndia: 'ഭാരത സർക്കാർ',
    ministryOfRuralDev: 'ഗ്രാമവികസന മന്ത്രാലയവും ഭൂവിഭവ വകുപ്പും',
    allRightsReserved: 'എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.',
    disclaimer: 'ഈ പോർട്ടൽ സുതാര്യതയ്ക്ക് വേണ്ടിയുള്ളതാണ്. ഔദ്യോഗിക ഗസറ്റ് വിജ്ഞാപനമാണ് അന്തിമം.',
    heroTitle: 'നിങ്ങളുടെ ഭൂമിയെക്കുറിച്ചുള്ള വിവരങ്ങൾ സുതാര്യമായി അറിയുക.',
    heroDesc: 'ഭൂമി ഏറ്റെടുക്കൽ പുരോഗതി കൃത്യമായി നിരീക്ഷിക്കുക, 100% സോളാറ്റിയം ഉൾപ്പെടെയുള്ള പൂർണ്ണ നഷ്ടപരിഹാരം ഉറപ്പാക്കുക, പരാതികൾ വേഗത്തിൽ പരിഹരിക്കുക.',
    findLandBtn: 'എന്റെ ഭൂമി കണ്ടെത്തുക',
    trackCaseBtn: 'കേസ് ട്രാക്ക് ചെയ്യുക',
    understandDocBtn: 'രേഖ വിശകലനം ചെയ്യുക',
    exploreMapBtn: 'ഭൂപടം പരിശോധിക്കുക',
    tickerAdvisory: 'പൗര അറിയിപ്പ്: ഭൂമി ഏറ്റെടുക്കൽ നോട്ടീസ് ലഭിച്ച് 60 ദിവസത്തിനകം വകുപ്പ് 15(1) പ്രകാരം ആക്ഷേപങ്ങൾ സമർപ്പിക്കാം.',
    noticeLabel: 'പുതിയ നോട്ടീസ്:',
    feature1Title: 'കൃത്യമായ ഭൂമി തിരച്ചിൽ',
    feature1Desc: 'സർവേ നമ്പർ ഉപയോഗിച്ച് ഭൂമിയുടെ വിസ്തീർണ്ണവും അതിരുകളും നിലവിലെ സ്ഥിതിയും പരിശോധിക്കുക.',
    feature2Title: 'സ്മാർട്ട് രേഖ വിശകലനം',
    feature2Desc: 'നോട്ടീസുകളിലെ നിയമവശങ്ങളും വ്യത്യാസങ്ങളും AI ഉപയോഗിച്ച് എളുപ്പത്തിൽ മനസ്സിലാക്കുക.',
    feature3Title: '100% നഷ്ടപരിഹാര സുതാര്യത',
    feature3Desc: 'RFCTLARR നിയമപ്രകാരമുള്ള നഷ്ടപരിഹാരവും പലിശയും DBT സ്റ്റാറ്റസും പരിശോധിക്കുക.',
    feature4Title: 'എളുപ്പത്തിലുള്ള പരാതി പരിഹാരം',
    feature4Desc: 'അളവിലോ നഷ്ടപരിഹാരത്തിലോ ഉള്ള വ്യത്യാസങ്ങൾ ഉദ്യോഗസ്ഥരെ നേരിട്ട് അറിയിച്ച് പരിഹാരം കാണുക.',
    compensation: 'നഷ്ടപരിഹാരം',
    rr: 'പുനരധിവാസം (R&R)',
    documents: 'രേഖകൾ',
    grievances: 'പരാതികൾ',
    actionRequired: 'നടപടി ആവശ്യമാണ്',
    inProgress: 'നടന്നുകൊണ്ടിരിക്കുന്നു',
    helpdesk: 'സഹായ കേന്ദ്രം',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    home: 'ഹോം',
    profile: 'പ്രൊഫൈൽ',
    settings: 'ക്രമീകരണങ്ങൾ',
    notifications: 'അറിയിപ്പുകൾ',
    logout: 'ലോഗ് ഔട്ട്',
    login: 'ലോഗിൻ',
    email: 'ഇമെയിൽ വിലാസം',
    password: 'പാസ്‌വേഡ്',
    forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
    register: 'രജിസ്റ്റർ ചെയ്യുക',
    rememberMe: 'എന്നെ ഓർമ്മിക്കുക',
    citizenLogin: 'പൗര ലോഗിൻ',
    officerLogin: 'ഉദ്യോഗസ്ഥ ലോഗിൻ',
    demoCredentials: 'ഡെമോ വിവരങ്ങൾ',
    enterEmail: 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
    enterPassword: 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
    welcomeCitizen: 'പൗര സ്വാഗതം',
    welcomeOfficer: 'ഉദ്യോഗസ്ഥ സ്വാഗതം',
    quickStats: 'ദ്രുത സ്ഥിതിവിവരക്കണക്കുകൾ',
    totalCases: 'ആകെ കേസുകൾ',
    resolvedCases: 'പരിഹരിച്ച കേസുകൾ',
    pendingReviews: 'തീർപ്പുകൽപ്പിക്കാത്തവ',
    myParcels: 'എന്റെ ഭൂമി പാർസലുകൾ',
    caseTimeline: 'കേസ് സമയക്രമം',
    recentActivity: 'സമീപകാല പ്രവർത്തനങ്ങൾ',
    downloadReport: 'റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    filterByStatus: 'സ്ഥിതി അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക',
    allStatuses: 'എല്ലാ അവസ്ഥകളും',
    sortBy: 'ക്രമീകരിക്കുക',
    newestFirst: 'പുതിയവ ആദ്യം',
    oldestFirst: 'പഴയവ ആദ്യം',
    name: 'പേര്',
    phone: 'ഫോൺ നമ്പർ',
    address: 'മേൽവിലാസം',
    remarks: 'കുറിപ്പുകൾ',
    category: 'വിഭാഗം',
    date: 'തീയതി',
    time: 'സമയം',
    type: 'തരം',
    viewAll: 'എല്ലാം കാണുക',
    clearFilters: 'ഫിൽട്ടറുകൾ നീക്കം ചെയ്യുക',
    resultsFound: 'ഫലങ്ങൾ കണ്ടെത്തി',
    noResults: 'ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
    fileUploadSuccess: 'ഫയൽ വിജയകരമായി അപ്‌ലോഡ് ചെയ്തു',
    fileUploadError: 'ഫയൽ അപ്‌ലോഡ് ചെയ്യുന്നതിൽ പിശക് സംഭവിച്ചു',
    fileDeleted: 'ഫയൽ നീക്കം ചെയ്തു',
    changesSaved: 'മാറ്റങ്ങൾ വിജയകരമായി സംരക്ഷിച്ചു',
    actionSuccess: 'പ്രവർത്തനം വിജയകരമായി പൂർത്തിയായി',
    actionFailed: 'പ്രവർത്തനം പരാജയപ്പെട്ടു',
    sessionExpired: 'സെഷൻ കാലാവധി കഴിഞ്ഞു, ദയവായി വീണ്ടും ലോഗിൻ ചെയ്യുക',
    unauthorized: 'അനധികൃത പ്രവേശനം',
    serverError: 'സെർവർ പിശക്, ദയവായി പിന്നീട് ശ്രമിക്കുക',
    networkError: 'നെറ്റ്‌വർക്ക് കണക്ഷൻ പിശക്',
    tryAgain: 'വീണ്ടും ശ്രമിക്കുക',
    goBack: 'പിന്നോട്ട് പോകുക',
    goToHome: 'ഹോമിലേക്ക് പോകുക',
    viewMore: 'കൂടുതൽ കാണുക',
    viewLess: 'കുറച്ച് കാണുക',
    copied: 'പകർത്തി!',
    copyToClipboard: 'ക്ലിപ്പ്ബോർഡിലേക്ക് പകർത്തുക',
    yes: 'അതെ',
    no: 'അല്ല',
    ok: 'ശരി',
    help: 'സഹായം',
    feedback: 'അഭിപ്രായം',
    contactUs: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
    aboutUs: 'ഞങ്ങളെക്കുറിച്ച്',
    version: 'പതിപ്പ്',
    systemStatus: 'സിസ്റ്റം നില',
    online: 'ഓൺലൈൻ',
    offline: 'ഓഫ്‌ലൈൻ',
    connecting: 'ബന്ധിപ്പിക്കുന്നു...',
    syncing: 'സിങ്ക് ചെയ്യുന്നു...',
    lastUpdated: 'അവസാനം പുതുക്കിയത്',
    justNow: 'ഇപ്പോൾത്തന്നെ',
    minutesAgo: 'മിനിറ്റുകൾക്ക് മുമ്പ്',
    hoursAgo: 'മണിക്കൂറുകൾക്ക് മുമ്പ്',
    daysAgo: 'ദിവസങ്ങൾക്ക് മുമ്പ്',
    readMore: 'കൂടുതൽ വായിക്കുക',
    showMore: 'കൂടുതൽ കാണിക്കുക',
    showLess: 'കുറച്ച് കാണിക്കുക',
    selectAll: 'എല്ലാം തിരഞ്ഞെടുക്കുക',
    deselectAll: 'എല്ലാം ഒഴിവാക്കുക',
    expandAll: 'എല്ലാം വികസിപ്പിക്കുക',
    collapseAll: 'എല്ലാം ചുരുക്കുക',
    openInNewTab: 'പുതിയ ടാബിൽ തുറക്കുക',
    previous: 'മുമ്പത്തെ',
    pageOf: 'പേജ്',
    rowsPerPage: 'ഒരു പേജിലെ വരികൾ',
    totalRecords: 'ആകെ രേഖകൾ',
    noRecordsFound: 'രേഖകളൊന്നും കണ്ടെത്തിയില്ല',
    pleaseWait: 'ദയവായി കാത്തിരിക്കുക...',
    somethingWentWrong: 'എന്തോ കുഴപ്പം സംഭവിച്ചു',
    fieldRequired: 'ഈ ഫീൽഡ് നിർബന്ധമാണ്',
    invalidEmail: 'സാധുവായ ഇമെയിൽ വിലാസം നൽകുക',
    invalidPhone: 'സാധുവായ 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക',
    passwordTooShort: 'പാസ്‌വേഡിന് കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ വേണം',
    passwordsDoNotMatch: 'പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല',
    termsAgreement: 'ഞാൻ നിബന്ധനകളും വ്യവസ്ഥകളും അംഗീകരിക്കുന്നു',
    agreeToTerms: 'തുടരുന്നതിന് ദയവായി നിബന്ധനകൾ അംഗീകരിക്കുക',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    currentLanguage: 'നിലവിലെ ഭാഷ',
    languageChanged: 'ഭാഷ വിജയകരമായി മാറ്റി',
    autoDetectLocation: 'ലൊക്കേഷൻ സ്വയമേവ കണ്ടെത്തുക',
    locationAccessDenied: 'ലൊക്കേഷൻ അനുമതി നിരസിച്ചു',
    useManualSearch: 'മാനുവൽ തിരച്ചിൽ ഉപയോഗിക്കുക',
    satelliteLayer: 'സാറ്റലൈറ്റ് ലെയർ',
    cadastralLayer: 'കാഡസ്ട്രൽ ലെയർ',
    projectBufferLayer: 'പ്രോജക്ട് ബഫർ ലെയർ',
    measuringDistance: 'ദൂരം അളക്കുന്നു',
    measuringArea: 'വിസ്തീർണ്ണം അളക്കുന്നു',
    clickToMeasure: 'അളക്കാൻ മാപ്പിൽ ക്ലിക്ക് ചെയ്യുക',
    clearMeasurement: 'അളവുകൾ മായ്‌ക്കുക',
    totalDistance: 'ആകെ ദൂരം',
    totalArea: 'ആകെ വിസ്തീർണ്ണം',
    meters: 'മീറ്റർ',
    kilometers: 'കിലോമീറ്റർ',
    discrepancyDetails: 'വ്യത്യാസ വിവരണം',
    affectedSections: 'ബാധിച്ച വിഭാഗങ്ങൾ',
    recommendedAction: 'ശുപാർശ ചെയ്യുന്ന നടപടി',
    fileGrievanceNow: 'ഇപ്പോൾത്തന്നെ പരാതി നൽകുക',
    viewDiscrepancyReport: 'വ്യത്യാസ റിപ്പോർട്ട് കാണുക',
    aiConfidence: 'AI കൃത്യതാ നിലവാരം',
    highConfidence: 'ഉയർന്ന കൃത്യത (95%+)',
    mediumConfidence: 'ഇടത്തരം കൃത്യത',
    lowConfidence: 'കുറഞ്ഞ കൃത്യത',
    extractedEntities: 'ശേഖരിച്ച വിവരങ്ങൾ',
    officialGazetteNo: 'ഔദ്യോഗിക ഗസറ്റ് നമ്പർ',
    notificationDate: 'വിജ്ഞാപന തീയതി',
    competentAuthorityName: 'സക്ഷമ അതോറിറ്റി ഉദ്യോഗസ്ഥൻ',
    hearingVenue: 'പബ്ലിക് ഹിയറിംഗ് വേദി',
    objectionDeadlineDate: 'ആക്ഷേപം നൽകാനുള്ള അവസാന തീയതി',
    documentVerifiedBadge: 'ഔദ്യോഗികമായി പരിശോധിച്ചുറപ്പിച്ചു',
    documentPendingBadge: 'പരിശോധന പുരോഗമിക്കുന്നു',
    documentRejectedBadge: 'രേഖ നിരസിച്ചു',
    reuploadDocument: 'രേഖ വീണ്ടും അപ്‌ലോഡ് ചെയ്യുക',
    reasonForRejection: 'നിരസിക്കാനുള്ള കാരണം',
    downloadCertificate: 'സർട്ടിഫിക്കറ്റ് ഡൗൺലോഡ് ചെയ്യുക',
    shareDocument: 'രേഖ പങ്കിടുക',
    printSummary: 'സംഗ്രഹം പ്രിന്റ് ചെയ്യുക',
    directBenefitTransfer: 'ഡയറക്ട് ബെനിഫിറ്റ് ട്രാൻസ്ഫർ (DBT)',
    pfmsTrackingStatus: 'PFMS പേയ്‌മെന്റ് ട്രാക്കിംഗ്',
    bankAccountVerified: 'ബാങ്ക് അക്കൗണ്ട് പരിശോധിച്ചുറപ്പിച്ചു',
    bankAccountPending: 'ബാങ്ക് അക്കൗണ്ട് പരിശോധന ബാക്കിയാണ്',
    treasuryRefNumber: 'ട്രഷറി റഫറൻസ് നമ്പർ',
    disbursementDate: 'തുക അനുവദിച്ച തീയതി',
    installmentNumber: 'ഗഡു നമ്പർ',
    partialPayment: 'ഭാഗിക പേയ്‌മെന്റ്',
    fullPayment: 'പൂർണ്ണ പേയ്‌മെന്റ്',
    solatiumAmount: 'സോളാറ്റിയം തുക (100%)',
    baseCompensation: 'അടിസ്ഥാന ഭൂമി നഷ്ടപരിഹാരം',
    statutoryInterestValue: 'നിയമാനുസൃത പലിശ തുക',
    totalAwardAmount: 'ആകെ അവാർഡ് തുക',
    displacedFamilyId: 'സ്ഥാനഭ്രംശം സംഭവിച്ച കുടുംബ ID',
    resettlementSiteName: 'പുനരധിവാസ കേന്ദ്രം',
    plotAllotmentStatus: 'പ്ലോട്ട് അനുവദിക്കൽ നില',
    housingGrantStatus: 'ഭവന നിർമ്മാണ ഗ്രാന്റ് നില',
    annuityBenefitStatus: 'പ്രതിമാസ പെൻഷൻ / ആന്വിറ്റി നില',
    skillTrainingStatus: 'തൊഴിൽ പരിശീലന നില',
    livelihoodGrant: 'ഉപജീവന പുനഃസ്ഥാപന ഗ്രാന്റ്',
    officerCaseManagement: 'കേസ് മാനേജ്മെന്റ് കൺട്രോൾ',
    citizenGrievanceQueue: 'പൗര പരാതികളുടെ നിര',
    hearingManagement: 'ഹിയറിംഗ് മാനേജ്മെന്റ്',
    awardDrafting: 'അവാർഡ് ഡ്രാഫ്റ്റിംഗും അംഗീകാരവും',
    fundSanction: 'ഫണ്ട് അനുവദിക്കലും വിതരണവും',
    reportsAndAnalytics: 'റിപ്പോർട്ടുകളും വിശകലനങ്ങളും',
    bulkNoticeGeneration: 'കൂട്ടത്തോടെ നോട്ടീസ് നൽകൽ',
    cadastralSync: 'റവന്യൂ കാഡസ്ട്രൽ സമന്വയം',
    exportToExcel: 'Excel ഫയലായി ഡൗൺലോഡ് ചെയ്യുക',
    exportToPdf: 'PDF റിപ്പോർട്ടായി ഡൗൺലോഡ് ചെയ്യുക',
    auditLog: 'ഓഡിറ്റ് ലോഗ്',
    loginHistory: 'ലോഗിൻ ചരിത്രം',
    officerBadge: 'ഔദ്യോഗിക ഉദ്യോഗസ്ഥ പദവി',
    citizenBadge: 'സ്ഥിരീകരിച്ച പൗരൻ',
    stepCompleted: 'ഈ ഘട്ടം പൂർത്തിയായി',
    stepInProgress: 'ഈ ഘട്ടം നടന്നുകൊണ്ടിരിക്കുന്നു',
    stepPending: 'ഈ ഘട്ടം ബാക്കിയാണ്',
    timelineOverview: 'സമഗ്രമായ ഏറ്റെടുക്കൽ സമയക്രമം',
    legalDisclaimer: 'നിയമപരമായ നിരാകരണം: ഈ വിവരങ്ങൾ പൊതുജന സൗകര്യാർത്ഥം നൽകിയിട്ടുള്ളതാണ്. ഗസറ്റ് വിജ്ഞാപനമാണ് അന്തിമം.',
    closeModal: 'വിൻഡോ അടയ്ക്കുക',
    viewReceipt: 'രസീത് കാണുക',
    downloadReceipt: 'രസീത് ഡൗൺലോഡ് ചെയ്യുക',
    sendSMSAlert: 'SMS മുന്നറിയിപ്പ് അയയ്ക്കുക',
    sendEmailAlert: 'ഇമെയിൽ മുന്നറിയിപ്പ് അയയ്ക്കുക',
    optOutOfAlerts: 'മുന്നറിയിപ്പുകൾ ഒഴിവാക്കുക',
    helpdeskSupport: '24/7 പൗര സഹായവാണി പിന്തുണ',
    quickGuide: 'ഉപയോക്തൃ സഹായി',
    termsText: 'സഹായ് പോർട്ടൽ നിബന്ധനകൾക്കും വ്യവസ്ഥകൾക്കും വിധേയമാണ്.',
  };

  writeLocale('ml', 'മലയാളം', t);
}
